package com.marina.marina.domain.util

import com.marina.marina.domain.model.Employee
import com.marina.marina.domain.model.Expense
import java.util.Calendar

/**
 * Dart SalaryEntitlementService (salary_entitlement_service.dart l.71-207) —
 * entitlements are derived from the EMPLOYEE-LINKED EXPENSES (the single
 * source of truth), never from separate cycle tables.
 *
 * Classification contract:
 * - سحب راتب / رواتب / سحب من الراتب → withdrawal (cash taken)
 * - سلفة → advance (cash taken — deducted from net entitlement)
 * - خصم من الراتب + isAutoGenerated + description contains قسط سلفة
 *   → installment paid against the advance (NOT a new deduction)
 * - خصم من الراتب (manual) / خصم راتب / خصم / غياب → real deduction
 */
object SalaryEntitlementCalculator {

    /** One salary transaction row (last-6 list on the Dart screen). */
    data class SalaryTransaction(
        val type: String, // سحب / سلفة / خصم
        val amount: Double,
        val date: String,
        val note: String,
        val category: String
    )

    data class Entitlement(
        val employee: Employee,
        val hireDate: String,
        val totalMonthsWorked: Int,
        val basicSalary: Double,
        val totalEntitlement: Double,
        val totalWithdrawals: Double,
        val totalAdvances: Double,
        val installmentsPaid: Double,
        val totalDeductions: Double,
        /** Net = entitlement − withdrawals − advances − deductions. */
        val netEntitlement: Double,
        val transactions: List<SalaryTransaction>
    )

    fun calculateMonthsDifference(from: Calendar, to: Calendar): Int {
        var months = (to.get(Calendar.YEAR) - from.get(Calendar.YEAR)) * 12 +
            (to.get(Calendar.MONTH) - from.get(Calendar.MONTH))
        if (to.get(Calendar.DAY_OF_MONTH) < from.get(Calendar.DAY_OF_MONTH)) {
            months--
        }
        return if (months < 0) 0 else months
    }

    fun calculateEmployeeEntitlement(
        employee: Employee,
        expenses: List<Expense>,
        nowMillis: Long = System.currentTimeMillis()
    ): Entitlement {
        val hireCal = HotelTimeEngine.parseDate(employee.hireDate)?.let {
            Calendar.getInstance().apply { timeInMillis = it }
        } ?: Calendar.getInstance().apply { timeInMillis = nowMillis }
        val nowCal = Calendar.getInstance().apply { timeInMillis = nowMillis }

        val monthsWorked = calculateMonthsDifference(hireCal, nowCal)
        val totalEntitlement = monthsWorked * employee.basicSalary

        // Only the employee's own live expenses count.
        val own = expenses.filter { it.relatedId == employee.id && it.deletedAt == null }

        var withdrawals = 0.0
        var advances = 0.0
        var installmentsPaid = 0.0
        var deductions = 0.0
        val transactions = mutableListOf<SalaryTransaction>()

        for (expense in own) {
            val type = expense.expenseType.trim()
            when (type) {
                "سحب راتب", "رواتب", "سحب من الراتب" -> {
                    withdrawals += expense.amount
                    transactions.add(SalaryTransaction("سحب", expense.amount, expense.date, expense.description, "سحب راتب"))
                }
                "سلفة" -> {
                    // Dart critical fix: ALL advances count as taken cash
                    // (installments are repayment, not a new deduction).
                    advances += expense.amount
                    transactions.add(SalaryTransaction("سلفة", expense.amount, expense.date, expense.description, "سلفة"))
                }
                "خصم من الراتب" -> {
                    val isInstallment = expense.isAutoGenerated && expense.description.contains("قسط سلفة")
                    if (isInstallment) {
                        installmentsPaid += expense.amount
                        // The advance itself is already listed — no duplicate row.
                    } else {
                        deductions += expense.amount
                        transactions.add(SalaryTransaction("خصم", expense.amount, expense.date, expense.description, "خصم من الراتب"))
                    }
                }
                "خصم راتب", "خصم", "غياب" -> {
                    deductions += expense.amount
                    transactions.add(SalaryTransaction("خصم", expense.amount, expense.date, expense.description, type))
                }
            }
        }

        val net = totalEntitlement - withdrawals - advances - deductions

        return Entitlement(
            employee = employee,
            hireDate = employee.hireDate,
            totalMonthsWorked = monthsWorked,
            basicSalary = employee.basicSalary,
            totalEntitlement = totalEntitlement,
            totalWithdrawals = withdrawals,
            totalAdvances = advances,
            installmentsPaid = installmentsPaid,
            totalDeductions = deductions,
            netEntitlement = net,
            transactions = transactions.sortedByDescending { it.date }
        )
    }

    fun calculateAll(
        employees: List<Employee>,
        expenses: List<Expense>,
        nowMillis: Long = System.currentTimeMillis()
    ): List<Entitlement> {
        // Dart l.71-84 — ACTIVE, non-deleted employees only.
        return employees
            .filter { it.deletedAt == null && StatusUtils.isEmployeeActive(it.status) }
            .map { calculateEmployeeEntitlement(it, expenses, nowMillis) }
    }

    /**
     * Dart SalaryCycleCalculator.calculate (salary_cycle_calculator.dart
     * l.61-93) — pure money math for the monthly cycle card.
     */
    data class CycleResult(
        val basicSalary: Double,
        val withdrawals: Double,
        val advances: Double,
        val installmentsPaid: Double,
        val deductions: Double,
        val carriedOverFromPrevious: Double,
        val totalBeforeCarryOver: Double,
        val remainingBalance: Double,
        val carryOverToNext: Double,
        val advanceBalance: Double
    )

    data class CycleInput(
        val basicSalary: Double,
        val withdrawals: Double,
        val advances: Double,
        val installmentsPaid: Double,
        val deductions: Double,
        val carriedOverFromPrevious: Double = 0.0
    )

    fun calculateCycle(input: CycleInput): CycleResult {
        val basicSalary = money(input.basicSalary)
        val withdrawals = money(input.withdrawals)
        val advances = money(input.advances)
        val installmentsPaid = money(input.installmentsPaid)
        val deductions = money(input.deductions)
        val carriedOver = money(input.carriedOverFromPrevious)

        val totalBeforeCarryOver = withdrawals + advances + deductions + carriedOver
        val signedRemaining = basicSalary - totalBeforeCarryOver
        val remainingBalance = if (signedRemaining > 0) signedRemaining else 0.0
        val carryOverToNext = if (signedRemaining < 0) -signedRemaining else 0.0
        val advanceBalance = (advances - installmentsPaid).coerceIn(0.0, advances)

        return CycleResult(
            basicSalary = basicSalary,
            withdrawals = withdrawals,
            advances = advances,
            installmentsPaid = installmentsPaid,
            deductions = deductions,
            carriedOverFromPrevious = carriedOver,
            totalBeforeCarryOver = totalBeforeCarryOver,
            remainingBalance = remainingBalance,
            carryOverToNext = carryOverToNext,
            advanceBalance = advanceBalance
        )
    }

    /** Dart _money — round once, clamp to the int32 money range. */
    private fun money(value: Double): Double =
        kotlin.math.round(value).coerceIn(0.0, Int.MAX_VALUE.toDouble())
}
