import 'package:drift/drift.dart' as d;

import '../../utils/id.dart';
import '../../utils/time.dart';
import '../local_db.dart';
import 'entity_adapter.dart';
import 'id_resolver.dart';
import 'resolve_result.dart';
import 'source.dart';

class ExpensesAdapter extends EntityAdapter<Expense, ExpensesCompanion> {
  ExpensesAdapter(this.resolver);
  final IdResolver resolver;

  @override
  String get collectionId => 'expenses';

  @override
  String get drivePath => 'expenses.json';

  @override
  String get tableName => 'expenses';

  @override
  Future<ResolveResult> resolveRefs(
    AppDatabase db,
    Map<String, dynamic> json, {
    required Source src,
  }) async {
    final createdAt = _epoch(json, 'createdAt', src);
    final lastModified = _epoch(json, 'lastModified', src);

    // ✅ حل FK الموظف لمصروفات الرواتب (relatedId)
    // عندما يكون expenseType مرتبطاً بالرواتب، نحل relatedId
    // عبر UUID لضمان التوافق عبر الأجهزة
    int? employeeRelatedId;
    final expenseType = _asString(json, 'expenseType', src) ?? '';
    if (_isSalaryExpenseType(expenseType)) {
      final remoteEmployeeUuid = _asString(json, 'employeeUuid', src) ??
          _asString(json, 'employee_local_uuid', src);
      final remoteRelatedId = _asInt(json, 'relatedId', src) ??
          _asInt(json, 'related_id', src);

      if (remoteEmployeeUuid != null && remoteEmployeeUuid.isNotEmpty) {
        // حل عبر UUID (الأكثر دقة)
        final row = await (db.select(db.employees)
              ..where((e) => e.localUuid.equals(remoteEmployeeUuid))
              ..limit(1))
            .getSingleOrNull();
        if (row != null) {
          employeeRelatedId = row.id;
        }
      }
      // Fallback: إذا لم يتم الحل عبر UUID، نحاول بالـ relatedId كـ local id
      if (employeeRelatedId == null && remoteRelatedId != null) {
        final row = await (db.select(db.employees)
              ..where((e) => e.id.equals(remoteRelatedId))
              ..limit(1))
            .getSingleOrNull();
        if (row != null) {
          employeeRelatedId = row.id;
        }
      }
    }

    return ResolveResult(
      createdAtEpoch: createdAt,
      lastModifiedEpoch: lastModified,
      employeeRelatedId: employeeRelatedId,
    );
  }

  @override
  ExpensesCompanion fromJson(
    Map<String, dynamic> json, {
    required Source src,
    required ResolveResult refs,
  }) {
    final now = Time.nowEpoch();
    final createdAt =
        refs.createdAtEpoch ?? _epoch(json, 'createdAt', src) ?? now;
    final lastModified =
        refs.lastModifiedEpoch ??
        _epoch(json, 'lastModified', src) ??
        createdAt;
    return ExpensesCompanion(
      id: _vInt(json, 'id', src),
      localUuid: d.Value(
        _asString(json, 'localUuid', src) ??
            _asString(json, 'local_uuid', src) ??
            IdGen.uuid(),
      ),
      serverId: _vInt(json, 'serverId', src),
      expenseType: _vStr(json, 'expenseType', src, fallback: ''),
      // ✅ إصلاح: لمصروفات الرواتب، استخدم relatedId المحلول عبر UUID
      // لتوافق الأجهزة المختلفة (relatedId على جهاز آخر قد لا يتطابق)
      relatedId: (_isSalaryExpenseType(
                  _asString(json, 'expenseType', src) ?? '',
                ) &&
                refs.employeeRelatedId != null)
          ? d.Value(refs.employeeRelatedId)
          : _vInt(json, 'relatedId', src),
      description: _vStr(json, 'description', src, fallback: ''),
      amount: _vDouble(json, 'amount', src, fallback: 0),
      date: _vStr(json, 'date', src, fallback: ''),
      cashTransactionId: _vInt(json, 'cashTransactionId', src),
      hotelDayKey: _vStr(json, 'hotelDayKey', src, altKey: 'hotel_day_key'),
      categoryUuid: _vStr(json, 'categoryUuid', src, altKey: 'category_uuid'),
      cashFlowUuid: _vStr(json, 'cashFlowUuid', src, altKey: 'cash_flow_uuid'),
      isAutoGenerated: _vBool(json, 'isAutoGenerated', src, fallback: false),
      createdAt: d.Value(createdAt),
      updatedAt: d.Value(_epoch(json, 'updatedAt', src) ?? createdAt),
      deletedAt: _vInt(json, 'deletedAt', src),
      lastModified: d.Value(lastModified),
      createdAtIso: _vStr(json, 'createdAtIso', src),
      updatedAtIso: _vStr(json, 'updatedAtIso', src),
      deletedAtIso: _vStr(json, 'deletedAtIso', src),
      createdAtEpoch: _vInt(json, 'createdAtEpoch', src, fallback: createdAt),
      lastModifiedEpoch: _vInt(
        json,
        'lastModifiedEpoch',
        src,
        fallback: lastModified,
      ),
      version: _vInt(json, 'version', src, fallback: 1),
      // ✅ إصلاح: عند src=Source.appwrite، نصر على origin='server' دائماً
      // لمنع مشكلة أن البيانات المسحوبة من السيرفر تحمل origin='mobile'
      // مما يمنع _cleanupOutboxAfterPull من تنظيف عناصر outbox بشكل صحيح
      origin: src == Source.appwrite || src == Source.drive
          ? const d.Value('server')
          : _vStr(json, 'origin', src, fallback: 'server'),
      vectorClock: _vStr(
        json,
        'vectorClock',
        src,
        altKey: 'vector_clock',
        fallback: '{}',
      ),
      deviceId: _vStr(json, 'deviceId', src, altKey: 'device_id'),
    );
  }

  @override
  Map<String, dynamic> toJson(Expense model, {required Source src}) {
    final map = <String, dynamic>{
      _k(src, 'id', 'id'): model.id,
      _k(src, 'localUuid', 'local_uuid'): model.localUuid,
      _k(src, 'serverId', 'server_id'): model.serverId,
      _k(src, 'expenseType', 'expense_type'): model.expenseType,
      _k(src, 'relatedId', 'related_id'): model.relatedId,
      _k(src, 'description', 'description'): model.description,
      _k(src, 'amount', 'amount'): model.amount,
      _k(src, 'date', 'date'): model.date,
      _k(src, 'cashTransactionId', 'cash_transaction_id'):
          model.cashTransactionId,
      _k(src, 'hotelDayKey', 'hotel_day_key'): model.hotelDayKey,
      _k(src, 'categoryUuid', 'category_uuid'): model.categoryUuid,
      _k(src, 'cashFlowUuid', 'cash_flow_uuid'): model.cashFlowUuid,
      _k(src, 'isAutoGenerated', 'is_auto_generated'): model.isAutoGenerated,
      _k(src, 'createdAt', 'created_at'): model.createdAt,
      _k(src, 'updatedAt', 'updated_at'): model.updatedAt,
      _k(src, 'deletedAt', 'deleted_at'): model.deletedAt,
      _k(src, 'lastModified', 'last_modified'): model.lastModified,
      _k(src, 'version', 'version'): model.version,
      _k(src, 'origin', 'origin'): model.origin,
      'sync_origin': model.origin,
      _k(src, 'vectorClock', 'vector_clock'): model.vectorClock,
      _k(src, 'deviceId', 'device_id'): model.deviceId,
      // ✅ حقول SyncFields المفقودة — ضرورية لمسار الـ outbox
      _k(src, 'createdAtIso', 'created_at_iso'): model.createdAtIso,
      _k(src, 'updatedAtIso', 'updated_at_iso'): model.updatedAtIso,
      _k(src, 'deletedAtIso', 'deleted_at_iso'): model.deletedAtIso,
      _k(src, 'createdAtEpoch', 'created_at_epoch'): model.createdAtEpoch,
      _k(src, 'lastModifiedEpoch', 'last_modified_epoch'): model.lastModifiedEpoch,
    };

    // ✅ إضافة employeeUuid لمصروفات الرواتب عند المزامنة مع Appwrite
    // هذا يسمح بحل FK الموظف عبر الأجهزة المختلفة
    // ملاحظة: لا يمكننا إضافة employeeUuid هنا لأننا لا نملك
    // بيانات الموظف — سيتم إضافتها في AppwriteSyncManager

    return map;
  }
}

d.Value<int> _vInt(
  Map<String, dynamic> json,
  String key,
  Source src, {
  String? altKey,
  int? fallback,
}) {
  final v =
      _asInt(json, key, src) ??
      (altKey != null ? _asInt(json, altKey, src) : null) ??
      fallback;
  return v == null ? const d.Value.absent() : d.Value(v);
}

d.Value<String> _vStr(
  Map<String, dynamic> json,
  String key,
  Source src, {
  String? altKey,
  String? fallback,
}) {
  final v =
      _asString(json, key, src) ??
      (altKey != null ? _asString(json, altKey, src) : null) ??
      fallback;
  return v == null ? const d.Value.absent() : d.Value(v);
}

d.Value<double> _vDouble(
  Map<String, dynamic> json,
  String key,
  Source src, {
  String? altKey,
  double? fallback,
}) {
  final v =
      _asDouble(json, key, src) ??
      (altKey != null ? _asDouble(json, altKey, src) : null) ??
      fallback;
  return v == null ? const d.Value.absent() : d.Value(v);
}

d.Value<bool> _vBool(
  Map<String, dynamic> json,
  String key,
  Source src, {
  String? altKey,
  bool? fallback,
}) {
  final v =
      _asBool(json, key, src) ??
      (altKey != null ? _asBool(json, altKey, src) : null) ??
      fallback;
  return v == null ? const d.Value.absent() : d.Value(v);
}

int? _epoch(Map<String, dynamic> json, String key, Source src) {
  final v = _asInt(json, key, src);
  if (v != null) {
    return v;
  }
  final s = _asString(json, key, src);
  if (s == null) {
    return null;
  }
  return int.tryParse(s);
}

int? _asInt(Map<String, dynamic> json, String key, Source src) {
  final v = _raw(json, key, src);
  if (v is bool) {
    return v ? 1 : 0;
  }
  if (v is int) {
    return v;
  }
  if (v is num) {
    return v.toInt();
  }
  if (v is String) {
    // تجاهل UUID أو strings طويلة
    if (v.contains('-') || v.length > 20) {
      return null;
    }
    return int.tryParse(v);
  }
  return null;
}

double? _asDouble(Map<String, dynamic> json, String key, Source src) {
  final v = _raw(json, key, src);
  if (v is double) {
    return v;
  }
  if (v is int) {
    return v.toDouble();
  }
  if (v is num) {
    return v.toDouble();
  }
  if (v is String) {
    return double.tryParse(v);
  }
  return null;
}

String? _asString(Map<String, dynamic> json, String key, Source src) {
  final v = _raw(json, key, src);
  if (v == null) {
    return null;
  }
  return v.toString();
}

bool? _asBool(Map<String, dynamic> json, String key, Source src) {
  final v = _raw(json, key, src);
  if (v is bool) {
    return v;
  }
  if (v is num) {
    return v != 0;
  }
  if (v is String) {
    final t = v.toLowerCase();
    if (t == 'true' || t == '1') {
      return true;
    }
    if (t == 'false' || t == '0') {
      return false;
    }
  }
  return null;
}

Object? _raw(Map<String, dynamic> json, String key, Source src) {
  if (json.containsKey(key)) {
    return json[key];
  }
  final alt = _altKey(key, src);
  if (alt != null && json.containsKey(alt)) {
    return json[alt];
  }
  return null;
}

/// هل نوع المصروف مرتبط بالرواتب
bool _isSalaryExpenseType(String type) {
  const salaryKeywords = ['رواتب', 'سحب راتب', 'سحب من الراتب', 'خصم راتب', 'خصم من الراتب'];
  for (final keyword in salaryKeywords) {
    if (type.contains(keyword)) return true;
  }
  return false;
}

String _k(Source src, String camel, String snake) =>
    src == Source.drive ? snake : camel;

String? _altKey(String camel, Source src) {
  if (src == Source.drive) {
    return camel;
  }
  final buf = StringBuffer();
  for (var i = 0; i < camel.length; i++) {
    final c = camel[i];
    if (c.toUpperCase() == c && c.toLowerCase() != c) {
      buf.write('_');
      buf.write(c.toLowerCase());
    } else {
      buf.write(c);
    }
  }
  return buf.toString();
}
