import 'package:drift/drift.dart' as d;

import '../../utils/id.dart';
import '../../utils/time.dart';
import '../local_db.dart';
import 'entity_adapter.dart';
import 'id_resolver.dart';
import 'resolve_result.dart';
import 'source.dart';

class SalaryPaymentsAdapter
    extends EntityAdapter<SalaryPayment, SalaryPaymentsCompanion> {
  SalaryPaymentsAdapter(this.resolver);
  final IdResolver resolver;

  @override
  String get collectionId => 'salary_payments';

  @override
  String get drivePath => 'salary_payments.json';

  @override
  String get tableName => 'salary_payments';

  @override
  Future<ResolveResult> resolveRefs(
    AppDatabase db,
    Map<String, dynamic> json, {
    required Source src,
  }) async {
    // ✅ حل FK دورة الراتب - التحقق من وجود الدورة محلياً قبل الإدراج
    final remoteCycleId =
        _asInt(json, 'cycleId', src) ?? _asInt(json, 'cycle_id', src);
    final cycleUuid =
        _asString(json, 'cycleLocalUuid', src) ??
        _asString(json, 'cycle_local_uuid', src);

    // ✅ إصلاح دقيق: حل شامل للمعرّف البعيد
    int? resolvedCycleId;

    // الطريقة 1: البحث بالـ UUID
    if (cycleUuid != null && cycleUuid.isNotEmpty) {
      resolvedCycleId = await resolver.resolveSalaryCycle(
        uuid: cycleUuid,
      );
    }

    // الطريقة 2: البحث بالـ id البعيد (كـ localId)
    if (resolvedCycleId == null && remoteCycleId != null) {
      resolvedCycleId = await resolver.resolveSalaryCycle(
        localId: remoteCycleId,
      );
    }

    // الطريقة 3: البحث بالـ serverId
    if (resolvedCycleId == null && remoteCycleId != null) {
      try {
        final row = await (db.select(db.salaryCycles)
              ..where((c) => c.serverId.equals(remoteCycleId))
              ..limit(1))
            .getSingleOrNull();
        if (row != null) {
          resolvedCycleId = row.id;
        }
      } catch (_) {}
    }

    final createdAt = _epoch(json, 'createdAt', src);
    final lastModified = _epoch(json, 'lastModified', src);
    return ResolveResult(
      salaryCycleLocalId: resolvedCycleId,
      createdAtEpoch: createdAt,
      lastModifiedEpoch: lastModified,
    );
  }

  @override
  SalaryPaymentsCompanion fromJson(
    Map<String, dynamic> json, {
    required Source src,
    required ResolveResult refs,
  }) {
    final now = Time.nowEpoch();
    final createdAt =
        refs.createdAtEpoch ?? _epoch(json, 'createdAt', src) ?? now;
    final lastModified =
        refs.lastModifiedEpoch ??
        _epoch(json, 'lastModified', src) ??
        createdAt;
    return SalaryPaymentsCompanion(
      id: _vInt(json, 'id', src),
      localUuid: d.Value(
        _asString(json, 'localUuid', src) ??
            _asString(json, 'local_uuid', src) ??
            IdGen.uuid(),
      ),
      serverId: _vInt(json, 'serverId', src),
      // ✅ إصلاح دقيق: استخدام salaryCycleLocalId المحلول بدل القيمة الخامة
      // إذا لم يتم حل الدورة (لا توجد محلياً — يتيمة)، نتخطى الحقل بـ absent()
      // لمنع إدراج قيمة FK غير صالحة (0 أو معرّف بعيد لا يتطابق محلياً)
      cycleId: refs.salaryCycleLocalId != null
          ? d.Value(refs.salaryCycleLocalId!)
          : (src == Source.appwrite || src == Source.drive)
              ? const d.Value.absent() // يتيمة — لا نستخدم القيمة الخامة البعيدة
              : _vInt(json, 'cycleId', src, altKey: 'cycle_id', fallback: 0),
      amount: _vInt(json, 'amount', src, fallback: 0),
      hotelDayKey: _vStr(json, 'hotelDayKey', src, altKey: 'hotel_day_key'),
      paymentDateIso: _vStr(
        json,
        'paymentDateIso',
        src,
        altKey: 'payment_date_iso',
        fallback: '',
      ),
      method: _vStr(json, 'method', src),
      isAutoGenerated: _vBool(json, 'isAutoGenerated', src, fallback: false),
      createdAt: d.Value(createdAt),
      updatedAt: d.Value(_epoch(json, 'updatedAt', src) ?? createdAt),
      deletedAt: _vInt(json, 'deletedAt', src),
      lastModified: d.Value(lastModified),
      createdAtIso: _vStr(json, 'createdAtIso', src),
      updatedAtIso: _vStr(json, 'updatedAtIso', src),
      deletedAtIso: _vStr(json, 'deletedAtIso', src),
      createdAtEpoch: _vInt(json, 'createdAtEpoch', src, fallback: createdAt),
      lastModifiedEpoch: _vInt(
        json,
        'lastModifiedEpoch',
        src,
        fallback: lastModified,
      ),
      version: _vInt(json, 'version', src, fallback: 1),
      // ✅ إصلاح: عند src=Source.appwrite، نصر على origin='server' دائماً
      // لمنع مشكلة أن البيانات المسحوبة من السيرفر تحمل origin='mobile'
      // مما يمنع _cleanupOutboxAfterPull من تنظيف عناصر outbox بشكل صحيح
      origin: src == Source.appwrite || src == Source.drive
          ? const d.Value('server')
          : _vStr(json, 'origin', src, fallback: 'server'),
      vectorClock: _vStr(
        json,
        'vectorClock',
        src,
        altKey: 'vector_clock',
        fallback: '{}',
      ),
    );
  }

  @override
  Map<String, dynamic> toJson(SalaryPayment model, {required Source src}) {
    return {
      _k(src, 'id', 'id'): model.id,
      _k(src, 'localUuid', 'local_uuid'): model.localUuid,
      _k(src, 'serverId', 'server_id'): model.serverId,
      _k(src, 'cycleId', 'cycle_id'): model.cycleId,
      _k(src, 'amount', 'amount'): model.amount,
      _k(src, 'hotelDayKey', 'hotel_day_key'): model.hotelDayKey,
      _k(src, 'paymentDateIso', 'payment_date_iso'): model.paymentDateIso,
      _k(src, 'method', 'method'): model.method,
      _k(src, 'isAutoGenerated', 'is_auto_generated'): model.isAutoGenerated,
      _k(src, 'createdAt', 'created_at'): model.createdAt,
      _k(src, 'updatedAt', 'updated_at'): model.updatedAt,
      _k(src, 'deletedAt', 'deleted_at'): model.deletedAt,
      _k(src, 'lastModified', 'last_modified'): model.lastModified,
      _k(src, 'version', 'version'): model.version,
      _k(src, 'origin', 'origin'): model.origin,
      _k(src, 'vectorClock', 'vector_clock'): model.vectorClock,
    };
  }
}

d.Value<int> _vInt(
  Map<String, dynamic> json,
  String key,
  Source src, {
  String? altKey,
  int? fallback,
}) {
  final v =
      _asInt(json, key, src) ??
      (altKey != null ? _asInt(json, altKey, src) : null) ??
      fallback;
  return v == null ? const d.Value.absent() : d.Value(v);
}

d.Value<String> _vStr(
  Map<String, dynamic> json,
  String key,
  Source src, {
  String? altKey,
  String? fallback,
}) {
  final v =
      _asString(json, key, src) ??
      (altKey != null ? _asString(json, altKey, src) : null) ??
      fallback;
  return v == null ? const d.Value.absent() : d.Value(v);
}

d.Value<bool> _vBool(
  Map<String, dynamic> json,
  String key,
  Source src, {
  String? altKey,
  bool? fallback,
}) {
  final v =
      _asBool(json, key, src) ??
      (altKey != null ? _asBool(json, altKey, src) : null) ??
      fallback;
  return v == null ? const d.Value.absent() : d.Value(v);
}

int? _epoch(Map<String, dynamic> json, String key, Source src) {
  final v = _asInt(json, key, src);
  if (v != null) {
    return v;
  }
  final s = _asString(json, key, src);
  if (s == null) {
    return null;
  }
  return int.tryParse(s);
}

int? _asInt(Map<String, dynamic> json, String key, Source src) {
  final v = _raw(json, key, src);
  if (v is bool) {
    return v ? 1 : 0;
  }
  if (v is int) {
    return v;
  }
  if (v is num) {
    return v.toInt();
  }
  if (v is String) {
    if (v.contains('-') || v.length > 20) {
      return null;
    }
    return int.tryParse(v);
  }
  return null;
}

bool? _asBool(Map<String, dynamic> json, String key, Source src) {
  final v = _raw(json, key, src);
  if (v is bool) {
    return v;
  }
  if (v is num) {
    return v != 0;
  }
  if (v is String) {
    final t = v.toLowerCase();
    if (t == 'true' || t == '1') {
      return true;
    }
    if (t == 'false' || t == '0') {
      return false;
    }
  }
  return null;
}

String? _asString(Map<String, dynamic> json, String key, Source src) {
  final v = _raw(json, key, src);
  if (v == null) {
    return null;
  }
  return v.toString();
}

Object? _raw(Map<String, dynamic> json, String key, Source src) {
  if (json.containsKey(key)) {
    return json[key];
  }
  final alt = _altKey(key, src);
  if (alt != null && json.containsKey(alt)) {
    return json[alt];
  }
  return null;
}

String _k(Source src, String camel, String snake) =>
    src == Source.drive ? snake : camel;

String? _altKey(String camel, Source src) {
  if (src == Source.drive) {
    return camel;
  }
  final buf = StringBuffer();
  for (var i = 0; i < camel.length; i++) {
    final c = camel[i];
    if (c.toUpperCase() == c && c.toLowerCase() != c) {
      buf.write('_');
      buf.write(c.toLowerCase());
    } else {
      buf.write(c);
    }
  }
  return buf.toString();
}
