package com.marina.marina.data

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName

@Entity(
    tableName = "expenses",
    indices = [
        Index("idx_expenses_hotel_day", "hotel_day_key"),
        Index("idx_expenses_category", "category_uuid"),
        Index("idx_expenses_date", "date"),
        Index("idx_expenses_active_hotel_day", "hotel_day_key, expense_type, date", "deleted_at IS NULL"),
        Index("idx_expenses_legacy_active_date", "date", "hotel_day_key IS NULL AND deleted_at IS NULL"),
        Index("idx_expenses_active_date", "date DESC", "deleted_at IS NULL")
    ]
)
data class Expense(
    @PrimaryKey(autoGenerate = true)
    @SerializedName("id")
    override val id: Long = 0,

    @SerializedName("expense_type")
    val expenseType: String,

    @SerializedName("related_id")
    val relatedId: Long? = null,

    @SerializedName("description")
    val description: String,

    @SerializedName("amount")
    val amount: Double,

    @SerializedName("date")
    val date: String,

    @SerializedName("cash_transaction_id")
    val cashTransactionId: Long? = null,

    @SerializedName("hotel_day_key")
    val hotelDayKey: String? = null,

    @SerializedName("category_uuid")
    val categoryUuid: String? = null,

    @SerializedName("cash_flow_uuid")
    val cashFlowUuid: String? = null,

    @SerializedName("is_auto_generated")
    val isAutoGenerated: Boolean = false,

    @SerializedName("employee_uuid")
    val employeeUuid: String? = null,

    @SerializedName("local_uuid")
    override val localUuid: String = "",

    @SerializedName("server_id")
    override val serverId: Int? = null,

    @SerializedName("created_at")
    override val createdAt: Long = 0,

    @SerializedName("updated_at")
    override val updatedAt: Long = 0,

    @SerializedName("deleted_at")
    override val deletedAt: Long? = null,

    @SerializedName("last_modified")
    override val lastModified: Long = 0,

    @SerializedName("created_at_iso")
    override val createdAtIso: String? = null,

    @SerializedName("updated_at_iso")
    override val updatedAtIso: String? = null,

    @SerializedName("deleted_at_iso")
    override val deletedAtIso: String? = null,

    @SerializedName("created_at_epoch")
    override val createdAtEpoch: Long = 0,

    @SerializedName("last_modified_epoch")
    override val lastModifiedEpoch: Long = 0,

    @SerializedName("version")
    override val version: Int = 1,

    @SerializedName("origin")
    override val origin: String = "local",

    @SerializedName("vector_clock")
    override val vectorClock: String = "{}",

    @SerializedName("device_id")
    override val deviceId: String = "",

    @SerializedName("sync_timestamp")
    override val syncTimestamp: Long = 0,

    @SerializedName("idempotency_key")
    override val idempotencyKey: String? = null
) : BaseSyncEntity(
    id = id,
    localUuid = localUuid,
    serverId = serverId,
    createdAt = createdAt,
    updatedAt = updatedAt,
    deletedAt = deletedAt,
    lastModified = lastModified,
    createdAtIso = createdAtIso,
    updatedAtIso = updatedAtIso,
    deletedAtIso = deletedAtIso,
    createdAtEpoch = createdAtEpoch,
    lastModifiedEpoch = lastModifiedEpoch,
    version = version,
    origin = origin,
    vectorClock = vectorClock,
    deviceId = deviceId,
    syncTimestamp = syncTimestamp,
    idempotencyKey = idempotencyKey
)