package com.marina.marina.data.mapper

import com.marina.marina.data.local.entity.AuditLogEntity
import com.marina.marina.data.local.entity.BlacklistEntryEntity
import com.marina.marina.data.local.entity.BookingNightEntity
import com.marina.marina.data.local.entity.BookingPriceAdjustmentEntity
import com.marina.marina.data.local.entity.CashTransactionEntity
import com.marina.marina.data.local.entity.GuestInfoEntity
import com.marina.marina.data.local.entity.PaymentVoidEntity
import com.marina.marina.data.local.entity.PriceAdjustmentEntity
import com.marina.marina.data.local.entity.SalaryCarryOverLogEntity
import com.marina.marina.data.local.entity.SalaryCycleEntity
import com.marina.marina.data.local.entity.SalaryPaymentEntity
import com.marina.marina.domain.model.BlacklistEntry
import com.marina.marina.domain.model.BookingNight
import com.marina.marina.domain.model.BookingPriceAdjustment
import com.marina.marina.domain.model.CashTransaction
import com.marina.marina.domain.model.GuestInfo
import com.marina.marina.domain.model.HotelDayLedger
import com.marina.marina.domain.model.PaymentVoid
import com.marina.marina.domain.model.SalaryCarryOverLog
import com.marina.marina.domain.model.SalaryCycle
import com.marina.marina.domain.model.SalaryPayment

fun BlacklistEntryEntity.toDomain(): BlacklistEntry = BlacklistEntry(
    id = id, name = name, nationality = nationality, nationalId = nationalId,
    phone = phone, reason = reason, notes = notes, reportedBy = reportedBy,
    active = active, localUuid = localUuid, createdAt = createdAt, updatedAt = updatedAt
)

fun BlacklistEntry.toEntity(): BlacklistEntryEntity = BlacklistEntryEntity(
    name = name, nationality = nationality, nationalId = nationalId,
    phone = phone, reason = reason, notes = notes, reportedBy = reportedBy, active = active
).copy(id = id, localUuid = localUuid, createdAt = createdAt, updatedAt = updatedAt)

fun GuestInfoEntity.toDomain(): GuestInfo = GuestInfo(
    id = id, roomNumber = roomNumber, guestName = guestName, nationality = nationality,
    idNumber = idNumber, idType = idType, issueDate = issueDate, issuePlace = issuePlace,
    governorate = governorate, notes = notes, guestPhone = guestPhone,
    localUuid = localUuid, createdAt = createdAt, updatedAt = updatedAt
)

fun GuestInfo.toEntity(): GuestInfoEntity = GuestInfoEntity(
    roomNumber = roomNumber, guestName = guestName, nationality = nationality,
    idNumber = idNumber, idType = idType, issueDate = issueDate, issuePlace = issuePlace,
    governorate = governorate, notes = notes, guestPhone = guestPhone
).copy(id = id, localUuid = localUuid, createdAt = createdAt, updatedAt = updatedAt)

fun CashTransactionEntity.toDomain(): CashTransaction = CashTransaction(
    id = id, registerId = registerId, transactionType = transactionType, amount = amount,
    referenceType = referenceType, referenceId = referenceId, description = description,
    transactionTime = transactionTime, createdBy = createdBy,
    localUuid = localUuid, createdAt = createdAt, updatedAt = updatedAt
)

fun CashTransaction.toEntity(): CashTransactionEntity = CashTransactionEntity(
    registerId = registerId, transactionType = transactionType, amount = amount,
    referenceType = referenceType, referenceId = referenceId, description = description,
    transactionTime = transactionTime, createdBy = createdBy
).copy(id = id, localUuid = localUuid, createdAt = createdAt, updatedAt = updatedAt)

fun SalaryCycleEntity.toDomain(): SalaryCycle = SalaryCycle(
    id = id, employeeId = employeeId, cycleKey = cycleKey, hotelDayStart = hotelDayStart,
    hotelDayEnd = hotelDayEnd, expectedAmount = expectedAmount, actualPaid = actualPaid,
    remainingAmount = remainingAmount, status = status,
    localUuid = localUuid, createdAt = createdAt, updatedAt = updatedAt
)

fun SalaryCycle.toEntity(): SalaryCycleEntity = SalaryCycleEntity(
    employeeId = employeeId, cycleKey = cycleKey, hotelDayStart = hotelDayStart,
    hotelDayEnd = hotelDayEnd, expectedAmount = expectedAmount, actualPaid = actualPaid,
    remainingAmount = remainingAmount, status = status
).copy(id = id, localUuid = localUuid, createdAt = createdAt, updatedAt = updatedAt)

fun SalaryPaymentEntity.toDomain(): SalaryPayment = SalaryPayment(
    id = id, cycleId = cycleId, amount = amount, hotelDayKey = hotelDayKey,
    paymentDateIso = paymentDateIso, method = method, isAutoGenerated = isAutoGenerated,
    localUuid = localUuid, createdAt = createdAt
)

fun SalaryPayment.toEntity(): SalaryPaymentEntity = SalaryPaymentEntity(
    cycleId = cycleId, amount = amount, hotelDayKey = hotelDayKey,
    paymentDateIso = paymentDateIso, method = method, isAutoGenerated = isAutoGenerated
).copy(id = id, localUuid = localUuid, createdAt = createdAt)

fun SalaryCarryOverLogEntity.toDomain(): SalaryCarryOverLog = SalaryCarryOverLog(
    id = id, employeeId = employeeId, amount = amount, previousCycleStart = previousCycleStart,
    previousCycleEnd = previousCycleEnd, newCycleStart = newCycleStart, newCycleEnd = newCycleEnd,
    reason = reason, carriedAt = carriedAt, localUuid = localUuid
)

fun SalaryCarryOverLog.toEntity(): SalaryCarryOverLogEntity = SalaryCarryOverLogEntity(
    employeeId = employeeId, amount = amount, previousCycleStart = previousCycleStart,
    previousCycleEnd = previousCycleEnd, newCycleStart = newCycleStart, newCycleEnd = newCycleEnd,
    reason = reason, carriedAt = carriedAt
).copy(id = id, localUuid = localUuid)

fun PaymentVoidEntity.toDomain(): PaymentVoid = PaymentVoid(
    id = id, originalPaymentUuid = originalPaymentUuid, originalPaymentId = originalPaymentId,
    bookingUuid = bookingUuid, voidedAmount = voidedAmount, voidReason = voidReason,
    voidedBy = voidedBy, voidedAt = voidedAt, voidedAtIso = voidedAtIso, hotelDayKey = hotelDayKey,
    reversalPaymentUuid = reversalPaymentUuid, approvedBy = approvedBy, note = note, localUuid = localUuid
)

fun PaymentVoid.toEntity(): PaymentVoidEntity = PaymentVoidEntity(
    originalPaymentUuid = originalPaymentUuid, originalPaymentId = originalPaymentId,
    bookingUuid = bookingUuid, voidedAmount = voidedAmount, voidReason = voidReason,
    voidedBy = voidedBy, voidedAt = voidedAt, voidedAtIso = voidedAtIso, hotelDayKey = hotelDayKey,
    reversalPaymentUuid = reversalPaymentUuid, approvedBy = approvedBy, note = note
).copy(id = id, localUuid = localUuid)

fun BookingNightEntity.toDomain(): BookingNight = BookingNight(
    id = id, bookingLocalId = bookingLocalId, hotelDayKey = hotelDayKey, nightStart = nightStart,
    nightEnd = nightEnd, nightlyRate = nightlyRate, sequence = sequence, baseRate = baseRate,
    adjustment = adjustment, finalRate = finalRate, localUuid = localUuid
)

fun BookingNight.toEntity(): BookingNightEntity = BookingNightEntity(
    bookingLocalId = bookingLocalId, hotelDayKey = hotelDayKey, nightStart = nightStart,
    nightEnd = nightEnd, nightlyRate = nightlyRate, sequence = sequence, baseRate = baseRate,
    adjustment = adjustment, finalRate = finalRate
).copy(id = id, localUuid = localUuid)

fun BookingPriceAdjustmentEntity.toDomain(): BookingPriceAdjustment = BookingPriceAdjustment(
    id = id, bookingLocalUuid = bookingLocalUuid, bookingLocalId = bookingLocalId,
    roomNumber = roomNumber, amount = amount, effectiveHotelDay = effectiveHotelDay,
    endHotelDay = endHotelDay, isActive = isActive, reason = reason, localUuid = localUuid
)

fun BookingPriceAdjustment.toEntity(): BookingPriceAdjustmentEntity = BookingPriceAdjustmentEntity(
    bookingLocalUuid = bookingLocalUuid, bookingLocalId = bookingLocalId, roomNumber = roomNumber,
    amount = amount, effectiveHotelDay = effectiveHotelDay, endHotelDay = endHotelDay,
    isActive = isActive, reason = reason
).copy(id = id, localUuid = localUuid)

fun HotelDayLedgerEntity.toDomain(): HotelDayLedger = HotelDayLedger(
    id = id, hotelDayKey = hotelDayKey, totalIncome = totalIncome, totalExpenses = totalExpenses,
    pendingBalances = pendingBalances, occupancyRate = occupancyRate, status = status, localUuid = localUuid
)

fun PriceAdjustmentEntity.toDomainAmount(): Double = newValue - previousValue

fun AuditLogEntity.describe(): String = "$operationType:$entityType:$entityUuid"
