org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.vfs.watch=true

kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process
kotlin.code.style=official

android.useAndroidX=true
android.enableJetifier=false
android.enableR8=true
android.enableDexingArtifactTransform=true

# Flutter migrator flags
android.builtInKotlin=false
android.newDsl=false
