[project]
name = "hotel"
region = "eu-central-1"

[git]
base_directory = "/"
deployment_branch = "Ali"

[hasura]
version = "v2.33.4-ce"
adminSecret = "yaWFRUH65;rEMZ-l_F2yC:f8PV@ajaa_"
webhookSecret = "yaWFRUH65;rEMZ-l_F2yC:f8PV@ajaa_"

[[hasura.jwtSecrets]]
type = "HS256"
key = "yaWFRUH65;rEMZ-l_F2yC:f8PV@ajaa_"

[hasura.settings]
corsDomain = ["*"]
devMode = false
enableConsole = true
enableAllowList = false
enableRemoteSchemaPermissions = true
enabledAPIs = ["metadata", "graphql", "pgdump", "config"]
liveQueriesMultiplexedRefetchInterval = 1000
stringifyNumericTypes = false

[hasura.logs]
level = "warn"

[hasura.events]
httpPoolSize = 100

[postgres.resources]
storage = { capacity = 1 }

[functions]
version = 20
