// ✅ (migration 69 — المرحلة F) اختبارات عقد العلاقات المالية المحمولة:
//   • الحقول الجديدة expenseKind / employeeLinkCleared / cycleUuid تعبر
//     مسار الدفع (mapper → filterPayload) ومسار السحب (adapter.fromJson)
//     دون إسقاط — على صيغتي Appwrite camelCase وDrive/legacy snake_case.
//   • اختبار توافق قوائم السماح (allowlist parity): كل مفتاح يرسله
//     المحوّل للكيانات الخمسة يجب أن ينجو من filterPayloadForCollection —
//     يكشف صنف فجوتي G-1b/G-2b (حقل يُرسل ثم يُقص قبل الرفع).
//   • الفهرس الفريد الجزئي (D1 0013): مرآة واحدة نشطة لكل expense_uuid،
//     والاستثناءات (محذوف ناعماً / expense_uuid NULL) مسموحة.
import 'package:drift/drift.dart' as d;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:marina_hotel_mobile/services/adapters/adapter_registry.dart';
import 'package:marina_hotel_mobile/services/adapters/source.dart';
import 'package:marina_hotel_mobile/services/appwrite_config.dart';
import 'package:marina_hotel_mobile/services/appwrite_sync_utils.dart';
import 'package:marina_hotel_mobile/services/local_db.dart';
import 'package:marina_hotel_mobile/services/salary_expense_classifier.dart';
import 'package:marina_hotel_mobile/services/sync/payload_mapper.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late AppDatabase db;
  late AdapterRegistry adapters;
  late PayloadMapper mapper;

  setUp(() {
    db = AppDatabase.forTesting(NativeDatabase.memory());
    adapters = AdapterRegistry(db);
    mapper = const PayloadMapper();
  });

  tearDown(() async {
    await db.close();
  });

  Future<Employee> insertEmployee(String uuid, String name) async {
    await db
        .into(db.employees)
        .insert(
          EmployeesCompanion.insert(
            name: name,
            basicSalary: 1000,
            status: 'نشط',
            localUuid: uuid,
            createdAt: 0,
            updatedAt: 0,
            lastModified: 0,
            createdAtEpoch: const d.Value(0),
            lastModifiedEpoch: const d.Value(0),
            version: const d.Value(1),
            origin: const d.Value('local'),
            vectorClock: const d.Value('{}'),
          ),
        );
    return await (db.select(
      db.employees,
    )..where((e) => e.localUuid.equals(uuid))).getSingle();
  }

  test('expense: expenseKind + employeeLinkCleared يعبران push (Appwrite)', () {
    const expense = Expense(
      id: 1,
      localUuid: 'exp-1',
      expenseType: 'سحب راتب',
      relatedId: null,
      description: 'سحب',
      amount: 50,
      date: '2026-01-01',
      isAutoGenerated: false,
      employeeUuid: 'emp-uuid-1',
      withdrawalUuid: 'wd-uuid-1',
      expenseKind: SalaryExpenseClassifier.kindSalaryWithdrawal,
      employeeLinkCleared: true,
      createdAt: 0,
      updatedAt: 0,
      lastModified: 0,
      createdAtEpoch: 0,
      lastModifiedEpoch: 0,
      version: 1,
      origin: 'local',
      vectorClock: '{}',
      deviceId: 'dev-1',
      syncTimestamp: 0,
    );

    final payload = mapper.expenseToRemote(expense);
    expect(payload['expenseKind'], 'salary_withdrawal');
    // ✅ علامة الإزالة تُرسل دائماً كـ boolean — حتى القيمة false
    expect(payload['employeeLinkCleared'], true);
    expect(payload['withdrawalUuid'], 'wd-uuid-1');

    // بعد تصفية السماح (Appwrite camelCase) تبقى الحقول — عقد D1 0015/0012
    final filtered = AppwriteSyncUtils.filterPayloadForCollection(
      AppwriteConfig.expensesCollectionId,
      Map<String, dynamic>.from(payload),
    );
    expect(filtered['expenseKind'], 'salary_withdrawal');
    expect(filtered['employeeLinkCleared'], true);
  });

  test('expense: سجل ما قبل العقد (NULL) يبقى بلا expenseKind', () {
    const expense = Expense(
      id: 1,
      localUuid: 'exp-legacy',
      expenseType: 'كهرباء',
      description: '',
      amount: 10.0,
      date: '2025-01-01',
      isAutoGenerated: false,
      createdAt: 0,
      updatedAt: 0,
      lastModified: 0,
      createdAtEpoch: 0,
      lastModifiedEpoch: 0,
      version: 1,
      origin: 'local',
      vectorClock: '{}',
      deviceId: '',
      syncTimestamp: 0,
      employeeLinkCleared: false,
    );
    final payload = mapper.expenseToRemote(expense);
    expect(payload.containsKey('expenseKind'), isFalse);
    // علامة الإزالة false تُرسل دائماً (boolean وليس putIfNotNull)
    expect(payload['employeeLinkCleared'], false);
  });

  test(
    'expense adapter: سحب الحقول الجديدة بالصيغتين + tombstone آمن',
    () async {
      // (أ) Appwrite camelCase
      final refs1 = await adapters.expenses.adapter.resolveRefs(
        db,
        const {},
        src: Source.appwrite,
      );
      final comp1 = adapters.expenses.adapter.fromJson(
        {
          'localUuid': 'exp-r1',
          'expenseType': 'رواتب',
          'expenseKind': 'salary_withdrawal',
          'employeeLinkCleared': true,
          'amount': 25.0,
          'date': '2026-01-01',
          'syncTimestamp': 0,
        },
        src: Source.appwrite,
        refs: refs1,
      );
      await db.into(db.expenses).insert(comp1);
      final row1 = await (db.select(
        db.expenses,
      )..where((e) => e.localUuid.equals('exp-r1'))).getSingle();
      expect(row1.expenseKind, 'salary_withdrawal');
      expect(row1.employeeLinkCleared, true);

      // (ب) snake_case (Drive/legacy)
      final refs2 = await adapters.expenses.adapter.resolveRefs(
        db,
        const {},
        src: Source.drive,
      );
      final comp2 = adapters.expenses.adapter.fromJson(
        {
          'local_uuid': 'exp-r2',
          'expense_type': 'خصم من الراتب',
          'expense_kind': 'salary_deduction',
          'employee_link_cleared': 1,
          'amount': 30.0,
          'date': '2026-01-02',
          'sync_timestamp': 0,
        },
        src: Source.drive,
        refs: refs2,
      );
      await db.into(db.expenses).insert(comp2);
      final row2 = await (db.select(
        db.expenses,
      )..where((e) => e.localUuid.equals('exp-r2'))).getSingle();
      expect(row2.expenseKind, 'salary_deduction');
      expect(row2.employeeLinkCleared, true);

      // (ج) غياب الحقلين في مستند قديم ⇒ NULL/absent — لا اشتقاق تخميني
      final refs3 = await adapters.expenses.adapter.resolveRefs(
        db,
        const {},
        src: Source.appwrite,
      );
      final comp3 = adapters.expenses.adapter.fromJson(
        {
          'localUuid': 'exp-old',
          'expenseType': 'كهرباء',
          'amount': 5.0,
          'date': '2025-06-01',
          'syncTimestamp': 0,
        },
        src: Source.appwrite,
        refs: refs3,
      );
      await db.into(db.expenses).insert(comp3);
      final row3 = await (db.select(
        db.expenses,
      )..where((e) => e.localUuid.equals('exp-old'))).getSingle();
      expect(row3.expenseKind, isNull); // سجل ما قبل العقد يبقى NULL
      expect(row3.employeeLinkCleared, false); // افتراضي آمن
    },
  );

  Future<void> insertCycle(String uuid, String employeeUuid) async {
    final emp = await (db.select(
      db.employees,
    )..where((e) => e.localUuid.equals(employeeUuid))).getSingle();
    await db
        .into(db.salaryCycles)
        .insert(
          SalaryCyclesCompanion.insert(
            employeeId: emp.id,
            cycleKey: '2026-01',
            localUuid: uuid,
            employeeUuid: d.Value(employeeUuid),
            createdAt: 0,
            updatedAt: 0,
            lastModified: 0,
            createdAtEpoch: const d.Value(0),
            lastModifiedEpoch: const d.Value(0),
            version: const d.Value(1),
            origin: const d.Value('local'),
            vectorClock: const d.Value('{}'),
            syncTimestamp: const d.Value(0),
          ),
        );
  }

  test(
    'salary payment: cycleUuid يُخزَّن عند السحب ويُرسل عند الدفع',
    () async {
      // (أ) الدفع من الحقل المخزّن + النجاة من تصفية السماح (فجوة G-1b)
      const payment = SalaryPayment(
        id: 1,
        localUuid: 'pay-1',
        cycleId: 0,
        amount: 100,
        paymentDateIso: '2026-01-01',
        isAutoGenerated: false,
        employeeUuid: 'emp-uuid-9',
        cycleUuid: 'cycle-uuid-9',
        createdAt: 0,
        updatedAt: 0,
        lastModified: 0,
        createdAtEpoch: 0,
        lastModifiedEpoch: 0,
        version: 1,
        origin: 'local',
        vectorClock: '{}',
        deviceId: 'dev-1',
        syncTimestamp: 0,
      );
      final payload = mapper.salaryPaymentToRemote(payment);
      expect(payload['cycleUuid'], 'cycle-uuid-9');
      expect(payload['cycleLocalUuid'], 'cycle-uuid-9');
      expect(payload['employeeUuid'], 'emp-uuid-9');

      final filtered = AppwriteSyncUtils.filterPayloadForCollection(
        AppwriteConfig.salaryPaymentsCollectionId,
        Map<String, dynamic>.from(payload),
      );
      // ✅ قبل الإصلاح كان filterPayloadForCollection يقص cycleUuid هنا
      expect(filtered['cycleUuid'], 'cycle-uuid-9');
      expect(filtered['cycleLocalUuid'], 'cycle-uuid-9');
      expect(filtered['employeeUuid'], 'emp-uuid-9');

      // (ب) السحب: يُقرأ من cycleUuid/cycle_uuid ويعبر منتجاً إلى القاعدة
      // الدورتان المشار إليهما يجب أن تكونا محليتين ليحل الـ FK (خلاف ذلك
      // يتخطى المُحوِّل الصف عمداً — دلالة اليتيم).
      await insertEmployee('emp-uuid-remote', 'موظف سحب 1');
      await insertEmployee('emp-uuid-legacy', 'موظف سحب 2');
      await insertCycle('cycle-uuid-remote', 'emp-uuid-remote');
      await insertCycle('cycle-uuid-legacy', 'emp-uuid-legacy');
      final payJson1 = <String, dynamic>{
        'localUuid': 'pay-r1',
        'cycleId': 0,
        'cycleUuid': 'cycle-uuid-remote',
        'employeeUuid': 'emp-uuid-remote',
        'amount': 100,
        'paymentDateIso': '2026-01-01',
        'syncTimestamp': 0,
      };
      final refs = await adapters.salaryPayments.adapter.resolveRefs(
        db,
        payJson1,
        src: Source.appwrite,
      );
      final comp = adapters.salaryPayments.adapter.fromJson(
        payJson1,
        src: Source.appwrite,
        refs: refs,
      );
      await db.into(db.salaryPayments).insert(comp);
      final row = await (db.select(
        db.salaryPayments,
      )..where((p) => p.localUuid.equals('pay-r1'))).getSingle();
      expect(row.cycleUuid, 'cycle-uuid-remote');
      expect(row.employeeUuid, 'emp-uuid-remote');

      // (ج) السحب بالمرادف القديم cycle_local_uuid (أجهزة قائمة)
      final payJson2 = <String, dynamic>{
        'localUuid': 'pay-r2',
        'cycleId': 0,
        'cycle_local_uuid': 'cycle-uuid-legacy',
        'amount': 5,
        'paymentDateIso': '2026-01-02',
        'syncTimestamp': 0,
      };
      final refs2 = await adapters.salaryPayments.adapter.resolveRefs(
        db,
        payJson2,
        src: Source.appwrite,
      );
      final comp2 = adapters.salaryPayments.adapter.fromJson(
        payJson2,
        src: Source.appwrite,
        refs: refs2,
      );
      await db.into(db.salaryPayments).insert(comp2);
      final row2 = await (db.select(
        db.salaryPayments,
      )..where((p) => p.localUuid.equals('pay-r2'))).getSingle();
      expect(row2.cycleUuid, 'cycle-uuid-legacy');

      // (د) غياب المفتاح البعيد كلياً ⇒ absent — لا يمحو رابطاً محفوظاً
      final refs3 = await adapters.salaryPayments.adapter.resolveRefs(
        db,
        const {},
        src: Source.appwrite,
      );
      final comp3 = adapters.salaryPayments.adapter.fromJson(
        {
          'localUuid': 'pay-r3',
          'cycleId': 0,
          'amount': 7,
          'paymentDateIso': '2026-01-03',
          'syncTimestamp': 0,
        },
        src: Source.appwrite,
        refs: refs3,
      );
      expect(comp3.cycleUuid.present, isFalse);
    },
  );

  test('salary cycle: employeeUuid يُرسل من الحقل المخزّن (mapper)', () {
    const cycle = SalaryCycle(
      id: 1,
      localUuid: 'cycle-1',
      employeeId: 1,
      employeeUuid: 'emp-uuid-1',
      cycleKey: '2026-01',
      expectedAmount: 0,
      actualPaid: 0,
      remainingAmount: 0,
      status: 'draft',
      createdAt: 0,
      updatedAt: 0,
      lastModified: 0,
      createdAtEpoch: 0,
      lastModifiedEpoch: 0,
      version: 1,
      origin: 'local',
      vectorClock: '{}',
      deviceId: 'dev-1',
      syncTimestamp: 0,
    );
    final payload = mapper.salaryCycleToRemote(cycle);
    expect(payload['employeeUuid'], 'emp-uuid-1');
    expect(payload['employeeLocalUuid'], 'emp-uuid-1');
  });

  test('allowlist parity: روابط سجل الترحيل تنجو من التصفية (فجوة G-2b)', () {
    const log = SalaryCarryOverLog(
      id: 1,
      localUuid: 'carry-1',
      employeeId: 1,
      employeeUuid: 'emp-uuid-1',
      amount: 100,
      previousCycleStart: '2025-12-01',
      previousCycleEnd: '2025-12-31',
      newCycleStart: '2026-01-01',
      newCycleEnd: '2026-01-31',
      reason: 'ترحيل',
      carriedAt: 0,
      fromCycleId: 'cycle-from-uuid',
      toCycleId: 'cycle-to-uuid',
      carryDate: '2026-01-01',
      hotelDayKey: '2026-01-01',
      createdAt: 0,
      updatedAt: 0,
      lastModified: 0,
      createdAtEpoch: 0,
      lastModifiedEpoch: 0,
      version: 1,
      origin: 'local',
      vectorClock: '{}',
      deviceId: 'dev-1',
      syncTimestamp: 0,
    );
    final payload = mapper.salaryCarryOverLogToRemote(log);
    expect(payload['fromCycleUuid'], 'cycle-from-uuid');
    expect(payload['toCycleUuid'], 'cycle-to-uuid');

    final filtered = AppwriteSyncUtils.filterPayloadForCollection(
      'salary_carry_over_logs',
      Map<String, dynamic>.from(payload),
    );
    // ✅ قبل الإصلاح كانت هذه المفاتيح تُقصّ هنا فلا تصل للسحابة أبداً
    expect(filtered['fromCycleUuid'], 'cycle-from-uuid');
    expect(filtered['toCycleUuid'], 'cycle-to-uuid');
    expect(filtered['fromCycleId'], 'cycle-from-uuid');
    expect(filtered['toCycleId'], 'cycle-to-uuid');
    expect(filtered['carryDate'], '2026-01-01');
  });

  test(
    'allowlist parity شامل: كل مفتاح يرسله المحوّل للكيانات الخمسة ينجو',
    () {
      // عينات نموذجية بكامل حقول العقد (بما فيها الجديدة) — المطلوب أن
      // ينجو كل مفتاح من filterPayloadForCollection (فجوتا G-1b/G-2b).
      final cases = <String, ({Map<String, dynamic> payload, String coll})>{
        'expenses': (
          payload: {
            'localUuid': 'x',
            'expenseType': 'رواتب',
            'description': '',
            'amount': 1.0,
            'date': '2026-01-01',
            'employeeUuid': 'e',
            'withdrawalUuid': 'w',
            'expenseKind': 'salary_withdrawal',
            'employeeLinkCleared': false,
          },
          coll: AppwriteConfig.expensesCollectionId,
        ),
        'salary_payments': (
          payload: {
            'localUuid': 'x',
            'cycleId': 1,
            'cycleUuid': 'c',
            'cycleLocalUuid': 'c',
            'employeeUuid': 'e',
            'employeeLocalUuid': 'e',
            'amount': 1,
            'paymentDateIso': '2026-01-01',
          },
          coll: AppwriteConfig.salaryPaymentsCollectionId,
        ),
        'salary_withdrawals': (
          payload: {
            'localUuid': 'x',
            'employeeId': 1,
            'employeeUuid': 'e',
            'employeeLocalUuid': 'e',
            'amount': 1.0,
            'withdrawDate': '2026-01-01',
            'withdrawalDate': '2026-01-01',
            'expenseUuid': 'ex',
          },
          coll: AppwriteConfig.salaryWithdrawalsCollectionId,
        ),
        'salary_carry_over_logs': (
          payload: {
            'localUuid': 'x',
            'employeeId': 1,
            'employeeUuid': 'e',
            'employeeLocalUuid': 'e',
            'fromCycleUuid': 'f',
            'toCycleUuid': 't',
            'fromCycleId': 'f',
            'toCycleId': 't',
            'carryDate': '2026-01-01',
            'hotelDayKey': '2026-01-01',
          },
          coll: 'salary_carry_over_logs',
        ),
      };

      cases.forEach((name, spec) {
        final filtered = AppwriteSyncUtils.filterPayloadForCollection(
          spec.coll,
          Map<String, dynamic>.from(spec.payload),
        );
        for (final key in spec.payload.keys) {
          expect(
            filtered.containsKey(key),
            isTrue,
            reason:
                'فجوة قص في $name: المفتاح "$key" يُرسل '
                'ولا ينجو من filterPayloadForCollection (صنف G-1b/G-2b)',
          );
        }
      });
    },
  );

  test(
    'الفهرس الفريد الجزئي: مرآة واحدة نشطة لكل expense_uuid (D1 0013)',
    () async {
      final emp = await insertEmployee('emp-u', 'موظف فهرس');
      const expenseUuid1 = 'exp-u-1';
      const expenseUuid2 = 'exp-u-2';

      Future<void> insertWithdrawal(String uuid, String? expenseUuid) async {
        await db
            .into(db.salaryWithdrawals)
            .insert(
              SalaryWithdrawalsCompanion.insert(
                employeeId: emp.id,
                amount: 10,
                withdrawDate: '2026-01-01',
                localUuid: uuid,
                employeeUuid: const d.Value('emp-u'),
                expenseUuid: expenseUuid == null
                    ? const d.Value.absent()
                    : d.Value(expenseUuid),
                createdAt: 0,
                updatedAt: 0,
                lastModified: 0,
                createdAtEpoch: const d.Value(0),
                lastModifiedEpoch: const d.Value(0),
                version: const d.Value(1),
                origin: const d.Value('local'),
                vectorClock: const d.Value('{}'),
              ),
            );
      }

      // أول مرآة نشطة لمصروف 1 — تُقبل
      await insertWithdrawal('w-1', expenseUuid1);
      // ثانية نشطة لنفس المصروف — يجب أن يرفضها القيد الفريد
      await expectLater(
        insertWithdrawal('w-2', expenseUuid1),
        throwsA(anything),
      );
      // سحبة ثانية لنفس المصروف لكن محذوفة ناعماً — مسموحة (فهرس جزئي)
      await db
          .into(db.salaryWithdrawals)
          .insert(
            SalaryWithdrawalsCompanion.insert(
              employeeId: emp.id,
              amount: 10,
              withdrawDate: '2026-01-01',
              localUuid: 'w-3',
              employeeUuid: const d.Value('emp-u'),
              expenseUuid: const d.Value(expenseUuid1),
              deletedAt: const d.Value(999),
              createdAt: 0,
              updatedAt: 0,
              lastModified: 0,
              createdAtEpoch: const d.Value(0),
              lastModifiedEpoch: const d.Value(0),
              version: const d.Value(1),
              origin: const d.Value('local'),
              vectorClock: const d.Value('{}'),
            ),
          );
      // سحبة نشطة لمصروف آخر — تُقبل
      await insertWithdrawal('w-4', expenseUuid2);
      // سحبة مباشرة بلا مصروف (expense_uuid NULL) — تُقبل (خارج نطاق القيد)
      await insertWithdrawal('w-5', null);
    },
  );

  test('تصنيف expenseKind حتمي من النوع المعلن (تحويل معجمي لا تخمين)', () {
    expect(
      SalaryExpenseClassifier.classifyExpenseKind('سلفة'),
      SalaryExpenseClassifier.kindSalaryAdvance,
    );
    expect(
      SalaryExpenseClassifier.classifyExpenseKind('سحب راتب'),
      SalaryExpenseClassifier.kindSalaryWithdrawal,
    );
    expect(
      SalaryExpenseClassifier.classifyExpenseKind('سحب من الراتب'),
      SalaryExpenseClassifier.kindSalaryWithdrawal,
    );
    expect(
      SalaryExpenseClassifier.classifyExpenseKind('رواتب'),
      SalaryExpenseClassifier.kindSalaryWithdrawal,
    );
    expect(
      SalaryExpenseClassifier.classifyExpenseKind('خصم من الراتب'),
      SalaryExpenseClassifier.kindSalaryDeduction,
    );
    expect(
      SalaryExpenseClassifier.classifyExpenseKind('غياب'),
      SalaryExpenseClassifier.kindSalaryDeduction,
    );
    expect(
      SalaryExpenseClassifier.classifyExpenseKind('كهرباء'),
      SalaryExpenseClassifier.kindNormal,
    );
    expect(
      SalaryExpenseClassifier.classifyExpenseKind(''),
      SalaryExpenseClassifier.kindUnclassified,
    );
    // الحارس: قيمة خارج العقد مرفوضة
    expect(SalaryExpenseClassifier.isAllowedExpenseKind('widget'), isFalse);
    expect(
      SalaryExpenseClassifier.isAllowedExpenseKind('salary_withdrawal'),
      isTrue,
    );
    expect(SalaryExpenseClassifier.isAllowedExpenseKind(null), isFalse);
  });
}
