package com.marina.marina.domain

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class Room(
    val id: Long = 0,
    val roomNumber: String = "",
    val type: String = "",
    val price: Double = 0.0,
    val status: String = "",
    val imageUrl: String? = null,
    val cleaningStatus: String = "clean",
    val requiresMaintenance: Boolean = false,
    val localUuid: String = "",
    val serverId: Int? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val deletedAt: Long? = null,
    val lastModified: Long = 0,
    val version: Int = 1,
    val origin: String = "local",
    val deviceId: String = "",
    val idempotencyKey: String? = null
) : Parcelable

@Parcelize
data class Booking(
    val id: Long = 0,
    val roomNumber: String = "",
    val guestName: String = "",
    val guestPhone: String = "",
    val guestIdType: String = "بطاقة شخصية",
    val guestIdNumber: String = "",
    val guestNationality: String = "",
    val checkinDate: String = "",
    val checkoutDate: String? = null,
    val status: String = "",
    val notes: String? = null,
    val discount: Double = 0.0,
    val discountType: String = "per_night",
    val expectedNights: Int = 1,
    val totalDueCached: Double = 0.0,
    val totalPaidCached: Double = 0.0,
    val remainingBalanceCached: Double = 0.0,
    val isFullyPaid: Boolean = false,
    val hotelDayCheckin: String? = null,
    val localUuid: String = "",
    val serverBookingId: Int? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val deletedAt: Long? = null,
    val lastModified: Long = 0,
    val version: Int = 1,
    val origin: String = "local",
    val deviceId: String = "",
    val idempotencyKey: String? = null
) : Parcelable

enum class PaymentMethod(val displayName: String, val displayNameAr: String) {
    CASH("Cash", "نقدي"),
    CARD("Card", "بطاقة ائتمانية"),
    TRANSFER("Transfer", "تحويل بنكي"),
    CHECK("Check", "شيك"),
    INSTALLMENT("Installment", "تقسيط");

    companion object {
        fun fromString(name: String): PaymentMethod =
            values().find { it.name == name } ?: CASH
    }
}

enum class PaymentStatus(val displayName: String, val displayNameAr: String) {
    PENDING("Pending", "في الانتظار"),
    COMPLETED("Completed", "مكتمل"),
    FAILED("Failed", "فشل"),
    REFUNDED("Refunded", "مسترد");

    companion object {
        fun fromString(name: String): PaymentStatus =
            values().find { it.name == name } ?: PENDING
    }
}

@Parcelize
data class Payment(
    val id: Long = 0,
    val bookingId: Long? = null,
    val roomNumber: String? = null,
    val amount: Double = 0.0,
    val paymentDate: String = "",
    val paymentMethod: String = "",
    val revenueType: String = "",
    val notes: String? = null,
    val referenceNumber: String? = null,
    val hotelDayKey: String? = null,
    val isVoided: Boolean = false,
    val receivedByName: String? = null,
    val localUuid: String = "",
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val version: Int = 1,
    val idempotencyKey: String? = null
) : Parcelable

@Parcelize
data class Employee(
    val id: Long = 0,
    val name: String = "",
    val basicSalary: Double = 0.0,
    val position: String = " موظف",
    val phone: String = "",
    val hireDate: String = "",
    val status: String = "",
    val terminationDate: String? = null,
    val employeeID: String? = null,
    val localUuid: String = "",
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val version: Int = 1
) : Parcelable

@Parcelize
data class Expense(
    val id: Long = 0,
    val expenseType: String = "",
    val description: String = "",
    val amount: Double = 0.0,
    val date: String = "",
    val hotelDayKey: String? = null,
    val categoryUuid: String? = null,
    val isAutoGenerated: Boolean = false,
    val localUuid: String = "",
    val createdAt: Long = 0,
    val updatedAt: Long = 0
) : Parcelable

@Parcelize
data class Debt(
    val id: Long = 0,
    val bookingId: Long? = null,
    val guestName: String = "",
    val checkinDate: String = "",
    val checkoutDate: String = "",
    val debtReason: String = "",
    val totalAmount: Double = 0.0,
    val paidAmount: Double = 0.0,
    val remainingAmount: Double = 0.0,
    val isSettled: Boolean = false,
    val paymentDate: String = "",
    val guestPhone: String? = null,
    val hotelDayOpened: String? = null,
    val localUuid: String = "",
    val createdAt: Long = 0
) : Parcelable

@Parcelize
data class BookingNote(
    val id: Long = 0,
    val bookingId: Long = 0,
    val noteText: String = "",
    val alertType: String = "",
    val isActive: Boolean = true,
    val localUuid: String = "",
    val createdAt: Long = 0
) : Parcelable

@Parcelize
data class ShiftNote(
    val id: Long = 0,
    val title: String = "",
    val content: String = "",
    val priority: String = "medium",
    val shiftType: String = "all",
    val isRead: Boolean = false,
    val createdBy: String = "user",
    val localUuid: String = "",
    val createdAt: Long = 0
) : Parcelable

@Parcelize
data class AuthUser(
    val id: Int = 0,
    val username: String = "",
    val fullName: String = "",
    val userType: String = "",
    val cloudUserId: String? = null,
    val permissions: List<String> = emptyList()
) : Parcelable {
    val name: String get() = if (fullName.isNotEmpty()) fullName else username
    val isAdmin: Boolean get() = userType == "admin" || permissions.contains("all")
}

@Parcelize
data class SyncState(
    val lastServerTs: Long = 0,
    val lastPullTs: Long = 0,
    val lastPushTs: Long = 0,
    val isSyncing: Boolean = false,
    val fullSyncComplete: Boolean = false
) : Parcelable