// ignore_for_file: lines_longer_than_80_chars
import 'package:drift/drift.dart' as d;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:marina_hotel_mobile/services/local_db.dart';
import 'package:marina_hotel_mobile/services/salary_entitlement_service.dart';
import 'package:marina_hotel_mobile/services/salary_expense_classifier.dart';

/// ✅ اختبارات المعادلة المحاسبية:
/// «مصروفات الرواتب يجب أن تساوي استحقاقات الموظف»
///
/// تغطي:
/// 1. السحب المباشر من شاشة الموظفين (salary_withdrawals فقط، بلا مصروف)
///    يجب أن يُخصم من استحقاق الموظف — كان مفقوداً تماماً قبل الإصلاح.
/// 2. السحب المرتبط بمصروف (مراية) لا يُعَد مرتين (dedup).
/// 3. السلفة تُحسب ضمن السلف (تدفق نقدي) وتُخصم من الاستحقاق.
/// 4. أقساط السلفة المولّدة تلقائياً تُحسب سداداً (لا خصماً جديداً).
/// 5. الخصوم اليدوية تُخصم من الاستحقاق.
/// 6. مرايا الخصوم السالبة في salary_withdrawals لا تُحتسب نقداً.
/// 7. الدورة الشهرية تحتسب السحب المباشر ضمن نطاقها الزمني فقط.
/// 8. المُصنِّف الموحّد: النقد = سحب + سلفة، والخصوم ليست نقداً.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late AppDatabase db;
  late SalaryEntitlementService service;

  setUp(() {
    db = AppDatabase.forTesting(NativeDatabase.memory());
    service = SalaryEntitlementService(db);
  });

  tearDown(() async {
    await db.close();
  });

  // ═══════════════════════════════════════════════════════════════════════
  // مساعدات
  // ═══════════════════════════════════════════════════════════════════════

  String _padded(int n) => n.toString().padLeft(2, '0');

  /// موظف براتب 1000 وتعيين منذ 12 شهراً بالضبط (اليوم 1 من الشهر)
  /// → إجمالي الاستحقاق = 12 × 1000 = 12000 بشكل حتمي.
  Future<int> createEmployee() async {
    final now = DateTime.now();
    final hire = DateTime(now.year - 1, now.month, 1);
    final hireStr = '${hire.year}-${_padded(hire.month)}-01';
    return db.into(db.employees).insert(
          EmployeesCompanion(
            name: const d.Value('موظف اختبار'),
            basicSalary: const d.Value(1000),
            status: const d.Value('active'),
            hireDate: d.Value(hireStr),
            localUuid: d.Value('emp-uuid-test'),
            createdAt: d.Value(1000),
            updatedAt: d.Value(1000),
            lastModified: d.Value(1000),
          ),
        );
  }

  Future<int> createExpense({
    required int employeeId,
    required String type,
    required double amount,
    String date = '2020-01-01',
    bool isAutoGenerated = false,
    String description = '',
  }) {
    return db.into(db.expenses).insert(
          ExpensesCompanion(
            expenseType: d.Value(type),
            relatedId: d.Value(employeeId),
            employeeUuid: d.Value('emp-uuid-test'),
            description: d.Value(description),
            amount: d.Value(amount),
            date: d.Value(date),
            hotelDayKey: d.Value(date),
            isAutoGenerated: d.Value(isAutoGenerated),
            localUuid: d.Value('exp-uuid-${DateTime.now().microsecondsSinceEpoch}-$amount'),
            createdAt: d.Value(1000),
            updatedAt: d.Value(1000),
            lastModified: d.Value(1000),
          ),
        );
  }

  /// سحب مباشر (بلا مصروف مقابل) — نفس ما تُنتجه شاشة الموظفين
  Future<int> createDirectWithdrawal({
    required int employeeId,
    required double amount,
    required String date,
    String? withdrawalType = 'سحب راتب',
    String? reason = 'direct_withdrawal_emp-uuid-test',
    String? reasonOverride,
  }) {
    return db.into(db.salaryWithdrawals).insert(
          SalaryWithdrawalsCompanion(
            employeeId: d.Value(employeeId),
            amount: d.Value(amount),
            withdrawDate: d.Value(date),
            reason: d.Value(reasonOverride ?? reason),
            withdrawalType: d.Value(withdrawalType),
            hotelDayKey: d.Value(date),
            localUuid: d.Value(
              'sw-uuid-${DateTime.now().microsecondsSinceEpoch}-$amount',
            ),
            createdAt: d.Value(1000),
            updatedAt: d.Value(1000),
            lastModified: d.Value(1000),
          ),
        );
  }

  /// ربط سحب بمصروف عبر العمود الخام expense_id (نفس _setExpenseIdRaw)
  Future<void> linkWithdrawalToExpense(int swId, int expenseId) async {
    await db.customStatement(
      'UPDATE salary_withdrawals SET expense_id = ? WHERE id = ?',
      [expenseId, swId],
    );
  }

  String _today() {
    final now = DateTime.now();
    return '${now.year}-${_padded(now.month)}-${_padded(now.day)}';
  }

  // ═══════════════════════════════════════════════════════════════════════
  // الاختبارات
  // ═══════════════════════════════════════════════════════════════════════

  group('المعادلة: مصروفات الرواتب = استحقاقات الموظف', () {
    test('بدون معاملات: الصافي = 12 شهر × 1000', () async {
      final empId = await createEmployee();
      final emp = await (db.select(
        db.employees,
      )..where((e) => e.id.equals(empId))).getSingle();

      final ent = await service.calculateEmployeeEntitlement(emp);
      expect(ent.totalEntitlement, 12000);
      expect(ent.totalWithdrawals, 0);
      expect(ent.netEntitlement, 12000);
    });

    test('السحب المباشر (بلا مصروف) يُخصم من الاستحقاق — الإصلاح الجوهري', () async {
      final empId = await createEmployee();
      final emp = await (db.select(
        db.employees,
      )..where((e) => e.id.equals(empId))).getSingle();

      // سحب مباشر من شاشة الموظفين: salary_withdrawals فقط
      await createDirectWithdrawal(
        employeeId: empId,
        amount: 4000,
        date: _today(),
      );

      final ent = await service.calculateEmployeeEntitlement(emp);
      expect(ent.totalWithdrawals, 4000);
      expect(ent.netEntitlement, 8000); // 12000 - 4000 (كان 12000 قبل الإصلاح!)
    });

    test('السحب المرتبط بمصروف لا يُعَد مرتين (dedup عبر expense_id)', () async {
      final empId = await createEmployee();
      final emp = await (db.select(
        db.employees,
      )..where((e) => e.id.equals(empId))).getSingle();

      // مصروف سحب راتب + مرايته المرتبطة (مسار شاشة المصروفات)
      final expenseId = await createExpense(
        employeeId: empId,
        type: 'سحب راتب',
        amount: 2500,
      );
      final swId = await createDirectWithdrawal(
        employeeId: empId,
        amount: 2500,
        date: '2020-01-01',
        reasonOverride: 'exp_$expenseId',
      );
      await linkWithdrawalToExpense(swId, expenseId);

      final ent = await service.calculateEmployeeEntitlement(emp);
      expect(ent.totalWithdrawals, 2500); // ليس 5000
      expect(ent.netEntitlement, 9500);
    });

    test('dedup عبر الرابط القديم reason=exp_N فقط (بلا عمود expense_id)', () async {
      final empId = await createEmployee();
      final emp = await (db.select(
        db.employees,
      )..where((e) => e.id.equals(empId))).getSingle();

      final expenseId = await createExpense(
        employeeId: empId,
        type: 'رواتب',
        amount: 1500,
      );
      await createDirectWithdrawal(
        employeeId: empId,
        amount: 1500,
        date: '2020-01-01',
        reasonOverride: 'exp_$expenseId',
        withdrawalType: null,
      );

      final ent = await service.calculateEmployeeEntitlement(emp);
      expect(ent.totalWithdrawals, 1500); // ليس 3000
    });

    test('السلفة تُحسب ضمن السلف وتُخصم من الصافي، وقسطها لا يُعَد خصماً', () async {
      final empId = await createEmployee();
      final emp = await (db.select(
        db.employees,
      )..where((e) => e.id.equals(empId))).getSingle();

      // سلفة 1000 + مرايتها
      final advanceExpId = await createExpense(
        employeeId: empId,
        type: 'سلفة',
        amount: 1000,
      );
      final swId = await createDirectWithdrawal(
        employeeId: empId,
        amount: 1000,
        date: '2020-01-01',
        withdrawalType: 'سلفة',
        reasonOverride: 'exp_$advanceExpId',
      );
      await linkWithdrawalToExpense(swId, advanceExpId);

      // قسط سلفة مولّد تلقائياً 300 — سداد لا خصم جديد
      await createExpense(
        employeeId: empId,
        type: 'خصم من الراتب',
        amount: 300,
        isAutoGenerated: true,
        description: 'قسط سلفة #$advanceExpId (1/3)',
      );

      final ent = await service.calculateEmployeeEntitlement(emp);
      expect(ent.totalAdvances, 1000);
      expect(ent.installmentsPaid, 300);
      expect(ent.totalDeductions, 0);
      expect(ent.netEntitlement, 11000); // 12000 - 1000
      expect(ent.advanceBalance, 700); // 1000 - 300
    });

    test('الخصم اليدوي يُخصم من الاستحقاق، ومراياه السالبة لا تُحتسب نقداً', () async {
      final empId = await createEmployee();
      final emp = await (db.select(
        db.employees,
      )..where((e) => e.id.equals(empId))).getSingle();

      // خصم يدوي من الراتب
      final dedExpId = await createExpense(
        employeeId: empId,
        type: 'خصم من الراتب',
        amount: 500,
      );
      // مراية الخصم سالبة في salary_withdrawals (كما يفعل saveFromExpense)
      final swId = await createDirectWithdrawal(
        employeeId: empId,
        amount: -500,
        date: '2020-01-01',
        withdrawalType: 'خصم من الراتب',
        reasonOverride: 'exp_$dedExpId',
      );
      await linkWithdrawalToExpense(swId, dedExpId);

      // خصم غياب آخر
      await createExpense(
        employeeId: empId,
        type: 'غياب',
        amount: 200,
      );

      final ent = await service.calculateEmployeeEntitlement(emp);
      expect(ent.totalDeductions, 700);
      expect(ent.totalWithdrawals, 0); // المراية السالبة ليست نقداً
      expect(ent.netEntitlement, 11300); // 12000 - 700
    });

    test('الدورة الشهرية تحتسب السحب المباشر ضمن نطاقها فقط', () async {
      final empId = await createEmployee();
      final emp = await (db.select(
        db.employees,
      )..where((e) => e.id.equals(empId))).getSingle();

      // سحب مباشر اليوم (داخل الدورة الحالية)
      await createDirectWithdrawal(
        employeeId: empId,
        amount: 300,
        date: _today(),
      );
      // سحب مباشر قديم (خارج الدورة الحالية)
      await createDirectWithdrawal(
        employeeId: empId,
        amount: 5000,
        date: '2020-01-01',
        reasonOverride: 'direct_withdrawal_old',
      );

      final cycle = await service.calculateCurrentCycle(emp);
      expect(cycle.totalWithdrawals, 300); // القديم خارج الدورة الحالية
      expect(cycle.availableToWithdraw, 700); // 1000 - 300
    });
  });

  group('المُصنِّف الموحّد SalaryExpenseClassifier', () {
    test('النقد الخارج: سحب + رواتب + سلفة', () {
      expect(SalaryExpenseClassifier.isSalaryCashOut('رواتب'), isTrue);
      expect(SalaryExpenseClassifier.isSalaryCashOut('سحب راتب'), isTrue);
      expect(SalaryExpenseClassifier.isSalaryCashOut('سحب من الراتب'), isTrue);
      expect(SalaryExpenseClassifier.isSalaryCashOut('سلفة'), isTrue);
      expect(SalaryExpenseClassifier.isSalaryCashOut(' سلفة '), isTrue);
    });

    test('الخصوم ليست نقداً خارجاً', () {
      expect(SalaryExpenseClassifier.isSalaryCashOut('خصم من الراتب'), isFalse);
      expect(SalaryExpenseClassifier.isSalaryCashOut('خصم راتب'), isFalse);
      expect(SalaryExpenseClassifier.isSalaryCashOut('غياب'), isFalse);
      expect(SalaryExpenseClassifier.isSalaryCashOut('ديزل'), isFalse);
      expect(SalaryExpenseClassifier.isSalaryCashOut(''), isFalse);
    });

    test('الخصوم تُصنف تسويات استحقاق', () {
      expect(SalaryExpenseClassifier.isSalaryDeduction('خصم من الراتب'), isTrue);
      expect(SalaryExpenseClassifier.isSalaryDeduction('خصم راتب'), isTrue);
      expect(SalaryExpenseClassifier.isSalaryDeduction('غياب'), isTrue);
      expect(SalaryExpenseClassifier.isSalaryDeduction('خصم'), isTrue);
      expect(SalaryExpenseClassifier.isSalaryDeduction('سلفة'), isFalse);
      expect(SalaryExpenseClassifier.isSalaryDeduction('سحب راتب'), isFalse);
    });

    test('سحب من نوع سلفة يُميَّز عبر isAdvanceWithdrawal', () {
      expect(SalaryExpenseClassifier.isAdvanceWithdrawal('سلفة'), isTrue);
      expect(SalaryExpenseClassifier.isAdvanceWithdrawal('سلفة عاجلة'), isTrue);
      expect(SalaryExpenseClassifier.isAdvanceWithdrawal('سحب راتب'), isFalse);
      expect(SalaryExpenseClassifier.isAdvanceWithdrawal(null), isFalse);
    });
  });
}
