package com.marina.marina.domain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/** Pure business model for an expense — no Room/Gson/Android persistence concerns. */
@Parcelize
data class Expense(
    val id: Long = 0,
    val expenseType: String = "",
    val relatedId: Long? = null,
    val description: String = "",
    val amount: Double = 0.0,
    val date: String = "",
    val hotelDayKey: String? = null,
    val categoryUuid: String? = null,
    val isAutoGenerated: Boolean = false,
    val employeeUuid: String? = null,
    val localUuid: String = "",
    val serverId: Int? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
    val deletedAt: Long? = null,
    val version: Int = 1
) : Parcelable
