package com.marina.marina.domain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class SalaryCycle(
    val id: Long = 0,
    val employeeId: Long = 0,
    val cycleKey: String = "",
    val hotelDayStart: String? = null,
    val hotelDayEnd: String? = null,
    val expectedAmount: Long = 0,
    val actualPaid: Long = 0,
    val remainingAmount: Long = 0,
    val status: String = "draft",
    val localUuid: String = "",
    val createdAt: Long = 0,
    val updatedAt: Long = 0
) : Parcelable

@Parcelize
data class SalaryPayment(
    val id: Long = 0,
    val cycleId: Long = 0,
    val amount: Long = 0,
    val hotelDayKey: String? = null,
    val paymentDateIso: String = "",
    val method: String? = null,
    val isAutoGenerated: Boolean = false,
    val localUuid: String = "",
    val createdAt: Long = 0
) : Parcelable

@Parcelize
data class SalaryCarryOverLog(
    val id: Long = 0,
    val employeeId: Long = 0,
    val amount: Double = 0.0,
    val previousCycleStart: String = "",
    val previousCycleEnd: String = "",
    val newCycleStart: String = "",
    val newCycleEnd: String = "",
    val reason: String = "",
    val carriedAt: Long = 0,
    val localUuid: String = ""
) : Parcelable
