package com.marina.marina.data.local.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.ColumnInfo
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName

@Entity(
    tableName = "expenses",
    indices = [
        Index(value = ["hotel_day_key"], name = "idx_expenses_hotel_day"),
        Index(value = ["category_uuid"], name = "idx_expenses_category"),
        Index(value = ["date"], name = "idx_expenses_date"),
        Index(value = ["hotel_day_key", "expense_type", "date"], name = "idx_expenses_active_hotel_day"),
        Index(value = ["date"], name = "idx_expenses_legacy_active_date"),
        Index(value = ["date"], orders = [androidx.room.Index.Order.DESC], name = "idx_expenses_active_date")
    ]
)
data class ExpenseEntity(
    @PrimaryKey(autoGenerate = true)
    @SerializedName("id")
    override val id: Long = 0,

    @SerializedName("expense_type")
    @ColumnInfo(name = "expense_type")
    val expenseType: String,

    @SerializedName("related_id")
    @ColumnInfo(name = "related_id")
    val relatedId: Long? = null,

    @SerializedName("description")
    val description: String,

    @SerializedName("amount")
    val amount: Double,

    @SerializedName("date")
    val date: String,

    @SerializedName("cash_transaction_id")
    @ColumnInfo(name = "cash_transaction_id")
    val cashTransactionId: Long? = null,

    @SerializedName("hotel_day_key")
    @ColumnInfo(name = "hotel_day_key")
    val hotelDayKey: String? = null,

    @SerializedName("category_uuid")
    @ColumnInfo(name = "category_uuid")
    val categoryUuid: String? = null,

    @SerializedName("cash_flow_uuid")
    @ColumnInfo(name = "cash_flow_uuid")
    val cashFlowUuid: String? = null,

    @SerializedName("is_auto_generated")
    @ColumnInfo(name = "is_auto_generated")
    val isAutoGenerated: Boolean = false,

    @SerializedName("employee_uuid")
    @ColumnInfo(name = "employee_uuid")
    val employeeUuid: String? = null,

    @SerializedName("local_uuid")
    @ColumnInfo(name = "local_uuid")
    override val localUuid: String = "",

    @SerializedName("server_id")
    @ColumnInfo(name = "server_id")
    override val serverId: Int? = null,

    @SerializedName("created_at")
    @ColumnInfo(name = "created_at")
    override val createdAt: Long = 0,

    @SerializedName("updated_at")
    @ColumnInfo(name = "updated_at")
    override val updatedAt: Long = 0,

    @SerializedName("deleted_at")
    @ColumnInfo(name = "deleted_at")
    override val deletedAt: Long? = null,

    @SerializedName("last_modified")
    @ColumnInfo(name = "last_modified")
    override val lastModified: Long = 0,

    @SerializedName("created_at_iso")
    @ColumnInfo(name = "created_at_iso")
    override val createdAtIso: String? = null,

    @SerializedName("updated_at_iso")
    @ColumnInfo(name = "updated_at_iso")
    override val updatedAtIso: String? = null,

    @SerializedName("deleted_at_iso")
    @ColumnInfo(name = "deleted_at_iso")
    override val deletedAtIso: String? = null,

    @SerializedName("created_at_epoch")
    @ColumnInfo(name = "created_at_epoch")
    override val createdAtEpoch: Long = 0,

    @SerializedName("last_modified_epoch")
    @ColumnInfo(name = "last_modified_epoch")
    override val lastModifiedEpoch: Long = 0,

    @SerializedName("version")
    override val version: Int = 1,

    @SerializedName("origin")
    override val origin: String = "local",

    @SerializedName("vector_clock")
    @ColumnInfo(name = "vector_clock")
    override val vectorClock: String = "{}",

    @SerializedName("device_id")
    @ColumnInfo(name = "device_id")
    override val deviceId: String = "",

    @SerializedName("sync_timestamp")
    @ColumnInfo(name = "sync_timestamp")
    override val syncTimestamp: Long = 0,

    @SerializedName("idempotency_key")
    @ColumnInfo(name = "idempotency_key")
    override val idempotencyKey: String? = null
) : BaseSyncEntity(
    id = id,
    localUuid = localUuid,
    serverId = serverId,
    createdAt = createdAt,
    updatedAt = updatedAt,
    deletedAt = deletedAt,
    lastModified = lastModified,
    createdAtIso = createdAtIso,
    updatedAtIso = updatedAtIso,
    deletedAtIso = deletedAtIso,
    createdAtEpoch = createdAtEpoch,
    lastModifiedEpoch = lastModifiedEpoch,
    version = version,
    origin = origin,
    vectorClock = vectorClock,
    deviceId = deviceId,
    syncTimestamp = syncTimestamp,
    idempotencyKey = idempotencyKey
)
