import 'package:drift/drift.dart';

import '../adapters/adapter_registry.dart';
import '../local_db.dart';
import 'outbox_dao.dart';

part 'expenses_dao.g.dart';

@DriftAccessor(tables: [Expenses])
class ExpensesDao extends DatabaseAccessor<AppDatabase> with _$ExpensesDaoMixin {
  ExpensesDao(super.db, this.outboxDao, this.adapters);
  final OutboxDao outboxDao;
  final AdapterRegistry adapters;

  Future<List<Expense>> list() async {
    return (select(expenses)..where((t) => t.deletedAt.isNull())..orderBy([(t) => OrderingTerm(expression: t.expenseDate, mode: OrderingMode.desc)])).get();
  }

  Stream<List<Expense>> watchAll() {
    return (select(expenses)..where((t) => t.deletedAt.isNull())..orderBy([(t) => OrderingTerm(expression: t.expenseDate, mode: OrderingMode.desc)])).watch();
  }

  Future<Expense?> getById(int id) => (select(expenses)..where((t) => t.id.equals(id))).getSingleOrNull();

  Future<int> insertOne(ExpensesCompanion data, {bool originIsServer = false}) async {
    return db.transaction(() async {
      final insertedId = await into(expenses).insert(data);
      if (!originIsServer) {
        // Outbox merge handled by repository layer
      }
      return insertedId;
    });
  }

  Future<int> updateById(int id, ExpensesCompanion data, {bool originIsServer = false}) async {
    return db.transaction(() async {
      final existing = await getById(id);
      if (existing == null) return 0;
      final comp = data.copyWith(
        updatedAt: Value(Time.nowEpoch()),
        lastModified: Value(Time.nowEpoch()),
        version: Value(existing.version + 1),
      );
      await update(expenses).replace(comp);
      if (!originIsServer) {
        // Outbox merge handled by repository layer
      }
      return 1;
    });
  }

  Future<int> softDelete(int id, {bool originIsServer = false}) async {
    return db.transaction(() async {
      final existing = await getById(id);
      if (existing == null) return 0;
      await (update(expenses)..where((t) => t.id.equals(id))).write(
        ExpensesCompanion(
          deletedAt: Value(Time.nowEpoch()),
          updatedAt: Value(Time.nowEpoch()),
          lastModified: Value(Time.nowEpoch()),
          version: Value(existing.version + 1),
        ),
      );
      if (!originIsServer) {
        // Outbox merge handled by repository layer
      }
      return 1;
    });
  }

  Future<int> getRecordCount() async {
    final query = selectOnly(expenses)..addColumns([expenses.id.count()]);
    final result = await query.getSingle();
    return result.read(expenses.id.count()) ?? 0;
  }

  Future<void> clearAllData() async {
    await delete(expenses).go();
  }

  Future<void> importFromJson(List<Map<String, dynamic>> data, {bool clearExisting = false}) async {
    await transaction(() async {
      if (clearExisting) {
        await delete(expenses).go();
      }
      for (final expJson in data) {
        final exp = Expense.fromJson(expJson);
        await into(expenses).insertOnConflictUpdate(
          ExpensesCompanion(
            id: Value(exp.id),
            localUuid: Value(exp.localUuid),
            serverId: Value(exp.serverId),
            expenseDate: Value(exp.expenseDate),
            expenseType: Value(exp.expenseType),
            amount: Value(exp.amount),
            description: Value(exp.description),
            paymentMethod: Value(exp.paymentMethod),
            categoryUuid: Value(exp.categoryUuid),
            cashFlowUuid: Value(exp.cashFlowUuid),
            relatedId: Value(exp.relatedId),
            isAutoGenerated: Value(exp.isAutoGenerated),
            hotelDayKey: Value(exp.hotelDayKey),
            createdAt: Value(exp.createdAt),
            updatedAt: Value(exp.updatedAt),
            deletedAt: Value(exp.deletedAt),
            lastModified: Value(exp.lastModified),
            version: Value(exp.version),
            origin: Value(exp.origin),
            createdAtIso: Value(exp.createdAtIso),
            updatedAtIso: Value(exp.updatedAtIso),
            deletedAtIso: Value(exp.deletedAtIso),
            createdAtEpoch: Value(exp.createdAtEpoch),
            lastModifiedEpoch: Value(exp.lastModifiedEpoch),
            vectorClock: Value(exp.vectorClock),
          ),
        );
      }
    });
  }

  Future<List<Map<String, dynamic>>> exportToJson() async {
    final list = await this.list();
    return list.map((e) => e.toJson()).toList();
  }
}
