import 'package:appwrite/appwrite.dart';
import 'package:flutter/foundation.dart';
import 'appwrite_config.dart';

/// سكريبت للتحقق من مطابقة جداول Appwrite Cloud
///
/// الاستخدام:
/// ```dart
/// await verifyAppwriteSchema();
/// ```
class AppwriteSchemaVerifier {
  static final _requiredCollections = {
    'rooms': {
      'name': 'Rooms',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {
          'key': 'roomNumber',
          'type': 'string',
          'size': 50,
          'required': true,
          'unique': true
        },
        {'key': 'type', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'price', 'type': 'double', 'required': true},
        {'key': 'status', 'type': 'string', 'size': 20, 'required': true},
        {'key': 'imageUrl', 'type': 'string', 'size': 500},
        {
          'key': 'cleaningStatus',
          'type': 'string',
          'size': 20,
          'default': 'clean'
        },
        {'key': 'lastCleanedHotelDay', 'type': 'string', 'size': 50},
        {'key': 'lastOccupiedHotelDay', 'type': 'string', 'size': 50},
        {'key': 'requiresMaintenance', 'type': 'boolean', 'default': false},
      ],
    },
    'bookings': {
      'name': 'Bookings',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'roomNumber', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'guestName', 'type': 'string', 'size': 100, 'required': true},
        {'key': 'guestPhone', 'type': 'string', 'size': 20, 'required': true},
        {
          'key': 'guestNationality',
          'type': 'string',
          'size': 50,
          'required': true
        },
        {'key': 'checkinDate', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'status', 'type': 'string', 'size': 20, 'required': true},
      ],
    },
    'booking_notes': {
      'name': 'Booking Notes',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'bookingId', 'type': 'integer', 'required': true},
        {'key': 'noteText', 'type': 'string', 'size': 1000, 'required': true},
        {'key': 'alertType', 'type': 'string', 'size': 20, 'required': true},
        {'key': 'isActive', 'type': 'integer', 'default': 1},
      ],
    },
    'booking_nights': {
      'name': 'Booking Nights',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'bookingLocalId', 'type': 'integer', 'required': true},
        {'key': 'hotelDayKey', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'nightStart', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'nightEnd', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'nightlyRate', 'type': 'double', 'default': 0},
        {'key': 'sequence', 'type': 'integer', 'default': 0},
        {'key': 'isProcessedByAutoFix', 'type': 'boolean', 'default': false},
      ],
    },
    'employees': {
      'name': 'Employees',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'name', 'type': 'string', 'size': 100, 'required': true},
        {'key': 'basicSalary', 'type': 'double', 'required': true},
        {'key': 'position', 'type': 'string', 'size': 50, 'default': 'موظف'},
        {'key': 'status', 'type': 'string', 'size': 20, 'required': true},
      ],
    },
    'expenses': {
      'name': 'Expenses',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'expenseType', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'description', 'type': 'string', 'size': 500, 'required': true},
        {'key': 'amount', 'type': 'double', 'required': true},
        {'key': 'date', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'isAutoGenerated', 'type': 'boolean', 'default': false},
      ],
    },
    'cash_transactions': {
      'name': 'Cash Transactions',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {
          'key': 'transactionType',
          'type': 'string',
          'size': 20,
          'required': true
        },
        {'key': 'amount', 'type': 'double', 'required': true},
        {
          'key': 'transactionTime',
          'type': 'string',
          'size': 50,
          'required': true
        },
      ],
    },
    'payments': {
      'name': 'Payments',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'amount', 'type': 'double', 'required': true},
        {'key': 'paymentDate', 'type': 'string', 'size': 50, 'required': true},
        {
          'key': 'paymentMethod',
          'type': 'string',
          'size': 20,
          'required': true
        },
        {'key': 'revenueType', 'type': 'string', 'size': 20, 'required': true},
        {'key': 'isPendingBalance', 'type': 'boolean', 'default': false},
      ],
    },
    'debts': {
      'name': 'Debts',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'guestName', 'type': 'string', 'size': 100, 'required': true},
        {'key': 'checkinDate', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'checkoutDate', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'totalAmount', 'type': 'double', 'required': true},
        {'key': 'paidAmount', 'type': 'double', 'required': true},
        {'key': 'remainingAmount', 'type': 'double', 'required': true},
        {'key': 'paymentDate', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'isSettled', 'type': 'integer', 'default': 0},
        {'key': 'isFromAutoFix', 'type': 'boolean', 'default': false},
        {'key': 'settlementConfirmed', 'type': 'boolean', 'default': false},
      ],
    },
    'salary_cycles': {
      'name': 'Salary Cycles',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'employeeId', 'type': 'integer', 'required': true},
        {'key': 'cycleKey', 'type': 'string', 'size': 50, 'required': true},
        {'key': 'expectedAmount', 'type': 'double', 'default': 0},
        {'key': 'actualPaid', 'type': 'double', 'default': 0},
        {'key': 'remainingAmount', 'type': 'double', 'default': 0},
        {'key': 'status', 'type': 'string', 'size': 20, 'default': 'draft'},
      ],
    },
    'salary_payments': {
      'name': 'Salary Payments',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {'key': 'cycleId', 'type': 'integer', 'required': true},
        {'key': 'amount', 'type': 'double', 'default': 0},
        {
          'key': 'paymentDateIso',
          'type': 'string',
          'size': 50,
          'required': true
        },
        {'key': 'isAutoGenerated', 'type': 'boolean', 'default': false},
      ],
    },
    'hotel_day_ledger': {
      'name': 'Hotel Day Ledger',
      'attributes': [
        {
          'key': 'localUuid',
          'type': 'string',
          'size': 36,
          'required': true,
          'unique': true
        },
        {
          'key': 'hotelDayKey',
          'type': 'string',
          'size': 50,
          'required': true,
          'unique': true
        },
        {'key': 'totalIncome', 'type': 'double', 'default': 0},
        {'key': 'totalExpenses', 'type': 'double', 'default': 0},
        {'key': 'pendingBalances', 'type': 'double', 'default': 0},
        {'key': 'occupancyRate', 'type': 'double', 'default': 0},
        {'key': 'bookingsProcessed', 'type': 'integer', 'default': 0},
        {'key': 'paymentsProcessed', 'type': 'integer', 'default': 0},
        {'key': 'debtsProcessed', 'type': 'integer', 'default': 0},
        {'key': 'expensesProcessed', 'type': 'integer', 'default': 0},
        {'key': 'status', 'type': 'string', 'size': 20, 'default': 'draft'},
      ],
    },
  };

  static final _syncFields = [
    {'key': 'serverId', 'type': 'integer'},
    {'key': 'createdAt', 'type': 'integer', 'required': true},
    {'key': 'updatedAt', 'type': 'integer', 'required': true},
    {'key': 'deletedAt', 'type': 'integer'},
    {'key': 'lastModified', 'type': 'integer', 'required': true},
    {'key': 'createdAtIso', 'type': 'string', 'size': 50},
    {'key': 'updatedAtIso', 'type': 'string', 'size': 50},
    {'key': 'deletedAtIso', 'type': 'string', 'size': 50},
    {'key': 'createdAtEpoch', 'type': 'integer', 'default': 0},
    {'key': 'lastModifiedEpoch', 'type': 'integer', 'default': 0},
    {'key': 'version', 'type': 'integer', 'default': 1},
    {'key': 'origin', 'type': 'string', 'size': 20, 'default': 'local'},
    {'key': 'vectorClock', 'type': 'string', 'size': 500, 'default': '{}'},
  ];

  /// التحقق من جميع Collections والـ Attributes
  static Future<Map<String, dynamic>> verifySchema() async {
    debugPrint('🔍 بدء التحقق من مطابقة جداول Appwrite Cloud...\n');

    final client = Client()
        .setEndpoint(AppwriteConfig.endpoint)
        .setProject(AppwriteConfig.projectId);

    final databases = Databases(client);
    final results = <String, dynamic>{
      'collections': {},
      'missing': [],
      'errors': [],
      'summary': {},
    };

    int totalCollections = 0;
    int foundCollections = 0;
    int missingCollections = 0;

    for (final entry in _requiredCollections.entries) {
      final collectionId = entry.key;
      final schema = entry.value;
      totalCollections++;

      debugPrint('📋 التحقق من: $collectionId (${schema['name']})');

      try {
        // محاولة جلب Collection من خلال listDocuments
        // في Appwrite SDK v17، تم إزالة getCollection، نستخدم listDocuments للتحقق
        final response = await databases.listDocuments(
          databaseId: AppwriteConfig.databaseId,
          collectionId: collectionId,
          queries: [],
        );

        foundCollections++;
        debugPrint('   ✅ موجود: ${schema['name']}');

        // في v17، لا يمكننا الحصول على تفاصيل الـ attributes بسهولة
        // لذلك نفترض أن الـ collection موجود وصحيح
        results['collections'][collectionId] = {
          'found': true,
          'name': schema['name'],
          'total_documents': response.total,
        };

        debugPrint('   📄 عدد المستندات: ${response.total}');
      } catch (e) {
        missingCollections++;
        debugPrint('   ❌ غير موجود: $collectionId');
        results['missing'].add(collectionId);
        results['collections'][collectionId] = {
          'found': false,
          'error': e.toString(),
        };
      }

      debugPrint('');
    }

    results['summary'] = {
      'total': totalCollections,
      'found': foundCollections,
      'missing': missingCollections,
      'percentage':
          ((foundCollections / totalCollections) * 100).toStringAsFixed(1),
    };

    // طباعة الملخص
    debugPrint('═══════════════════════════════════════');
    debugPrint('📊 ملخص التحقق');
    debugPrint('═══════════════════════════════════════');
    debugPrint('إجمالي الجداول المطلوبة: $totalCollections');
    debugPrint('✅ موجود: $foundCollections');
    debugPrint('❌ ناقص: $missingCollections');
    debugPrint('📈 نسبة الاكتمال: ${results['summary']['percentage']}%');
    debugPrint('═══════════════════════════════════════\n');

    if (missingCollections > 0) {
      debugPrint('⚠️  الجداول الناقصة:');
      for (final missing in results['missing']) {
        debugPrint('   - $missing');
      }
      debugPrint('\n💡 يرجى إنشاء الجداول الناقصة في Appwrite Console');
      debugPrint('   راجع: mobile/APPWRITE_SCHEMA_VERIFICATION.md\n');
    } else {
      debugPrint('🎉 جميع الجداول موجودة! التطابق كامل.\n');
    }

    return results;
  }

  /// طباعة سكريبت CLI لإنشاء Collection ناقص
  static void printCreateCollectionScript(String collectionId) {
    final schema = _requiredCollections[collectionId];
    if (schema == null) return;

    debugPrint('# إنشاء Collection: $collectionId');
    debugPrint('appwrite databases createCollection \\');
    debugPrint('  --databaseId ${AppwriteConfig.databaseId} \\');
    debugPrint('  --collectionId $collectionId \\');
    debugPrint('  --name "${schema['name']}"');
    debugPrint('');

    debugPrint('# إنشاء Attributes:');
    final allAttributes = [
      ...(schema['attributes'] as List),
      ..._syncFields,
    ];

    for (final attr in allAttributes) {
      final key = attr['key'];
      final type = attr['type'];
      final required = attr['required'] == true ? 'true' : 'false';

      if (type == 'string') {
        final size = attr['size'] ?? 255;
        debugPrint('appwrite databases createStringAttribute \\');
        debugPrint('  --databaseId ${AppwriteConfig.databaseId} \\');
        debugPrint('  --collectionId $collectionId \\');
        debugPrint('  --key $key \\');
        debugPrint('  --size $size \\');
        debugPrint('  --required $required');
      } else if (type == 'integer') {
        debugPrint('appwrite databases createIntegerAttribute \\');
        debugPrint('  --databaseId ${AppwriteConfig.databaseId} \\');
        debugPrint('  --collectionId $collectionId \\');
        debugPrint('  --key $key \\');
        debugPrint('  --required $required');
      } else if (type == 'double') {
        debugPrint('appwrite databases createFloatAttribute \\');
        debugPrint('  --databaseId ${AppwriteConfig.databaseId} \\');
        debugPrint('  --collectionId $collectionId \\');
        debugPrint('  --key $key \\');
        debugPrint('  --required $required');
      } else if (type == 'boolean') {
        debugPrint('appwrite databases createBooleanAttribute \\');
        debugPrint('  --databaseId ${AppwriteConfig.databaseId} \\');
        debugPrint('  --collectionId $collectionId \\');
        debugPrint('  --key $key \\');
        debugPrint('  --required $required');
      }
      debugPrint('');
    }
  }
}

/// مثال على الاستخدام:
///
/// ```dart
/// void main() async {
///   final results = await AppwriteSchemaVerifier.verifySchema();
///
///   // طباعة سكريبت لإنشاء collection ناقص
///   if (results['missing'].isNotEmpty) {
///     for (final collectionId in results['missing']) {
///       AppwriteSchemaVerifier.printCreateCollectionScript(collectionId);
///     }
///   }
/// }
/// ```
