import '../utils/hotel_date_helper.dart';

/// فئة أدوات موحدة لمعالجة البيانات قبل إرسالها أو بعد سحبها من Appwrite
class AppwriteSyncUtils {
  /// الحقول التي يجب تحويلها إلى أعداد صحيحة (بناءً على قيود Appwrite الحالية)
  /// ⚠️ تم التحديث بناءً على فحص Appwrite Cloud الفعلي (2026-05-15)
  /// - cash_transactions.amount: integer على Cloud ✓
  /// - salary_withdrawals.amount: integer على Cloud ✓
  /// - payment_voids.voidedAmount: integer على Cloud ✓
  /// - booking_price_adjustments.amount: integer على Cloud ✓ (أُضيف 2026-05-15)
  /// - debts.remainingAmount: integer على Cloud ✓ (أُضيف 2026-05-15)
  /// - debts.totalAmount/paidAmount: double على Cloud (لا تحتاج تحويل)
  static const Map<String, Set<String>> _intAmountFields = {
    'cash_transactions': {'amount'},
    'salary_withdrawals': {'amount'},
    'payment_voids': {'voidedAmount'},
    'booking_price_adjustments': {'amount'},
    'debts': {'remainingAmount'},
  };

  // ══════════════════════════════════════════════════════════════════════════
  // مخطط حقول Appwrite Cloud الفعلي — تم تدقيقه في 2026-06-14
  // ⚠️ هذا هو المصدر الوحيد للحقيقة — لا تخمن حقولاً!
  // أي حقل غير موجود هنا سيُزال تلقائياً قبل الإرسال لمنع "Unknown attribute"
  // ══════════════════════════════════════════════════════════════════════════
  static const Map<String, Set<String>> validFieldsPerCollection = {
    'rooms': {
      'cleaningStatus', 'createdAt', 'createdAtEpoch', 'createdAtIso',
      'deletedAt', 'deletedAtIso', 'deviceId', 'idempotencyKey', 'imageUrl',
      'lastCleanedHotelDay', 'lastModified', 'lastModifiedEpoch',
      'lastOccupiedHotelDay', 'localUuid', 'origin', 'price',
      'requiresMaintenance', 'roomNumber', 'roomType', 'serverId',
      'status', 'type', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'bookings': {
      'actualCheckout', 'checkinDate', 'checkoutDate', 'guestAddress',
      'guestEmail', 'guestIdIssueDate', 'guestIdIssuePlace', 'guestIdNumber',
      'guestIdType', 'guestName', 'guestNationality', 'guestPhone',
      'hotelDayCheckin', 'hotelDayCheckout', 'isFullyPaid', 'isOverdue',
      'lastNightEpoch', 'localUuid', 'needsCheckoutReview', 'notes',
      'roomNumber', 'serverBookingId', 'serverId', 'status', 'stayDurationIso',
      // ✅ إصلاح حرج لمنع فقدان التحديثات (Lost Update):
      // هذه الحقول كانت مفقودة من المخطط المحلي، مما يسبب:
      //   1. filterPayloadForCollection يحذفها قبل الرفع → مستند Appwrite
      //      لا يحتوي على lastModified/version/origin/deletedAt إلخ.
      //   2. عند السحب، _isRemoteDataNewer يجد lastModified=null في البيان
      //      البعيد → كان يرجع true (احتياطاً) → يستبدل المحلي الأحدث بالبعيد القديم
      //   3. النتيجة: نزيل تم تسجيل مغادرته على جهاز 1 يُعاد إلى "محجوز"
      //      على جهاز 2 بعد السحب الكامل
      // الآن هذه الحقول مُضافة لتضمن:
      //   - رفع lastModified/version/origin/deletedAt مع كل تغيير
      //   - حل التعارضات بشكل صحيح (Last Write Wins) عبر مقارنة lastModified
      //   - منع استبدال الأحدث بالأقدم
      'createdAt', 'createdAtEpoch', 'createdAtIso',
      'updatedAt', 'updatedAtIso',
      'deletedAt', 'deletedAtIso',
      'lastModified', 'lastModifiedEpoch',
      'version', 'origin', 'vectorClock',
      'deviceId',
      // حقول إضافية محسوبة موجودة في نموذج Booking
      'calculatedNights', 'expectedNights', 'totalNightsCached',
      'totalDueCached', 'totalPaidCached', 'remainingBalanceCached',
      'discount', 'discountType', 'discountStartDate',
      // ✅ إصلاح (2026-06-27): حقول موجودة على Appwrite Cloud لكن لم تكن مُدرجة
      // — كانت تُحذف بواسطة filterPayloadForCollection قبل الرفع
      'financialFrozenAt',   // integer? — تاريخ تجميد الحسابات المالية
      'financialHash',       // string? (64) — هاش للحالة المالية
      'syncTimestamp',       // integer? — طابع زمني للمزامنة
      'sync_origin',         // string? (64) — مصدر المزامنة (snake_case)
      'idempotencyKey',      // string? (255) — مفتاح Idempotency
      'id',                  // integer? — معرف (optional على Cloud)
    },
    'expenses': {
      'amount', 'cashFlowUuid', 'cashTransactionId', 'categoryUuid',
      'createdAt', 'createdAtEpoch', 'createdAtIso', 'date', 'deletedAt',
      'deletedAtIso', 'description', 'deviceId', 'expenseType', 'hotelDayKey',
      'idempotencyKey', 'isAutoGenerated', 'lastModified', 'lastModifiedEpoch',
      'localUuid', 'origin', 'relatedId', 'serverId', 'updatedAt',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'employees': {
      'basicSalary', 'createdAt', 'createdAtEpoch', 'createdAtIso',
      'deletedAt', 'deletedAtIso', 'deviceId', 'EmployeeID', 'hireDate',
      'id', 'idempotencyKey', 'lastModified', 'lastModifiedEpoch', 'localUuid',
      'name', 'origin', 'phone', 'position', 'serverId', 'status',
      'syncTimestamp', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'debts': {
      'bookingLocalId', 'checkinDate', 'checkoutDate', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'dateRecorded', 'debtReason',
      'debtUuid', 'deletedAt', 'deletedAtIso', 'deviceId', 'guestName',
      'hotelDayClosed', 'hotelDayOpened', 'idempotencyKey', 'isFromAutoFix',
      'isSettled', 'lastModified', 'lastModifiedEpoch', 'localUuid', 'note',
      'origin', 'paidAmount', 'paymentDate', 'pledge', 'pledgeType',
      'remainingAmount', 'serverId', 'settlementConfirmed', 'totalAmount',
      'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'booking_notes': {
      'alertType', 'alertUntil', 'bookingId', 'bookingUuid', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'deletedAt', 'deletedAtIso',
      'deviceId', 'idempotencyKey', 'isActive', 'lastModified',
      'lastModifiedEpoch', 'localUuid', 'note', 'noteText', 'origin',
      'serverId', 'sync_origin', 'syncTimestamp', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'booking_nights': {
      'baseRate', 'bookingLocalId', 'createdAt', 'createdAtEpoch',
      'createdAtIso', 'deletedAt', 'deletedAtIso', 'deviceId', 'hotelDayKey',
      'idempotencyKey', 'isProcessedByAutoFix', 'lastModified',
      'lastModifiedEpoch', 'localUuid', 'nightEnd', 'nightlyRate',
      'nightStart', 'origin', 'sequence', 'serverId', 'syncTimestamp',
      'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'cash_transactions': {
      'amount', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'createdBy',
      'deletedAt', 'deletedAtIso', 'description', 'deviceId',
      'idempotencyKey', 'lastModified', 'lastModifiedEpoch', 'localUuid',
      'origin', 'referenceId', 'referenceType', 'registerId', 'serverId',
      'syncTimestamp', 'transactionTime', 'transactionType', 'updatedAt',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'shift_notes': {
      'content', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'createdBy',
      'deletedAt', 'deletedAtIso', 'deviceId', 'expiresAt', 'idempotencyKey',
      'isRead', 'lastModified', 'lastModifiedEpoch', 'localUuid', 'origin',
      'priority', 'serverId', 'shiftDate', 'shiftType', 'syncTimestamp',
      'title', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'salary_cycles': {
      'actualPaid', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'cycleKey',
      'deletedAt', 'deletedAtIso', 'deviceId', 'employeeId', 'expectedAmount',
      'hotelDayEnd', 'hotelDayStart', 'idempotencyKey', 'lastModified',
      'lastModifiedEpoch', 'localUuid', 'origin', 'remainingAmount',
      'serverId', 'status', 'syncTimestamp', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'salary_payments': {
      'createdAt', 'createdAtEpoch', 'createdAtIso', 'cycleId', 'deletedAt',
      'deletedAtIso', 'deviceId', 'employeeId', 'hotelDayKey',
      'idempotencyKey', 'isAutoGenerated', 'lastModified', 'lastModifiedEpoch',
      'localUuid', 'method', 'notes', 'origin', 'paymentDate',
      'paymentDateIso', 'serverId', 'syncTimestamp', 'updatedAt',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'salary_withdrawals': {
      'action', 'amount', 'createdAt', 'createdAtEpoch', 'createdAtIso',
      'date', 'deletedAt', 'deletedAtIso', 'description', 'deviceId',
      'employeeId', 'employeeLocalUuid', 'employeeUuid', 'expenseId',
      'hotelDayKey', 'id', 'idempotencyKey', 'lastModified',
      'lastModifiedEpoch', 'localUuid', 'name', 'note', 'origin', 'reason',
      'serverId', 'syncTimestamp', 'sync_origin', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version', 'withdrawDate', 'withdrawalType',
    },
    'salary_carry_over_logs': {
      'amount', 'carriedAt', 'createdAt', 'createdAtEpoch', 'createdAtIso',
      'deletedAt', 'deletedAtIso', 'deviceId', 'employeeId', 'id',
      'lastModified', 'lastModifiedEpoch', 'localUuid', 'newCycleEnd',
      'newCycleStart', 'origin', 'previousCycleEnd', 'previousCycleStart',
      'reason', 'serverId', 'updatedAt', 'updatedAtIso', 'vectorClock',
      'version',
    },
    'price_adjustments': {
      'adjustmentMode', 'adjustmentType', 'appliedBy', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'deletedAt', 'deletedAtIso', 'deviceId',
      'effectiveDate', 'hotelDayKey', 'idempotencyKey', 'isReversed',
      'lastModified', 'lastModifiedEpoch', 'localUuid', 'newValue', 'origin',
      'previousValue', 'reason', 'reversedAt', 'reversedBy', 'roomNumber',
      'serverId', 'syncTimestamp', 'targetType', 'targetUuid', 'updatedAt',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'booking_price_adjustments': {
      'adjustmentMode', 'adjustmentType', 'appliedBy', 'bookingLocalId',
      'bookingLocalUuid', 'cancelledAt', 'cancelledBy', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'deletedAt', 'deletedAtIso',
      'deviceId', 'effectiveHotelDay', 'endHotelDay', 'idempotencyKey',
      'isActive', 'lastModified', 'lastModifiedEpoch', 'localUuid', 'origin',
      'reason', 'serverId', 'updatedAt', 'updatedAtIso', 'vectorClock',
      'version',
    },
    'audit_logs': {
      'action', 'amountImpact', 'changedFields', 'createdAt', 'deletedAt',
      'deviceId', 'entityId', 'entityType', 'entityUuid', 'hotelDayKey',
      'ipAddress', 'isFinancial', 'lastModified', 'localUuid', 'newState',
      'operationType', 'origin', 'performedBy', 'previousState',
      'syncTimestamp', 'timestamp', 'timestampIso', 'updatedAt',
      'vectorClock', 'version',
    },
    'payment_voids': {
      'approvedBy', 'bookingUuid', 'createdAt', 'createdAtEpoch',
      'createdAtIso', 'deletedAt', 'deletedAtIso', 'deviceId',
      'hotelDayKey', 'idempotencyKey', 'lastModified', 'lastModifiedEpoch',
      'localUuid', 'note', 'origin', 'originalAmount', 'originalPaymentId',
      'originalPaymentUuid', 'paymentUuid', 'reversalPaymentUuid', 'serverId',
      'syncTimestamp', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
      'voidedAmount', 'voidedAt', 'voidedAtIso', 'voidedBy', 'voidReason',
    },
    'guest_infos': {
      'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'deviceId', 'governorate', 'guestName', 'id',
      'idempotencyKey', 'idNumber', 'idType', 'issueDate', 'issuePlace',
      'lastModified', 'lastModifiedEpoch', 'localUuid', 'nationality', 'notes',
      'origin', 'roomNumber', 'serverId', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'blacklist': {
      'active', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'deviceId', 'idempotencyKey', 'lastModified',
      'lastModifiedEpoch', 'localUuid', 'name', 'nationalId', 'nationality',
      'notes', 'origin', 'phone', 'reason', 'reportedBy', 'serverId',
      'syncTimestamp', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'devices': {
      'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'deviceId', 'deviceModel', 'deviceName', 'deviceType',
      'fcmToken', 'isActive', 'lastActive', 'lastModified',
      'lastModifiedEpoch', 'lastSeen', 'localUuid', 'origin', 'osVersion',
      'serverId', 'status', 'syncTimestamp', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'sync_logs': {
      'action', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'details', 'deviceId', 'direction', 'endTime',
      'errorMessage', 'lastModified', 'lastModifiedEpoch', 'localUuid',
      'origin', 'serverId', 'startTime', 'status', 'syncId', 'syncType',
      'timestamp', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'app_settings': {
      // واتساب
      'wa_api_type', 'wa_api_base_url', 'wa_api_instance_id', 'wa_api_token',
      'wa_custom_url_template', 'wa_sendzen_api_key', 'wa_sendzen_from_number',
      'wa_template',
      // تيليجرام
      'telegram_enabled', 'telegram_bot_token', 'telegram_chat_id',
      'telegram_notifications_enabled', 'telegram_daily_report_enabled',
      'telegram_daily_report_time',
      // إعدادات الفندق
      'hotel_name', 'hotel_cutoff_hour', 'dark_mode',
      // لارك (Lark)
      'lark_enabled', 'lark_app_id', 'lark_app_secret', 'lark_webhook_url',
      'lark_daily_report_enabled', 'lark_daily_report_time',
      'lark_daily_report_chat_id', 'lark_notifications_enabled',
      // إعدادات المزامنة
      'appwrite_sync_interval', 'appwrite_auto_sync_on_connect',
      'appwrite_log_level', 'appwrite_log_file', 'appwrite_log_console',
      'conflict_strategy', 'sync_performance_profile', 'wifi_only_sync',
      'sync_origin',
      // النسخ الاحتياطي التلقائي
      'auto_backup_time', 'auto_backup_frequency', 'scheduled_backup_enabled',
      // إعدادات الوجهة الثانوية (secondary_appwrite_config مخزن كـ JSON string)
      'secondary_appwrite_config', 'enabled', 'endpoint', 'project_id',
      'database_id', 'api_key', 'push_enabled', 'pull_enabled',
      // مفاتيح عامة
      'key', 'value', 'createdAt', 'updatedAt',
      // SyncFields
      'localUuid', 'serverId', 'deletedAt', 'lastModified', 'version',
      'origin', 'vectorClock', 'deviceId', 'createdAtEpoch',
      'lastModifiedEpoch', 'createdAtIso', 'updatedAtIso', 'deletedAtIso',
      'syncTimestamp',
    },
    'outbox': {
      'createdAt', 'deletedAt', 'isRead', 'lastModified', 'localUuid',
      'message', 'origin', 'recipient', 'sentAt', 'serverId', 'updatedAt',
      'version',
    },
    'sync_state': {
      'createdAt', 'deletedAt', 'isSyncing', 'lastModified', 'lastSyncTime',
      'localUuid', 'origin', 'serverId', 'sync_origin', 'updatedAt', 'version',
    },
    'app_users': {
      'active', 'credentials_version', 'full_name', 'fullName', 'last_login',
      'lastLogin', 'password', 'permissions', 'sync_origin', 'user_type',
      'username', 'userType', 'version',
    },
  };

  /// تصفية الحمولة — إبقاء فقط الحقول الموجودة في مخطط Appwrite الفعلي
  /// ⚠️ هذا يمنع خطأ "Unknown attribute" نهائياً
  /// إذا لم يكن المجموعة معروفة، يتم إرجاع الحمولة كما هي (بدون تصفية)
  static Map<String, dynamic> filterPayloadForCollection(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final validFields = validFieldsPerCollection[collectionId];
    if (validFields == null) return payload; // مجموعة غير معروفة — لا نصفي

    final result = <String, dynamic>{};
    for (final entry in payload.entries) {
      if (validFields.contains(entry.key)) {
        result[entry.key] = entry.value;
      }
    }
    return result;
  }

  /// تطهير البيانات وإزالة الحقول غير المدعومة أو المحسوبة
  static Map<String, dynamic> sanitizePayload(
    String entity,
    Map<String, dynamic> payload, {
    String? collectionId,
  }) {
    var result = Map<String, dynamic>.from(payload);

    // 1. إزالة الحقول المحسوبة التي لا تُخزن في Appwrite
    result = HotelDateHelper.stripComputedFieldsForEntity(entity, result);

    // 2. إزالة الحقول التقنية الخاصة بـ Drift أو Appwrite metadata إذا وجدت
    result.remove('id'); // المعرف المحلي التلقائي
    result.remove('\u0024id');
    result.remove('\u0024createdAt');
    result.remove('\u0024updatedAt');
    result.remove('\u0024permissions');
    result.remove('\u0024databaseId');
    result.remove('\u0024collectionId');

    // 3. إزالة حقول Delta Sync الداخلية التي لا وجود لها في مخطط Appwrite
    //    هذه الحقول تُضاف بواسطة DeltaSyncService.compute() و _preparePayload()
    result.remove('row_hash');       // حقل داخلي — ليس في أي مجموعة Appwrite
    result.remove('client_ts');      // حقل داخلي

    // 4. تحويل أسماء الحقول من snake_case إلى camelCase
    //    ⚠️ حرج: Appwrite Cloud يستخدم camelCase في جميع المجموعات المتزامنة
    //    (deletedAt, lastModified, localUuid, إلخ)
    //    بينما Delta Sync Push يرسل snake_case (deleted_at, last_modified, local_uuid)
    //    بدون هذا التحويل، يتجاهل Appwrite الحقول مثل deleted_at → الجهاز الآخر
    //    لا يرى softDelete → يرى 30 بدلاً من 15
    result = _convertKeysToCamelCase(result);

    // 5. بعد التحويل: إزالة الحقول الداخلية بأسمائها camelCase
    result.remove('rowHash');        // من row_hash
    result.remove('clientTs');       // من client_ts

    // 6. تحويل الأنواع المالية إذا لزم الأمر
    if (collectionId != null) {
      result = convertAmountTypesForAppwrite(collectionId, result);
    }

    // 7. ⚠️ تصفية نهائية: إبقاء فقط الحقول الموجودة في مخطط Appwrite الفعلي
    //    هذا يمنع خطأ "Unknown attribute" نهائياً — بغض النظر عن مصدر الحقل
    if (collectionId != null) {
      result = filterPayloadForCollection(collectionId, result);
    }

    return result;
  }

  /// تحويل جميع مفاتيح الخريطة من snake_case إلى camelCase بشكل متكرر
  /// الحقول التي لا تحتوي على _ تُترك كما هي (مثل amount, notes)
  static Map<String, dynamic> _convertKeysToCamelCase(
    Map<String, dynamic> input,
  ) {
    final result = <String, dynamic>{};
    for (final entry in input.entries) {
      final camelKey = toCamelCase(entry.key);
      final value = entry.value;
      if (value is Map<String, dynamic>) {
        result[camelKey] = _convertKeysToCamelCase(value);
      } else if (value is List) {
        result[camelKey] = value.map((item) {
          if (item is Map<String, dynamic>) {
            return _convertKeysToCamelCase(item);
          }
          return item;
        }).toList();
      } else {
        result[camelKey] = value;
      }
    }
    return result;
  }

  /// تحويل حقول المبالغ إلى أعداد صحيحة للمجموعات التي تتطلب ذلك
  static Map<String, dynamic> convertAmountTypesForAppwrite(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final intFields = _intAmountFields[collectionId];
    if (intFields == null || intFields.isEmpty) return payload;

    final result = Map<String, dynamic>.from(payload);
    for (final field in intFields) {
      if (result.containsKey(field) && result[field] is num) {
        result[field] = (result[field] as num).round();
      }
    }
    return result;
  }

  /// تحويل حقول المبالغ من أعداد صحيحة (Cloud) إلى double (محلي)
  /// يُستخدم عند سحب البيانات من Appwrite Cloud إلى قاعدة البيانات المحلية
  static Map<String, dynamic> convertAmountTypesFromAppwrite(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final intFields = _intAmountFields[collectionId];
    if (intFields == null || intFields.isEmpty) return payload;

    final result = Map<String, dynamic>.from(payload);
    for (final field in intFields) {
      if (result.containsKey(field) && result[field] is num) {
        // تحويل integer إلى double للمحلي (مثلاً 5000 → 5000.0)
        result[field] = (result[field] as num).toDouble();
      }
    }
    return result;
  }

  /// الحقول التي يجب أن تبقى snake_case في Appwrite (لا تُحوّل إلى camelCase)
  /// ⚠️ تم تدقيقها مقابل مخطط Appwrite الفعلي (2026-06-14)
  /// فقط الحقول snake_case الموجودة فعلاً في مخطط Appwrite تُضاف هنا
  /// ❌ sync_vector_clock غير موجود في أي مجموعة — لا يُضاف
  static const Set<String> _preserveSnakeCase = {
    'sync_origin',  // موجود فقط في: booking_notes, sync_state, app_users
    // app_settings كلها snake_case — لكنها تُرسل مباشرة بدون toCamelCase
  };

  /// تحويل أسماء الحقول من snake_case إلى camelCase (للتوافق مع Appwrite)
  /// ⚠️ الحقول في _preserveSnakeCase لا تُحوّل لأن Appwrite يتطلبها snake_case
  static String toCamelCase(String input) {
    if (!input.contains('_')) return input;
    if (_preserveSnakeCase.contains(input)) return input;
    final parts = input.split('_');
    final first = parts.first;
    final rest = parts
        .skip(1)
        .map((p) => p.isEmpty ? '' : '${p[0].toUpperCase()}${p.substring(1)}');
    return '$first${rest.join()}';
  }
}
