import '../utils/hotel_date_helper.dart';
import 'dart:convert';

/// فئة أدوات موحدة لمعالجة البيانات قبل إرسالها أو بعد سحبها من Appwrite
class AppwriteSyncUtils {
  // ══════════════════════════════════════════════════════════════════════════
  // ✅ الخيار 2: مفاتيح app_settings النصّية (WhatsApp/Telegram) التي تُجمَّع
  // في حقل واحد `config_json` بدل أعمدة منفصلة، لتفادي حدّ حجم الصف في Appwrite.
  // تُستخدم في الرفع (تجميع) والسحب (تفكيك) معاً لضمان التماثل.
  // ⚠️ مصدر وحيد للحقيقة — يجب استخدامه في Primary و Secondary معاً (DRY).
  // 🔒 ملاحظة أمنية: لا تُضِف 'api_key' هنا — رفعه للسحابة يُخزّن مفتاح الوصول
  //    داخل النظام الذي يحميه (ثغرة أمنية). ولا 'appwrite_log_level' (إعداد محلي).
  // ══════════════════════════════════════════════════════════════════════════
  static const List<String> appSettingsConfigKeys = [
    'wa_api_type',
    'wa_api_base_url',
    'wa_api_instance_id',
    'wa_api_token',
    'wa_custom_url_template',
    'wa_sendzen_api_key',
    'wa_sendzen_from_number',
    'telegram_bot_token',
    'telegram_chat_id',
  ];

  // ══════════════════════════════════════════════════════════════════════════
  // ✅ Field Projection (Pull) — تقليل السحب على مستوى السجل
  // ──────────────────────────────────────────────────────────────────────────
  // بدل جلب كل حقول المستند في كل سحب، نطلب فقط الحقول المعروفة للتطبيق عبر
  // Query.select. القائمة مشتقّة من `validFieldsPerCollection` (نفس مصدر الحقيقة
  // المستخدم في تصفية الرفع)، لذا فالسحب متماثل مع الرفع تماماً: أي حقل لا يرفعه
  // التطبيق لا يُطلب عند السحب — بلا فقدان بيانات فعلي.
  //
  // 🔒 kill-switch: اجعل [fieldProjectionEnabled] = false لتعطيلها فوراً والعودة
  //    لجلب المستند الكامل دون أي تغييرات أخرى.
  // 🛟 أمان: مسار السحب في AppwriteService يُعيد المحاولة تلقائياً بدون select إن
  //    فشل بسبب سمة غير موجودة (حقل قديم في القائمة) — فلا تتعطّل مزامنة كولكشن.
  // ══════════════════════════════════════════════════════════════════════════
  static bool fieldProjectionEnabled = true;

  /// حقول نظام Appwrite التي يعتمد عليها مسار السحب/حل التعارض دائماً.
  static const List<String> _systemSelectFields = [
    r'$id',
    r'$createdAt',
    r'$updatedAt',
  ];

  /// يُعيد قائمة السمات المطلوبة عبر Query.select للكولكشن [collectionId]،
  /// أو null إذا كانت الإسقاطات معطّلة أو الكولكشن غير معروف (→ يُجلب المستند كاملاً).
  static List<String>? selectFieldsFor(String collectionId) {
    if (!fieldProjectionEnabled) {
      return null;
    }
    final fields = validFieldsPerCollection[collectionId];
    if (fields == null || fields.isEmpty) {
      return null;
    }
    return [...fields, ..._systemSelectFields];
  }

  /// الحقول التي يجب تحويلها إلى أعداد صحيحة (بناءً على قيود Appwrite الحالية)
  /// ⚠️ تم التحديث بناءً على الجداول الفعلية (remainingAmount وسواها أصبحت double)
  /// - payment_voids.voidedAmount: integer على Cloud ✓ (المتبقي الوحيد)
  static const Map<String, Set<String>> _intAmountFields = {
    'payment_voids': {'voidedAmount'},
  };

  // ══════════════════════════════════════════════════════════════════════════
  // مخطط حقول Appwrite Cloud الفعلي — تم تدقيقه في 2026-06-14
  // ⚠️ هذا هو المصدر الوحيد للحقيقة — لا تخمن حقولاً!
  // أي حقل غير موجود هنا سيُزال تلقائياً قبل الإرسال لمنع "Unknown attribute"
  // ══════════════════════════════════════════════════════════════════════════
  static const Map<String, Set<String>> validFieldsPerCollection = {
    'app_settings': {
      // ✅ الإصلاح: حذف 'api_key' (لا يُرفع للسحابة — ثغرة أمنية، ولا يُستخدم
      //    في _appSettingsToMap أصلاً) و 'appwrite_log_level' (إعداد محلي فقط).
      //    كلاهما محذوف من SCHEMA في unified_appwrite_setup.js — إبقاؤهما هنا
      //    يُضلّل المُطوّر ويُخاطر بتمريرهما عبر _filterPayload في المستقبل.
      'appwrite_auto_sync_on_connect',
      'appwrite_log_console',
      'appwrite_log_file',
      'appwrite_sync_interval',
      'auto_backup_frequency',
      'auto_backup_time',
      'conflict_strategy',
      // ✅ الخيار 2: مفاتيح WhatsApp/Telegram النصّية مُجمّعة في config_json
      'config_json',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'dark_mode',
      'database_id',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'enabled',
      'endpoint',
      'hotel_cutoff_hour',
      'hotel_name',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'origin',
      'project_id',
      'pull_enabled',
      'push_enabled',
      'scheduled_backup_enabled',
      'secondary_appwrite_config',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'sync_performance_profile',
      'telegram_bot_token',
      'telegram_chat_id',
      'telegram_daily_report_enabled',
      'telegram_daily_report_time',
      'telegram_enabled',
      'telegram_notifications_enabled',
      'updatedAt',
      'updatedAtIso',
      'version',
      'wa_api_base_url',
      'wa_api_instance_id',
      'wa_api_token',
      'wa_api_type',
      'wa_custom_url_template',
      'wa_sendzen_api_key',
      'wa_sendzen_from_number',
      'wifi_only_sync',
    },
    'app_users': {
      'active',
      'credentials_version',
      'full_name',
      'last_login',
      'lastModifiedEpoch',
      'password',
      'permissions',
      'role',
      'syncTimestamp',
      'userType',
      'user_type',
      'username',
      'version',
      'localUuid',
      'createdAt',
      'updatedAt',
      'lastModified',
      'vectorClock',
      'deviceId',
    },
    'audit_logs': {
      'action',
      'amountImpact',
      'changedFields',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'entityId',
      'entityType',
      'entityUuid',
      'hotelDayKey',
      'appliedDate',
      'idempotencyKey',
      'ipAddress',
      'isFinancial',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'newState',
      'operationType',
      'origin',
      'performedBy',
      'previousState',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'timestamp',
      'timestampIso',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'blacklist': {
      'active',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'name',
      'nationalId',
      'nationality',
      'notes',
      'origin',
      'phone',
      'reason',
      'reportedBy',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'booking_nights': {
      'adjustment',
      'appliedAdjustmentUuid',
      'appliedAdjustmentsJson',
      'baseRate',
      'bookingLocalId',
      'bookingUuidCache',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'finalRate',
      'hotelDayKey',
      'appliedDate',
      'idempotencyKey',
      'isProcessedByAutoFix',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'nightEnd',
      'nightStart',
      'nightlyRate',
      'origin',
      'sequence',
      'serverBookingId',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'booking_notes': {
      'alertType',
      'alertUntil',
      'bookingId',
      'bookingUuidCache',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'id',
      'idempotencyKey',
      'isActive',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'noteText',
      'origin',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'booking_price_adjustments': {
      'adjustmentMode',
      'adjustmentType',
      'amount',
      'appliedAt',
      'appliedBy',
      'bookingLocalId',
      'bookingLocalUuid',
      'bookingUuid',
      'cancelledAt',
      'cancelledBy',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'effectiveHotelDay',
      'endHotelDay',
      'hotelDayKey',
      'appliedDate',
      'idempotencyKey',
      'isActive',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'origin',
      'reason',
      'roomNumber',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'bookings': {
      'actualCheckout',
      'calculatedNights',
      'checkinDate',
      'checkoutDate',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'discount',
      'discountStartDate',
      'discountType',
      'amount',
      'expectedNights',
      'financialFrozenAt',
      'financialHash',
      'guestAddress',
      'guestEmail',
      'guestIdIssueDate',
      'guestIdIssuePlace',
      'guestIdNumber',
      'guestIdType',
      'guestName',
      'guestNationality',
      'guestPhone',
      'hotelDayCheckin',
      'hotelDayCheckout',
      'id',
      'idempotencyKey',
      'isFullyPaid',
      'isOverdue',
      'lastModified',
      'lastModifiedEpoch',
      'lastNightEpoch',
      'localUuid',
      'needsCheckoutReview',
      'notes',
      'origin',
      'remainingBalanceCached',
      'roomNumber',
      'serverBookingId',
      'serverId',
      'status',
      'stayDurationIso',
      'syncTimestamp',
      'sync_origin',
      'totalDueCached',
      'totalNightsCached',
      'totalPaidCached',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'cash_transactions': {
      'amount',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'createdBy',
      'deletedAt',
      'deletedAtIso',
      'description',
      'deviceId',
      'id',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'origin',
      'referenceId',
      'referenceType',
      'registerId',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'transactionTime',
      'transactionType',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'debts': {
      'amount',
      'bookingLocalId',
      'bookingUuidCache',
      'checkinDate',
      'checkoutDate',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'date',
      'dateRecorded',
      'debtReason',
      'debtUuid',
      'debtorName',
      'deletedAt',
      'deletedAtIso',
      'description',
      'deviceId',
      'dueDate',
      'guestName',
      'guestPhone',
      'hotelDayClosed',
      'hotelDayOpened',
      'id',
      'idempotencyKey',
      'isFromAutoFix',
      'isSettled',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'note',
      'origin',
      'paidAmount',
      'paymentDate',
      'pledge',
      'pledgeType',
      'remainingAmount',
      'serverId',
      'settlementConfirmed',
      'status',
      'syncTimestamp',
      'sync_origin',
      'sync_vector_clock',
      'sync_version',
      'totalAmount',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'devices': {
      'appVersion',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'deviceModel',
      'deviceName',
      'deviceType',
      'fcmToken',
      'idempotencyKey',
      'isActive',
      'lastActive',
      'lastModified',
      'lastModifiedEpoch',
      'lastSeen',
      'localUuid',
      'origin',
      'osVersion',
      'platform',
      'serverId',
      'status',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'employees': {
      'EmployeeID',
      'basicSalary',
      'salary',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'hireDate',
      'id',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'name',
      'origin',
      'phone',
      'position',
      'serverId',
      'status',
      'syncTimestamp',
      'sync_origin',
      'terminationDate',
      'terminationReason',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'expenses': {
      'amount',
      'cashFlowUuid',
      'cashTransactionId',
      'categoryUuid',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'date',
      'deletedAt',
      'deletedAtIso',
      'description',
      'deviceId',
      'employeeUuid',
      'expenseType',
      'hotelDayKey',
      'id',
      'idempotencyKey',
      'isAutoGenerated',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'origin',
      'relatedId',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'guest_infos': {
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'governorate',
      'guestName',
      'idNumber',
      'idType',
      'idempotencyKey',
      'issueDate',
      'issuePlace',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'nationality',
      'notes',
      'origin',
      'roomNumber',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'payment_voids': {
      'approvedBy',
      'bookingUuid',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'hotelDayKey',
      'appliedDate',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'note',
      'origin',
      'originalAmount',
      'originalPaymentId',
      'originalPaymentUuid',
      'paymentUuid',
      'reversalPaymentUuid',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
      'voidReason',
      'voidedAmount',
      'voidedAt',
      'voidedAtIso',
      'voidedBy',
    },
    'payments': {
      'amount',
      'bookingLocalId',
      'bookingUuidCache',
      'cashTransactionLocalId',
      'cashTransactionServerId',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'discountAmount',
      'discountStartDate',
      'hotelDayKey',
      'id',
      'idempotencyKey',
      'isImmutable',
      'isPendingBalance',
      'isVoided',
      'lastModified',
      'lastModifiedEpoch',
      'linkedDebtUuid',
      'localUuid',
      'notes',
      'origin',
      'paymentDate',
      'paymentMethod',
      'referenceNumber',
      'revenueType',
      'receivedByName',
      'receivedByUserId',
      'receivedSessionUuid',
      'receivedByCloudId',
      'roomNumber',
      'serverBookingId',
      'serverId',
      'serverPaymentId',
      'syncTimestamp',
      'sync_origin',
      'sync_vector_clock',
      'sync_version',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
      'voidReason',
      'voidedAt',
      'voidedBy',
    },
    'price_adjustments': {
      'adjustmentMode',
      'adjustmentType',
      'appliedBy',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'effectiveDate',
      'hotelDayKey',
      'appliedDate',
      'idempotencyKey',
      'isReversed',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'newValue',
      'origin',
      'previousValue',
      'reason',
      'reversedAt',
      'reversedBy',
      'roomNumber',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'targetType',
      'targetUuid',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'inventory_items': {
      'category',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'idempotencyKey',
      'isActive',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'minimumQuantity',
      'name',
      'origin',
      'quantity',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'unit',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'inventory_transactions': {
      'balanceAfter',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'idempotencyKey',
      'itemId',
      'itemLocalUuid',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'movementType',
      'note',
      'origin',
      'quantity',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'userId',
      'userName',
      'vectorClock',
      'version',
    },
    'rooms': {
      'basePrice',
      'bedsCount',
      'cleaningStatus',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'floor',
      'id',
      'idempotencyKey',
      'imageUrl',
      'lastCleanedHotelDay',
      'lastModified',
      'lastModifiedEpoch',
      'lastOccupiedHotelDay',
      'localUuid',
      'origin',
      'price',
      'requiresMaintenance',
      'roomNumber',
      'roomType',
      'serverId',
      'status',
      'syncTimestamp',
      'sync_origin',
      'type',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'salary_carry_over_logs': {
      'amount',
      'carriedAt',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'employeeId',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'newCycleEnd',
      'newCycleStart',
      'origin',
      'previousCycleEnd',
      'previousCycleStart',
      'reason',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'salary_cycles': {
      'actualPaid',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'cycleKey',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'employeeId',
      'expectedAmount',
      'hotelDayEnd',
      'hotelDayStart',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'origin',
      'remainingAmount',
      'serverId',
      'status',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'salary_payments': {
      'amount',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'cycleId',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'hotelDayKey',
      'id',
      'idempotencyKey',
      'isAutoGenerated',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'method',
      'origin',
      'paymentDateIso',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'salary_withdrawals': {
      'action',
      'amount',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'date',
      'deletedAt',
      'deletedAtIso',
      'description',
      'deviceId',
      'employeeId',
      'employeeLocalUuid',
      'employeeUuid',
      'expenseId',
      'hotelDayKey',
      'appliedDate',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'name',
      'note',
      'origin',
      'reason',
      'serverId',
      'syncTimestamp',
      'sync_origin',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
      'withdrawDate',
      'withdrawalDate',
      'withdrawalType',
    },
    'shift_notes': {
      'content',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'createdBy',
      'deletedAt',
      'deletedAtIso',
      'deviceId',
      'expiresAt',
      'id',
      'idempotencyKey',
      'isRead',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'note',
      'origin',
      'priority',
      'serverId',
      'shiftDate',
      'shiftType',
      'syncTimestamp',
      'sync_origin',
      'title',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'sync_logs': {
      'action',
      'changesDownloaded',
      'changesUploaded',
      'checksumMatched',
      'collection',
      'conflicts',
      'createdAt',
      'createdAtEpoch',
      'createdAtIso',
      'deletedAt',
      'deletedAtIso',
      'details',
      'deviceId',
      'direction',
      'documentId',
      'durationMs',
      'endTime',
      'errorMessage',
      'errors',
      'idempotencyKey',
      'lastModified',
      'lastModifiedEpoch',
      'localUuid',
      'metadata',
      'operation',
      'operations',
      'origin',
      'records',
      'recordsPulled',
      'recordsPushed',
      'serverId',
      'startTime',
      'status',
      'syncId',
      'syncTimestamp',
      'syncType',
      'sync_origin',
      'timestamp',
      'timestampIso',
      'updatedAt',
      'updatedAtIso',
      'vectorClock',
      'version',
    },
    'sync_state': {
      'createdAt',
      'deletedAt',
      'isSyncing',
      'lastModified',
      'lastSyncTime',
      'localUuid',
      'origin',
      'serverId',
      'sync_origin',
      'updatedAt',
      'version',
    },
  };

  // ══════════════════════════════════════════════════════════════════════════
  // مخطط Appwrite Cloud الفعلي — خريطة (حقل → نوع)
  // ⚠️ هذا هو المصدر الوحيد للحقيقة — لا تخمن حقولاً!
  // أي حقل غير موجود هنا سيُزال تلقائياً قبل الإرسال لمنع "Unknown attribute"
  // ══════════════════════════════════════════════════════════════════════════
  static const Map<String, Map<String, String>> collectionSchema = {
    'inventory_items': {
      'localUuid': 'string',
      'name': 'string',
      'unit': 'string',
      'category': 'string',
      'quantity': 'integer',
      'minimumQuantity': 'integer',
      'isActive': 'boolean',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'syncTimestamp': 'integer',
      'deviceId': 'string',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'sync_origin': 'string',
      'idempotencyKey': 'string',
    },
    'inventory_transactions': {
      'localUuid': 'string',
      'itemLocalUuid': 'string',
      'itemId': 'integer',
      'movementType': 'string',
      'quantity': 'integer',
      'balanceAfter': 'integer',
      'note': 'string',
      'userId': 'integer',
      'userName': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'syncTimestamp': 'integer',
      'deviceId': 'string',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'sync_origin': 'string',
      'idempotencyKey': 'string',
    },
    'rooms': {
      'localUuid': 'string',
      'roomNumber': 'string',
      'type': 'string',
      'price': 'double',
      'status': 'string',
      'imageUrl': 'string',
      'cleaningStatus': 'string',
      'lastCleanedHotelDay': 'string',
      'lastOccupiedHotelDay': 'string',
      'requiresMaintenance': 'boolean',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'syncTimestamp': 'integer',
      'deviceId': 'string',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'sync_origin': 'string',
      'idempotencyKey': 'string',
    },
    'bookings': {
      'localUuid': 'string',
      'serverBookingId': 'integer',
      'roomNumber': 'string',
      'guestName': 'string',
      'guestPhone': 'string',
      'guestIdType': 'string',
      'guestIdNumber': 'string',
      'guestIdIssueDate': 'string',
      'guestIdIssuePlace': 'string',
      'guestNationality': 'string',
      'guestEmail': 'string',
      'guestAddress': 'string',
      'checkinDate': 'string',
      'checkoutDate': 'string',
      'actualCheckout': 'string',
      'status': 'string',
      'notes': 'string',
      'expectedNights': 'integer',
      'calculatedNights': 'integer',
      'totalNightsCached': 'integer',
      'stayDurationIso': 'string',
      'lastNightEpoch': 'integer',
      'isOverdue': 'boolean',
      'needsCheckoutReview': 'boolean',
      'totalDueCached': 'double',
      'totalPaidCached': 'double',
      'remainingBalanceCached': 'double',
      'isFullyPaid': 'boolean',
      'discount': 'double',
      // حقل amount الموحّد لجدول bookings (مطابق للمخطط الموحّد
      // unified_appwrite_setup.js). القيمة مشتقّة من totalDueCached في
      // payload_mapper، ويُبقيها الفلتر ليطابق الأساسية والثانوية.
      'amount': 'double',
      'discountType': 'string',
      'discountStartDate': 'string',
      'hotelDayCheckin': 'string',
      'hotelDayCheckout': 'string',
      'financialFrozenAt': 'integer',
      'financialHash': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'syncTimestamp': 'integer',
      'deviceId': 'string',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'sync_origin': 'string',
      'idempotencyKey': 'string',
    },
    'payments': {
      'localUuid': 'string',
      'serverPaymentId': 'integer',
      'bookingLocalId': 'integer',
      'serverBookingId': 'integer',
      'roomNumber': 'string',
      'amount': 'double',
      'paymentDate': 'string',
      'notes': 'string',
      'paymentMethod': 'string',
      'revenueType': 'string',
      'cashTransactionLocalId': 'integer',
      'cashTransactionServerId': 'integer',
      'referenceNumber': 'string',
      'hotelDayKey': 'string',
      'isPendingBalance': 'boolean',
      'linkedDebtUuid': 'string',
      'bookingUuidCache': 'string',
      'isVoided': 'boolean',
      'voidedAt': 'integer',
      'voidedBy': 'string',
      'voidReason': 'string',
      'isImmutable': 'boolean',
      'discountAmount': 'double',
      'discountStartDate': 'string',
      'receivedByUserId': 'integer',
      'receivedByName': 'string',
      'receivedSessionUuid': 'string',
      'receivedByCloudId': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'syncTimestamp': 'integer',
      'deviceId': 'string',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'sync_origin': 'string',
      'idempotencyKey': 'string',
    },
    'expenses': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'expenseType': 'string',
      'relatedId': 'integer',
      'description': 'string',
      'amount': 'double',
      'date': 'string',
      'cashTransactionId': 'integer',
      'hotelDayKey': 'string',
      'categoryUuid': 'string',
      'cashFlowUuid': 'string',
      'isAutoGenerated': 'boolean',
      'employeeUuid': 'string',
    },
    'debts': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'bookingLocalId': 'integer',
      'bookingUuidCache': 'string',
      'guestName': 'string',
      'checkinDate': 'string',
      'checkoutDate': 'string',
      'dateRecorded': 'string',
      'debtReason': 'string',
      'totalAmount': 'double',
      'paidAmount': 'double',
      'remainingAmount': 'double',
      'paymentDate': 'string',
      'isSettled': 'boolean',
      'pledge': 'string',
      'pledgeType': 'string',
      'note': 'string',
      'debtUuid': 'string',
      'hotelDayOpened': 'string',
      'hotelDayClosed': 'string',
      'isFromAutoFix': 'boolean',
      'settlementConfirmed': 'boolean',
      'amount': 'double',
      'date': 'string',
      'debtorName': 'string',
      'description': 'string',
      'dueDate': 'string',
      'guestPhone': 'string',
      'status': 'string',
    },
    'employees': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'name': 'string',
      'basicSalary': 'double',
      'salary': 'double',
      'position': 'string',
      'phone': 'string',
      'hireDate': 'string',
      'status': 'string',
      'terminationDate': 'string',
      'terminationReason': 'string',
      'EmployeeID': 'string',
    },
    'booking_notes': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'bookingId': 'integer',
      'noteText': 'string',
      'alertType': 'string',
      'alertUntil': 'string',
      'isActive': 'boolean',
      'bookingUuidCache': 'string',
    },
    'booking_nights': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'bookingLocalId': 'integer',
      'bookingUuidCache': 'string',
      'hotelDayKey': 'string',
      'nightStart': 'string',
      'nightEnd': 'string',
      'nightlyRate': 'double',
      'sequence': 'integer',
      'isProcessedByAutoFix': 'boolean',
      'baseRate': 'double',
      'adjustment': 'double',
      'finalRate': 'double',
      'appliedAdjustmentUuid': 'string',
      'appliedAdjustmentsJson': 'string',
      'serverBookingId': 'integer',
    },
    'cash_transactions': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'registerId': 'integer',
      'transactionType': 'string',
      'amount': 'double',
      'referenceType': 'string',
      'referenceId': 'integer',
      'description': 'string',
      'transactionTime': 'string',
      'createdBy': 'string',
    },
    'salary_cycles': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'employeeId': 'integer',
      'cycleKey': 'string',
      'hotelDayStart': 'string',
      'hotelDayEnd': 'string',
      'expectedAmount': 'integer',
      'actualPaid': 'integer',
      'remainingAmount': 'integer',
      'status': 'string',
    },
    'salary_payments': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'cycleId': 'integer',
      'amount': 'integer',
      'hotelDayKey': 'string',
      'paymentDateIso': 'string',
      'method': 'string',
      'isAutoGenerated': 'boolean',
    },
    'salary_withdrawals': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'employeeId': 'integer',
      'employeeLocalUuid': 'string',
      'employeeUuid': 'string',
      'amount': 'double',
      'withdrawDate': 'string',
      'withdrawalDate': 'string',
      'reason': 'string',
      'hotelDayKey': 'string',
      'withdrawalType': 'string',
      'description': 'string',
      'expenseId': 'integer',
      'name': 'string',
      'note': 'string',
      'action': 'string',
      'date': 'string',
    },
    'salary_carry_over_logs': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'employeeId': 'integer',
      'amount': 'double',
      'previousCycleStart': 'string',
      'previousCycleEnd': 'string',
      'newCycleStart': 'string',
      'newCycleEnd': 'string',
      'reason': 'string',
      'carriedAt': 'integer',
    },
    'blacklist': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'string',
      'updatedAt': 'string',
      'deletedAt': 'string',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'name': 'string',
      'nationality': 'string',
      'nationalId': 'string',
      'phone': 'string',
      'reason': 'string',
      'notes': 'string',
      'reportedBy': 'string',
      'active': 'boolean',
      'guestName': 'string',
      'guestPhone': 'string',
      'guestIdNumber': 'string',
      'isActive': 'boolean',
      'addedDate': 'string',
      'addedBy': 'string',
    },
    'shift_notes': {
      'localUuid': 'string',
      'serverId': 'integer',
      // يجب أن يطابق مخطط Appwrite الموحد: epoch seconds في integer.
      // القيمة النصية كانت تُرسل بسبب هذا التعريف وتسبب document_invalid_structure.
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'title': 'string',
      'content': 'string',
      'priority': 'string',
      'shiftType': 'string',
      'isRead': 'boolean',
      'expiresAt': 'string',
      'createdBy': 'string',
      'note': 'string',
      'shiftDate': 'string',
    },
    'price_adjustments': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'targetType': 'string',
      'targetUuid': 'string',
      'adjustmentType': 'string',
      // ✅ نوع مطابق للنشر الفعلي (double على الوجهتين)؛ المحوّل يحوّل double→int
      'previousValue': 'double',
      'newValue': 'double',
      'reason': 'string',
      'effectiveDate': 'string',
      'appliedBy': 'string',
      'hotelDayKey': 'string',
      'isReversed': 'boolean',
      'reversedAt': 'string',
      'reversedBy': 'string',
    },
    'booking_price_adjustments': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'bookingLocalUuid': 'string',
      'bookingUuid': 'string',
      'bookingLocalId': 'integer',
      'roomNumber': 'string',
      'adjustmentType': 'integer',
      'adjustmentMode': 'string',
      'amount': 'double',
      'effectiveHotelDay': 'string',
      // ✅ إصلاح 2026-07-26: hotelDayKey مطلوب على Appwrite Cloud
      // محلياً effectiveHotelDay = hotelDayKey (نفس القيمة، اسم مختلف)
      'hotelDayKey': 'string',
      'appliedDate': 'string',
      'endHotelDay': 'string',
      'isActive': 'boolean',
      'reason': 'string',
      'appliedBy': 'string',
      'appliedAt': 'integer',
      'cancelledAt': 'string',
      'cancelledBy': 'string',
    },
    'audit_logs': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'createdAtEpoch': 'integer',
      'createdAtIso': 'string',
      'updatedAt': 'integer',
      'updatedAtIso': 'string',
      'deletedAt': 'integer',
      'deletedAtIso': 'string',
      'lastModified': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'operationType': 'string',
      'entityType': 'string',
      'entityUuid': 'string',
      'entityId': 'integer',
      'previousState': 'string',
      'newState': 'string',
      'changedFields': 'string',
      'performedBy': 'string',
      'ipAddress': 'string',
      'hotelDayKey': 'string',
      'timestamp': 'integer',
      'timestampIso': 'string',
      'isFinancial': 'boolean',
      // ✅ نوع مطابق للنشر الفعلي (double على الوجهتين)؛ المحوّل يحوّل double→int
      'amountImpact': 'double',
      'action': 'string',
    },
    'payment_voids': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'originalPaymentUuid': 'string',
      'originalPaymentId': 'integer',
      'bookingUuid': 'string',
      'voidedAmount': 'integer',
      'voidReason': 'string',
      'voidedBy': 'string',
      'voidedAt': 'integer',
      'voidedAtIso': 'string',
      'hotelDayKey': 'string',
      'reversalPaymentUuid': 'string',
      'approvedBy': 'string',
      'note': 'string',
      'originalAmount': 'double',
      'paymentUuid': 'string',
    },
    'guest_infos': {
      'localUuid': 'string',
      'serverId': 'integer',
      'createdAt': 'integer',
      'updatedAt': 'integer',
      'deletedAt': 'integer',
      'lastModified': 'integer',
      'createdAtIso': 'string',
      'updatedAtIso': 'string',
      'deletedAtIso': 'string',
      'createdAtEpoch': 'integer',
      'lastModifiedEpoch': 'integer',
      'version': 'integer',
      'origin': 'string',
      'vectorClock': 'string',
      'deviceId': 'string',
      'idempotencyKey': 'string',
      'syncTimestamp': 'integer',
      'sync_origin': 'string',
      'roomNumber': 'string',
      'guestName': 'string',
      'nationality': 'string',
      'idNumber': 'string',
      'idType': 'string',
      'issueDate': 'string',
      'issuePlace': 'string',
      'governorate': 'string',
      'notes': 'string',
    },
  };

  /// يضمن تمثيل vectorClock كسلسلة JSON صالحة ضمن حد Appwrite (1000 حرف).
  ///
  /// قد تصل القيمة كـ Map بعد دمج التعارضات، أو كنص تالف من سجل قديم. لا
  /// يجوز أن تمنع بيانات الفندق الأساسية من الرفع بسبب بيانات وصفية تالفة؛
  /// لذلك نُعيد ساعة فارغة آمنة في الحالات غير الصالحة أو الطويلة جداً.
  static String normalizeVectorClock(dynamic value) {
    dynamic decoded;
    if (value is String) {
      final trimmed = value.trim();
      if (trimmed.isEmpty || trimmed == '{}') return '{}';
      try {
        decoded = jsonDecode(trimmed);
      } catch (_) {
        return '{}';
      }
    } else if (value is Map) {
      decoded = value;
    } else {
      return '{}';
    }

    if (decoded is! Map) return '{}';

    final normalized = <String, int>{};
    decoded.forEach((key, rawCounter) {
      final deviceId = key.toString().trim();
      final counter = rawCounter is num
          ? rawCounter.toInt()
          : int.tryParse(rawCounter.toString());
      if (deviceId.isNotEmpty && counter != null && counter >= 0) {
        normalized[deviceId] = counter;
      }
    });

    final serialized = jsonEncode(normalized);
    return serialized.length <= 1000 ? serialized : '{}';
  }

  /// دفاع أخير للحمولات التي لا تمر عبر PayloadMapper.
  static Map<String, dynamic> normalizeVectorClockInPayload(
    Map<String, dynamic> payload,
  ) {
    if (!payload.containsKey('vectorClock')) {
      return Map<String, dynamic>.from(payload);
    }
    final normalized = Map<String, dynamic>.from(payload);
    normalized['vectorClock'] = normalizeVectorClock(normalized['vectorClock']);
    return normalized;
  }

  /// تصفية الحمولة — إبقاء فقط الحقول الموجودة في مخطط Appwrite الفعلي
  /// ⚠️ هذا يمنع خطأ "Unknown attribute" نهائياً
  /// إذا لم يكن المجموعة معروفة، يتم إرجاع الحمولة كما هي (بدون تصفية)
  static Map<String, dynamic> filterPayloadForCollection(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final schema = collectionSchema[collectionId];
    if (schema == null) {
      // fallback to old behavior for backward compatibility
      final validFields = validFieldsPerCollection[collectionId];
      if (validFields == null) return payload;
      final result = <String, dynamic>{};
      for (final entry in payload.entries) {
        if (validFields.contains(entry.key)) {
          result[entry.key] = entry.value;
        }
      }
      return result;
    }

    final normalizedPayload = normalizeVectorClockInPayload(payload);
    final result = <String, dynamic>{};
    for (final entry in normalizedPayload.entries) {
      final fieldSchema = schema[entry.key];
      if (fieldSchema != null) {
        result[entry.key] = _coerceToType(entry.value, fieldSchema);
      }
    }
    return result;
  }

  /// تحوير القيم إلى الأنواع المناسبة لمخطط Appwrite
  /// - integer: bool, num, String → int
  /// - double: يبقى كما هو أو يُقرَب
  /// - boolean: bool, num, String ("true", "1", "false", "0") → bool
  /// - string: أي قيمة → toString()
  static dynamic _coerceToType(dynamic value, String type) {
    if (value == null) return null;

    switch (type) {
      case 'integer':
        if (value is int) return value;
        if (value is num) return value.toInt();
        if (value is bool) return value ? 1 : 0;
        if (value is String) {
          final parsed = int.tryParse(value);
          return parsed ?? 0;
        }
        return 0;
      case 'double':
        if (value is double) return value;
        if (value is num) return value.toDouble();
        if (value is bool) return value ? 1.0 : 0.0;
        if (value is String) {
          final parsed = double.tryParse(value);
          return parsed ?? 0.0;
        }
        return 0.0;
      case 'boolean':
        if (value is bool) return value;
        if (value is num) return value != 0;
        if (value is String) {
          final lower = value.toLowerCase();
          if (lower == 'true' || lower == '1') return true;
          if (lower == 'false' || lower == '0') return false;
        }
        return false;
      case 'string':
        // Appwrite string attributes لا تقبل Map/List مباشرة. الساعات المتجهة
        // والحقول JSON قد تصل كمركبات بعد دمج OCC، فتُسلسل بدلاً من Map.toString().
        if (value is Map || value is Iterable) return jsonEncode(value);
        return value.toString();
      default:
        return value;
    }
  }

  /// تطهير البيانات وإزالة الحقول غير المدعومة أو المحسوبة
  static Map<String, dynamic> sanitizePayload(
    String entity,
    Map<String, dynamic> payload, {
    String? collectionId,
  }) {
    var result = Map<String, dynamic>.from(payload);

    // 1. إزالة الحقول المحسوبة التي لا تُخزن في Appwrite
    result = HotelDateHelper.stripComputedFieldsForEntity(entity, result);

    // 2. إزالة الحقول التقنية الخاصة بـ Drift أو Appwrite metadata إذا وجدت
    result.remove('id'); // المعرف المحلي التلقائي
    result.remove('\u0024id');
    result.remove('\u0024createdAt');
    result.remove('\u0024updatedAt');
    result.remove('\u0024permissions');
    result.remove('\u0024databaseId');
    result.remove('\u0024collectionId');

    // 3. إزالة حقول Delta Sync الداخلية التي لا وجود لها في مخطط Appwrite
    //    هذه الحقول تُضاف بواسطة DeltaSyncService.compute() و _preparePayload()
    result.remove('row_hash'); // حقل داخلي — ليس في أي مجموعة Appwrite
    result.remove('client_ts'); // حقل داخلي

    // 4. تحويل أسماء الحقول من snake_case إلى camelCase
    //    ⚠️ حرج: Appwrite Cloud يستخدم camelCase في جميع المجموعات المتزامنة
    //    (deletedAt, lastModified, localUuid, إلخ)
    //    بينما Delta Sync Push يرسل snake_case (deleted_at, last_modified, local_uuid)
    //    بدون هذا التحويل، يتجاهل Appwrite الحقول مثل deleted_at → الجهاز الآخر
    //    لا يرى softDelete → يرى 30 بدلاً من 15
    result = _convertKeysToCamelCase(result);

    // 5. بعد التحويل: إزالة الحقول الداخلية بأسمائها camelCase
    result.remove('rowHash'); // من row_hash
    result.remove('clientTs'); // من client_ts

    // 6. تحويل الأنواع المالية إذا لزم الأمر
    if (collectionId != null) {
      result = convertAmountTypesForAppwrite(collectionId, result);
    }

    // 7. ⚠️ تصفية نهائية: إبقاء فقط الحقول الموجودة في مخطط Appwrite الفعلي
    //    هذا يمنع خطأ "Unknown attribute" نهائياً — بغض النظر عن مصدر الحقل
    if (collectionId != null) {
      result = filterPayloadForCollection(collectionId, result);
    }

    return result;
  }

  /// تحويل جميع مفاتيح الخريطة من snake_case إلى camelCase بشكل متكرر
  /// الحقول التي لا تحتوي على _ تُترك كما هي (مثل amount, notes)
  static Map<String, dynamic> _convertKeysToCamelCase(
    Map<String, dynamic> input,
  ) {
    final result = <String, dynamic>{};
    for (final entry in input.entries) {
      final camelKey = toCamelCase(entry.key);
      final value = entry.value;
      if (value is Map<String, dynamic>) {
        result[camelKey] = _convertKeysToCamelCase(value);
      } else if (value is List) {
        result[camelKey] = value.map((item) {
          if (item is Map<String, dynamic>) {
            return _convertKeysToCamelCase(item);
          }
          return item;
        }).toList();
      } else {
        result[camelKey] = value;
      }
    }
    return result;
  }

  /// تحويل حقول المبالغ إلى أعداد صحيحة للمجموعات التي تتطلب ذلك
  static Map<String, dynamic> convertAmountTypesForAppwrite(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final intFields = _intAmountFields[collectionId];
    if (intFields == null || intFields.isEmpty) return payload;

    final result = Map<String, dynamic>.from(payload);
    for (final field in intFields) {
      if (result.containsKey(field) && result[field] is num) {
        result[field] = (result[field] as num).round();
      }
    }
    return result;
  }

  /// تحويل حقول المبالغ من أعداد صحيحة (Cloud) إلى double (محلي)
  /// يُستخدم عند سحب البيانات من Appwrite Cloud إلى قاعدة البيانات المحلية
  static Map<String, dynamic> convertAmountTypesFromAppwrite(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final intFields = _intAmountFields[collectionId];
    if (intFields == null || intFields.isEmpty) return payload;

    final result = Map<String, dynamic>.from(payload);
    for (final field in intFields) {
      if (result.containsKey(field) && result[field] is num) {
        // تحويل integer إلى double للمحلي (مثلاً 5000 → 5000.0)
        result[field] = (result[field] as num).toDouble();
      }
    }
    return result;
  }

  /// الحقول التي يجب أن تبقى snake_case في Appwrite (لا تُحوّل إلى camelCase)
  /// ⚠️ تم تدقيقها مقابل مخطط Appwrite الفعلي (2026-06-14)
  /// فقط الحقول snake_case الموجودة فعلاً في مخطط Appwrite تُضاف هنا
  /// ❌ sync_vector_clock غير موجود في أي مجموعة — لا يُضاف
  static const Set<String> _preserveSnakeCase = {
    'sync_origin', // موجود فقط في: booking_notes, sync_state, app_users
    // ═══════════════════════════════════════════════════════════════
    // حقول app_settings — كلها snake_case في Appwrite Cloud
    // عند إضافة حقل جديد إلى _appSettingsToMap، يجب إضافته هنا أيضاً
    // ═══════════════════════════════════════════════════════════════
    'hotel_name',
    'hotel_cutoff_hour',
    'dark_mode',
    'wa_api_type',
    'wa_api_base_url',
    'wa_api_instance_id',
    'wa_custom_url_template',
    'wa_sendzen_api_key',
    'wa_sendzen_from_number',
    'telegram_enabled',
    'telegram_chat_id',
    'telegram_notifications_enabled',
    'telegram_daily_report_enabled',
    'telegram_daily_report_time',
    'appwrite_sync_interval',
    'api_key',
    'database_id',
    'endpoint',
    'enabled',
    'project_id',
    'pull_enabled',
    'push_enabled',
  };

  /// تحويل أسماء الحقول من snake_case إلى camelCase (للتوافق مع Appwrite)
  /// ⚠️ الحقول في _preserveSnakeCase لا تُحوّل لأن Appwrite يتطلبها snake_case
  static String toCamelCase(String input) {
    if (!input.contains('_')) return input;
    if (_preserveSnakeCase.contains(input)) return input;
    final parts = input.split('_');
    final first = parts.first;
    final rest = parts
        .skip(1)
        .map((p) => p.isEmpty ? '' : '${p[0].toUpperCase()}${p.substring(1)}');
    return '$first${rest.join()}';
  }
}
