import '../utils/hotel_date_helper.dart';

/// فئة أدوات موحدة لمعالجة البيانات قبل إرسالها أو بعد سحبها من Appwrite
class AppwriteSyncUtils {
  /// الحقول التي يجب تحويلها إلى أعداد صحيحة (بناءً على قيود Appwrite الحالية)
  /// ⚠️ تم التحديث بناءً على فحص Appwrite Cloud الفعلي (2026-05-15)
  /// - cash_transactions.amount: integer على Cloud ✓
  /// - salary_withdrawals.amount: integer على Cloud ✓
  /// - payment_voids.voidedAmount: integer على Cloud ✓
  /// - booking_price_adjustments.amount: integer على Cloud ✓ (أُضيف 2026-05-15)
  /// - debts.remainingAmount: integer على Cloud ✓ (أُضيف 2026-05-15)
  /// - debts.totalAmount/paidAmount: double على Cloud (لا تحتاج تحويل)
  static const Map<String, Set<String>> _intAmountFields = {
    'cash_transactions': {'amount'},
    'salary_withdrawals': {'amount'},
    'payment_voids': {'voidedAmount'},
    'booking_price_adjustments': {'amount'},
    'debts': {'remainingAmount'},
  };

  // ══════════════════════════════════════════════════════════════════════════
  // مخطط حقول Appwrite Cloud الفعلي — تم تدقيقه في 2026-06-15
  // ⚠️ هذا هو المصدر الوحيد للحقيقة — لا تخمن حقولاً!
  // أي حقل غير موجود هنا سيُزال تلقائياً قبل الإرسال لمنع "Unknown attribute"
  // ══════════════════════════════════════════════════════════════════════════
  static const Map<String, Set<String>> validFieldsPerCollection = {
    'rooms': {
      'cleaningStatus', 'createdAt', 'createdAtEpoch', 'createdAtIso',
      'deletedAt', 'deletedAtIso', 'deviceId', 'imageUrl',
      'lastCleanedHotelDay', 'lastModified', 'lastModifiedEpoch',
      'lastOccupiedHotelDay', 'localUuid', 'origin', 'price',
      'requiresMaintenance', 'roomNumber', 'serverId',
      'status', 'syncTimestamp', 'type', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'bookings': {
      'actualCheckout', 'calculatedNights', 'checkinDate', 'checkoutDate',
      'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'deviceId', 'discount', 'discountStartDate',
      'discountType', 'expectedNights', 'guestAddress', 'guestEmail',
      'guestIdIssueDate', 'guestIdIssuePlace', 'guestIdNumber', 'guestIdType',
      'guestName', 'guestNationality', 'guestPhone', 'hotelDayCheckin',
      'hotelDayCheckout', 'isFullyPaid', 'isOverdue', 'lastModified',
      'lastModifiedEpoch', 'lastNightEpoch', 'localUuid',
      'needsCheckoutReview', 'notes', 'origin', 'remainingBalanceCached',
      'roomNumber', 'serverBookingId', 'serverId', 'status',
      'stayDurationIso', 'syncTimestamp', 'totalDueCached',
      'totalNightsCached', 'totalPaidCached', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'expenses': {
      'amount', 'cashFlowUuid', 'cashTransactionId', 'categoryUuid',
      'createdAt', 'createdAtEpoch', 'createdAtIso', 'date', 'deletedAt',
      'deletedAtIso', 'description', 'deviceId', 'employeeUuid',
      'expenseType', 'hotelDayKey', 'isAutoGenerated',
      'lastModified', 'lastModifiedEpoch', 'localUuid', 'origin', 'relatedId',
      'serverId', 'syncTimestamp', 'updatedAt', 'updatedAtIso', 'vectorClock',
      'version',
    },
    'employees': {
      'basicSalary', 'createdAt', 'createdAtEpoch', 'createdAtIso',
      'deletedAt', 'deletedAtIso', 'deviceId', 'hireDate',
      'lastModified', 'lastModifiedEpoch', 'localUuid',
      'name', 'origin', 'phone', 'position', 'serverId', 'status',
      'syncTimestamp', 'terminationDate', 'terminationReason', 'updatedAt',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'payments': {
      'amount', 'bookingLocalId', 'bookingUuidCache',
      'cashTransactionLocalId', 'cashTransactionServerId', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'deletedAt', 'deletedAtIso',
      'deviceId', 'discountAmount', 'discountStartDate', 'hotelDayKey',
      'isPendingBalance', 'isVoided', 'lastModified',
      'lastModifiedEpoch', 'linkedDebtUuid', 'localUuid', 'notes', 'origin',
      'paymentDate', 'paymentMethod', 'referenceNumber', 'revenueType',
      'roomNumber', 'serverBookingId', 'serverId', 'serverPaymentId',
      'syncTimestamp', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
      'voidedAt', 'voidedBy',
    },
    'debts': {
      'bookingLocalId', 'checkinDate', 'checkoutDate', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'dateRecorded', 'debtReason',
      'debtUuid', 'deletedAt', 'deletedAtIso', 'deviceId',
      'guestName', 'hotelDayClosed', 'hotelDayOpened', 'isFromAutoFix',
      'isSettled', 'lastModified', 'lastModifiedEpoch', 'localUuid', 'note',
      'origin', 'paidAmount', 'paymentDate', 'pledge', 'pledgeType',
      'remainingAmount', 'serverId', 'settlementConfirmed', 'syncTimestamp',
      'totalAmount', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'booking_notes': {
      'alertType', 'alertUntil', 'bookingId', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'deletedAt', 'deletedAtIso',
      'deviceId', 'isActive', 'lastModified',
      'lastModifiedEpoch', 'localUuid', 'noteText', 'origin',
      'serverId', 'syncTimestamp', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'booking_nights': {
      'adjustment', 'appliedAdjustmentUuid', 'appliedAdjustmentsJson',
      'baseRate', 'bookingLocalId', 'bookingUuidCache', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'deletedAt', 'deletedAtIso',
      'deviceId', 'finalRate', 'hotelDayKey',
      'isProcessedByAutoFix', 'lastModified', 'lastModifiedEpoch',
      'localUuid', 'nightEnd', 'nightlyRate', 'nightStart', 'origin',
      'sequence', 'serverBookingId', 'serverId',
      'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'cash_transactions': {
      'amount', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'createdBy',
      'deletedAt', 'deletedAtIso', 'description', 'deviceId',
      'lastModified', 'lastModifiedEpoch', 'localUuid',
      'origin', 'referenceId', 'referenceType', 'registerId', 'serverId',
      'syncTimestamp', 'transactionTime', 'transactionType', 'updatedAt',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'shift_notes': {
      'content', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'createdBy',
      'deletedAt', 'deletedAtIso', 'deviceId', 'expiresAt',
      'isRead', 'lastModified', 'lastModifiedEpoch', 'localUuid', 'note',
      'origin', 'priority', 'serverId', 'shiftDate', 'shiftType',
      'syncTimestamp', 'title', 'updatedAt', 'updatedAtIso', 'vectorClock',
      'version',
    },
    'salary_cycles': {
      'actualPaid', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'cycleKey',
      'deletedAt', 'deletedAtIso', 'deviceId', 'employeeId', 'expectedAmount',
      'hotelDayEnd', 'hotelDayStart', 'lastModified',
      'lastModifiedEpoch', 'localUuid', 'origin', 'remainingAmount',
      'serverId', 'status', 'syncTimestamp', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'salary_payments': {
      'amount', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'cycleId',
      'deletedAt', 'deletedAtIso', 'deviceId', 'hotelDayKey',
      'isAutoGenerated', 'lastModified', 'lastModifiedEpoch',
      'localUuid', 'method', 'origin',
      'paymentDateIso', 'serverId', 'syncTimestamp', 'updatedAt',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'salary_withdrawals': {
      'action', 'amount', 'createdAt', 'createdAtEpoch', 'createdAtIso',
      'date', 'deletedAt', 'deletedAtIso', 'description', 'deviceId',
      'employeeId', 'employeeUuid', 'expenseId', 'hotelDayKey',
      'lastModified', 'lastModifiedEpoch', 'localUuid',
      'name', 'note', 'origin', 'reason', 'serverId',
      'updatedAt', 'updatedAtIso', 'vectorClock', 'version', 'withdrawDate',
      'withdrawalType',
    },
    'price_adjustments': {
      'adjustmentType', 'appliedBy', 'createdAt',
      'createdAtEpoch', 'createdAtIso', 'deletedAt', 'deletedAtIso',
      'deviceId', 'effectiveDate', 'hotelDayKey', 'isReversed',
      'lastModified', 'lastModifiedEpoch', 'localUuid', 'newValue', 'origin',
      'previousValue', 'reason', 'reversedAt', 'reversedBy',
      'serverId', 'syncTimestamp', 'targetType', 'targetUuid', 'updatedAt',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'booking_price_adjustments': {
      'adjustmentMode', 'adjustmentType', 'amount', 'appliedBy',
      'bookingLocalId', 'bookingLocalUuid', 'cancelledAt', 'cancelledBy',
      'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'deviceId', 'effectiveHotelDay', 'endHotelDay',
      'isActive', 'lastModified', 'lastModifiedEpoch', 'localUuid', 'origin',
      'reason', 'roomNumber', 'serverId', 'updatedAt', 'updatedAtIso',
      'vectorClock', 'version',
    },
    'audit_logs': {
      'amountImpact', 'changedFields', 'createdAt', 'createdAtEpoch',
      'createdAtIso', 'deletedAt', 'deletedAtIso',
      'deviceId', 'entityId', 'entityType', 'entityUuid', 'hotelDayKey',
      'ipAddress', 'isFinancial', 'lastModified', 'localUuid', 'newState',
      'operationType', 'origin', 'performedBy', 'previousState',
      'serverId', 'syncTimestamp', 'timestamp', 'timestampIso',
      'updatedAtIso', 'vectorClock', 'version',
    },
    'payment_voids': {
      'approvedBy', 'bookingUuid', 'createdAt', 'createdAtEpoch',
      'createdAtIso', 'deletedAt', 'deletedAtIso', 'deviceId',
      'hotelDayKey', 'lastModified', 'lastModifiedEpoch',
      'localUuid', 'note', 'origin', 'originalAmount', 'originalPaymentId',
      'originalPaymentUuid', 'paymentUuid', 'reversalPaymentUuid', 'serverId',
      'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
      'voidedAmount', 'voidedAt', 'voidedAtIso', 'voidedBy', 'voidReason',
    },
    'guest_infos': {
      'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'deviceId', 'governorate', 'guestName',
      'idNumber', 'idType', 'issueDate', 'issuePlace',
      'lastModified', 'lastModifiedEpoch', 'localUuid', 'nationality',
      'notes', 'origin', 'roomNumber', 'serverId', 'syncTimestamp',
      'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'blacklist': {
      'active', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'deviceId', 'lastModified',
      'lastModifiedEpoch', 'localUuid', 'name', 'nationalId', 'nationality',
      'notes', 'origin', 'phone', 'reason', 'reportedBy', 'serverId',
      'syncTimestamp', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'devices': {
      'createdAt', 'deviceId', 'deviceModel', 'deviceName',
      'lastActive', 'lastSeen', 'localUuid', 'origin', 'osVersion',
      'status', 'updatedAt', 'version',
    },
    'sync_logs': {
      'action', 'createdAt', 'createdAtEpoch', 'createdAtIso', 'deletedAt',
      'deletedAtIso', 'details', 'deviceId', 'direction', 'endTime',
      'errorMessage', 'lastModified', 'lastModifiedEpoch', 'localUuid',
      'origin', 'serverId', 'startTime', 'status', 'syncId', 'syncType',
      'timestamp', 'updatedAt', 'updatedAtIso', 'vectorClock', 'version',
    },
    'app_settings': {
      // ✅ localUuid مطلوب في مخطط Appwrite Cloud (required attribute)
      // بدونه: خطأ 400 "Missing required attribute localUuid"
      'localUuid',
      'value',
      'appwrite_sync_interval', 'dark_mode', 'hotel_cutoff_hour',
      'hotel_name', 'key', 'lark_app_id', 'lark_app_secret',
      'lark_daily_report_chat_id', 'lark_daily_report_enabled',
      'lark_daily_report_time', 'lark_enabled', 'lark_webhook_url',
      'telegram_bot_token', 'telegram_chat_id',
      'telegram_daily_report_enabled', 'telegram_daily_report_time',
      'telegram_enabled', 'telegram_notifications_enabled',
      'wa_api_base_url', 'wa_api_instance_id', 'wa_api_token',
      'wa_api_type', 'wa_custom_url_template', 'wa_sendzen_api_key',
      'wa_sendzen_from_number', 'wa_template',
    },
    // ⚠️ المجموعات التالية غير موجودة في Appwrite Cloud حالياً
    // إذا أُنشئت مستقبلاً، يجب تحديث هذه القوائم بدقة
    'outbox': {
      'entity', 'op', 'localUuid', 'serverId', 'payload', 'clientTs',
      'attempts', 'lastError', 'idempotencyKey', 'processingStatus',
      'processingStartedAt', 'processingWorker', 'source',
    },
    'sync_state': {
      'createdAt', 'deletedAt', 'isSyncing', 'lastModified', 'lastSyncTime',
      'localUuid', 'origin', 'serverId', 'sync_origin', 'updatedAt', 'version',
    },
    'app_users': {
      'active', 'credentials_version', 'full_name', 'fullName', 'last_login',
      'lastLogin', 'password', 'permissions', 'sync_origin', 'user_type',
      'username', 'userType', 'version',
    },
  };

  /// تصفية الحمولة — إبقاء فقط الحقول الموجودة في مخطط Appwrite الفعلي
  /// ⚠️ هذا يمنع خطأ "Unknown attribute" نهائياً
  /// إذا لم يكن المجموعة معروفة، يتم إرجاع الحمولة كما هي (بدون تصفية)
  static Map<String, dynamic> filterPayloadForCollection(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final validFields = validFieldsPerCollection[collectionId];
    if (validFields == null) return payload; // مجموعة غير معروفة — لا نصفي

    final result = <String, dynamic>{};
    for (final entry in payload.entries) {
      if (validFields.contains(entry.key)) {
        result[entry.key] = entry.value;
      }
    }
    return result;
  }

  /// تطهير البيانات وإزالة الحقول غير المدعومة أو المحسوبة
  static Map<String, dynamic> sanitizePayload(
    String entity,
    Map<String, dynamic> payload, {
    String? collectionId,
  }) {
    var result = Map<String, dynamic>.from(payload);

    // 1. إزالة الحقول المحسوبة التي لا تُخزن في Appwrite
    result = HotelDateHelper.stripComputedFieldsForEntity(entity, result);

    // 2. إزالة الحقول التقنية الخاصة بـ Drift أو Appwrite metadata إذا وجدت
    result.remove('id'); // المعرف المحلي التلقائي
    result.remove('\u0024id');
    result.remove('\u0024createdAt');
    result.remove('\u0024updatedAt');
    result.remove('\u0024permissions');
    result.remove('\u0024databaseId');
    result.remove('\u0024collectionId');

    // 3. إزالة حقول Delta Sync الداخلية التي لا وجود لها في مخطط Appwrite
    //    هذه الحقول تُضاف بواسطة DeltaSyncService.compute() و _preparePayload()
    result.remove('row_hash');       // حقل داخلي — ليس في أي مجموعة Appwrite
    result.remove('client_ts');      // حقل داخلي

    // 4. تحويل أسماء الحقول من snake_case إلى camelCase
    //    ⚠️ حرج: Appwrite Cloud يستخدم camelCase في جميع المجموعات المتزامنة
    //    (deletedAt, lastModified, localUuid, إلخ)
    //    بينما Delta Sync Push يرسل snake_case (deleted_at, last_modified, local_uuid)
    //    بدون هذا التحويل، يتجاهل Appwrite الحقول مثل deleted_at → الجهاز الآخر
    //    لا يرى softDelete → يرى 30 بدلاً من 15
    result = _convertKeysToCamelCase(result);

    // 5. بعد التحويل: إزالة الحقول الداخلية بأسمائها camelCase
    result.remove('rowHash');        // من row_hash
    result.remove('clientTs');       // من client_ts

    // 6. تحويل الأنواع المالية إذا لزم الأمر
    if (collectionId != null) {
      result = convertAmountTypesForAppwrite(collectionId, result);
    }

    // 7. ⚠️ تصفية نهائية: إبقاء فقط الحقول الموجودة في مخطط Appwrite الفعلي
    //    هذا يمنع خطأ "Unknown attribute" نهائياً — بغض النظر عن مصدر الحقل
    if (collectionId != null) {
      result = filterPayloadForCollection(collectionId, result);
    }

    return result;
  }

  /// تحويل جميع مفاتيح الخريطة من snake_case إلى camelCase بشكل متكرر
  /// الحقول التي لا تحتوي على _ تُترك كما هي (مثل amount, notes)
  static Map<String, dynamic> _convertKeysToCamelCase(
    Map<String, dynamic> input,
  ) {
    final result = <String, dynamic>{};
    for (final entry in input.entries) {
      final camelKey = toCamelCase(entry.key);
      final value = entry.value;
      if (value is Map<String, dynamic>) {
        result[camelKey] = _convertKeysToCamelCase(value);
      } else if (value is List) {
        result[camelKey] = value.map((item) {
          if (item is Map<String, dynamic>) {
            return _convertKeysToCamelCase(item);
          }
          return item;
        }).toList();
      } else {
        result[camelKey] = value;
      }
    }
    return result;
  }

  /// تحويل حقول المبالغ إلى أعداد صحيحة للمجموعات التي تتطلب ذلك
  static Map<String, dynamic> convertAmountTypesForAppwrite(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final intFields = _intAmountFields[collectionId];
    if (intFields == null || intFields.isEmpty) return payload;

    final result = Map<String, dynamic>.from(payload);
    for (final field in intFields) {
      if (result.containsKey(field) && result[field] is num) {
        result[field] = (result[field] as num).round();
      }
    }
    return result;
  }

  /// تحويل حقول المبالغ من أعداد صحيحة (Cloud) إلى double (محلي)
  /// يُستخدم عند سحب البيانات من Appwrite Cloud إلى قاعدة البيانات المحلية
  static Map<String, dynamic> convertAmountTypesFromAppwrite(
    String collectionId,
    Map<String, dynamic> payload,
  ) {
    final intFields = _intAmountFields[collectionId];
    if (intFields == null || intFields.isEmpty) return payload;

    final result = Map<String, dynamic>.from(payload);
    for (final field in intFields) {
      if (result.containsKey(field) && result[field] is num) {
        // تحويل integer إلى double للمحلي (مثلاً 5000 → 5000.0)
        result[field] = (result[field] as num).toDouble();
      }
    }
    return result;
  }

  /// الحقول التي يجب أن تبقى snake_case في Appwrite (لا تُحوّل إلى camelCase)
  /// ⚠️ تم تدقيقها مقابل مخطط Appwrite الفعلي (2026-06-15)
  /// فقط الحقول snake_case الموجودة فعلاً في مخطط Appwrite تُضاف هنا
  /// ❌ sync_origin غير موجود في أي مجموعة متزامنة — لا يُضاف
  /// ❌ sync_vector_clock غير موجود في أي مجموعة — لا يُضاف
  static const Set<String> _preserveSnakeCase = {
    // app_settings كلها snake_case — لكنها تُرسل مباشرة بدون toCamelCase
  };

  /// تحويل أسماء الحقول من snake_case إلى camelCase (للتوافق مع Appwrite)
  /// ⚠️ الحقول في _preserveSnakeCase لا تُحوّل لأن Appwrite يتطلبها snake_case
  static String toCamelCase(String input) {
    if (!input.contains('_')) return input;
    if (_preserveSnakeCase.contains(input)) return input;
    final parts = input.split('_');
    final first = parts.first;
    final rest = parts
        .skip(1)
        .map((p) => p.isEmpty ? '' : '${p[0].toUpperCase()}${p.substring(1)}');
    return '$first${rest.join()}';
  }

  /// ⚠️ تطبيع UUID إلى الصيغة **بدون شرطة** (32 حرف hex متصلة).
  ///
  /// **المشكلة التي يحلها:**
  /// Appwrite يتعامل مع UUIDs كـ strings حرفية — لا يُطبّعها. فـ:
  ///   - `c0e88e8614054f718279a86e632e3921` (32 حرف بدون شرطة)
  ///   - `c0e88e86-1405-4f71-8279-a86e632e3921` (36 حرف مع شرطة)
  /// هما document IDs مختلفة تماماً بالنسبة لـ Appwrite، مما يُسبب:
  ///   1. `updateDocument(noHyphensId)` → 404 (المستند مخزن بالصيغة المع شرطة)
  ///   2. `createDocument(noHyphensId)` → 409 (إذا وُجد بنفس الـ ID)
  ///   3. تكرار المستندات (نسختان لكل كيان منطقي)
  ///
  /// **الحل المعتمد:** توحيد كل UUIDs إلى **بدون شرطة** (أقصر، أوفر مساحة،
  /// أسهل في URLs وأسماء الملفات). ويتم تطبيق ذلك:
  ///   1. على كل ID قبل إرساله إلى Appwrite.
  ///   2. على حقل `localUuid` داخل الحمولة.
  ///   3. على كل UUIDs المخزنة محلياً عبر Drift schema migration.
  ///   4. على المستندات الموجودة في Appwrite Cloud عبر سكربت migration.
  ///
  /// **أمثلة:**
  ///   - `c0e88e86-1405-4f71-8279-a86e632e3921` → `c0e88e8614054f718279a86e632e3921`
  ///   - `c0e88e8614054f718279a86e632e3921` → `c0e88e8614054f718279a86e632e3921` (لا تغيير)
  ///   - `C0E88E86-1405-4F71-8279-A86E632E3921` → `c0e88e8614054f718279a86e632e3921` ( lowercase )
  ///   - `whatsapp_settings` → `whatsapp_settings` (ليس hex، يُعاد كما هو)
  ///   - `ID.unique()` → `ID.unique()` (ليس hex، يُعاد كما هو)
  ///   - `auto-1234567890-abcd1234` → `auto-1234567890-abcd1234` (ليس hex، يُعاد كما هو)
  static String normalizeUuid(String id) {
    // إذا كان الـ ID فارغاً، أعدمه كما هو
    if (id.isEmpty) return id;

    // إذا كان يحتوي على أحرف غير hex أو شرطة، فهو ليس UUID (مثل 'whatsapp_settings')
    // نتحقق من النسخة بدون شرطة
    final stripped = id.replaceAll('-', '');
    // UUID v4 القياسي = 32 حرف hex. نقبل 32 فقط.
    if (stripped.length != 32) return id;
    // التحقق من أن كل الأحرف hex
    final hexRegex = RegExp(r'^[0-9a-fA-F]+$');
    if (!hexRegex.hasMatch(stripped)) return id;

    // تطبيع إلى الصيغة بدون شرطة + lowercase
    return stripped.toLowerCase();
  }

  /// تطبيع UUID مع إرجاع null إذا كان المدخل null.
  static String? normalizeUuidNullable(String? id) {
    if (id == null) return null;
    return normalizeUuid(id);
  }

  /// فحص ما إذا كان الـ ID يحتاج تطبيع (أي ليس بالفعل بالصيغة بدون شرطة).
  /// يُستخدم في migrations لتحديد الصفوف التي تحتاج تحديث.
  static bool needsNormalization(String id) {
    if (id.isEmpty) return false;
    // ليس UUID أصلاً
    final stripped = id.replaceAll('-', '');
    if (stripped.length != 32) return false;
    final hexRegex = RegExp(r'^[0-9a-fA-F]+$');
    if (!hexRegex.hasMatch(stripped)) return false;
    // إذا كان يطابق الصيغة المعيارية (بدون شرطة + lowercase) لا يحتاج تطبيع
    return id != stripped.toLowerCase();
  }
}
