part of 'local_db.dart';

class Booking {
  final int id;
  final String localUuid;
  final int? serverId;
  final int createdAt;
  final int updatedAt;
  final int? deletedAt;
  final int lastModified;
  final String? createdAtIso;
  final String? updatedAtIso;
  final String? deletedAtIso;
  final int createdAtEpoch;
  final int lastModifiedEpoch;
  final int version;
  final String origin;
  final String vectorClock;
  final String? deviceId;
  final int? serverBookingId;
  final String roomNumber;
  final String guestName;
  final String guestPhone;
  final String guestIdType;
  final String guestIdNumber;
  final String? guestIdIssueDate;
  final String? guestIdIssuePlace;
  final String guestNationality;
  final String? guestEmail;
  final String? guestAddress;
  final String checkinDate;
  final String? checkoutDate;
  final String? actualCheckout;
  final String status;
  final String? notes;
  final double discount;
  final String discountType;
  final String? discountStartDate;
  final int expectedNights;
  final int calculatedNights;
  final int totalNightsCached;
  final String? stayDurationIso;
  final int? lastNightEpoch;
  final bool isOverdue;
  final bool needsCheckoutReview;
  final double totalDueCached;
  final double totalPaidCached;
  final double remainingBalanceCached;
  final bool isFullyPaid;
  final String? hotelDayCheckin;
  final String? hotelDayCheckout;

  const Booking({
    required this.id,
    required this.localUuid,
    this.serverId,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.lastModified,
    this.createdAtIso,
    this.updatedAtIso,
    this.deletedAtIso,
    this.createdAtEpoch = 0,
    this.lastModifiedEpoch = 0,
    this.version = 1,
    this.origin = 'local',
    this.vectorClock = '{}',
    this.deviceId,
    this.serverBookingId,
    required this.roomNumber,
    required this.guestName,
    required this.guestPhone,
    this.guestIdType = 'بطاقة شخصية',
    this.guestIdNumber = '',
    this.guestIdIssueDate,
    this.guestIdIssuePlace,
    required this.guestNationality,
    this.guestEmail,
    this.guestAddress,
    required this.checkinDate,
    this.checkoutDate,
    this.actualCheckout,
    required this.status,
    this.notes,
    this.discount = 0,
    this.discountType = 'per_night',
    this.discountStartDate,
    this.expectedNights = 1,
    this.calculatedNights = 1,
    this.totalNightsCached = 0,
    this.stayDurationIso,
    this.lastNightEpoch,
    this.isOverdue = false,
    this.needsCheckoutReview = false,
    this.totalDueCached = 0.0,
    this.totalPaidCached = 0.0,
    this.remainingBalanceCached = 0.0,
    this.isFullyPaid = false,
    this.hotelDayCheckin,
    this.hotelDayCheckout,
  });
}

class Expense {
  final int id;
  final String localUuid;
  final int? serverId;
  final int createdAt;
  final int updatedAt;
  final int? deletedAt;
  final int lastModified;
  final String? createdAtIso;
  final String? updatedAtIso;
  final String? deletedAtIso;
  final int createdAtEpoch;
  final int lastModifiedEpoch;
  final int version;
  final String origin;
  final String vectorClock;
  final String? deviceId;
  final String expenseType;
  final int? relatedId;
  final String description;
  final double amount;
  final String date;
  final int? cashTransactionId;
  final String? hotelDayKey;
  final String? categoryUuid;
  final String? cashFlowUuid;
  final bool isAutoGenerated;

  const Expense({
    required this.id,
    required this.localUuid,
    this.serverId,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.lastModified,
    this.createdAtIso,
    this.updatedAtIso,
    this.deletedAtIso,
    this.createdAtEpoch = 0,
    this.lastModifiedEpoch = 0,
    this.version = 1,
    this.origin = 'local',
    this.vectorClock = '{}',
    this.deviceId,
    required this.expenseType,
    this.relatedId,
    required this.description,
    required this.amount,
    required this.date,
    this.cashTransactionId,
    this.hotelDayKey,
    this.categoryUuid,
    this.cashFlowUuid,
    this.isAutoGenerated = false,
  });
}

class Payment {
  final int id;
  final String localUuid;
  final int? serverId;
  final int createdAt;
  final int updatedAt;
  final int? deletedAt;
  final int lastModified;
  final String? createdAtIso;
  final String? updatedAtIso;
  final String? deletedAtIso;
  final int createdAtEpoch;
  final int lastModifiedEpoch;
  final int version;
  final String origin;
  final String vectorClock;
  final String? deviceId;
  final int? serverPaymentId;
  final int? bookingLocalId;
  final int? serverBookingId;
  final String? roomNumber;
  final double amount;
  final String paymentDate;
  final String? notes;
  final String paymentMethod;
  final String revenueType;
  final int? cashTransactionLocalId;
  final int? cashTransactionServerId;
  final String? referenceNumber;
  final String? hotelDayKey;
  final bool isPendingBalance;
  final String? linkedDebtUuid;
  final String? bookingUuidCache;
  final double? discountAmount;
  final String? discountStartDate;
  final bool isVoided;
  final int? voidedAt;
  final String? voidedBy;

  const Payment({
    required this.id,
    required this.localUuid,
    this.serverId,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
    required this.lastModified,
    this.createdAtIso,
    this.updatedAtIso,
    this.deletedAtIso,
    this.createdAtEpoch = 0,
    this.lastModifiedEpoch = 0,
    this.version = 1,
    this.origin = 'local',
    this.vectorClock = '{}',
    this.deviceId,
    this.serverPaymentId,
    this.bookingLocalId,
    this.serverBookingId,
    this.roomNumber,
    required this.amount,
    required this.paymentDate,
    this.notes,
    required this.paymentMethod,
    required this.revenueType,
    this.cashTransactionLocalId,
    this.cashTransactionServerId,
    this.referenceNumber,
    this.hotelDayKey,
    this.isPendingBalance = false,
    this.linkedDebtUuid,
    this.bookingUuidCache,
    this.discountAmount,
    this.discountStartDate,
    this.isVoided = false,
    this.voidedAt,
    this.voidedBy,
  });
}
