import 'package:drift/drift.dart' as d;

import '../daos/outbox_dao.dart';
import '../local_db.dart';
import '../utils/id.dart';
import '../utils/time.dart';
import 'appwrite_sync_manager.dart';

/// خدمة موحدة لمعاملات مصروفات الرواتب + مرايا السحوبات.
///
/// تضمن أن العمليات المتعددة الجداول (مصروف + سحبة مرآة) تُنفذ
/// في معاملة واحدة ذرية — لا مصروف بلا مرآة، لا مرآة بلا مصروف.
class SalaryExpenseService {
  SalaryExpenseService(this._db) : _outboxDao = OutboxDao(_db);

  final AppDatabase _db;
  final OutboxDao _outboxDao;

  /// ينشئ مصروف راتب + سحبة مرآة في معاملة واحدة.
  Future<int> createSalaryExpenseWithMirror({
    required String expenseType,
    required int employeeId,
    required String description,
    required double amount,
    required String date,
    required String hotelDayKey,
    required String employeeUuid,
    required String action,
    required double signedAmount,
    String? recorderName,
    bool originIsServer = false,
  }) async {
    final now = Time.nowEpoch();
    final expenseUuid = IdGen.uuid();
    final withdrawalUuid = IdGen.uuid();
    final deviceId = AppwriteSyncManager.currentDeviceIdStatic ?? '';

    return _db.transaction(() async {
      // 1. إنشاء المصروف
      final expenseId = await _db
          .into(_db.expenses)
          .insert(
            ExpensesCompanion(
              localUuid: d.Value(expenseUuid),
              expenseType: d.Value(expenseType),
              relatedId: d.Value(employeeId),
              description: d.Value(description),
              amount: d.Value(amount),
              date: d.Value(date),
              hotelDayKey: d.Value(hotelDayKey),
              employeeUuid: d.Value(employeeUuid),
              createdAt: d.Value(now),
              updatedAt: d.Value(now),
              deletedAt: const d.Value.absent(),
              lastModified: d.Value(now),
              createdAtEpoch: d.Value(now),
              lastModifiedEpoch: d.Value(now),
              version: const d.Value(1),
              origin: d.Value(originIsServer ? 'server' : 'local'),
              vectorClock: const d.Value('{}'),
              isAutoGenerated: const d.Value(false),
            ),
          );

      // 2. إنشاء السحبة المرآة
      final reasonText = 'exp_$expenseId';
      final withdrawalId = await _db
          .into(_db.salaryWithdrawals)
          .insert(
            SalaryWithdrawalsCompanion(
              localUuid: d.Value(withdrawalUuid),
              employeeId: d.Value(employeeId),
              employeeUuid: d.Value(employeeUuid),
              amount: d.Value(signedAmount),
              withdrawDate: d.Value(date),
              reason: d.Value(reasonText),
              withdrawalType: d.Value(action),
              description: d.Value(description),
              hotelDayKey: d.Value(hotelDayKey),
              recorderName: recorderName != null && recorderName.isNotEmpty
                  ? d.Value(recorderName)
                  : const d.Value.absent(),
              deviceId: d.Value(deviceId),
              createdAt: d.Value(now),
              updatedAt: d.Value(now),
              deletedAt: const d.Value.absent(),
              lastModified: d.Value(now),
              createdAtEpoch: d.Value(now),
              lastModifiedEpoch: d.Value(now),
              version: const d.Value(1),
              origin: d.Value(originIsServer ? 'server' : 'local'),
              vectorClock: const d.Value('{}'),
            ),
          );

      // 3. كتابة expense_id في العمود الخام
      await _db.customStatement(
        'UPDATE salary_withdrawals SET expense_id = ? WHERE id = ?',
        [expenseId, withdrawalId],
      );

      // 4. إنشاء إدخالات outbox داخل المعاملة
      if (!originIsServer) {
        // outbox للمصروف
        await _outboxDao.merge(
          entity: 'expenses',
          op: 'create',
          localUuid: expenseUuid,
          payload: {
            'expenseType': expenseType,
            'relatedId': employeeId,
            'employeeUuid': employeeUuid,
            'description': description,
            'amount': amount,
            'date': date,
            'hotelDayKey': hotelDayKey,
            'isAutoGenerated': false,
            'deviceId': deviceId,
          },
          clientTs: now,
        );

        // outbox للسحبة
        await _outboxDao.merge(
          entity: 'salary_withdrawals',
          op: 'create',
          localUuid: withdrawalUuid,
          payload: {
            'employeeId': employeeId,
            'employeeUuid': employeeUuid,
            'amount': signedAmount,
            'withdrawDate': date,
            'reason': reasonText,
            'withdrawalType': action,
            'description': description,
            'hotelDayKey': hotelDayKey,
            'expenseId': expenseId,
            'deviceId': deviceId,
            if (recorderName != null && recorderName.isNotEmpty)
              'recorderName': recorderName,
          },
          clientTs: now,
        );
      }

      return expenseId;
    });
  }

  /// يُحدث مصروف راتب + سحبة مرآة في معاملة واحدة.
  Future<void> updateSalaryExpenseWithMirror({
    required int expenseId,
    required int employeeId,
    required String employeeUuid,
    required String expenseType,
    required String description,
    required double amount,
    required String date,
    required String hotelDayKey,
    required String action,
    required double signedAmount,
    double? previousAmount,
    int? previousEmployeeId,
    String? note,
    String? recorderName,
    bool originIsServer = false,
  }) async {
    final now = Time.nowEpoch();
    final reasonText = 'exp_$expenseId';
    final deviceId = AppwriteSyncManager.currentDeviceIdStatic ?? '';

    await _db.transaction(() async {
      // 1. جلب المصروف الحالي لـ localUuid و version
      final existingExpense = await (_db.select(_db.expenses)
            ..where((t) => t.id.equals(expenseId)))
          .getSingleOrNull();
      if (existingExpense == null) {
        throw StateError('Expense $expenseId not found');
      }
      final expenseLocalUuid = existingExpense.localUuid;
      final expenseVersion = existingExpense.version;

      // 2. تحديث المصروف
      await (_db.update(_db.expenses)
            ..where((t) => t.id.equals(expenseId)))
          .write(
        ExpensesCompanion(
          expenseType: d.Value(expenseType),
          relatedId: d.Value(employeeId),
          description: d.Value(description),
          amount: d.Value(amount),
          date: d.Value(date),
          hotelDayKey: d.Value(hotelDayKey),
          employeeUuid: d.Value(employeeUuid),
          updatedAt: d.Value(now),
          lastModified: originIsServer
              ? const d.Value.absent()
              : d.Value(now),
          version: d.Value(expenseVersion + 1),
        ),
      );

      // 3. البحث عن السحبة المرآة الموجودة
      final existingWithdrawals = await _db
          .customSelect(
            'SELECT id, local_uuid, version FROM salary_withdrawals WHERE expense_id = ? AND deleted_at IS NULL',
            variables: [d.Variable.withInt(expenseId)],
          )
          .get();

      SalaryWithdrawal? matchedWithdrawal;
      if (existingWithdrawals.isNotEmpty) {
        for (final row in existingWithdrawals) {
          final w = await (_db.select(_db.salaryWithdrawals)
                ..where((t) => t.id.equals(row.read<int>('id'))))
              .getSingleOrNull();
          if (w != null) {
            matchedWithdrawal = w;
            break;
          }
        }
      }

      // إذا لم توجد عبر expense_id، ابحث عبر reason
      if (matchedWithdrawal == null) {
        final byReason = await (_db.select(_db.salaryWithdrawals)
              ..where((t) =>
                  t.reason.like('%exp_$expenseId%') & t.deletedAt.isNull()))
            .get();
        for (final w in byReason) {
          if (w.employeeId == employeeId ||
              (previousEmployeeId != null && w.employeeId == previousEmployeeId)) {
            matchedWithdrawal = w;
            break;
          }
        }
      }

      if (matchedWithdrawal != null) {
        // تحديث السحبة الموجودة
        await (_db.update(_db.salaryWithdrawals)
              ..where((t) => t.id.equals(matchedWithdrawal!.id)))
            .write(
          SalaryWithdrawalsCompanion(
            employeeId: d.Value(employeeId),
            employeeUuid: d.Value(employeeUuid),
            amount: d.Value(signedAmount),
            withdrawDate: d.Value(date),
            reason: d.Value(reasonText),
            withdrawalType: d.Value(action),
            description: d.Value(note ?? description),
            hotelDayKey: d.Value(hotelDayKey),
            recorderName: recorderName != null && recorderName.isNotEmpty
                ? d.Value(recorderName)
                : const d.Value.absent(),
            deviceId: deviceId.isEmpty
                ? const d.Value.absent()
                : d.Value(deviceId),
            updatedAt: d.Value(now),
            lastModified: originIsServer
                ? const d.Value.absent()
                : d.Value(now),
            version: d.Value(matchedWithdrawal.version + 1),
          ),
        );

        // تحديث expense_id في العمود الخام
        await _db.customStatement(
          'UPDATE salary_withdrawals SET expense_id = ? WHERE id = ?',
          [expenseId, matchedWithdrawal.id],
        );

        if (!originIsServer) {
          await _outboxDao.merge(
            entity: 'salary_withdrawals',
            op: 'update',
            localUuid: matchedWithdrawal.localUuid,
            serverId: matchedWithdrawal.serverId,
            payload: {
              'employeeId': employeeId,
              'employeeUuid': employeeUuid,
              'amount': signedAmount,
              'withdrawDate': date,
              'reason': reasonText,
              'withdrawalType': action,
              'description': note ?? description,
              'hotelDayKey': hotelDayKey,
              'lastModified': now,
              'expenseId': expenseId,
            },
            clientTs: now,
          );
        }
      } else {
        // إنشاء سحبة جديدة
        final withdrawalUuid = IdGen.uuid();
        final newWithdrawalId = await _db
            .into(_db.salaryWithdrawals)
            .insert(
              SalaryWithdrawalsCompanion(
                localUuid: d.Value(withdrawalUuid),
                employeeId: d.Value(employeeId),
                employeeUuid: d.Value(employeeUuid),
                amount: d.Value(signedAmount),
                withdrawDate: d.Value(date),
                reason: d.Value(reasonText),
                withdrawalType: d.Value(action),
                description: d.Value(note ?? description),
                hotelDayKey: d.Value(hotelDayKey),
                recorderName: recorderName != null && recorderName.isNotEmpty
                    ? d.Value(recorderName)
                    : const d.Value.absent(),
                deviceId: d.Value(deviceId),
                createdAt: d.Value(now),
                updatedAt: d.Value(now),
                deletedAt: const d.Value.absent(),
                lastModified: d.Value(now),
                createdAtEpoch: d.Value(now),
                lastModifiedEpoch: d.Value(now),
                version: const d.Value(1),
                origin: d.Value(originIsServer ? 'server' : 'local'),
                vectorClock: const d.Value('{}'),
              ),
            );

        await _db.customStatement(
          'UPDATE salary_withdrawals SET expense_id = ? WHERE id = ?',
          [expenseId, newWithdrawalId],
        );

        if (!originIsServer) {
          await _outboxDao.merge(
            entity: 'salary_withdrawals',
            op: 'create',
            localUuid: withdrawalUuid,
            payload: {
              'employeeId': employeeId,
              'employeeUuid': employeeUuid,
              'amount': signedAmount,
              'withdrawDate': date,
              'reason': reasonText,
              'withdrawalType': action,
              'description': note ?? description,
              'hotelDayKey': hotelDayKey,
              'expenseId': expenseId,
              'deviceId': deviceId,
            },
            clientTs: now,
          );
        }
      }

      // 4. outbox للمصروف
      if (!originIsServer) {
        await _outboxDao.merge(
          entity: 'expenses',
          op: 'update',
          localUuid: expenseLocalUuid,
          payload: {
            'expenseType': expenseType,
            'relatedId': employeeId,
            'employeeUuid': employeeUuid,
            'description': description,
            'amount': amount,
            'date': date,
            'hotelDayKey': hotelDayKey,
            'lastModified': now,
          },
          clientTs: now,
        );
      }
    });
  }

  /// يحذف مصروف راتب + سحبة مرآة في معاملة واحدة (soft delete).
  Future<void> deleteSalaryExpenseWithMirror({
    required int expenseId,
    required String expenseLocalUuid,
    String? withdrawalLocalUuid,
    int? employeeId,
    String? employeeUuid,
    bool originIsServer = false,
  }) async {
    final now = Time.nowEpoch();
    final deviceId = AppwriteSyncManager.currentDeviceIdStatic ?? '';

    await _db.transaction(() async {
      // 1. soft delete للمصروف
      await (_db.update(_db.expenses)
            ..where((t) => t.id.equals(expenseId)))
          .write(
        ExpensesCompanion(
          deletedAt: d.Value(now),
          updatedAt: d.Value(now),
          lastModified: originIsServer ? const d.Value.absent() : d.Value(now),
          version: d.Value(1),
        ),
      );

      // 2. soft delete للسحبة المرآة
      final existingWithdrawals = await _db
          .customSelect(
            'SELECT id, local_uuid, version FROM salary_withdrawals WHERE expense_id = ? AND deleted_at IS NULL',
            variables: [d.Variable.withInt(expenseId)],
          )
          .get();

      for (final row in existingWithdrawals) {
        final wId = row.read<int>('id');
        final wLocalUuid = row.read<String>('local_uuid');
        final wVersion = row.read<int>('version');

        // فلترة حسب الموظف إذا مُرّر
        if (employeeId != null || (employeeUuid != null && employeeUuid.isNotEmpty)) {
          final w = await (_db.select(_db.salaryWithdrawals)
                ..where((t) => t.id.equals(wId)))
            .getSingleOrNull();
          if (w != null) {
            final match = (employeeId != null && w.employeeId == employeeId) ||
                (employeeUuid != null && employeeUuid.isNotEmpty && w.employeeUuid == employeeUuid);
            if (!match) continue;
          }
        }

        await (_db.update(_db.salaryWithdrawals)
              ..where((t) => t.id.equals(wId)))
            .write(
          SalaryWithdrawalsCompanion(
            deletedAt: d.Value(now),
            updatedAt: d.Value(now),
            lastModified: originIsServer ? const d.Value.absent() : d.Value(now),
            version: d.Value(wVersion + 1),
          ),
        );

        if (!originIsServer) {
          await _outboxDao.merge(
            entity: 'salary_withdrawals',
            op: 'update',
            localUuid: wLocalUuid,
            payload: {
              'employeeId': employeeId,
              'deletedAt': now,
              'lastModified': now,
            },
            clientTs: now,
          );
        }
      }

      // 3. outbox للمصروف
      if (!originIsServer) {
        await _outboxDao.merge(
          entity: 'expenses',
          op: 'update',
          localUuid: expenseLocalUuid,
          payload: {
            'deletedAt': now,
            'lastModified': now,
          },
          clientTs: now,
        );
      }
    });
  }

  /// يعيد تعيين موظف لمصروف راتب + سحبة مرآة في معاملة واحدة.
  Future<void> reassignSalaryExpenseEmployee({
    required int expenseId,
    required int newEmployeeId,
    required String newEmployeeUuid,
    required String expenseLocalUuid,
    bool originIsServer = false,
  }) async {
    final now = Time.nowEpoch();
    final deviceId = AppwriteSyncManager.currentDeviceIdStatic ?? '';

    await _db.transaction(() async {
      // 1. تحديث المصروف
      final existingExpense = await (_db.select(_db.expenses)
            ..where((t) => t.id.equals(expenseId)))
          .getSingleOrNull();
      if (existingExpense == null) {
        throw StateError('Expense $expenseId not found');
      }
      final expenseVersion = existingExpense.version;

      await (_db.update(_db.expenses)
            ..where((t) => t.id.equals(expenseId)))
          .write(
        ExpensesCompanion(
          relatedId: d.Value(newEmployeeId),
          employeeUuid: d.Value(newEmployeeUuid),
          updatedAt: d.Value(now),
          lastModified: originIsServer ? const d.Value.absent() : d.Value(now),
          version: d.Value(expenseVersion + 1),
        ),
      );

      // 2. تحديث السحبة المرآة
      final existingWithdrawals = await _db
          .customSelect(
            'SELECT id, local_uuid, version FROM salary_withdrawals WHERE expense_id = ? AND deleted_at IS NULL',
            variables: [d.Variable.withInt(expenseId)],
          )
          .get();

      for (final row in existingWithdrawals) {
        final wId = row.read<int>('id');
        final wLocalUuid = row.read<String>('local_uuid');
        final wVersion = row.read<int>('version');

        await (_db.update(_db.salaryWithdrawals)
              ..where((t) => t.id.equals(wId)))
            .write(
          SalaryWithdrawalsCompanion(
            employeeId: d.Value(newEmployeeId),
            employeeUuid: d.Value(newEmployeeUuid),
            updatedAt: d.Value(now),
            lastModified: originIsServer ? const d.Value.absent() : d.Value(now),
            version: d.Value(wVersion + 1),
          ),
        );

        if (!originIsServer) {
          await _outboxDao.merge(
            entity: 'salary_withdrawals',
            op: 'update',
            localUuid: wLocalUuid,
            payload: {
              'employeeId': newEmployeeId,
              'employeeUuid': newEmployeeUuid,
              'lastModified': now,
            },
            clientTs: now,
          );
        }
      }

      // 3. outbox للمصروف
      if (!originIsServer) {
        await _outboxDao.merge(
          entity: 'expenses',
          op: 'update',
          localUuid: expenseLocalUuid,
          payload: {
            'relatedId': newEmployeeId,
            'employeeUuid': newEmployeeUuid,
            'lastModified': now,
          },
          clientTs: now,
        );
      }
    });
  }
}