import '../utils/status_utils.dart';
import 'local_db.dart';

class SalaryEntitlement {

  SalaryEntitlement({
    required this.employee,
    required this.hireDate,
    required this.totalMonthsWorked,
    required this.basicSalary,
    required this.totalEntitlement,
    required this.totalWithdrawals,
    required this.totalAdvances,
    required this.installmentsPaid,
    required this.totalDeductions,
    required this.netEntitlement,
    required this.transactions,
  });
  final Employee employee;
  final DateTime hireDate;
  final int totalMonthsWorked;
  final double basicSalary;
  final double totalEntitlement;

  /// سحب راتب مباشر (سحب راتب / رواتب / سحب من الراتب)
  final double totalWithdrawals;

  /// إجمالي السلف المعطاة (كل أنواع السلفة)
  final double totalAdvances;

  /// إجمالي أقساط السلف المسددة (خصم من الراتب تلقائي = قسط سلفة)
  final double installmentsPaid;

  /// خصوم حقيقية (غياب / خصم / خصم راتب / خصم من الراتب يدوي)
  final double totalDeductions;

  final double netEntitlement;
  final List<SalaryTransaction> transactions;

  /// رصيد السلف المتبقي = إجمالي السلف - الأقساط المسددة
  double get advanceBalance => totalAdvances - installmentsPaid;
}

class SalaryTransaction {

  SalaryTransaction({
    required this.type,
    required this.amount,
    required this.date,
    this.note,
    this.category,
  });
  final String type; // 'سحب', 'سلفة', 'خصم'
  final double amount;
  final String date;
  final String? note;
  final String? category; // 'سحب راتب', 'سلفة', 'غياب', 'خصم راتب', 'خصم من الراتب', ...
}

class SalaryEntitlementService {

  SalaryEntitlementService(this._db);
  final AppDatabase _db;

  Future<List<SalaryEntitlement>> calculateAllEntitlements() async {
    final employees = await (_db.select(
      _db.employees,
    )..where((e) => e.deletedAt.isNull())
     ..where((e) => e.status.isIn(StatusUtils.activeEmployeeStatuses)))
        .get();

    final entitlements = <SalaryEntitlement>[];
    for (final employee in employees) {
      final entitlement = await calculateEmployeeEntitlement(employee);
      entitlements.add(entitlement);
    }
    return entitlements;
  }

  Future<SalaryEntitlement> calculateEmployeeEntitlement(
    Employee employee,
  ) async {
    final now = DateTime.now();
    DateTime hireDate;
    try {
      hireDate = employee.hireDate.isNotEmpty
          ? DateTime.parse(employee.hireDate)
          : now;
    } catch (e) {
      hireDate = now;
    }

    final totalMonthsWorked = _calculateMonthsDifference(hireDate, now);
    final totalEntitlement = totalMonthsWorked * employee.basicSalary;

    final expenses = await (_db.select(
      _db.expenses,
    )..where((e) => e.relatedId.equals(employee.id))
     ..where((e) => e.deletedAt.isNull()))
        .get();

    double totalWithdrawals = 0; // سحب راتب فقط
    double totalAdvances = 0; // سلفة فقط
    double installmentsPaid = 0; // أقساط سلفة مسددة
    double totalDeductions = 0; // خصوم حقيقية
    final transactions = <SalaryTransaction>[];

    for (final expense in expenses) {
      final type = expense.expenseType.trim();

      if (type == 'سحب راتب' || type == 'رواتب' || type == 'سحب من الراتب') {
        // ✅ سحب راتب مباشر
        totalWithdrawals += expense.amount;
        transactions.add(
          SalaryTransaction(
            type: 'سحب',
            amount: expense.amount,
            date: expense.date,
            note: expense.description,
            category: 'سحب راتب',
          ),
        );
      } else if (type == 'سلفة') {
        // ✅ إصلاح حرج: جميع السلف تُحسب كـ سحب — الموظف استلم المبلغ فعلاً
        // سابقاً كان isAutoGenerated يُستبعد مما يسبب ازدواج:
        // السلفة لا تظهر كـ سحب + أقساطها تظهر كخصم = حساب مزدوج
        totalAdvances += expense.amount;
        transactions.add(
          SalaryTransaction(
            type: 'سلفة',
            amount: expense.amount,
            date: expense.date,
            note: expense.description,
            category: 'سلفة',
          ),
        );
      } else if (type == 'خصم من الراتب') {
        // ✅ إصلاح حرج: أقساط السلفة لا تُحسب كخصم — السلفة محسوبة كـ سحب
        // قسط السلفة = سداد للسلفة وليس خصماً جديداً
        final isInstallment = expense.isAutoGenerated &&
            expense.description.contains('قسط سلفة');
        if (isInstallment) {
          // قسط سلفة — يُسجل كمسدد من رصيد السلفة
          installmentsPaid += expense.amount;
          // لا نضيفه للمعاملات لأن السلفة نفسها معروضة كـ سحب
        } else {
          // خصم يدوي من الراتب — خصم حقيقي
          totalDeductions += expense.amount;
          transactions.add(
            SalaryTransaction(
              type: 'خصم',
              amount: expense.amount,
              date: expense.date,
              note: expense.description,
              category: 'خصم من الراتب',
            ),
          );
        }
      } else if (type == 'خصم راتب' || type == 'خصم' || type == 'غياب') {
        // خصوم حقيقية
        totalDeductions += expense.amount;
        transactions.add(
          SalaryTransaction(
            type: 'خصم',
            amount: expense.amount,
            date: expense.date,
            note: expense.description,
            category: type,
          ),
        );
      }
    }

    transactions.sort((a, b) => b.date.compareTo(a.date));
    // ✅ إصلاح: صافي المستحقات = الاستحقاق - السحبيات - السلف - الخصومات
    // السلفة مبلغ استلمه الموظف فعلاً فيجب خصمه من المستحقات
    final netEntitlement =
        totalEntitlement - totalWithdrawals - totalAdvances - totalDeductions;

    return SalaryEntitlement(
      employee: employee,
      hireDate: hireDate,
      totalMonthsWorked: totalMonthsWorked,
      basicSalary: employee.basicSalary,
      totalEntitlement: totalEntitlement,
      totalWithdrawals: totalWithdrawals,
      totalAdvances: totalAdvances,
      installmentsPaid: installmentsPaid,
      totalDeductions: totalDeductions,
      netEntitlement: netEntitlement,
      transactions: transactions,
    );
  }

  int _calculateMonthsDifference(DateTime from, DateTime to) {
    int months = (to.year - from.year) * 12 + (to.month - from.month);
    if (to.day < from.day) {
      months--;
    }
    return months < 0 ? 0 : months;
  }

  Future<Map<String, dynamic>> getSummary() async {
    final entitlements = await calculateAllEntitlements();
    double totalEntitlements = 0,
        totalWithdrawals = 0,
        totalAdvances = 0,
        totalDeductions = 0,
        totalNet = 0;
    for (final e in entitlements) {
      totalEntitlements += e.totalEntitlement;
      totalWithdrawals += e.totalWithdrawals;
      totalAdvances += e.totalAdvances;
      totalDeductions += e.totalDeductions;
      totalNet += e.netEntitlement;
    }
    return {
      'count': entitlements.length,
      'totalEntitlements': totalEntitlements,
      'totalWithdrawals': totalWithdrawals,
      'totalAdvances': totalAdvances,
      'totalDeductions': totalDeductions,
      'totalNet': totalNet,
      'entitlements': entitlements,
    };
  }
}
