import 'package:drift/drift.dart' as d;

import '../utils/id.dart';
import '../utils/status_utils.dart';
import '../utils/time.dart';
import 'crashlytics_service.dart';
import 'daos/outbox_dao.dart';
import 'local_db.dart';
import 'salary_cycle_calculator.dart';
import 'salary_expense_classifier.dart';
import 'salary_mirror_matcher.dart';
import 'package:marina_hotel_mobile/utils/debug_log.dart';

class SalaryEntitlement {
  SalaryEntitlement({
    required this.employee,
    required this.hireDate,
    required this.totalMonthsWorked,
    required this.basicSalary,
    required this.totalEntitlement,
    required this.totalWithdrawals,
    required this.totalAdvances,
    required this.installmentsPaid,
    required this.totalDeductions,
    required this.netEntitlement,
    required this.transactions,
  });
  final Employee employee;
  final DateTime hireDate;
  final int totalMonthsWorked;
  final double basicSalary;
  final double totalEntitlement;

  /// سحب راتب مباشر (سحب راتب / رواتب / سحب من الراتب)
  final double totalWithdrawals;

  /// إجمالي السلف المعطاة (كل أنواع السلفة)
  final double totalAdvances;

  /// إجمالي أقساط السلف المسددة (خصم من الراتب تلقائي = قسط سلفة)
  final double installmentsPaid;

  /// خصوم حقيقية (غياب / خصم / خصم راتب / خصم من الراتب يدوي)
  final double totalDeductions;

  final double netEntitlement;
  final List<SalaryTransaction> transactions;

  /// رصيد السلف المتبقي = إجمالي السلف - الأقساط المسددة
  double get advanceBalance => totalAdvances - installmentsPaid;
}

class SalaryTransaction {
  SalaryTransaction({
    required this.type,
    required this.amount,
    required this.date,
    this.note,
    this.category,
  });
  final String type; // 'سحب', 'سلفة', 'خصم'
  final double amount;
  final String date;
  final String? note;
  final String?
  category; // 'سحب راتب', 'سلفة', 'غياب', 'خصم راتب', 'خصم من الراتب', ...
}

class SalaryEntitlementService {
  SalaryEntitlementService(this._db);
  final AppDatabase _db;

  Future<List<SalaryEntitlement>> calculateAllEntitlements() async {
    final employees =
        await (_db.select(_db.employees)
              ..where((e) => e.deletedAt.isNull())
              ..where((e) => e.status.isIn(StatusUtils.activeEmployeeStatuses)))
            .get();

    final entitlements = <SalaryEntitlement>[];
    for (final employee in employees) {
      final entitlement = await calculateEmployeeEntitlement(employee);
      entitlements.add(entitlement);
    }
    return entitlements;
  }

  Future<SalaryEntitlement> calculateEmployeeEntitlement(
    Employee employee,
  ) async {
    final now = DateTime.now();
    DateTime hireDate;
    try {
      hireDate = employee.hireDate.isNotEmpty
          ? DateTime.parse(employee.hireDate)
          : now;
    } catch (e) {
      hireDate = now;
    }

    final totalMonthsWorked = _calculateMonthsDifference(hireDate, now);
    final totalEntitlement = totalMonthsWorked * employee.basicSalary;

    final expenses =
        await (_db.select(_db.expenses)
              ..where((e) => e.relatedId.equals(employee.id))
              ..where((e) => e.deletedAt.isNull()))
            .get();

    double totalWithdrawals = 0; // سحب راتب فقط
    double totalAdvances = 0; // سلفة فقط
    double installmentsPaid = 0; // أقساط سلفة مسددة
    double totalDeductions = 0; // خصوم حقيقية
    final transactions = <SalaryTransaction>[];

    // ✅ كل معرفات مصروفات الموظف تُعتبر "مقروءة" — أي سحب مرتبط بأحدِها
    // لا يُعَد مرة ثانية من salary_withdrawals (منع الازدواج)
    final linkedExpenseIds = expenses.map((e) => e.id).toSet();

    for (final expense in expenses) {
      final type = expense.expenseType.trim();

      if (SalaryExpenseClassifier.isSalaryDeduction(type)) {
        if (type.contains('خصم من الراتب')) {
          // ✅ إصلاح حرج: أقساط السلفة لا تُحسب كخصم — السلفة محسوبة كـ سحب
          // قسط السلفة = سداد للسلفة وليس خصماً جديداً
          final isInstallment =
              expense.isAutoGenerated && expense.description.contains('قسط سلفة');
          if (isInstallment) {
            // قسط سلفة — يُسجل كمسدد من رصيد السلفة
            installmentsPaid += expense.amount;
            // لا نضيفه للمعاملات لأن السلفة نفسها معروضة كـ سحب
          } else {
            // خصم يدوي من الراتب — خصم حقيقي
            totalDeductions += expense.amount;
            transactions.add(
              SalaryTransaction(
                type: 'خصم',
                amount: expense.amount,
                date: expense.date,
                note: expense.description,
                category: 'خصم من الراتب',
              ),
            );
          }
        } else {
          // خصوم حقيقية (خصم راتب / خصم / غياب)
          totalDeductions += expense.amount;
          transactions.add(
            SalaryTransaction(
              type: 'خصم',
              amount: expense.amount,
              date: expense.date,
              note: expense.description,
              category: type,
            ),
          );
        }
      } else if (SalaryExpenseClassifier.isSalaryCashOut(type)) {
        if (type.contains('سلفة')) {
          // ✅ إصلاح حرج: جميع السلف تُحسب كـ سحب — الموظف استلم المبلغ فعلاً
          // سابقاً كان isAutoGenerated يُستبعد مما يسبب ازدواج:
          // السلفة لا تظهر كـ سحب + أقساطها تظهر كخصم = حساب مزدوج
          totalAdvances += expense.amount;
          transactions.add(
            SalaryTransaction(
              type: 'سلفة',
              amount: expense.amount,
              date: expense.date,
              note: expense.description,
              category: 'سلفة',
            ),
          );
        } else {
          // ✅ سحب راتب مباشر
          totalWithdrawals += expense.amount;
          transactions.add(
            SalaryTransaction(
              type: 'سحب',
              amount: expense.amount,
              date: expense.date,
              note: expense.description,
              category: 'سحب راتب',
            ),
          );
        }
      }
    }

    // ✅ إصلاح المعادلة «مصروفات الرواتب = استحقاقات الموظف»:
    // السحوبات المباشرة من شاشة الموظفين تُنشأ في salary_withdrawals فقط
    // (expenseId = 0) بلا مصروف مقابل — نقد خرج فعلاً لكنه لم يكن يُخصم
    // من الاستحقاق إطلاقاً لأن الحساب أعلاه يقرأ جدول expenses فقط.
    // الآن تُضاف السحوبات غير المرتبطة بأي مصروف مقروء.
    final directWithdrawals = await _getUnlinkedWithdrawals(
      employee.id,
      linkedExpenseIds,
      employeeExpenses: expenses,
    );
    for (final w in directWithdrawals) {
      if (SalaryExpenseClassifier.isAdvanceWithdrawal(w.withdrawalType)) {
        totalAdvances += w.amount;
        transactions.add(
          SalaryTransaction(
            type: 'سلفة',
            amount: w.amount,
            date: w.date,
            note: w.description,
            category: 'سلفة',
          ),
        );
      } else {
        totalWithdrawals += w.amount;
        transactions.add(
          SalaryTransaction(
            type: 'سحب',
            amount: w.amount,
            date: w.date,
            note: w.description,
            category: 'سحب راتب',
          ),
        );
      }
    }

    transactions.sort((a, b) => b.date.compareTo(a.date));
    // ✅ إصلاح: صافي المستحقات = الاستحقاق - السحبيات - السلف - الخصومات
    // السلفة مبلغ استلمه الموظف فعلاً فيجب خصمه من المستحقات
    final netEntitlement =
        totalEntitlement - totalWithdrawals - totalAdvances - totalDeductions;

    return SalaryEntitlement(
      employee: employee,
      hireDate: hireDate,
      totalMonthsWorked: totalMonthsWorked,
      basicSalary: employee.basicSalary,
      totalEntitlement: totalEntitlement,
      totalWithdrawals: totalWithdrawals,
      totalAdvances: totalAdvances,
      installmentsPaid: installmentsPaid,
      totalDeductions: totalDeductions,
      netEntitlement: netEntitlement,
      transactions: transactions,
    );
  }

  int _calculateMonthsDifference(DateTime from, DateTime to) {
    int months = (to.year - from.year) * 12 + (to.month - from.month);
    if (to.day < from.day) {
      months--;
    }
    return months < 0 ? 0 : months;
  }

  Future<Map<String, dynamic>> getSummary() async {
    final entitlements = await calculateAllEntitlements();
    double totalEntitlements = 0,
        totalWithdrawals = 0,
        totalAdvances = 0,
        totalDeductions = 0,
        totalNet = 0;
    for (final e in entitlements) {
      totalEntitlements += e.totalEntitlement;
      totalWithdrawals += e.totalWithdrawals;
      totalAdvances += e.totalAdvances;
      totalDeductions += e.totalDeductions;
      totalNet += e.netEntitlement;
    }
    return {
      'count': entitlements.length,
      'totalEntitlements': totalEntitlements,
      'totalWithdrawals': totalWithdrawals,
      'totalAdvances': totalAdvances,
      'totalDeductions': totalDeductions,
      'totalNet': totalNet,
      'entitlements': entitlements,
    };
  }

  // ═══════════════════════════════════════════════════════════════
  // نظام الدورات الشهرية + الترحيل التلقائي
  // ═══════════════════════════════════════════════════════════════

  /// حساب الدورة الشهرية الحالية للموظف
  Future<MonthlySalaryCycle> calculateCurrentCycle(Employee employee) async {
    await _ensureAutomaticCarryOver(employee);

    final now = DateTime.now();
    final hireDate = _parseDate(employee.hireDate) ?? now;

    final cycleStart = _getCycleStart(hireDate, now);
    final cycleEnd = _getCycleEnd(cycleStart);

    final carriedOver = await _calculateAccumulatedCarryOver(
      employee,
      hireDate,
      cycleStart,
    );
    final cycleTxns = await _getCycleTransactions(
      employee,
      cycleStart,
      cycleEnd,
    );
    final carryOverLogs = await _getCarryOverLogsForCycle(
      employee.id,
      cycleStart,
    );

    return MonthlySalaryCycle(
      employee: employee,
      cycleStart: cycleStart,
      cycleEnd: cycleEnd,
      basicSalary: employee.basicSalary,
      totalWithdrawals: cycleTxns.withdrawals,
      totalDeductions: cycleTxns.deductions,
      totalAdvances: cycleTxns.advances,
      installmentsPaid: cycleTxns.installmentsPaid,
      carriedOverFromPrevious: carriedOver,
      transactions: cycleTxns.transactions,
      carryOverLogs: carryOverLogs,
    );
  }

  /// حساب كل الدورات الشهرية للموظف
  Future<List<MonthlySalaryCycle>> calculateAllCycles(Employee employee) async {
    await _ensureAutomaticCarryOver(employee);

    final now = DateTime.now();
    final hireDate = _parseDate(employee.hireDate) ?? now;

    final cycles = <MonthlySalaryCycle>[];
    var cycleStart = _getCycleStart(hireDate, hireDate);
    var carriedOver = 0.0;

    while (cycleStart.isBefore(now) || cycleStart.isAtSameMomentAs(now)) {
      final cycleEnd = _getCycleEnd(cycleStart);
      final txns = await _getCycleTransactions(employee, cycleStart, cycleEnd);
      final carryOverLogs = await _getCarryOverLogsForCycle(
        employee.id,
        cycleStart,
      );

      final displayTxns = List<SalaryCycleTransaction>.from(txns.transactions);
      if (carriedOver > 0) {
        displayTxns.insert(
          0,
          SalaryCycleTransaction(
            type: 'ترحيل',
            amount: carriedOver,
            date: _formatDate(cycleStart),
            note: 'مبلغ مرحّل من الدورة السابقة لتجاوز السحب',
            category: 'ترحيل',
            isCarryOver: true,
          ),
        );
      }

      final cycle = MonthlySalaryCycle(
        employee: employee,
        cycleStart: cycleStart,
        cycleEnd: cycleEnd,
        basicSalary: employee.basicSalary,
        totalWithdrawals: txns.withdrawals,
        totalDeductions: txns.deductions,
        totalAdvances: txns.advances,
        installmentsPaid: txns.installmentsPaid,
        carriedOverFromPrevious: carriedOver,
        transactions: displayTxns,
        carryOverLogs: carryOverLogs,
      );

      carriedOver = cycle.carryOverToNext;
      cycles.add(cycle);

      final nextStart = cycleEnd.add(const Duration(days: 1));
      if (nextStart.isAfter(now)) break;
      cycleStart = nextStart;
    }

    return cycles.reversed.toList();
  }

  /// تشغيل الترحيل كجزء من قراءة الدورة دون أن يفشل عرض الشاشة إذا تعذر
  /// التسجيل مؤقتاً. الفشل يُسجل وتبقى عملية الحساب قابلة لإعادة المحاولة.
  Future<void> _ensureAutomaticCarryOver(Employee employee) async {
    try {
      await processAutoCarryOver(employee);
    } catch (e, stack) {
      dlog(() => '⚠️ تعذر الترحيل التلقائي مؤقتاً: $e');
      await CrashlyticsService.instance.recordScreenError(
        screen: 'SalaryEntitlementService',
        action: 'processAutoCarryOver',
        error: e,
        stackTrace: stack,
        severity: CrashlyticsSeverity.warning,
      );
    }
  }

  /// الترحيل التلقائي — ينشئ سجل عند تجاوز الراتب
  Future<void> processAutoCarryOver(Employee employee) async {
    final now = DateTime.now();
    final hireDate = _parseDate(employee.hireDate) ?? now;
    final currentCycleStart = _getCycleStart(hireDate, now);
    final previousCycleEnd = currentCycleStart.subtract(
      const Duration(days: 1),
    );
    final previousCycleStart = _getCycleStart(hireDate, previousCycleEnd);

    if (previousCycleStart.isBefore(hireDate)) return;

    final carriedOver = await _calculateAccumulatedCarryOver(
      employee,
      hireDate,
      currentCycleStart,
    );
    if (carriedOver <= 0) return;

    final currentCycleEnd = _getCycleEnd(currentCycleStart);
    final reason =
        'تم ترحيل مبلغ ${carriedOver.toStringAsFixed(0)} ريال '
        'إلى دورة الراتب التالية '
        'بسبب تجاوز إجمالي السحوبات والخصومات للراتب '
        'في دورة ${_formatDate(previousCycleStart)} إلى ${_formatDate(previousCycleEnd)}.';

    final nowEpoch = Time.nowEpoch();
    final carryLogUuid = IdGen.uuid();

    // SQLite transaction serializes competing calls from repeated screen opens
    // or two local triggers. The duplicate check and insert must be atomic.
    await _db.transaction(() async {
      final existing = await _checkExistingCarryOver(
        employee.id,
        previousCycleStart,
        currentCycleStart,
      );
      if (existing) return;

      await _db
          .into(_db.salaryCarryOverLogs)
          .insert(
            SalaryCarryOverLogsCompanion.insert(
              employeeId: employee.id,
              amount: carriedOver,
              previousCycleStart: _formatDate(previousCycleStart),
              previousCycleEnd: _formatDate(previousCycleEnd),
              newCycleStart: _formatDate(currentCycleStart),
              newCycleEnd: _formatDate(currentCycleEnd),
              reason: reason,
              carriedAt: nowEpoch,
              localUuid: carryLogUuid,
              createdAt: nowEpoch,
              updatedAt: nowEpoch,
              lastModified: nowEpoch,
            ),
          );

      // Keep the database write and its sync intent in one transaction.
      await OutboxDao(_db).merge(
        entity: 'salary_carry_over_logs',
        op: 'create',
        localUuid: carryLogUuid,
        clientTs: nowEpoch,
        payload: {
          'employeeId': employee.id,
          'amount': carriedOver,
          'previousCycleStart': _formatDate(previousCycleStart),
          'previousCycleEnd': _formatDate(previousCycleEnd),
          'newCycleStart': _formatDate(currentCycleStart),
          'newCycleEnd': _formatDate(currentCycleEnd),
          'reason': reason,
          'carriedAt': nowEpoch,
        },
      );
    });

    dlog(() => '📝 ترحيل تلقائي: $carriedOver للموظف ${employee.name}');
  }

  /// جلب كل سجلات الترحيل لموظف
  Future<List<SalaryCarryOverLog>> getAllCarryOverLogs(int employeeId) async {
    return (_db.select(_db.salaryCarryOverLogs)
          ..where((t) => t.employeeId.equals(employeeId))
          ..where((t) => t.deletedAt.isNull())
          ..orderBy([(t) => d.OrderingTerm.desc(t.carriedAt)]))
        .get();
  }

  // ─── أدوات مساعدة للدورات ───

  Future<double> _calculateAccumulatedCarryOver(
    Employee employee,
    DateTime hireDate,
    DateTime targetCycleStart,
  ) async {
    var cycleStart = _getCycleStart(hireDate, hireDate);
    var carryOver = 0.0;

    while (cycleStart.isBefore(targetCycleStart)) {
      final cycleEnd = _getCycleEnd(cycleStart);
      final txns = await _getCycleTransactions(employee, cycleStart, cycleEnd);
      final totalDeductions =
          txns.withdrawals + txns.deductions + txns.advances + carryOver;
      final remaining = employee.basicSalary - totalDeductions;
      carryOver = remaining < 0 ? remaining.abs() : 0.0;
      cycleStart = cycleEnd.add(const Duration(days: 1));
    }

    return carryOver;
  }

  Future<_CycleTxns> _getCycleTransactions(
    Employee employee,
    DateTime cycleStart,
    DateTime cycleEnd,
  ) async {
    final expenses =
        await (_db.select(_db.expenses)
              ..where((e) => e.relatedId.equals(employee.id))
              ..where((e) => e.deletedAt.isNull()))
            .get();

    double withdrawals = 0, deductions = 0, advances = 0, installmentsPaid = 0;
    final transactions = <SalaryCycleTransaction>[];

    final linkedExpenseIds = expenses.map((e) => e.id).toSet();

    for (final expense in expenses) {
      final expDate = _parseDate(expense.date);
      if (expDate == null) continue;
      if (expDate.isBefore(cycleStart) || expDate.isAfter(cycleEnd)) continue;

      final type = expense.expenseType.trim();

      if (SalaryExpenseClassifier.isSalaryDeduction(type)) {
        if (type.contains('خصم من الراتب')) {
          final isInstallment =
              expense.isAutoGenerated && expense.description.contains('قسط سلفة');
          if (isInstallment) {
            installmentsPaid += expense.amount;
          } else {
            deductions += expense.amount;
            transactions.add(
              SalaryCycleTransaction(
                type: 'خصم',
                amount: expense.amount,
                date: expense.date,
                note: expense.description,
                category: 'خصم من الراتب',
              ),
            );
          }
        } else {
          deductions += expense.amount;
          transactions.add(
            SalaryCycleTransaction(
              type: 'خصم',
              amount: expense.amount,
              date: expense.date,
              note: expense.description,
              category: type,
            ),
          );
        }
      } else if (SalaryExpenseClassifier.isSalaryCashOut(type)) {
        if (type.contains('سلفة')) {
          advances += expense.amount;
          transactions.add(
            SalaryCycleTransaction(
              type: 'سلفة',
              amount: expense.amount,
              date: expense.date,
              note: expense.description,
              category: 'سلفة',
            ),
          );
        } else {
          withdrawals += expense.amount;
          transactions.add(
            SalaryCycleTransaction(
              type: 'سحب',
              amount: expense.amount,
              date: expense.date,
              note: expense.description,
              category: 'سحب راتب',
            ),
          );
        }
      }
    }

    // ✅ إصلاح المعادلة: السحوبات المباشرة (بلا مصروف مقابل) تدخل الدورة
    // الشهرية أيضاً — وإلا ظل "المتاح للسحب" أعلى من الواقع.
    final directWithdrawals = await _getUnlinkedWithdrawals(
      employee.id,
      linkedExpenseIds,
      cycleStart: cycleStart,
      cycleEnd: cycleEnd,
      employeeExpenses: expenses,
    );
    for (final w in directWithdrawals) {
      if (SalaryExpenseClassifier.isAdvanceWithdrawal(w.withdrawalType)) {
        advances += w.amount;
        transactions.add(
          SalaryCycleTransaction(
            type: 'سلفة',
            amount: w.amount,
            date: w.date,
            note: w.description,
            category: 'سلفة',
          ),
        );
      } else {
        withdrawals += w.amount;
        transactions.add(
          SalaryCycleTransaction(
            type: 'سحب',
            amount: w.amount,
            date: w.date,
            note: w.description,
            category: 'سحب راتب',
          ),
        );
      }
    }

    transactions.sort((a, b) => b.date.compareTo(a.date));
    return _CycleTxns(
      withdrawals,
      deductions,
      advances,
      installmentsPaid,
      transactions,
    );
  }

  /// السحوبات المباشرة غير المرتبطة بأي مصروف مقروء.
  ///
  /// مصدرها زر «سحب راتب» في شاشة الموظفين (settings_employees) الذي ينشئ
  /// سجلاً في salary_withdrawals فقط بلا مصروف مقابل (expenseId = 0).
  /// dedup عبر SalaryMirrorMatcher (مصدر الحقيقة الموحّد):
  ///   1. عمود expense_id الخام (Migration 40) — إن أشار لمصروف مقروء.
  ///   2. نمط reason القديم "exp_N" — إن كان N مصروفاً مقروءاً (id أو serverId).
  ///   3. مطابقة بيانات حتمية (موظف + نقدي + مبلغ + يوم) — تُغلق ثغرة العد
  ///      المزدوج عبر الأجهزة: المصروف السحابي بلا معرف رقمي فيأخذ id محلياً
  ///      جديداً بينما السحبة المرآة تبقى على exp_N لجهاز المصدر (حالة
  ///      «الاورمو محمد» المثبتة 2026-09-14).
  /// المرايا السالبة (خصوم) تُهمل — الخصم يُقرأ من جدول المصروفات فقط.
  Future<List<_DirectWithdrawalData>> _getUnlinkedWithdrawals(
    int employeeId,
    Set<int> linkedExpenseIds, {
    DateTime? cycleStart,
    DateTime? cycleEnd,
    List<Expense>? employeeExpenses,
  }) async {
    final rows =
        await (_db.select(_db.salaryWithdrawals)
              ..where((t) => t.employeeId.equals(employeeId))
              ..where((t) => t.deletedAt.isNull()))
            .get();
    if (rows.isEmpty) return const [];

    // مرشحو المستوى 3: مصروفات الموظف النقدي فقط (بنطاق القراءة المطلوب)
    final candidates = (employeeExpenses ?? const <Expense>[])
        .map(
          (e) => MirrorExpenseCandidate(
            id: e.id,
            serverId: e.serverId,
            expenseType: e.expenseType,
            amount: e.amount,
            date: e.date,
            hotelDayKey: e.hotelDayKey,
            relatedId: e.relatedId,
          ),
        )
        .toList(growable: false);

    final result = <_DirectWithdrawalData>[];
    for (final sw in rows) {
      // المرايا السالبة للخصوم — تُقرأ من المصروفات (ليست نقداً)
      if (sw.amount <= 0) continue;

      final isMirror = SalaryMirrorMatcher.isMirrorOfReadExpense(
        expenseId: sw.expenseId,
        reason: sw.reason,
        amount: sw.amount,
        hotelDayKey: sw.hotelDayKey,
        withdrawDate: sw.withdrawDate,
        employeeId: employeeId,
        expenses: candidates,
      );
      if (isMirror) continue;

      // فلترة نطاق الدورة الزمني عند الطلب
      if (cycleStart != null && cycleEnd != null) {
        final dt = _parseDate(sw.withdrawDate);
        if (dt == null) continue;
        if (dt.isBefore(cycleStart) || dt.isAfter(cycleEnd)) continue;
      }

      result.add(
        _DirectWithdrawalData(
          amount: sw.amount,
          date: sw.withdrawDate,
          withdrawalType: sw.withdrawalType,
          description: sw.description,
        ),
      );
    }
    return result;
  }

  Future<bool> _checkExistingCarryOver(
    int employeeId,
    DateTime prevStart,
    DateTime newStart,
  ) async {
    final result =
        await (_db.select(_db.salaryCarryOverLogs)
              ..where((t) => t.employeeId.equals(employeeId))
              ..where(
                (t) => t.previousCycleStart.equals(_formatDate(prevStart)),
              )
              ..where((t) => t.newCycleStart.equals(_formatDate(newStart)))
              ..where((t) => t.deletedAt.isNull())
              ..limit(1))
            .get();
    return result.isNotEmpty;
  }

  Future<List<SalaryCarryOverLog>> _getCarryOverLogsForCycle(
    int employeeId,
    DateTime cycleStart,
  ) async {
    final startStr = _formatDate(cycleStart);
    return (_db.select(_db.salaryCarryOverLogs)
          ..where((t) => t.employeeId.equals(employeeId))
          ..where((t) => t.deletedAt.isNull())
          ..where(
            (t) =>
                t.newCycleStart.equals(startStr) |
                t.previousCycleStart.equals(startStr),
          )
          ..orderBy([(t) => d.OrderingTerm.desc(t.carriedAt)]))
        .get();
  }

  DateTime _getCycleStart(DateTime hireDate, DateTime referenceDate) {
    final int day = hireDate.day;
    int year = referenceDate.year;
    int month = referenceDate.month;
    if (referenceDate.day < day) {
      month--;
      if (month < 1) {
        month = 12;
        year--;
      }
    }
    final daysInMonth = DateTime(year, month + 1, 0).day;
    final actualDay = day > daysInMonth ? daysInMonth : day;
    return DateTime(year, month, actualDay);
  }

  DateTime _getCycleEnd(DateTime cycleStart) {
    final nextStart = DateTime(
      cycleStart.year,
      cycleStart.month + 1,
      cycleStart.day,
    );
    return nextStart.subtract(const Duration(days: 1));
  }

  DateTime? _parseDate(String dateStr) {
    if (dateStr.isEmpty) return null;
    try {
      final normalized = dateStr.contains('T')
          ? dateStr
          : dateStr.replaceFirst(' ', 'T');
      final withSeconds = normalized.length == 16
          ? '$normalized:00'
          : normalized;
      return DateTime.parse(withSeconds);
    } catch (_) {
      try {
        return DateTime.parse(dateStr.split(' ').first);
      } catch (_) {
        return null;
      }
    }
  }

  String _formatDate(DateTime dt) {
    return '${dt.year}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')}';
  }
}

// ═══════════════════════════════════════════════════════════════
// نماذج الدورة الشهرية
// ═══════════════════════════════════════════════════════════════

class MonthlySalaryCycle {
  MonthlySalaryCycle({
    required this.employee,
    required this.cycleStart,
    required this.cycleEnd,
    required this.basicSalary,
    required this.totalWithdrawals,
    required this.totalDeductions,
    required this.totalAdvances,
    required this.installmentsPaid,
    required this.carriedOverFromPrevious,
    required this.transactions,
    required this.carryOverLogs,
  });

  final Employee employee;
  final DateTime cycleStart;
  final DateTime cycleEnd;
  final double basicSalary;
  final double totalWithdrawals;
  final double totalDeductions;
  final double totalAdvances;
  final double installmentsPaid;
  final double carriedOverFromPrevious;
  final List<SalaryCycleTransaction> transactions;
  final List<SalaryCarryOverLog> carryOverLogs;

  SalaryCycleResult get calculation => SalaryCycleCalculator.calculate(
    SalaryCycleInput(
      basicSalary: basicSalary,
      withdrawals: totalWithdrawals,
      advances: totalAdvances,
      installmentsPaid: installmentsPaid,
      deductions: totalDeductions,
      carriedOverFromPrevious: carriedOverFromPrevious,
    ),
  );

  double get totalDeductionsAndWithdrawals =>
      calculation.totalBeforeCarryOver.toDouble();
  double get remainingBalance =>
      calculation.remainingBalance.toDouble() - calculation.carryOverToNext;
  bool get hasExceeded => calculation.hasExceeded;
  double get carryOverToNext => calculation.carryOverToNext.toDouble();
  double get availableToWithdraw =>
      remainingBalance > 0 ? remainingBalance : 0.0;

  String get cycleKey =>
      '${cycleStart.day}/${cycleStart.month}/${cycleStart.year} → '
      '${cycleEnd.day}/${cycleEnd.month}/${cycleEnd.year}';

  String get monthLabel {
    const months = [
      '',
      'يناير',
      'فبراير',
      'مارس',
      'أبريل',
      'مايو',
      'يونيو',
      'يوليو',
      'أغسطس',
      'سبتمبر',
      'أكتوبر',
      'نوفمبر',
      'ديسمبر',
    ];
    return '${months[cycleStart.month]} ${cycleStart.year}';
  }
}

class SalaryCycleTransaction {
  SalaryCycleTransaction({
    required this.type,
    required this.amount,
    required this.date,
    this.note,
    this.category,
    this.isCarryOver = false,
  });

  final String type;
  final double amount;
  final String date;
  final String? note;
  final String? category;
  final bool isCarryOver;
}

class _CycleTxns {
  _CycleTxns(
    this.withdrawals,
    this.deductions,
    this.advances,
    this.installmentsPaid,
    this.transactions,
  );
  final double withdrawals;
  final double deductions;
  final double advances;
  final double installmentsPaid;
  final List<SalaryCycleTransaction> transactions;
}

/// سحب مباشر غير مرتبط بمصروف — يُحتسب ضمن الاستحقاق والدورات
/// والشاشات النقدية حتى تتساوى مصروفات الرواتب مع استحقاقات الموظف.
class _DirectWithdrawalData {
  _DirectWithdrawalData({
    required this.amount,
    required this.date,
    this.withdrawalType,
    this.description,
  });
  final double amount;
  final String date;
  final String? withdrawalType;
  final String? description;
}
