import '../utils/hotel_time_engine.dart';
import '../utils/time.dart';
import 'local_db.dart';
import 'repositories/expenses_repository.dart';
import 'repositories/salary_withdrawals_repository.dart';

class SalaryAdvanceInstallmentsService {
  SalaryAdvanceInstallmentsService(
    this._db,
    this._expensesRepo,
    this._salaryWithdrawalsRepo,
  );

  final AppDatabase _db;
  final ExpensesRepository _expensesRepo;
  final SalaryWithdrawalsRepository _salaryWithdrawalsRepo;

  Future<void> createInstallmentAdvance({
    required int employeeId,
    required double totalAmount,
    required String advanceDate,
    required String description,
    required int installments,
    bool startNextMonth = true,
  }) async {
    if (employeeId <= 0) {
      return;
    }
    if (totalAmount <= 0) {
      return;
    }
    if (installments <= 0) {
      return;
    }

    final date = Time.safeIsoToDateString(advanceDate);
    final effectiveDescription =
        description.trim().isNotEmpty ? description.trim() : 'سلفة';

    await _db.transaction(() async {
      final advanceExpenseId = await _expensesRepo.createAutoGenerated(
        expenseType: 'سلفة',
        relatedId: employeeId,
        description: '$effectiveDescription (مقسطة على $installments)',
        amount: totalAmount,
        date: date,
      );

      await _salaryWithdrawalsRepo.saveFromExpense(
        expenseId: advanceExpenseId,
        employeeId: employeeId,
        action: 'سلفة',
        amount: totalAmount,
        date: date,
        note: effectiveDescription,
        hotelDayKey: HotelTimeEngine.getHotelDayKeyFromDate(date),
      );

      final base = totalAmount / installments;
      final baseRounded = (base).roundToDouble();
      double remaining = totalAmount;

      DateTime baseDate;
      try {
        baseDate = DateTime.parse(date);
      } catch (_) {
        baseDate = DateTime.now();
      }

      for (var i = 1; i <= installments; i++) {
        final isLast = i == installments;
        final amt = isLast ? remaining : baseRounded;
        remaining = (remaining - amt).roundToDouble();

        final monthsToAdd = (startNextMonth ? 1 : 0) + (i - 1);
        final due = _addMonthsPreserveDay(baseDate, monthsToAdd);
        final dueStr = Time.dateToString(due);

        final instDesc = 'قسط سلفة #$advanceExpenseId ($i/$installments)';

        final exists = await (_db.select(_db.expenses)
              ..where((e) => e.deletedAt.isNull())
              ..where((e) => e.isAutoGenerated.equals(true))
              ..where((e) => e.relatedId.equals(employeeId))
              ..where((e) => e.expenseType.equals('خصم من الراتب'))
              ..where((e) => e.date.equals(dueStr))
              ..where((e) => e.description.equals(instDesc)))
            .getSingleOrNull();

        if (exists != null) {
          continue;
        }

        final installmentExpenseId = await _expensesRepo.createAutoGenerated(
          expenseType: 'خصم من الراتب',
          relatedId: employeeId,
          description: instDesc,
          amount: amt,
          date: dueStr,
        );

        await _salaryWithdrawalsRepo.saveFromExpense(
          expenseId: installmentExpenseId,
          employeeId: employeeId,
          action: 'خصم من الراتب',
          amount: -amt,
          date: dueStr,
          note: instDesc,
          hotelDayKey: HotelTimeEngine.getHotelDayKeyFromDate(dueStr),
        );
      }
    });
  }

  DateTime _addMonthsPreserveDay(DateTime base, int monthsToAdd) {
    final targetMonth = base.month + monthsToAdd;
    final firstOfTarget = DateTime(base.year, targetMonth);
    final lastDay = DateTime(firstOfTarget.year, firstOfTarget.month + 1, 0).day;
    final day = base.day <= lastDay ? base.day : lastDay;
    return DateTime(firstOfTarget.year, firstOfTarget.month, day);
  }
}
