import 'dart:async';

import 'package:drift/drift.dart' as d;

import '../../utils/hotel_time_engine.dart';
import '../../utils/time.dart';
import '../auto_backup_manager.dart';
import '../crashlytics_service.dart';
import '../daos/expenses_dao.dart';
import '../daos/outbox_dao.dart';
import '../local_db.dart';

class ExpensesRepository {
  ExpensesRepository(this.db) {
    outbox = OutboxDao(db);
    dao = ExpensesDao(db, outbox);
  }
  final AppDatabase db;
  late final OutboxDao outbox;
  late final ExpensesDao dao;

  Stream<List<Expense>> watchAll() => dao.watchList();
  Stream<List<Expense>> watchByHotelDayKey(String hotelDayKey) =>
      dao.watchByHotelDayKey(hotelDayKey);
  Stream<Expense?> watchOne(int id) => dao.watchById(id);
  Future<List<Expense>> listFiltered({
    String? from,
    String? to,
    String? expenseType,
  }) => dao.listFiltered(from: from, to: to, expenseType: expenseType);

  /// البحث المتقدم مع دعم البحث النصي في الوصف ونوع المصروف
  Future<List<Expense>> listWithSearch({
    String? search,
    String? from,
    String? to,
  }) => dao.list(search: search, from: from, to: to);

  /// فلترة بـ hotelDayKey مع دعم البحث النصي — الطريقة الدقيقة
  Future<List<Expense>> listFilteredByHotelDay({
    String? fromHotelDay,
    String? toHotelDay,
    String? expenseType,
    String? search,
  }) => dao.listFilteredByHotelDay(
    fromHotelDay: fromHotelDay,
    toHotelDay: toHotelDay,
    expenseType: expenseType,
    search: search,
  );

  Future<int> create({
    required String expenseType,
    int? relatedId,
    required String description,
    required double amount,
    required String date,
  }) async {
    try {
      final normalizedDate = Time.safeIsoToDateString(date);
      // ✅ إصلاح: حساب hotelDayKey باستخدام 14:00:01 من التاريخ التقويمي
      // المنتقي يعطي تاريخ بدون وقت — تمريره مباشرة يُفسَّر كمنتصف الليل (00:00)
      // مما يُعطي اليوم الفندقي السابق خطأً.
      // مثال: اختيار "19 مايو" → getHotelDayKeyFromIso("2026-05-19") = midnight < 14:00 → "2026-05-18" ❌
      // بينما المستخدم يقصد اليوم الفندقي 19 مايو (14:00 يوم 19 → 13:59 يوم 20)
      // الحل: نمرّر 14:00:01 مثلما تفعل شاشة الفلترة (_hotelDayKeyFromDate)
      final hotelDayKey = _hotelDayKeyFromCalendarDate(normalizedDate);
      final result = await dao.insertOne(
        ExpensesCompanion(
          expenseType: d.Value(expenseType),
          relatedId: d.Value(relatedId),
          description: d.Value(description),
          amount: d.Value(amount),
          date: d.Value(normalizedDate),
          hotelDayKey: d.Value(hotelDayKey),
        ),
      );
      unawaited(AutoBackupManager.instance.onDataChange(
        'expenses',
        'INSERT',
        recordData: {'amount': amount},
      ),);
      return result;
    } catch (e, stack) {
      await CrashlyticsService.instance.recordScreenError(
        screen: 'ExpensesRepository',
        action: 'create',
        error: e,
        stackTrace: stack,
        severity: CrashlyticsSeverity.fatal,
        extra: {'expenseType': expenseType, 'amount': '$amount'},
      );
      rethrow;
    }
  }

  /// إنشاء مصروف مُولّد تلقائياً (سلفة مقسطة / خصم من الراتب)
  Future<int> createAutoGenerated({
    required String expenseType,
    int? relatedId,
    required String description,
    required double amount,
    required String date,
  }) async {
    try {
      final normalizedDate = Time.safeIsoToDateString(date);
      // ✅ إصلاح: استخدام _hotelDayKeyFromCalendarDate لضمان الاتساق مع create/update
      final hotelDayKey = _hotelDayKeyFromCalendarDate(normalizedDate);
      final result = await dao.insertOne(
        ExpensesCompanion(
          expenseType: d.Value(expenseType),
          relatedId: d.Value(relatedId),
          description: d.Value(description),
          amount: d.Value(amount),
          date: d.Value(normalizedDate),
          hotelDayKey: d.Value(hotelDayKey),
          isAutoGenerated: const d.Value(true),
        ),
      );
      unawaited(AutoBackupManager.instance.onDataChange(
        'expenses',
        'INSERT',
        recordData: {'amount': amount, 'isAutoGenerated': true},
      ),);
      return result;
    } catch (e, stack) {
      await CrashlyticsService.instance.recordScreenError(
        screen: 'ExpensesRepository',
        action: 'createAutoGenerated',
        error: e,
        stackTrace: stack,
        severity: CrashlyticsSeverity.fatal,
        extra: {'expenseType': expenseType, 'amount': '$amount'},
      );
      rethrow;
    }
  }

  Future<int> update(
    int id, {
    String? expenseType,
    int? relatedId,
    String? description,
    double? amount,
    String? date,
  }) async {
    try {
      final normalizedDate = date != null ? Time.safeIsoToDateString(date) : null;
      final result = await dao.updateById(
        id,
        ExpensesCompanion(
          expenseType: expenseType != null
              ? d.Value(expenseType)
              : const d.Value.absent(),
          relatedId: relatedId != null
              ? d.Value(relatedId)
              : const d.Value.absent(),
          description: description != null
              ? d.Value(description)
              : const d.Value.absent(),
          amount: amount != null ? d.Value(amount) : const d.Value.absent(),
          date: normalizedDate != null
              ? d.Value(normalizedDate)
              : const d.Value.absent(),
          // ✅ إصلاح: حساب hotelDayKey بنفس طريقة create — باستخدام 14:00:01
          hotelDayKey: date != null
              ? d.Value(_hotelDayKeyFromCalendarDate(normalizedDate!))
              : const d.Value.absent(),
        ),
      );
      if (result > 0) {
        unawaited(AutoBackupManager.instance.onDataChange(
          'expenses',
          'UPDATE',
          recordData: {'id': id},
        ),);
      }
      return result;
    } catch (e, stack) {
      await CrashlyticsService.instance.recordScreenError(
        screen: 'ExpensesRepository',
        action: 'update',
        error: e,
        stackTrace: stack,
        extra: {'id': '$id'},
      );
      rethrow;
    }
  }

  Future<int> delete(int id) async {
    try {
      final result = await dao.softDelete(id);
      if (result > 0) {
        unawaited(AutoBackupManager.instance.onDataChange(
          'expenses',
          'DELETE',
          recordData: {'id': id},
        ),);
      }
      return result;
    } catch (e, stack) {
      await CrashlyticsService.instance.recordScreenError(
        screen: 'ExpensesRepository',
        action: 'delete',
        error: e,
        stackTrace: stack,
        extra: {'id': '$id'},
      );
      rethrow;
    }
  }

  // دوال النسخ الاحتياطي

  /// تصدير بيانات المصروفات
  Future<Map<String, dynamic>> exportData() async {
    final expensesData = await dao.exportToJson();
    final recordCount = await dao.getRecordCount();

    return {'data': expensesData, 'count': recordCount, 'entity': 'expenses'};
  }

  /// استيراد بيانات المصروفات
  Future<void> importData(Map<String, dynamic> data) async {
    if (data.containsKey('data') && data['data'] is List) {
      await dao.importFromJson(
        List<Map<String, dynamic>>.from(data['data'] as List),
      );
    }
  }

  /// مسح جميع البيانات
  Future<void> clearAllData() async {
    await dao.clearAllData();
  }

  /// الحصول على إجمالي عدد السجلات
  Future<int> getRecordCount() async {
    return dao.getRecordCount();
  }

  /// الحصول على إجمالي المصروفات لتاريخ محدد
  Future<double> getTotalByDate(String date) async {
    final result = await db.customSelect(
      'SELECT COALESCE(SUM(amount), 0.0) AS total FROM expenses WHERE date LIKE ? AND deleted_at IS NULL',
      variables: [d.Variable.withString('$date%')],
      readsFrom: {db.expenses},
    ).getSingle();
    return (result.data['total'] as num).toDouble();
  }

  Future<double> getTotalByHotelDayKey(String hotelDayKey) async {
    final result = await db.customSelect(
      'SELECT COALESCE(SUM(amount), 0.0) AS total FROM expenses '
      'WHERE deleted_at IS NULL AND (hotel_day_key = ? OR (hotel_day_key IS NULL AND date LIKE ?))',
      variables: [d.Variable.withString(hotelDayKey), d.Variable.withString('$hotelDayKey%')],
      readsFrom: {db.expenses},
    ).getSingle();
    return (result.data['total'] as num).toDouble();
  }

  /// إصلاح سجلات المصروفات القديمة التي تحتوي على hotelDayKey خاطئ
  /// (كان يُعيَّن بالتاريخ التقويمي بدلاً من مفتاح اليوم الفندقي)
  ///
  /// يُستدعى مرة واحدة عند تشغيل التطبيق لتصحيح البيانات التاريخية.
  Future<int> backfillHotelDayKeys() async {
    final allExpenses = await dao.list(includeDeleted: true);
    int fixed = 0;
    for (final expense in allExpenses) {
      if (expense.hotelDayKey == null || expense.hotelDayKey!.isEmpty) {
        continue;
      }
      // ✅ إصلاح: استخدام _hotelDayKeyFromCalendarDate بدلاً من getHotelDayKeyFromIso
      // لأن حقل date يخزن تاريخاً تقويمياً بدون وقت (yyyy-MM-dd)
      // وتمريره مباشرة لـ getHotelDayKeyFromIso يُنتج اليوم الفندقي السابق خطأً
      final correctKey = _hotelDayKeyFromCalendarDate(expense.date);
      if (expense.hotelDayKey != correctKey) {
        await (db.update(db.expenses)
              ..where((t) => t.id.equals(expense.id)))
            .write(
          ExpensesCompanion(
            hotelDayKey: d.Value(correctKey),
          ),
        );
        fixed++;
      }
    }
    return fixed;
  }

  /// حساب مفتاح اليوم الفندقي من تاريخ تقويمي (بدون وقت)
  ///
  /// المنتقي يعطي تاريخاً بدون وقت مثل "2026-05-19".
  /// إذا مررناه مباشرة لـ HotelTimeEngine.getHotelDayKeyFromIso،
  /// يُفسَّر كمنتصف الليل (00:00:00) وهو قبل 14:00، فيُعطي اليوم السابق خطأً.
  ///
  /// الحل: نمرّر 14:00:01 لضمان أن التاريخ التقويمي يُعطي نفس اليوم الفندقي.
  /// هذا يطابق منطق _hotelDayKeyFromDate في expenses_list.dart
  static String _hotelDayKeyFromCalendarDate(String calendarDate) {
    try {
      final parts = calendarDate.split('-');
      if (parts.length != 3) {
        return HotelTimeEngine.getHotelDayKey();
      }
      final year = int.tryParse(parts[0]) ?? 1;
      final month = int.tryParse(parts[1]) ?? 1;
      final day = int.tryParse(parts[2]) ?? 1;
      return HotelTimeEngine.getHotelDayKey(
        dateTime: DateTime(year, month, day, 14, 0, 1),
      );
    } catch (_) {
      return HotelTimeEngine.getHotelDayKey();
    }
  }
}
