const { createCollection } = require('./lib');

async function main() {
  console.log('=== Batch 6: payment_voids + guest_infos + salary_cycles + salary_payments + salary_withdrawals ===');

  await createCollection('payment_voids', [
    { key: 'originalPaymentUuid', type: 'string', size: 64, required: true },
    { key: 'originalPaymentId', type: 'integer', required: true },
    { key: 'bookingUuid', type: 'string', size: 64, required: true },
    { key: 'voidedAmount', type: 'integer', required: true },
    { key: 'voidReason', type: 'string', size: 1024, required: true },
    { key: 'voidedBy', type: 'string', size: 128, required: true },
    { key: 'voidedAt', type: 'integer', required: true },
    { key: 'voidedAtIso', type: 'string', size: 50, required: true },
    { key: 'hotelDayKey', type: 'string', size: 50, required: true },
    { key: 'reversalPaymentUuid', type: 'string', size: 64, required: false },
    { key: 'approvedBy', type: 'string', size: 128, required: false },
  ]);

  await createCollection('guest_infos', [
    { key: 'roomNumber', type: 'string', size: 20, required: true },
    { key: 'guestName', type: 'string', size: 255, required: true },
    { key: 'nationality', type: 'string', size: 100, required: true },
    { key: 'idNumber', type: 'string', size: 100, required: true },
    { key: 'idType', type: 'string', size: 100, required: false, default: '\u0628\u0637\u0627\u0642\u0629 \u0634\u062e\u0635\u064a\u0629' },
    { key: 'issueDate', type: 'string', size: 50, required: false },
    { key: 'issuePlace', type: 'string', size: 255, required: false },
    { key: 'governorate', type: 'string', size: 100, required: false },
    { key: 'notes', type: 'string', size: 2048, required: false },
  ]);

  await createCollection('salary_cycles', [
    { key: 'employeeId', type: 'integer', required: true },
    { key: 'cycleKey', type: 'string', size: 50, required: true },
    { key: 'hotelDayStart', type: 'string', size: 50, required: false },
    { key: 'hotelDayEnd', type: 'string', size: 50, required: false },
    { key: 'expectedAmount', type: 'integer', required: false, default: 0 },
    { key: 'actualPaid', type: 'integer', required: false, default: 0 },
    { key: 'remainingAmount', type: 'integer', required: false, default: 0 },
    { key: 'status', type: 'string', size: 50, required: false, default: 'draft' },
  ]);

  await createCollection('salary_payments', [
    { key: 'cycleId', type: 'integer', required: true },
    { key: 'amount', type: 'integer', required: false, default: 0 },
    { key: 'hotelDayKey', type: 'string', size: 50, required: false },
    { key: 'paymentDateIso', type: 'string', size: 50, required: true },
    { key: 'method', type: 'string', size: 50, required: false },
    { key: 'isAutoGenerated', type: 'boolean', required: false, default: false },
  ]);

  await createCollection('salary_withdrawals', [
    { key: 'employeeId', type: 'integer', required: true },
    { key: 'amount', type: 'double', required: true },
    { key: 'withdrawDate', type: 'string', size: 50, required: true },
    { key: 'reason', type: 'string', size: 512, required: false },
    { key: 'hotelDayKey', type: 'string', size: 50, required: false },
    { key: 'withdrawalType', type: 'string', size: 50, required: false },
    { key: 'description', type: 'string', size: 1024, required: false },
  ]);

  console.log('\n✅ Batch 6 complete!');
}

main().catch(console.error);
