// ═══════════════════════════════════════════════════════════════
//  ai.test.ts — hermetic coverage for the natural-language endpoint
//
//  The Workers AI binding is mocked in-process (handleAiRequest takes
//  env as a parameter), so tests exercise the allow-listed SQL, the
//  two-step write confirmation, the role guard and every validation
//  branch without any network access or Cloudflare credentials.
// ═══════════════════════════════════════════════════════════════

import { env } from 'cloudflare:test';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { handleAiRequest, type AiBinding } from '../src/ai';
import { resetDb, uniqueUuid } from './helpers';

beforeEach(async () => {
  await resetDb();
});

function mockAi(plan: unknown): AiBinding {
  return {
    async run(_model: string, _input: unknown) {
      // Real Workers AI returns { response: "<string>" } for text models.
      return { response: JSON.stringify(plan) };
    },
  };
}

// ✅ (2026-09-20) نماذج 2026 (llama-3.3-70b) ترجع chat.completion من
// الربط — {choices: [{message: {content}}]} بدل {response: "…"} القديمة.
function chatAi(plan: unknown): AiBinding {
  return {
    async run() {
      return { choices: [{ message: { content: JSON.stringify(plan) } }] };
    },
  };
}

function garbageAi(): AiBinding {
  return {
    async run() {
      return { response: 'عذراً لا أستطيع إرجاع JSON' };
    },
  };
}

// ✅ (2026-09-20) ربط [AI] يرمي استثناء — حالة الإنتاج الحالية التي
// دفعت المالك لإنشاء توكن Workers AI (cfut_…) لمسار REST الاحتياطي.
function throwingAi(reason = 'binding unavailable in production'): AiBinding {
  return {
    async run() {
      throw new Error(reason);
    },
  };
}

function aiRequest(body: unknown): Request {
  return new Request('https://example.com/api/ai/query', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

const seedRoom = (uuid: string, number: string, status: string, deleted = false) =>
  env.DB.prepare(
    `INSERT INTO rooms (local_uuid, room_number, type, price, status, created_at, updated_at, last_modified, deleted_at)
     VALUES (?,?,?,?,?,?,?,0,?)`,
  ).bind(uuid, number, 'double', 80, status, 1700000000, 1700000000, deleted ? 1700000001 : null).run();

const seedBooking = (uuid: string, room: string, guest: string, status: string, deleted = false) =>
  env.DB.prepare(
    `INSERT INTO bookings (local_uuid, room_number, guest_name, guest_phone, guest_nationality, checkin_date, checkout_date, status, created_at, updated_at, last_modified, deleted_at)
     VALUES (?,?,?,?,?,?,?,?,?,?,0,?)`,
  ).bind(uuid, room, guest, '777000', 'يمني', '2026-09-15', '2026-09-18', status, 1700000000, 1700000000, deleted ? 1700000001 : null).run();

interface SeededEmployee {
  id: number;
  uuid: string;
}

async function seedEmployee(name: string, basicSalary: number, opts: { hireDate?: string; status?: string; deleted?: boolean } = {}): Promise<SeededEmployee> {
  const uuid = uniqueUuid('emp');
  const result = await env.DB.prepare(
    `INSERT INTO employees (name, basic_salary, status, hire_date, local_uuid, created_at, updated_at, last_modified, deleted_at)
     VALUES (?,?,?,?,?,?,?,0,?)`,
  ).bind(name, basicSalary, opts.status ?? 'active', opts.hireDate ?? '2026-01-01', uuid, 1700000000, 1700000000, opts.deleted ? 1700000001 : null).run();
  return { id: result.meta.last_row_id as number, uuid };
}

/** Employee money movement stored as an EXPENSE — the app's canonical model
 * (SalaryEntitlementService reads expenses, never salary_withdrawals). */
const seedEmployeeExpense = (opts: { employeeUuid?: string | null; employeeId?: number | null; type: string; amount: number; date: string; description?: string; autoGenerated?: boolean; deleted?: boolean }) =>
  env.DB.prepare(
    `INSERT INTO expenses (expense_type, description, amount, date, employee_uuid, related_id, is_auto_generated, local_uuid, created_at, updated_at, last_modified, deleted_at)
     VALUES (?,?,?,?,?,?,?,?,?,?,0,?)`,
  ).bind(
    opts.type,
    opts.description ?? 'بند',
    opts.amount,
    opts.date,
    opts.employeeUuid ?? null,
    opts.employeeId ?? null,
    opts.autoGenerated ? 1 : 0,
    uniqueUuid('exp'),
    1700000000,
    1700000000,
    opts.deleted ? 1700000001 : null,
  ).run();

const seedExpense = (uuid: string, type: string, amount: number, date: string, deleted = false) =>
  env.DB.prepare(
    `INSERT INTO expenses (expense_type, description, amount, date, local_uuid, created_at, updated_at, last_modified, deleted_at)
     VALUES (?,?,?,?,?,?,?,0,?)`,
  ).bind(type, 'بند', amount, date, uuid, 1700000000, 1700000000, deleted ? 1700000001 : null).run();

async function expenseCount(): Promise<number> {
  const row = await env.DB.prepare('SELECT COUNT(*) AS c FROM expenses').first<{ c: number }>();
  return row?.c ?? 0;
}

describe('ai: query flow (read-only)', () => {
  it('rooms_available returns only vacant, non-deleted rooms', async () => {
    await seedRoom(uniqueUuid('r1'), '101', 'available');
    await seedRoom(uniqueUuid('r2'), '102', 'available');
    await seedRoom(uniqueUuid('r3'), '103', 'occupied');
    await seedRoom(uniqueUuid('r4'), '104', 'available', true);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'كم غرفة شاغرة؟' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'rooms_available', explanation: 'الغرف الشاغرة' }) },
      'employee',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ room_number: string }>; requires_confirmation: boolean; answer: string };
    expect(body.rows.map((r) => r.room_number)).toEqual(['101', '102']);
    expect(body.requires_confirmation).toBe(false);
    expect(body.answer).toBe('الغرف الشاغرة');
    expect(await expenseCount()).toBe(0);
  });

  it('guest_search matches by partial name and ignores deleted bookings', async () => {
    await seedBooking(uniqueUuid('b1'), '201', 'أحمد سالم', 'active');
    await seedBooking(uniqueUuid('b2'), '202', 'سالم ناصر', 'active');
    await seedBooking(uniqueUuid('b3'), '203', 'أحمد صالح', 'active', true);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'ابحث عن النزيل أحمد' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'guest_search', guestName: 'أحمد', explanation: 'نتائج البحث' }) },
      'employee',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ guest_name: string }> };
    expect(body.rows).toHaveLength(1);
    expect(body.rows[0]?.guest_name).toBe('أحمد سالم');
  });

  it('employee_withdrawals mirrors the app expense classification (withdrawals/advances/deductions, قسط سلفة excluded)', async () => {
    const employee = await seedEmployee('عمر حسن', 100000);
    // Cash withdrawals (three canonical types)
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سحب راتب', amount: 30000, date: '2026-09-10' });
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'رواتب', amount: 10000, date: '2026-09-12' });
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سحب من الراتب', amount: 5000, date: '2026-09-15' });
    // Advance
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سلفة', amount: 15000, date: '2026-09-11' });
    // Non-cash deductions
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'خصم راتب', amount: 2000, date: '2026-09-13' });
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'غياب', amount: 1000, date: '2026-09-14' });
    // Auto salary-loan installment — NOT a deduction, NOT a withdrawal
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'خصم من الراتب', amount: 4000, date: '2026-09-16', description: 'قسط سلفة يناير', autoGenerated: true });
    // Manual خصم من الراتب — real deduction
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'خصم من الراتب', amount: 500, date: '2026-09-17' });
    // Unrelated expense type — ignored entirely
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'ديزل', amount: 99000, date: '2026-09-18' });
    // Deleted expense — ignored
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سحب راتب', amount: 77000, date: '2026-09-18', deleted: true });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'كم سحب عمر حسن؟' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'employee_withdrawals', employeeName: 'عمر', explanation: 'السحوبات' }) },
      'manager',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ name: string; total_withdrawn: number; total_advances: number; total_deductions: number; entries: number }> };
    expect(body.rows).toHaveLength(1);
    const row = body.rows[0]!;
    expect(row.total_withdrawn).toBe(45000);
    expect(row.total_advances).toBe(15000);
    expect(row.total_deductions).toBe(3500); // خصم راتب 2000 + غياب 1000 + يدوي 500
    expect(row.entries).toBe(8); // 3 سحب + سلفة + 4 خصومات/أقساط — ديزل والمحذوف خارجا
  });

  it('employee_withdrawals with a date range only counts entries inside the window, but the employee still appears with zero totals otherwise', async () => {
    const employee = await seedEmployee('سلطان', 100000);
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سحب راتب', amount: 20000, date: '2026-09-05' });
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سلفة', amount: 8000, date: '2026-09-10' });
    // Outside the requested window — must not be counted when a range is given.
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سحب راتب', amount: 50000, date: '2026-08-01' });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'كم سحب سلطان من 1 إلى 15 سبتمبر؟' }),
      {
        DB: env.DB,
        AI: mockAi({
          kind: 'query',
          queryType: 'employee_withdrawals',
          employeeName: 'سلطان',
          dateFrom: '2026-09-01',
          dateTo: '2026-09-15',
          explanation: 'السحوبات',
        }),
      },
      'manager',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as {
      rows: Array<{ name: string; total_withdrawn: number; total_advances: number; entries: number }>;
    };
    expect(body.rows).toHaveLength(1);
    expect(body.rows[0]).toMatchObject({ name: 'سلطان', total_withdrawn: 20000, total_advances: 8000, entries: 2 });

    // A window with zero matching entries must still return the employee row
    // (zero totals) — proving the date filter lives in the LEFT JOIN's ON
    // clause, not a WHERE that would silently drop unmatched employees.
    const emptyWindowRes = await handleAiRequest(
      aiRequest({ prompt: 'كم سحب سلطان في يناير؟' }),
      {
        DB: env.DB,
        AI: mockAi({
          kind: 'query',
          queryType: 'employee_withdrawals',
          employeeName: 'سلطان',
          dateFrom: '2026-01-01',
          dateTo: '2026-01-31',
          explanation: 'السحوبات',
        }),
      },
      'manager',
    );
    expect(emptyWindowRes.status).toBe(200);
    const emptyBody = (await emptyWindowRes.json()) as {
      rows: Array<{ name: string; total_withdrawn: number; entries: number }>;
    };
    expect(emptyBody.rows).toHaveLength(1);
    expect(emptyBody.rows[0]).toMatchObject({ name: 'سلطان', total_withdrawn: 0, entries: 0 });
  });

  it('employee money joins survive undashed uuids and related_id fallback', async () => {
    const dashed = await seedEmployee('ناصر', 50000);
    const fallback = await seedEmployee('سالم', 50000);
    // Undashed uuid — must still resolve (production has both forms)
    await seedEmployeeExpense({ employeeUuid: dashed.uuid.replace(/-/g, ''), type: 'سحب راتب', amount: 10000, date: '2026-09-01' });
    // No uuid — device-local related_id fallback (pre-migration rows)
    await seedEmployeeExpense({ employeeId: fallback.id, type: 'سحب راتب', amount: 20000, date: '2026-09-02' });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'سحوبات الموظفين' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'employee_withdrawals', explanation: 'x' }) },
      'manager',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ name: string; total_withdrawn: number }> };
    const byName = new Map(body.rows.map((r) => [r.name, r.total_withdrawn]));
    expect(byName.get('ناصر')).toBe(10000);
    expect(byName.get('سالم')).toBe(20000);
  });

  it('employee_salary computes entitlement with the app calendar-months formula', async () => {
    // Hire on the 1st of the month N months ago → months = full month slots
    const monthsAgo = 5;
    const hire = new Date();
    hire.setUTCDate(1);
    hire.setUTCMonth(hire.getUTCMonth() - monthsAgo);
    const hireDate = hire.toISOString().slice(0, 10);
    const employee = await seedEmployee('محمد احمد', 100000, { hireDate });
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سحب راتب', amount: 30000, date: '2026-09-10' });
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'سلفة', amount: 15000, date: '2026-09-11' });
    await seedEmployeeExpense({ employeeUuid: employee.uuid, type: 'غياب', amount: 3000, date: '2026-09-12' });
    // terminated employee must not appear
    const terminated = await seedEmployee('مسرّح قديماً', 100000, { hireDate, status: 'مسرّح' });
    await seedEmployeeExpense({ employeeUuid: terminated.uuid, type: 'سحب راتب', amount: 50000, date: '2026-09-10' });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'كم استحقاق محمد احمد؟' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'employee_salary', employeeName: 'محمد', explanation: 'الاستحقاق' }) },
      'manager',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ name: string; months_worked: number; total_entitlement: number; total_withdrawn: number; total_advances: number; total_deductions: number; net_entitlement: number }> };
    expect(body.rows).toHaveLength(1);
    const row = body.rows[0]!;
    expect(row.name).toBe('محمد احمد');
    expect(row.months_worked).toBe(monthsAgo);
    expect(row.total_entitlement).toBe(monthsAgo * 100000);
    expect(row.total_withdrawn).toBe(30000);
    expect(row.total_advances).toBe(15000);
    expect(row.total_deductions).toBe(3000);
    expect(row.net_entitlement).toBe(monthsAgo * 100000 - 30000 - 15000 - 3000);
  });

  it('salary_expenses aggregates CASH salary expenses only, per employee, best-spender first', async () => {
    const a = await seedEmployee('أ', 50000);
    const b = await seedEmployee('ب', 50000);
    await seedEmployeeExpense({ employeeUuid: a.uuid, type: 'سحب راتب', amount: 10000, date: '2026-09-01' });
    await seedEmployeeExpense({ employeeUuid: a.uuid, type: 'سلفة', amount: 5000, date: '2026-09-02' });
    await seedEmployeeExpense({ employeeUuid: b.uuid, type: 'رواتب', amount: 30000, date: '2026-09-03' });
    // Non-cash deductions — never cash salary expenses
    await seedEmployeeExpense({ employeeUuid: b.uuid, type: 'غياب', amount: 99000, date: '2026-09-04' });
    await seedEmployeeExpense({ employeeUuid: b.uuid, type: 'خصم راتب', amount: 88000, date: '2026-09-05' });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'مصروفات الموظفين والرواتب' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'salary_expenses', explanation: 'x' }) },
      'manager',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ name: string; withdrawals: number; advances: number }>; answer: string };
    expect(body.rows).toHaveLength(2);
    expect(body.rows[0]?.name).toBe('ب'); // 30000 cash > أ's 15000
    expect(body.rows[1]).toMatchObject({ name: 'أ', withdrawals: 10000, advances: 5000 });
    expect(body.answer).toContain('45000');
  });

  it('expenses_total aggregates by type inside the requested window only', async () => {
    await seedExpense(uniqueUuid('e1'), 'وقود', 500, '2026-09-05');
    await seedExpense(uniqueUuid('e2'), 'وقود', 300, '2026-09-20');
    await seedExpense(uniqueUuid('e3'), 'صيانة', 1000, '2026-09-12');
    await seedExpense(uniqueUuid('e4'), 'خارج النطاق', 999, '2026-08-31');
    await seedExpense(uniqueUuid('e5'), 'محذوف', 777, '2026-09-13', true);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'مصروفات سبتمبر' }),
      {
        DB: env.DB,
        AI: mockAi({ kind: 'query', queryType: 'expenses_total', dateFrom: '2026-09-01', dateTo: '2026-09-30', explanation: 'المصروفات' }),
      },
      'employee',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ expense_type: string; entries: number; total: number }> };
    const byType = new Map(body.rows.map((r) => [r.expense_type, r]));
    expect(byType.get('وقود')).toMatchObject({ entries: 2, total: 800 });
    expect(byType.get('صيانة')).toMatchObject({ entries: 1, total: 1000 });
    expect(byType.has('خارج النطاق')).toBe(false);
    expect(byType.has('محذوف')).toBe(false);
  });
});

describe('ai: add_expense (two-step write)', () => {
  const expensePlan = {
    kind: 'add_expense',
    expenseType: 'صيانة',
    description: 'إيجار المولد',
    amountPerDay: 40000,
    dateFrom: '2026-09-19',
    dateTo: '2026-09-21',
    explanation: 'إضافة مصروف يومي',
  };

  it('first pass asks for confirmation and writes nothing', async () => {
    const res = await handleAiRequest(
      aiRequest({ prompt: 'أضف مصروف 40 ألف لكل يوم من 19 إلى 21 سبتمبر' }),
      { DB: env.DB, AI: mockAi(expensePlan) },
      'admin',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { requires_confirmation: boolean; answer: string };
    expect(body.requires_confirmation).toBe(true);
    expect(body.answer).toContain('40000');
    expect(await expenseCount()).toBe(0);
  });

  it('confirmed plan inserts one row per day with ai origin', async () => {
    const res = await handleAiRequest(
      aiRequest({ plan: expensePlan, confirm: true }),
      { DB: env.DB, AI: mockAi(expensePlan) },
      'manager',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { answer: string };
    expect(body.answer).toContain('3');
    const rows = await env.DB.prepare(
      'SELECT expense_type, description, amount, date, hotel_day_key, is_auto_generated, origin, device_id FROM expenses ORDER BY date',
    ).all<{ expense_type: string; description: string; amount: number; date: string; hotel_day_key: string; is_auto_generated: number; origin: string; device_id: string }>();
    expect(rows.results).toHaveLength(3);
    expect(rows.results.map((r) => r.date)).toEqual(['2026-09-19', '2026-09-20', '2026-09-21']);
    for (const row of rows.results) {
      expect(row.expense_type).toBe('صيانة');
      expect(row.description).toBe('إيجار المولد');
      expect(row.amount).toBe(40000);
      expect(row.hotel_day_key).toBe(row.date);
      expect(row.is_auto_generated).toBe(0);
      expect(row.origin).toBe('ai');
      expect(row.device_id).toBe('worker');
    }
  });

  it('rejects roles below manager with 403 and no write', async () => {
    const res = await handleAiRequest(
      aiRequest({ plan: expensePlan, confirm: true }),
      { DB: env.DB, AI: mockAi(expensePlan) },
      'employee',
    );
    expect(res.status).toBe(403);
    expect(await expenseCount()).toBe(0);
  });
});

describe('ai: validation and failure modes', () => {
  it('empty prompt yields 400 without touching the model', async () => {
    const res = await handleAiRequest(aiRequest({ prompt: '   ' }), { DB: env.DB, AI: mockAi({}) }, 'admin');
    expect(res.status).toBe(400);
  });

  it('unsupported intent returns the explanation, not an error status', async () => {
    const res = await handleAiRequest(
      aiRequest({ prompt: 'احذف كل البيانات' }),
      { DB: env.DB, AI: mockAi({ kind: 'unsupported', explanation: 'لا يمكن تنفيذ هذا الطلب لأسباب أمنية' }) },
      'admin',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { answer: string; requires_confirmation: boolean };
    expect(body.requires_confirmation).toBe(false);
    expect(body.answer).toContain('لا يمكن');
  });

  it('query with unrecognized type asks for clarification', async () => {
    const res = await handleAiRequest(
      aiRequest({ prompt: 'شيء غير مفهوم' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', explanation: 'غير واضح' }) },
      'admin',
    );
    const body = (await res.json()) as { answer: string };
    expect(body.answer).toContain('لم أتعرف');
  });

  it('employee queries without a name return every active employee', async () => {
    await seedEmployee('موظف أول', 50000);
    await seedEmployee('موظف ثانٍ', 60000);
    await seedEmployee('موقوف', 70000, { status: 'موقوف' });
    await seedEmployee('محذوف', 80000, { deleted: true });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'رواتب الموظفين' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'employee_withdrawals', explanation: 'x' }) },
      'admin',
    );
    const body = (await res.json()) as { rows: Array<{ name: string }> };
    const names = body.rows.map((r) => r.name);
    expect(names).toHaveLength(2);
    expect(names).toContain('موظف أول');
    expect(names).toContain('موظف ثانٍ');
  });

  it('add_expense with a non-positive amount is rejected before any write', async () => {
    const res = await handleAiRequest(
      aiRequest({ prompt: 'أضف مصروفاً بدون مبلغ' }),
      {
        DB: env.DB,
        AI: mockAi({ kind: 'add_expense', expenseType: 'وقود', description: 'بلا مبلغ', amountPerDay: 0, dateFrom: '2026-09-19', dateTo: '2026-09-19', explanation: 'e' }),
      },
      'admin',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { requires_confirmation: boolean; answer: string };
    expect(body.requires_confirmation).toBe(false);
    expect(body.answer).toContain('المبلغ');
    expect(await expenseCount()).toBe(0);
  });

  it('add_expense with an inverted date range is rejected', async () => {
    const res = await handleAiRequest(
      aiRequest({ prompt: 'أضف مصروفاً بتواريخ معكوسة' }),
      {
        DB: env.DB,
        AI: mockAi({ kind: 'add_expense', expenseType: 'وقود', description: 'معكوس', amountPerDay: 100, dateFrom: '2026-09-21', dateTo: '2026-09-19', explanation: 'e' }),
      },
      'admin',
    );
    const body = (await res.json()) as { requires_confirmation: boolean; answer: string };
    expect(body.requires_confirmation).toBe(false);
    expect(body.answer).toContain('التاريخ');
    expect(await expenseCount()).toBe(0);
  });

  it('malformed model output yields 502, never a crash', async () => {
    const res = await handleAiRequest(aiRequest({ prompt: 'أي شيء' }), { DB: env.DB, AI: garbageAi() }, 'admin');
    expect(res.status).toBe(502);
    const body = (await res.json()) as { error: string };
    expect(body.error).toContain('تحليل');
  });
});

// ═══════════════════════════════════════════════════════════
//  2026 model upgrade (llama-3.3-70b-fp8-fast) — ✅ (2026-09-20)
//  الطراز القديم أوقفه Cloudflare (5028، 2026-05-30). العقود هنا
//  تثبت: صيغة chat.completion الجديدة تُحلّ، وتواريخ 1970 (أثر
//  epoch من النماذج الحديثة رغم التعليمات) تُعالج حتمياً.
// ═══════════════════════════════════════════════════════════

describe('ai: 2026 model upgrade contracts', () => {
  it('chat.completion shape from the binding parses and the query executes', async () => {
    await seedRoom(uniqueUuid(), '601', 'شاغرة');
    const res = await handleAiRequest(
      aiRequest({ prompt: 'وش الغرف الشاغرة؟' }),
      { DB: env.DB, AI: chatAi({ kind: 'query', queryType: 'rooms_available', explanation: 'شاغرة' }) },
      'admin',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { requires_confirmation: boolean; rows: Array<{ room_number: string }> };
    expect(body.requires_confirmation).toBe(false);
    expect(body.rows.some((r) => r.room_number === '601')).toBe(true);
  });

  it('epoch default dates (1970-01-01) on add_expense become today per design', async () => {
    const today = new Date().toISOString().slice(0, 10);
    const res = await handleAiRequest(
      aiRequest({ prompt: 'اضف مصروف اشتراك انترنت 60000 شهرياً' }),
      {
        DB: env.DB,
        AI: chatAi({
          kind: 'add_expense',
          expenseType: 'اشتراك انترنت',
          description: 'اشتراك انترنت',
          amountPerDay: 2000,
          dateFrom: '1970-01-01',
          dateTo: '1970-01-01',
          explanation: 'e',
        }),
      },
      'admin',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { plan: { dateFrom?: string; dateTo?: string }; requires_confirmation: boolean };
    expect(body.plan.dateFrom).toBe(today);
    expect(body.plan.dateTo).toBe(today);
    expect(body.requires_confirmation).toBe(true);
    expect(await expenseCount()).toBe(0);
  });

  it('yearless user range (1970-MM-DD artifact) is coerced to the current year', async () => {
    const year = new Date().toISOString().slice(0, 4);
    const res = await handleAiRequest(
      aiRequest({ prompt: 'اضف مصروف صيانة مولد 40 ألف لكل يوم من 15 الى 18 سبتمبر' }),
      {
        DB: env.DB,
        AI: chatAi({
          kind: 'add_expense',
          expenseType: 'صيانة مولد',
          description: 'صيانة مولد',
          amountPerDay: 40000,
          dateFrom: '1970-09-15',
          dateTo: '1970-09-18',
          explanation: 'e',
        }),
      },
      'admin',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { plan: { dateFrom?: string; dateTo?: string } };
    expect(body.plan.dateFrom).toBe(`${year}-09-15`);
    expect(body.plan.dateTo).toBe(`${year}-09-18`);
  });

  it('junk epoch dates on a query are cleared so resolveWindow defaults apply', async () => {
    const res = await handleAiRequest(
      aiRequest({ prompt: 'ايش اتجاه الاشغال والايرادات؟' }),
      {
        DB: env.DB,
        AI: chatAi({
          kind: 'query',
          queryType: 'occupancy_trend',
          dateFrom: '1970-01-01',
          dateTo: '1970-01-31',
          explanation: 'e',
        }),
      },
      'admin',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { plan: { dateFrom?: string; dateTo?: string }; rows: unknown[] };
    expect(body.plan.dateFrom).toBeUndefined();
    expect(body.plan.dateTo).toBeUndefined();
    expect(Array.isArray(body.rows)).toBe(true);
  });

  it('client-confirmed plans keep their explicit dates untouched (no sanitization on the confirm path)', async () => {
    const res = await handleAiRequest(
      aiRequest({
        confirm: true,
        plan: {
          kind: 'add_expense',
          expenseType: 'نظافة',
          description: 'مصروف نظافة',
          amountPerDay: 100,
          dateFrom: '2026-05-08',
          dateTo: '2026-05-08',
          explanation: 'e',
        },
      }),
      { DB: env.DB, AI: chatAi({ kind: 'unsupported', explanation: 'x' }) },
      'admin',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { plan: { dateFrom?: string }; answer: string };
    expect(body.plan.dateFrom).toBe('2026-05-08');
    expect(body.answer).toContain('تمت إضافة');
    await env.DB.prepare("DELETE FROM expenses WHERE origin = 'ai'").run();
  });
});

// ═══════════════════════════════════════════════════════════════
//  REST fallback (AI_TOKEN secret) — ✅ (2026-09-20)
//  طلب المالك: «Worker ai token … اضفة الى ai». الربط [AI] المُنشر
//  يفشل في الإنتاج (502 «تعذر تحليل الطلب») بينما REST بنفس الطراز
//  يعمل بالتوكن — العقود هنا تثبت: الاحتياط يعمل عند فشل الربط، لا
//  يُستدعى أبداً عند نجاحه، ويعيد سلوك 502 القائم بلا توكن.
// ═══════════════════════════════════════════════════════════════

describe('ai: REST fallback (AI_TOKEN secret)', () => {
  const restUrl = 'https://api.cloudflare.com/client/v4/accounts/acct-123/ai/run/@cf/meta/llama-3.3-70b-instruct-fp8-fast';

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('binding failure falls back to REST and the query executes end-to-end', async () => {
    await seedRoom(uniqueUuid(), '501', 'شاغرة');
    let calledUrl: string | undefined;
    let calledAuth: string | undefined;
    const fetchMock = vi.fn(
      async (input: unknown, init?: RequestInit) => {
        calledUrl = String(input);
        calledAuth = (init?.headers as Record<string, string> | undefined)?.Authorization;
        return new Response(
          JSON.stringify({
            result: {
              choices: [{
                message: {
                  content: JSON.stringify({ kind: 'query', queryType: 'rooms_available', explanation: 'الغرف الشاغرة' }),
                },
              }],
            },
          }),
          { status: 200, headers: { 'Content-Type': 'application/json' } },
        );
      },
    );
    vi.stubGlobal('fetch', fetchMock);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'ما هي الغرف الشاغرة؟' }),
      { DB: env.DB, AI: throwingAi(), AI_TOKEN: 'cfut_test_token', CLOUDFLARE_ACCOUNT_ID: 'acct-123' },
      'admin',
    );

    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ room_number: string }>; answer: string };
    expect(body.rows.map((r) => r.room_number)).toContain('501');
    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(calledUrl).toBe(restUrl);
    expect(calledAuth).toBe('Bearer cfut_test_token');
  });

  it('unparseable binding output is rescued by REST when the token exists', async () => {
    const fetchMock = vi.fn(async () =>
      new Response(
        JSON.stringify({
          result: {
            choices: [{
              message: {
                content: JSON.stringify({ kind: 'unsupported', explanation: 'الطلب غير واضح' }),
              },
            }],
          },
        }),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      ),
    );
    vi.stubGlobal('fetch', fetchMock);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'أي شيء' }),
      { DB: env.DB, AI: garbageAi(), AI_TOKEN: 'cfut_test_token', CLOUDFLARE_ACCOUNT_ID: 'acct-123' },
      'admin',
    );

    expect(res.status).toBe(200);
    const body = (await res.json()) as { answer: string };
    expect(body.answer).toContain('الطلب غير واضح');
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });

  it('binding failure WITHOUT the token keeps the legacy 502 and never calls REST', async () => {
    const fetchMock = vi.fn(async () => {
      throw new Error('REST must not be called without AI_TOKEN');
    });
    vi.stubGlobal('fetch', fetchMock);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'أي شيء' }),
      { DB: env.DB, AI: throwingAi() },
      'admin',
    );

    expect(res.status).toBe(502);
    const body = (await res.json()) as { error: string };
    expect(body.error).toContain('تحليل');
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it('whitespace-only token counts as absent (502, no REST call)', async () => {
    const fetchMock = vi.fn(async () => {
      throw new Error('REST must not be called');
    });
    vi.stubGlobal('fetch', fetchMock);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'أي شيء' }),
      { DB: env.DB, AI: throwingAi(), AI_TOKEN: '   ', CLOUDFLARE_ACCOUNT_ID: 'acct-123' },
      'admin',
    );

    expect(res.status).toBe(502);
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it('REST failure surfaces 502 (both paths down)', async () => {
    const fetchMock = vi.fn(async () => new Response('boom', { status: 500 }));
    vi.stubGlobal('fetch', fetchMock);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'أي شيء' }),
      { DB: env.DB, AI: throwingAi(), AI_TOKEN: 'cfut_test_token', CLOUDFLARE_ACCOUNT_ID: 'acct-123' },
      'admin',
    );

    expect(res.status).toBe(502);
  });

  it('healthy binding never touches REST even when the token exists', async () => {
    const fetchMock = vi.fn(async () => {
      throw new Error('REST must not be called when the binding works');
    });
    vi.stubGlobal('fetch', fetchMock);

    const res = await handleAiRequest(
      aiRequest({ prompt: 'الغرف' }),
      {
        DB: env.DB,
        AI: mockAi({ kind: 'query', queryType: 'rooms_all', explanation: 'كل الغرف' }),
        AI_TOKEN: 'cfut_test_token',
        CLOUDFLARE_ACCOUNT_ID: 'acct-123',
      },
      'admin',
    );

    expect(res.status).toBe(200);
    expect(fetchMock).not.toHaveBeenCalled();
  });
});

// ═══════════════════════════════════════════════════════════════
//  Analytics (occupancy / bookings) + bilingual status regression
//  Production D1 holds the Arabic status forms ('شاغرة'/'محجوزة') —
//  every filter must accept both languages.
// ═══════════════════════════════════════════════════════════════

const today = new Date().toISOString().slice(0, 10);
const dayAt = (offset: number) => {
  const d = new Date(`${today}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + offset);
  return d.toISOString().slice(0, 10);
};

const seedStay = (uuid: string, room: string, guest: string, status: string, opts: { checkin: string; checkout?: string | null; nights: number; due: number; paid: number }) =>
  env.DB.prepare(
    `INSERT INTO bookings (local_uuid, room_number, guest_name, guest_phone, guest_nationality, checkin_date, checkout_date, status, calculated_nights, total_due_cached, total_paid_cached, remaining_balance_cached, created_at, updated_at, last_modified)
     VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)`,
  ).bind(uuid, room, guest, '777000', 'يمني', opts.checkin, opts.checkout ?? null, status, opts.nights, opts.due, opts.paid, Math.max(opts.due - opts.paid, 0), 1700000000, 1700000000).run();

const seedPayment = (uuid: string, amount: number, paymentDate: string) =>
  env.DB.prepare(
    `INSERT INTO payments (local_uuid, amount, payment_date, payment_method, revenue_type, created_at, updated_at, last_modified)
     VALUES (?,?,?,?,?,?,?,0)`,
  ).bind(uuid, amount, paymentDate, 'نقدي', 'إيراد', 1700000000, 1700000000).run();

describe('ai: bilingual statuses (production regression)', () => {
  it('rooms_available matches both Arabic and English vacant statuses', async () => {
    await seedRoom(uniqueUuid('r1'), '101', 'شاغرة');
    await seedRoom(uniqueUuid('r2'), '102', 'available');
    await seedRoom(uniqueUuid('r3'), '103', 'محجوزة');
    await seedRoom(uniqueUuid('r4'), '104', 'occupied');

    const res = await handleAiRequest(
      aiRequest({ prompt: 'الغرف الشاغرة' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'rooms_available', explanation: 'x' }) },
      'employee',
    );
    const body = (await res.json()) as { rows: Array<{ room_number: string }> };
    expect(body.rows.map((r) => r.room_number)).toEqual(['101', '102']);
  });

  it('current_guests matches the Arabic active booking status', async () => {
    await seedStay(uniqueUuid('b1'), '201', 'سالم', 'محجوزة', { checkin: dayAt(-2), checkout: dayAt(3), nights: 5, due: 50000, paid: 20000 });
    await seedStay(uniqueUuid('b2'), '202', 'مكتمل ضيف', 'مكتمل', { checkin: dayAt(-10), checkout: dayAt(-5), nights: 5, due: 50000, paid: 50000 });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'من النزلاء الموجودين؟' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'current_guests', explanation: 'x' }) },
      'employee',
    );
    const body = (await res.json()) as { rows: Array<{ guest_name: string }> };
    expect(body.rows).toHaveLength(1);
    expect(body.rows[0]?.guest_name).toBe('سالم');
  });
});

describe('ai: occupancy and booking analytics', () => {
  it('occupancy_summary reports totals, percentage and arrivals today', async () => {
    await seedRoom(uniqueUuid('r1'), '101', 'شاغرة');
    await seedRoom(uniqueUuid('r2'), '102', 'شاغرة');
    await seedRoom(uniqueUuid('r3'), '103', 'محجوزة');
    await seedRoom(uniqueUuid('r4'), '104', 'محجوزة');
    await seedRoom(uniqueUuid('r5'), '105', 'محجوزة', true); // deleted — excluded
    await seedStay(uniqueUuid('b1'), '103', 'نزيل قديم', 'محجوزة', { checkin: dayAt(-3), checkout: dayAt(2), nights: 5, due: 100, paid: 0 });
    await seedStay(uniqueUuid('b2'), '104', 'واصل اليوم', 'محجوزة', { checkin: today, checkout: dayAt(2), nights: 2, due: 100, paid: 0 });
    await seedStay(uniqueUuid('b3'), '105', 'ملغي', 'ملغي', { checkin: today, checkout: dayAt(2), nights: 2, due: 100, paid: 0 });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'ما نسبة الإشغال الحالية؟' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'occupancy_summary', explanation: 'x' }) },
      'employee',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ total_rooms: number; occupied_rooms: number; available_rooms: number; occupancy_pct: number; active_bookings: number; arrivals_today: number }>; answer: string };
    expect(body.rows).toHaveLength(1);
    const summary = body.rows[0]!;
    expect(summary.total_rooms).toBe(4);
    expect(summary.occupied_rooms).toBe(2);
    expect(summary.available_rooms).toBe(2);
    expect(summary.occupancy_pct).toBe(50);
    expect(summary.active_bookings).toBe(2);
    expect(summary.arrivals_today).toBe(1);
    expect(body.answer).toContain('50%');
  });

  it('occupancy_trend counts overdue stays as occupied and future days by schedule', async () => {
    await seedRoom(uniqueUuid('r1'), '101', 'شاغرة');
    await seedRoom(uniqueUuid('r2'), '102', 'شاغرة');
    // Overdue by one day: checkout was yesterday, status still active —
    // the guest is physically still in the room (mirrors rooms.status).
    await seedStay(uniqueUuid('b1'), '101', 'نزيل', 'محجوزة', { checkin: dayAt(-2), checkout: dayAt(-1), nights: 1, due: 30000, paid: 0 });
    await seedPayment(uniqueUuid('p1'), 15000, `${dayAt(-1)}T10:00:00`);
    await seedExpense(uniqueUuid('e1'), 'ديزل', 5000, dayAt(-1));

    const res = await handleAiRequest(
      aiRequest({ prompt: 'اتجاه الإشغال' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'occupancy_trend', dateFrom: dayAt(-2), dateTo: dayAt(1), explanation: 'x' }) },
      'employee',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ date: string; occupied_rooms: number; occupancy_pct: number; bookings: number; revenue: number; expenses: number }>; answer: string };
    expect(body.rows).toHaveLength(4);
    const byDate = new Map(body.rows.map((r) => [r.date, r]));
    // Past + today: the overdue guest still occupies the room
    expect(byDate.get(dayAt(-2))?.occupied_rooms).toBe(1);
    expect(byDate.get(dayAt(-1))?.occupied_rooms).toBe(1);
    expect(byDate.get(today)?.occupied_rooms).toBe(1);
    // Tomorrow: schedule says checkout passed → not occupied
    expect(byDate.get(dayAt(1))?.occupied_rooms).toBe(0);
    expect(byDate.get(dayAt(-2))?.occupancy_pct).toBe(50);
    expect(byDate.get(dayAt(-1))?.revenue).toBe(15000);
    expect(byDate.get(dayAt(-1))?.expenses).toBe(5000);
    expect(body.answer).toContain('اتجاه الإشغال');
  });

  it('booking_analysis reports per-day arrivals, expected revenue and departures', async () => {
    await seedStay(uniqueUuid('b1'), '101', 'نزيل 1', 'محجوزة', { checkin: dayAt(-2), checkout: dayAt(-1), nights: 1, due: 10000, paid: 10000 });
    await seedStay(uniqueUuid('b2'), '102', 'نزيل 2', 'محجوزة', { checkin: dayAt(-1), checkout: dayAt(1), nights: 2, due: 20000, paid: 0 });
    await seedStay(uniqueUuid('b3'), '103', 'قديم', 'مكتمل', { checkin: dayAt(-20), checkout: dayAt(-2), nights: 18, due: 5000, paid: 5000 });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'حلل الحجوزات' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'booking_analysis', dateFrom: dayAt(-3), dateTo: today, explanation: 'x' }) },
      'manager',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ date: string; bookings: number; rooms_booked: number }>; answer: string };
    expect(body.rows).toHaveLength(2);
    const byDate = new Map(body.rows.map((r) => [r.date, r]));
    expect(byDate.get(dayAt(-2))?.bookings).toBe(1);
    expect(byDate.get(dayAt(-1))?.bookings).toBe(1);
    // b3 checked in outside the window → excluded from arrivals
    // departures inside window: b1 (checkout dayAt(-1)); b3 checked out dayAt(-2) → also inside
    expect(body.answer).toContain('2 حجزاً');
    expect(body.answer).toContain('مغادرات 2');
  });

  it('overdue_bookings flags active stays past checkout and ignores completed ones', async () => {
    await seedStay(uniqueUuid('b1'), '301', 'متأخر صالح', 'محجوزة', { checkin: dayAt(-10), checkout: dayAt(-3), nights: 7, due: 70000, paid: 20000 });
    await seedStay(uniqueUuid('b2'), '302', 'غادر فعلاً', 'مكتمل', { checkin: dayAt(-15), checkout: dayAt(-8), nights: 7, due: 70000, paid: 70000 });
    await seedStay(uniqueUuid('b3'), '303', 'ما زال مقيم', 'محجوزة', { checkin: dayAt(-1), checkout: dayAt(2), nights: 3, due: 30000, paid: 0 });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'هل توجد حجوزات متأخرة؟' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'overdue_bookings', explanation: 'x' }) },
      'employee',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ guest_name: string; overdue_days: number; overdue_status: string; remaining_balance: number }>; answer: string };
    expect(body.rows).toHaveLength(1);
    expect(body.rows[0]?.guest_name).toBe('متأخر صالح');
    expect(body.rows[0]?.overdue_days).toBe(3);
    expect(body.rows[0]?.remaining_balance).toBe(50000);
    expect(body.rows[0]?.overdue_status).toContain('متأخر');
    expect(body.answer).toContain('1');
  });

  it('stay_statistics averages nights and totals the money columns', async () => {
    await seedStay(uniqueUuid('b1'), '401', 'أ', 'محجوزة', { checkin: dayAt(-10), nights: 10, due: 100000, paid: 60000 });
    await seedStay(uniqueUuid('b2'), '402', 'ب', 'محجوزة', { checkin: dayAt(-20), nights: 20, due: 200000, paid: 200000 });
    await seedStay(uniqueUuid('b3'), '403', 'منته', 'مكتمل', { checkin: dayAt(-40), checkout: dayAt(-30), nights: 30, due: 999999, paid: 999999 });

    const res = await handleAiRequest(
      aiRequest({ prompt: 'ما متوسط مدة الإقامة؟' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'stay_statistics', explanation: 'x' }) },
      'employee',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ bookings: number; avg_nights: number; longest_stay_nights: number; expected_revenue: number; collected_revenue: number; remaining_balance: number }> };
    const stats = body.rows[0]!;
    expect(stats.bookings).toBe(2);
    expect(stats.avg_nights).toBe(15);
    expect(stats.longest_stay_nights).toBe(20);
    expect(stats.expected_revenue).toBe(300000);
    expect(stats.collected_revenue).toBe(260000);
    expect(stats.remaining_balance).toBe(40000);
  });

  it('occupancy_trend defaults to the last 30 days when no window given', async () => {
    const res = await handleAiRequest(
      aiRequest({ prompt: 'اتجاه الإشغال' }),
      { DB: env.DB, AI: mockAi({ kind: 'query', queryType: 'occupancy_trend', explanation: 'x' }) },
      'employee',
    );
    expect(res.status).toBe(200);
    const body = (await res.json()) as { rows: Array<{ date: string }> };
    expect(body.rows).toHaveLength(30);
    expect(body.rows[0]?.date).toBe(dayAt(-29));
    expect(body.rows[29]?.date).toBe(today);
  });
});
