/// ============================================================
/// Marina Hotel - Appwrite Collections Summary
/// ============================================================
/// Script to list all collections and their fields
/// Run: dart run lib/scripts/appwrite_collections_summary.dart
/// ============================================================

class AppwriteCollections {
  static const String databaseId = 'hotel_db';
  
  /// Core Collections (6)
  static const Map<String, List<String>> coreCollections = {
    'rooms': [
      'id', 'roomNumber', 'type', 'price', 'status', 'imageUrl',
      'cleaningStatus', 'lastCleanedHotelDay', 'lastOccupiedHotelDay',
      'requiresMaintenance',
      // Sync fields
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModified', 'createdAtIso', 'updatedAtIso', 'deletedAtIso',
      'createdAtEpoch', 'lastModifiedEpoch', 'version', 'origin', 'vectorClock',
    ],
    'bookings': [
      'id', 'serverBookingId', 'roomNumber', 'guestName', 'guestPhone',
      'guestIdType', 'guestIdNumber', 'guestNationality', 'guestEmail',
      'checkinDate', 'checkoutDate', 'actualCheckout', 'status', 'notes',
      'discount', 'discountType', 'expectedNights', 'calculatedNights',
      'totalDueCached', 'totalPaidCached', 'remainingBalanceCached',
      'isFullyPaid', 'hotelDayCheckin', 'hotelDayCheckout',
      // Sync fields
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'payments': [
      'id', 'serverPaymentId', 'bookingLocalId', 'serverBookingId',
      'roomNumber', 'amount', 'paymentDate', 'notes', 'paymentMethod',
      'revenueType', 'cashTransactionLocalId', 'referenceNumber',
      'hotelDayKey', 'discountAmount', 'discountStartDate', 'isVoided',
      // Sync fields
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'expenses': [
      'id', 'expenseType', 'relatedId', 'description', 'amount',
      'date', 'cashTransactionId', 'hotelDayKey', 'categoryUuid',
      'isAutoGenerated',
      // Sync fields
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'employees': [
      'id', 'name', 'basicSalary', 'position', 'phone',
      'hireDate', 'status',
      // Sync fields
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'debts': [
      'id', 'bookingLocalId', 'guestName', 'checkinDate', 'checkoutDate',
      'dateRecorded', 'debtReason', 'totalAmount', 'paidAmount',
      'remainingAmount', 'paymentDate', 'isSettled', 'pledge',
      'pledgeType', 'note', 'debtUuid', 'hotelDayOpened',
      'hotelDayClosed', 'isFromAutoFix', 'settlementConfirmed',
      // Sync fields
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
  };
  
  /// Extended Collections (13)
  static const Map<String, List<String>> extendedCollections = {
    'booking_notes': [
      'id', 'bookingId', 'noteText', 'alertType', 'alertUntil', 'isActive',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'cash_transactions': [
      'id', 'registerId', 'transactionType', 'amount',
      'referenceType', 'referenceId', 'description', 'transactionTime', 'createdBy',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'booking_nights': [
      'id', 'bookingLocalId', 'hotelDayKey', 'nightStart', 'nightEnd',
      'nightlyRate', 'sequence', 'isProcessedByAutoFix', 'baseRate',
      'adjustment', 'finalRate',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'hotel_day_ledger': [
      'id', 'hotelDayKey', 'totalIncome', 'totalExpenses',
      'pendingBalances', 'occupancyRate', 'bookingsProcessed',
      'paymentsProcessed', 'debtsProcessed', 'expensesProcessed', 'status',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'salary_cycles': [
      'id', 'employeeId', 'cycleKey', 'hotelDayStart', 'hotelDayEnd',
      'expectedAmount', 'actualPaid', 'remainingAmount', 'status',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'salary_payments': [
      'id', 'cycleId', 'amount', 'hotelDayKey', 'paymentDateIso',
      'method', 'isAutoGenerated',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'salary_withdrawals': [
      'id', 'employeeId', 'amount', 'withdrawDate', 'reason',
      'hotelDayKey', 'withdrawalType', 'description',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'shift_notes': [
      'id', 'title', 'content', 'priority', 'shiftType', 'isRead',
      'expiresAt', 'createdBy',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'price_adjustments': [
      'id', 'targetType', 'targetUuid', 'adjustmentType',
      'previousValue', 'newValue', 'reason', 'effectiveDate',
      'appliedBy', 'hotelDayKey', 'isReversed', 'reversedAt', 'reversedBy',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'booking_price_adjustments': [
      'id', 'bookingLocalUuid', 'bookingLocalId', 'roomNumber',
      'adjustmentType', 'adjustmentMode', 'amount', 'effectiveHotelDay',
      'endHotelDay', 'isActive', 'reason', 'appliedBy',
      'cancelledAt', 'cancelledBy',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'audit_logs': [
      'id', 'localUuid', 'operationType', 'entityType', 'entityUuid',
      'entityId', 'previousState', 'newState', 'changedFields',
      'performedBy', 'deviceId', 'ipAddress', 'hotelDayKey',
      'timestamp', 'timestampIso', 'isFinancial', 'amountImpact',
      'createdAt',
    ],
    'payment_voids': [
      'id', 'originalPaymentUuid', 'originalPaymentId', 'bookingUuid',
      'voidedAmount', 'voidReason', 'voidedBy', 'voidedAt',
      'voidedAtIso', 'hotelDayKey', 'reversalPaymentUuid', 'approvedBy',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
    'guest_infos': [
      'id', 'roomNumber', 'guestName', 'nationality', 'idNumber',
      'idType', 'issueDate', 'issuePlace', 'governorate', 'notes',
      'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
      'lastModification', 'version', 'origin', 'vectorClock',
    ],
  };
  
  /// All Collections merged
  static Map<String, List<String>> get allCollections => {
    ...coreCollections,
    ...extendedCollections,
  };
  
  /// Print summary
  static void printSummary() {
    print('═' * 60);
    print('📦 Marina Hotel - Appwrite Collections Summary');
    print('═' * 60);
    print('Database ID: $databaseId');
    print('');
    
    print('━━ Core Collections (${coreCollections.length}) ━━');
    for (final entry in coreCollections.entries) {
      print('  • ${entry.key}: ${entry.value.length} fields');
    }
    print('');
    
    print('━━ Extended Collections (${extendedCollections.length}) ━━');
    for (final entry in extendedCollections.entries) {
      print('  • ${entry.key}: ${entry.value.length} fields');
    }
    print('');
    
    print('━ Total: ${allCollections.length} Collections ━');
    print('═' * 60);
  }
  
  /// Print detailed fields for a collection
  static void printCollectionDetails(String collectionName) {
    final fields = allCollections[collectionName];
    if (fields == null) {
      print('Collection "$collectionName" not found!');
      return;
    }
    
    print('━━ $collectionName (${fields.length} fields) ━━');
    for (final field in fields) {
      print('  - $field');
    }
  }
}

void main(List<String> args) {
  AppwriteCollections.printSummary();
  
  if (args.isNotEmpty) {
    print('');
    AppwriteCollections.printCollectionDetails(args.first);
  }
}
