package com.marina.marina.domain.util

import com.marina.marina.domain.model.Employee
import com.marina.marina.domain.model.Expense
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class SalaryEntitlementCalculatorTest {
    @Test
    fun stableKindsOverrideDescriptionsWithoutMergingIndependentEvents() {
        val employee = Employee(id = 7, localUuid = "e", name = "E", basicSalary = 1000.0)
        val expenses = listOf(
            Expense(localUuid = "one", employeeUuid = "e", amount = 100.0, expenseKind = "salary_withdrawal", description = "new text"),
            Expense(localUuid = "two", employeeUuid = "e", amount = 100.0, expenseKind = "salary_withdrawal", description = "new text"),
            Expense(localUuid = "three", employeeUuid = "e", amount = 100.0, expenseKind = "salary_installment", description = "new text"),
            Expense(localUuid = "four", employeeUuid = "e", amount = 25.0, expenseKind = "salary_deduction", description = "قسط سلفة")
        )
        val result = SalaryEntitlementCalculator.calculateEmployeeEntitlement(employee, expenses)
        assertEquals(200.0, result.totalWithdrawals, 0.0)
        assertEquals(100.0, result.installmentsPaid, 0.0)
        assertEquals(25.0, result.totalDeductions, 0.0)
    }

    @Test
    fun ambiguousHistoryIsFlaggedWithoutGuessingOrChangingPriorDeduction() {
        val employee = Employee(id = 7, localUuid = "e", name = "E", basicSalary = 1000.0)
        val expense = Expense(employeeUuid = "e", amount = 100.0, expenseType = "خصم من الراتب",
            isAutoGenerated = true, description = "unknown old note", expenseKind = "unclassified")
        val before = SalaryEntitlementCalculator.calculateEmployeeEntitlement(employee, listOf(expense))
        val after = SalaryEntitlementCalculator.calculateEmployeeEntitlement(employee,
            listOf(expense.copy(description = "قسط سلفة edited later")))
        assertEquals(1, after.unclassifiedExpenseCount)
        assertEquals(100.0, after.totalDeductions, 0.0)
        assertEquals(before.netEntitlement, after.netEntitlement, 0.0)
    }

    @Test
    fun employeeUuidIsAuthoritativeAndNumericIdIsLegacyOnly() {
        val employee = Employee(
            id = 7,
            name = "Employee",
            basicSalary = 100_000.0,
            hireDate = "2020-01-01",
            localUuid = "ABCDEF01-2345-6789-ABCD-0123456789AB"
        )
        val expenses = listOf(
            Expense(expenseType = "سلفة", relatedId = 99, employeeUuid = "abcdef0123456789abcd0123456789ab", amount = 10.0),
            Expense(expenseType = "سلفة", relatedId = 7, employeeUuid = "another-employee-uuid", amount = 100.0),
            Expense(expenseType = "سلفة", relatedId = 7, employeeUuid = null, amount = 20.0)
        )

        val result = SalaryEntitlementCalculator.calculateEmployeeEntitlement(
            employee = employee,
            expenses = expenses,
            nowMillis = 1_790_000_000_000L
        )

        assertEquals(30.0, result.totalAdvances, 0.0)
    }
}
