// test/unit/expense_kind_edit_preservation_test.dart
//
// ✅ (2026-10-07) حارس عقد m69: تصنيف المصروف المحمول (expense_kind)
// لا يُخفَّض عند تعديل المصروف من شاشة المصروفات.
//
// العيب الذي يمنعه هذا الاختبار (مُثبت بالكود قبل الإصلاح):
//   • createAutoGenerated يكتب «خصم من الراتب» مع salary_installment
//     لأنه الوحيد القادر على تمييز قسط السلفة عن الخصم اليدوي.
//   • شاشة المصروفات تعدّل عبر update(expenseType: …) بلا تمرير
//     expenseKind (تحقق: لا ذكر لـ expenseKind في lib/screens إطلاقاً).
//   • كان update يشتق التصنيف من النوع وحده ⇒ salary_deduction —
//     فيفقد «قسط السلفة» بمجرد تعديل المبلغ أو الوصف.
//
// الإصلاح: الاشتقاق يقرأ is_auto_generated المخزّن في الصف نفسه
// (حالة معلنة، ليست تخميناً) ويُبقي salary_installment.
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:marina_hotel_mobile/services/local_db.dart';
import 'package:marina_hotel_mobile/services/repositories/expenses_repository.dart';
import 'package:marina_hotel_mobile/services/salary_expense_classifier.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const day = '2026-10-07';

  late AppDatabase db;
  late ExpensesRepository repo;

  setUp(() {
    db = AppDatabase.forTesting(NativeDatabase.memory());
    repo = ExpensesRepository(db);
  });

  tearDown(() async {
    await db.close();
  });

  Future<Expense> row(int id) =>
      (db.select(db.expenses)..where((e) => e.id.equals(id))).getSingle();

  group('اشتقاق التصنيف (وحدة)', () {
    test('خصم يدوي ≠ قسط سلفة مولّد — isAutoGenerated هو الفاصل', () {
      expect(
        SalaryExpenseClassifier.classifyExpenseKind('خصم من الراتب'),
        SalaryExpenseClassifier.kindSalaryDeduction,
      );
      expect(
        SalaryExpenseClassifier.classifyExpenseKind(
          'خصم من الراتب',
          isAutoGenerated: true,
        ),
        SalaryExpenseClassifier.kindSalaryInstallment,
      );
    });

    test('السلفة تبقى salary_advance في الحالتين (النوع نفسه)', () {
      expect(
        SalaryExpenseClassifier.classifyExpenseKind('سلفة'),
        SalaryExpenseClassifier.kindSalaryAdvance,
      );
      expect(
        SalaryExpenseClassifier.classifyExpenseKind(
          'سلفة',
          isAutoGenerated: true,
        ),
        SalaryExpenseClassifier.kindSalaryAdvance,
      );
    });
  });

  group('التصنيف عبر مسار التعديل — لا فقدان قسط السلفة', () {
    test('قسط سلفة مولّد: تعديل المبلغ والنوع معاً يُبقي salary_installment', () async {
      final id = await repo.createAutoGenerated(
        expenseType: 'خصم من الراتب',
        description: 'قسط سلفة 1/3',
        amount: 500,
        date: day,
      );
      expect(
        (await row(id)).expenseKind,
        SalaryExpenseClassifier.kindSalaryInstallment,
      );

      // نفس استدعاء شاشة المصروفات: نوع صريح بلا تصنيف صريح.
      await repo.update(
        id,
        expenseType: 'خصم من الراتب',
        description: 'قسط سلفة 1/3 (معدّل)',
        amount: 450,
        date: day,
      );

      final updated = await row(id);
      expect(updated.amount, 450);
      expect(
        updated.expenseKind,
        SalaryExpenseClassifier.kindSalaryInstallment,
        reason: 'تعديل قسط سلفة يجب ألا يُخفّض تصنيفه إلى salary_deduction',
      );
    });

    test('خصم يدوي: التعديل يُبقي salary_deduction (لا ترقية خاطئة)', () async {
      final id = await repo.create(
        expenseType: 'خصم من الراتب',
        description: 'خصم يدوي',
        amount: 100,
        date: day,
      );
      expect(
        (await row(id)).expenseKind,
        SalaryExpenseClassifier.kindSalaryDeduction,
      );

      await repo.update(
        id,
        expenseType: 'خصم من الراتب',
        amount: 120,
        date: day,
      );

      expect(
        (await row(id)).expenseKind,
        SalaryExpenseClassifier.kindSalaryDeduction,
        reason: 'الخصم اليدوي ليس قسط سلفة — is_auto_generated=0',
      );
    });

    test('تعديل بلا نوع ولا تصنيف ⇒ لا يُمحى التصنيف المخزّن', () async {
      final id = await repo.createAutoGenerated(
        expenseType: 'خصم من الراتب',
        description: 'قسط سلفة 2/3',
        amount: 500,
        date: day,
      );

      await repo.update(id, amount: 400);

      expect(
        (await row(id)).expenseKind,
        SalaryExpenseClassifier.kindSalaryInstallment,
      );
    });

    test('تصنيف صريح صحيح يفوز على الاشتقاق', () async {
      final id = await repo.createAutoGenerated(
        expenseType: 'خصم من الراتب',
        description: 'قسط سلفة 3/3',
        amount: 500,
        date: day,
      );

      await repo.update(
        id,
        expenseType: 'خصم من الراتب',
        expenseKind: SalaryExpenseClassifier.kindSalaryDeduction,
      );

      expect(
        (await row(id)).expenseKind,
        SalaryExpenseClassifier.kindSalaryDeduction,
      );
    });

    test('تحويل قسط السلفة إلى نوع عادي ⇒ التصنيف يتبع النوع الجديد', () async {
      final id = await repo.createAutoGenerated(
        expenseType: 'خصم من الراتب',
        description: 'قسط سلفة — سيُحوَّل',
        amount: 500,
        date: day,
      );

      await repo.update(id, expenseType: 'كهرباء', date: day);

      expect((await row(id)).expenseKind, SalaryExpenseClassifier.kindNormal);
    });
  });
}
