// test/unit/m69_field_consumers_test.dart
//
// ✅ (2026-10-07 — م-3) مستهلكو حقول عقد m69 محلياً — الحقل نقل حيّ لا عبور.
//
// كانت الحقول تصل وتُخزَّن وتُرفع، بلا قارئ محلي واحد:
//   1) employeeLinkCleared: علم «المستخدم أزال رابط الموظف عمداً». بلا
//      مستهلكَين كان:
//        • سحب مستند قديم (ما قبل العقد، بلا مفتاح العلم) يعيد كتابة
//          employeeUuid/relatedId ⇒ إحياء رابط أزاله المستخدم
//          (انتهاك «الحذف الصريح لا يُنقض»)،
//        • وخدمة اتساق روابط الموظف تُعيد تعبئة uuid ويتيماً.
//   2) expenseKind: التصنيف المحمول. كان يُشتق محلياً من نص النوع عند أي
//      تعديل ⇒ طمس قيمة وصلت من جهاز آخر (مثل salary_installment قبل أن
//      يعرف هذا الجهاز سياق القسط).
//
// هذا الاختبار يقفل المستهلكين الثلاثة:
//   أ) ExpensesAdapter: قمع إحياء الرابط من حمولة ما قبل العقد + احترام
//      التصريح الصريح بإعادة الربط (employeeLinkCleared=false).
//   ب) EmployeeLinkConsistencyService: علم الإزالة مقدّس — لا إصلاح ولا
//      تعبئة فوقه.
//   ج) ExpensesRepository.update: التصنيف المخزّن (المحمول) يبقى ما دام
//      النوع لم يتغير؛ الاشتقاق فقط عند تغيير النوع فعلاً.
import 'package:drift/drift.dart' as d;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:marina_hotel_mobile/services/adapters/expenses_adapter.dart';
import 'package:marina_hotel_mobile/services/adapters/id_resolver.dart';
import 'package:marina_hotel_mobile/services/adapters/source.dart';
import 'package:marina_hotel_mobile/services/employee_link_consistency_service.dart';
import 'package:marina_hotel_mobile/services/local_db.dart';
import 'package:marina_hotel_mobile/services/repositories/expenses_repository.dart';
import 'package:marina_hotel_mobile/services/salary_expense_classifier.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late AppDatabase db;
  late ExpensesAdapter adapter;

  setUp(() {
    db = AppDatabase.forTesting(NativeDatabase.memory());
    adapter = ExpensesAdapter(IdResolver(db));
  });

  tearDown(() async {
    await db.close();
  });

  Future<int> insertEmployee(String uuid) => db
      .into(db.employees)
      .insert(
        EmployeesCompanion(
          name: const d.Value('موظف اختبار'),
          basicSalary: const d.Value(1000),
          status: const d.Value('active'),
          localUuid: d.Value(uuid),
          createdAt: const d.Value(1000),
          updatedAt: const d.Value(1000),
          lastModified: const d.Value(1000),
        ),
      );

  Future<int> insertExpense({
    required String uuid,
    required String type,
    String? employeeUuid,
    int? relatedId,
    bool linkCleared = false,
    String? expenseKind,
    bool isAutoGenerated = false,
    double amount = 1000,
  }) => db
      .into(db.expenses)
      .insert(
        ExpensesCompanion(
          expenseType: d.Value(type),
          description: const d.Value('وصف'),
          amount: d.Value(amount),
          date: const d.Value('2026-10-01'),
          hotelDayKey: const d.Value('2026-10-01'),
          employeeUuid: employeeUuid != null
              ? d.Value(employeeUuid)
              : const d.Value.absent(),
          relatedId: relatedId != null
              ? d.Value(relatedId)
              : const d.Value.absent(),
          employeeLinkCleared: d.Value(linkCleared),
          expenseKind: expenseKind != null
              ? d.Value(expenseKind)
              : const d.Value.absent(),
          isAutoGenerated: d.Value(isAutoGenerated),
          localUuid: d.Value(uuid),
          createdAt: const d.Value(1000),
          updatedAt: const d.Value(1000),
          lastModified: const d.Value(1000),
        ),
      );

  // ═══════════════════════════════════════════════════════════════════
  //  أ) ExpensesAdapter — قمع إحياء الرابط المُزال
  // ═══════════════════════════════════════════════════════════════════
  group('ExpensesAdapter — لا إحياء لرابط أزاله المستخدم', () {
    /// حمولة سجل ما قبل العقد: بلا مفتاح employeeLinkCleared إطلاقاً،
    /// وتحمل رابطاً قديماً (employeeUuid + relatedId) — هذا ما ترفعه نسخة
    /// التطبيق السابقة، وما يبقى في السحابة من تاريخ ما قبل m69.
    Map<String, dynamic> preContractPayload({
      required String localUuid,
      String type = 'رواتب',
      String? employeeUuid = 'emp-uuid-1',
      int? relatedId = 42,
    }) => <String, dynamic>{
      'localUuid': localUuid,
      'expenseType': type,
      'description': 'وصف',
      'amount': 1000,
      'date': '2026-10-01',
      'hotelDayKey': '2026-10-01',
      if (employeeUuid != null) 'employeeUuid': employeeUuid,
      if (relatedId != null) 'relatedId': relatedId,
    };

    test('صف محلي مُزال الرابط + حمولة ما قبل العقد ⇒ قمع كامل', () async {
      await insertEmployee('emp-uuid-1');
      await insertExpense(
        uuid: 'exp-1',
        type: 'خصم من الراتب',
        linkCleared: true,
        expenseKind: SalaryExpenseClassifier.kindSalaryDeduction,
      );

      final json = preContractPayload(localUuid: 'exp-1');
      final refs = await adapter.resolveRefs(db, json, src: Source.appwrite);
      expect(
        refs.suppressEmployeeLink,
        isTrue,
        reason: 'الحمولة القديمة لا يجوز أن تُحيي رابطاً أزاله المستخدم',
      );

      final comp = adapter.fromJson(json, src: Source.appwrite, refs: refs);
      expect(comp.employeeUuid.present, isTrue);
      expect(comp.employeeUuid.value, isNull, reason: 'الهوية تبقى ممسوحة');
      expect(comp.relatedId.present, isTrue);
      expect(comp.relatedId.value, isNull, reason: 'الرقم اليتيم يبقى ممسوحاً');
      expect(
        comp.employeeLinkCleared.value,
        isTrue,
        reason: 'العلم يبقى مرفوعاً',
      );
    });

    test(
      'تصريح صريح بإعادة الربط (employeeLinkCleared=false) يُحترم',
      () async {
        await insertEmployee('emp-uuid-1');
        await insertExpense(
          uuid: 'exp-1',
          type: 'خصم من الراتب',
          linkCleared: true,
        );

        final json = preContractPayload(localUuid: 'exp-1')
          ..['employeeLinkCleared'] = false
          ..['expenseKind'] = SalaryExpenseClassifier.kindSalaryWithdrawal;
        final refs = await adapter.resolveRefs(db, json, src: Source.appwrite);
        expect(
          refs.suppressEmployeeLink,
          isFalse,
          reason: 'نسخة ما بعد العقد تُصرّح بالإحياء ⇒ تُطبَّق كأي تعديل مشروع',
        );
      },
    );

    test('مصدر محلي (استعادة نسخة) ⇒ لا قمع أبداً', () async {
      await insertExpense(
        uuid: 'exp-1',
        type: 'خصم من الراتب',
        linkCleared: true,
      );
      final json = preContractPayload(localUuid: 'exp-1');
      final refs = await adapter.resolveRefs(db, json, src: Source.local);
      expect(refs.suppressEmployeeLink, isFalse);
    });

    test('صف غير مُزال الرابط ⇒ السلوك القديم بلا تغيير', () async {
      await insertEmployee('emp-uuid-1');
      await insertExpense(uuid: 'exp-1', type: 'رواتب');
      final json = preContractPayload(localUuid: 'exp-1');
      final refs = await adapter.resolveRefs(db, json, src: Source.appwrite);
      expect(refs.suppressEmployeeLink, isFalse);
    });
  });

  // ═══════════════════════════════════════════════════════════════════
  //  ب) EmployeeLinkConsistencyService — العلم مقدّس
  // ═══════════════════════════════════════════════════════════════════
  group('خدمة اتساق الروابط — لا إصلاح فوق إزالة صريحة', () {
    test('لا تُعبّأ هوية يتيماً على صف أزاله المستخدم', () async {
      final empId = await insertEmployee('emp-uuid-1');
      final expId = await insertExpense(
        uuid: 'exp-1',
        type: 'خصم من الراتب',
        relatedId: empId,
        employeeUuid:
            null, // أُزيلت الهوية، وبقي الرقم (قبل إصلاح clearRelatedId)
        linkCleared: true,
      );

      final service = EmployeeLinkConsistencyService(db);
      final report = await service.repairLinksForEmployee(empId);

      final row = await (db.select(
        db.expenses,
      )..where((e) => e.id.equals(expId))).getSingle();
      expect(row.employeeUuid, isNull, reason: 'لا تُعاد الهوية أبداً');
      expect(
        report.expensesUuidBackfilled,
        equals(0),
        reason: 'الإزالة الصريحة تُستثنى من الإصلاح لا تُعدّ يتيمة',
      );
      expect(
        report.notes.any((n) => n.contains('أزاله المستخدم')),
        isTrue,
        reason: 'يجب أن يظهر سبب الاستثناء في التقرير (لا صمت)',
      );
    });

    test('الصف العادي (بلا علم) ما زال يُعبّأ كالمعتاد', () async {
      final empId = await insertEmployee('emp-uuid-1');
      final expId = await insertExpense(
        uuid: 'exp-2',
        type: 'سحب راتب',
        relatedId: empId,
        employeeUuid: null,
      );

      final service = EmployeeLinkConsistencyService(db);
      final report = await service.repairLinksForEmployee(empId);

      final row = await (db.select(
        db.expenses,
      )..where((e) => e.id.equals(expId))).getSingle();
      expect(row.employeeUuid, equals('emp-uuid-1'));
      expect(report.expensesUuidBackfilled, equals(1));
    });

    test(
      'update بـ clearRelatedId يمسح الرقم والهوية معاً ويُبقي العلم',
      () async {
        final empId = await insertEmployee('emp-uuid-1');
        final expId = await insertExpense(
          uuid: 'exp-3',
          type: 'سحب راتب',
          relatedId: empId,
          employeeUuid: 'emp-uuid-1',
        );

        final repo = ExpensesRepository(db);
        await repo.update(
          expId,
          expenseType: 'صيانة',
          employeeUuid: '',
          clearRelatedId: true,
          employeeLinkCleared: true,
        );

        final row = await (db.select(
          db.expenses,
        )..where((e) => e.id.equals(expId))).getSingle();
        expect(row.relatedId, isNull, reason: 'الرقم اليتيم يزول مع الإزالة');
        expect(row.employeeUuid, isNull);
        expect(row.employeeLinkCleared, isTrue);

        // وبعد الإزالة: خدمة الاتساق لا تُحيي شيئاً
        final service = EmployeeLinkConsistencyService(db);
        await service.repairLinksForEmployee(empId);
        final after = await (db.select(
          db.expenses,
        )..where((e) => e.id.equals(expId))).getSingle();
        expect(after.relatedId, isNull);
        expect(after.employeeUuid, isNull);
      },
    );
  });

  // ═══════════════════════════════════════════════════════════════════
  //  ج) repository — التصنيف المحمول حيّ محلياً
  // ═══════════════════════════════════════════════════════════════════
  group('ExpensesRepository — التصنيف المخزّن لا يُمحى بتعديل محايد', () {
    test('نوع لم يتغير ⇒ يبقى التصنيف الواصل من المزامنة', () async {
      final expId = await insertExpense(
        uuid: 'exp-kind-1',
        type: 'خصم من الراتب',
        expenseKind: SalaryExpenseClassifier.kindSalaryInstallment,
        isAutoGenerated: false, // جهاز آخر يعرف سياق القسط؛ هذا الجهاز لا
      );

      final repo = ExpensesRepository(db);
      await repo.update(expId, expenseType: 'خصم من الراتب', amount: 250);

      final row = await (db.select(
        db.expenses,
      )..where((e) => e.id.equals(expId))).getSingle();
      expect(
        row.expenseKind,
        equals(SalaryExpenseClassifier.kindSalaryInstallment),
        reason: 'الاشتقاق المحلي (salary_deduction) لا يطمس قيمة المزامنة',
      );
      expect(row.amount, equals(250));
    });

    test('تعديل بلا نوع إطلاقاً ⇒ التصنيف لا يُمحى', () async {
      final expId = await insertExpense(
        uuid: 'exp-kind-2',
        type: 'سلفة',
        expenseKind: SalaryExpenseClassifier.kindSalaryAdvance,
      );
      final repo = ExpensesRepository(db);
      await repo.update(expId, amount: 99);
      final row = await (db.select(
        db.expenses,
      )..where((e) => e.id.equals(expId))).getSingle();
      expect(
        row.expenseKind,
        equals(SalaryExpenseClassifier.kindSalaryAdvance),
      );
    });

    test('تغيير النوع فعلاً ⇒ إعادة اشتقاق (الدلالة تغيّرت)', () async {
      final expId = await insertExpense(
        uuid: 'exp-kind-3',
        type: 'سلفة',
        expenseKind: SalaryExpenseClassifier.kindSalaryAdvance,
      );
      final repo = ExpensesRepository(db);
      await repo.update(expId, expenseType: 'خصم من الراتب');
      final row = await (db.select(
        db.expenses,
      )..where((e) => e.id.equals(expId))).getSingle();
      expect(
        row.expenseKind,
        equals(SalaryExpenseClassifier.kindSalaryDeduction),
        reason: 'النوع تغيّر ⇒ التصنيف يتبع الدلالة الجديدة',
      );
    });

    test('نوع غير راتبي ⇒ normal', () async {
      final expId = await insertExpense(
        uuid: 'exp-kind-4',
        type: 'سلفة',
        expenseKind: SalaryExpenseClassifier.kindSalaryAdvance,
      );
      final repo = ExpensesRepository(db);
      await repo.update(expId, expenseType: 'صيانة');
      final row = await (db.select(
        db.expenses,
      )..where((e) => e.id.equals(expId))).getSingle();
      expect(row.expenseKind, equals(SalaryExpenseClassifier.kindNormal));
    });
  });
}
