// test/unit/payload_mapper_fields_test.dart
//
// ✅ اختبارات لـ PayloadMapper: التأكد من إرسال الحقول الإلزامية للمزامنة
// (syncTimestamp للمقارنة مع المحلي + createdAtEpoch/lastModifiedEpoch المطلوبة
// من Appwrite + createdAtIso/updatedAtIso/deletedAtIso للتعارضات).
// (إصلاح 2026-08-08 لـ 5 mappers كانت تفتقر لهذه الحقول).

import 'package:flutter_test/flutter_test.dart';
import 'package:marina_hotel_mobile/services/local_db.dart';
import 'package:marina_hotel_mobile/services/sync/payload_mapper.dart';

BookingNote _note() => BookingNote(
  localUuid: 'u1',
  createdAt: 1,
  updatedAt: 1,
  lastModified: 1,
  createdAtEpoch: 1,
  lastModifiedEpoch: 1,
  version: 1,
  origin: 'local',
  vectorClock: '{}',
  deviceId: 'd1',
  id: 1,
  bookingId: 1,
  noteText: 'n',
  alertType: 'info',
  isActive: 1,
);

BookingNight _night() => BookingNight(
  localUuid: 'u2',
  createdAt: 1,
  updatedAt: 1,
  lastModified: 1,
  createdAtEpoch: 1,
  lastModifiedEpoch: 1,
  version: 1,
  origin: 'local',
  vectorClock: '{}',
  deviceId: 'd1',
  id: 1,
  bookingLocalId: 1,
  hotelDayKey: '2026-01-01',
  nightStart: '2026-01-01',
  nightEnd: '2026-01-02',
  nightlyRate: 0,
  sequence: 1,
  isProcessedByAutoFix: false,
  baseRate: 0,
  adjustment: 0,
  finalRate: 0,
);

CashTransaction _tx() => CashTransaction(
  localUuid: 'u3',
  createdAt: 1,
  updatedAt: 1,
  lastModified: 1,
  createdAtEpoch: 1,
  lastModifiedEpoch: 1,
  version: 1,
  origin: 'local',
  vectorClock: '{}',
  deviceId: 'd1',
  id: 1,
  transactionType: 'sale',
  amount: 10,
  transactionTime: '2026-01-01',
);

SalaryCycle _cycle() => SalaryCycle(
  localUuid: 'u4',
  createdAt: 1,
  updatedAt: 1,
  lastModified: 1,
  createdAtEpoch: 1,
  lastModifiedEpoch: 1,
  version: 1,
  origin: 'local',
  vectorClock: '{}',
  deviceId: 'd1',
  id: 1,
  employeeId: 1,
  cycleKey: 'c1',
  expectedAmount: 0,
  actualPaid: 0,
  remainingAmount: 0,
  status: 'draft',
);

SalaryPayment _payment() => SalaryPayment(
  localUuid: 'u5',
  createdAt: 1,
  updatedAt: 1,
  lastModified: 1,
  createdAtEpoch: 1,
  lastModifiedEpoch: 1,
  version: 1,
  origin: 'local',
  vectorClock: '{}',
  deviceId: 'd1',
  id: 1,
  cycleId: 1,
  amount: 0,
  paymentDateIso: '2026-01-01',
  isAutoGenerated: false,
);

void main() {
  const mapper = PayloadMapper();

  test('bookingNoteToRemote يرسل الحقول الإلزامية', () {
    final data = mapper.bookingNoteToRemote(_note());
    expect(data['syncTimestamp'], isA<int>());
    expect(data['createdAtEpoch'], isNotNull);
    expect(data['lastModifiedEpoch'], isNotNull);
    expect(data.containsKey('createdAtIso'), isTrue);
    expect(data.containsKey('updatedAtIso'), isTrue);
    expect(data.containsKey('deletedAtIso'), isTrue);
  });

  test('bookingNightToRemote يرسل الحقول الإلزامية', () {
    final data = mapper.bookingNightToRemote(_night());
    expect(data['syncTimestamp'], isA<int>());
    expect(data['createdAtEpoch'], isNotNull);
    expect(data['lastModifiedEpoch'], isNotNull);
    expect(data.containsKey('createdAtIso'), isTrue);
    expect(data.containsKey('updatedAtIso'), isTrue);
    expect(data.containsKey('deletedAtIso'), isTrue);
  });

  test('cashTransactionToRemote يرسل الحقول الإلزامية', () {
    final data = mapper.cashTransactionToRemote(_tx());
    expect(data['syncTimestamp'], isA<int>());
    expect(data['createdAtEpoch'], isNotNull);
    expect(data['lastModifiedEpoch'], isNotNull);
    expect(data.containsKey('createdAtIso'), isTrue);
    expect(data.containsKey('updatedAtIso'), isTrue);
    expect(data.containsKey('deletedAtIso'), isTrue);
  });

  test('salaryCycleToRemote يرسل الحقول الإلزامية', () {
    final data = mapper.salaryCycleToRemote(_cycle());
    expect(data['syncTimestamp'], isA<int>());
    expect(data['createdAtEpoch'], isNotNull);
    expect(data['lastModifiedEpoch'], isNotNull);
    expect(data.containsKey('createdAtIso'), isTrue);
    expect(data.containsKey('updatedAtIso'), isTrue);
    expect(data.containsKey('deletedAtIso'), isTrue);
  });

  test('salaryPaymentToRemote يرسل الحقول الإلزامية', () {
    final data = mapper.salaryPaymentToRemote(_payment());
    expect(data['syncTimestamp'], isA<int>());
    expect(data['createdAtEpoch'], isNotNull);
    expect(data['lastModifiedEpoch'], isNotNull);
    expect(data.containsKey('createdAtIso'), isTrue);
    expect(data.containsKey('updatedAtIso'), isTrue);
    expect(data.containsKey('deletedAtIso'), isTrue);
  });
}
