// ============================================================================
//  PayloadMapper — Contract Unit Tests (coverage expansion)
// ============================================================================
//  اختبارات عقود التحويل إلى حمولات السحابة (lib/services/sync/
//  payload_mapper.dart) للكيانات التي لم تكن مغطاة سابقاً:
//    roomToRemote / bookingToRemote / expenseToRemote / employeeToRemote /
//    guestInfoToRemote / paymentVoidToRemote
//
//  ما تحرسه هذه الاختبارات (بترتيب الأهمية):
//    1. الهوية: localUuid يُرسل دائماً (مفتاح الترابط عبر الأجهزة).
//    2. سلامة الربط: لا يُرسل أبداً معرف محلي autoIncrement للسيرفر.
//    3. الساعة المتجهة والجهاز: vectorClock/deviceId موجودان دائماً.
//    4. دلالات putIfNotNull / putIfStringNotEmpty (غياب الفارغ/النل).
//    5. تطبيع bookingUuidCache للصيغة القياسية بالشرطات.
//    6. syncTimestamp = lastModified (حتمية الـ LWW).
//    7. تصفية sanitizePayload: لا يخرج أي حقل خارج مخطط Appwrite.
// ============================================================================

library marina_hotel_mobile.test.unit.payload_mapper_coverage_test;

import 'package:flutter_test/flutter_test.dart';
import 'package:marina_hotel_mobile/services/local_db.dart';
import 'package:marina_hotel_mobile/services/sync/payload_mapper.dart';

const int _t0 = 1758700000000; // لحظة ثابتة لحتمية الاختبارات

Room _room({
  String? imageUrl,
  String? lastCleanedHotelDay,
  String? idempotencyKey,
  bool requiresMaintenance = false,
}) {
  return Room(
    id: 7,
    localUuid: 'room-uuid-0001',
    serverId: null,
    createdAt: _t0,
    updatedAt: _t0,
    deletedAt: null,
    lastModified: _t0,
    createdAtIso: null,
    updatedAtIso: null,
    deletedAtIso: null,
    createdAtEpoch: _t0,
    lastModifiedEpoch: _t0,
    version: 1,
    origin: 'local',
    vectorClock: '{"dev-a":3}',
    deviceId: 'dev-a',
    syncTimestamp: 0,
    roomNumber: '101',
    type: 'سويت',
    price: 25000,
    status: 'شاغرة',
    imageUrl: imageUrl,
    cleaningStatus: 'clean',
    lastCleanedHotelDay: lastCleanedHotelDay,
    lastOccupiedHotelDay: null,
    requiresMaintenance: requiresMaintenance,
    idempotencyKey: idempotencyKey,
  );
}

Booking _booking() {
  return Booking(
    id: 12,
    localUuid: 'booking-uuid-0001',
    serverId: null,
    serverBookingId: null,
    createdAt: _t0,
    updatedAt: _t0,
    deletedAt: null,
    lastModified: _t0,
    createdAtIso: null,
    updatedAtIso: null,
    deletedAtIso: null,
    createdAtEpoch: _t0,
    lastModifiedEpoch: _t0,
    version: 2,
    origin: 'cloud',
    vectorClock: '{"dev-a":9}',
    deviceId: 'dev-a',
    syncTimestamp: 0,
    roomNumber: '101',
    guestName: 'أحمد صالح',
    guestPhone: '+967777000000',
    guestIdType: 'بطاقة شخصية',
    guestIdNumber: '12345',
    guestIdIssueDate: null,
    guestIdIssuePlace: null,
    guestNationality: 'يمني',
    guestEmail: null,
    guestAddress: null,
    checkinDate: '2026-09-20',
    checkoutDate: null,
    actualCheckout: null,
    status: 'محجوزة',
    notes: null,
    discount: 0,
    discountType: 'per_night',
    discountStartDate: null,
    expectedNights: 3,
    calculatedNights: 2,
    totalNightsCached: 2,
    stayDurationIso: null,
    lastNightEpoch: null,
    isOverdue: false,
    needsCheckoutReview: false,
    totalDueCached: 75000,
    totalPaidCached: 30000,
    remainingBalanceCached: 45000,
    isFullyPaid: false,
    hotelDayCheckin: '2026-09-20',
    hotelDayCheckout: null,
    financialFrozenAt: null,
    financialHash: null,
    idempotencyKey: null,
  );
}

Expense _expense({bool isAutoGenerated = false, String? employeeUuid}) {
  return Expense(
    id: 3,
    localUuid: 'expense-uuid-0001',
    serverId: null,
    createdAt: _t0,
    updatedAt: _t0,
    deletedAt: null,
    lastModified: _t0,
    createdAtIso: null,
    updatedAtIso: null,
    deletedAtIso: null,
    createdAtEpoch: _t0,
    lastModifiedEpoch: _t0,
    version: 1,
    origin: 'local',
    vectorClock: '{}',
    deviceId: 'dev-a',
    syncTimestamp: 0,
    expenseType: 'صيانة',
    relatedId: null,
    description: 'إصلاح مكيف غرفة 101',
    amount: 5000,
    date: '2026-09-23',
    cashTransactionId: null,
    hotelDayKey: '2026-09-23',
    categoryUuid: null,
    cashFlowUuid: null,
    isAutoGenerated: isAutoGenerated,
    employeeUuid: employeeUuid,
    idempotencyKey: null,
  );
}

Employee _employee() {
  return Employee(
    id: 5,
    localUuid: 'employee-uuid-0001',
    serverId: null,
    createdAt: _t0,
    updatedAt: _t0,
    deletedAt: null,
    lastModified: _t0,
    createdAtIso: null,
    updatedAtIso: null,
    deletedAtIso: null,
    createdAtEpoch: _t0,
    lastModifiedEpoch: _t0,
    version: 1,
    origin: 'local',
    vectorClock: '{}',
    deviceId: 'dev-a',
    syncTimestamp: 0,
    name: 'سالم علي',
    basicSalary: 120000,
    position: 'موظف استقبال',
    phone: '777123456',
    hireDate: '2026-01-01',
    status: 'على رأس العمل',
    terminationDate: null,
    terminationReason: null,
    employeeID: 'EMP-77',
    idempotencyKey: null,
  );
}

GuestInfo _guestInfo({String? governorate, String? notes}) {
  return GuestInfo(
    id: 9,
    localUuid: 'guestinfo-uuid-0001',
    serverId: null,
    createdAt: _t0,
    updatedAt: _t0,
    deletedAt: null,
    lastModified: _t0,
    createdAtIso: null,
    updatedAtIso: null,
    deletedAtIso: null,
    createdAtEpoch: _t0,
    lastModifiedEpoch: _t0,
    version: 1,
    origin: 'local',
    vectorClock: '{}',
    deviceId: 'dev-a',
    syncTimestamp: 0,
    roomNumber: '101',
    guestName: 'أحمد صالح',
    nationality: 'يمني',
    idNumber: '12345',
    idType: 'بطاقة شخصية',
    issueDate: null,
    issuePlace: null,
    governorate: governorate,
    notes: notes,
    guestPhone: '+967777000000',
    idempotencyKey: null,
  );
}

PaymentVoid _paymentVoid({double? originalAmount, String? note}) {
  return PaymentVoid(
    id: 4,
    localUuid: 'void-uuid-0001',
    serverId: null,
    createdAt: _t0,
    updatedAt: _t0,
    deletedAt: null,
    lastModified: _t0,
    createdAtIso: null,
    updatedAtIso: null,
    deletedAtIso: null,
    createdAtEpoch: _t0,
    lastModifiedEpoch: _t0,
    version: 1,
    origin: 'local',
    vectorClock: '{}',
    deviceId: 'dev-a',
    syncTimestamp: 0,
    originalPaymentUuid: 'payment-uuid-0001',
    originalPaymentId: 44,
    bookingUuid: 'booking-uuid-0001',
    voidedAmount: 15000,
    voidReason: 'خطأ إدخال',
    voidedBy: 'manager-1',
    voidedAt: _t0,
    voidedAtIso: '2026-09-24T12:00:00.000',
    hotelDayKey: '2026-09-24',
    reversalPaymentUuid: null,
    approvedBy: null,
    note: note,
    originalAmount: originalAmount,
    paymentUuid: null,
    idempotencyKey: null,
  );
}

void main() {
  const mapper = PayloadMapper();

  group('roomToRemote', () {
    test('يُرسل الهوية وحقول المزامنة الأساسية', () {
      final payload = mapper.roomToRemote(_room());

      expect(payload['localUuid'], 'room-uuid-0001');
      expect(payload['roomNumber'], '101');
      expect(payload['type'], 'سويت');
      expect(payload['price'], 25000);
      expect(payload['status'], 'شاغرة');
      expect(payload['version'], 1);
      expect(payload['origin'], 'local');
      expect(payload['vectorClock'], '{"dev-a":3}');
      expect(payload['deviceId'], 'dev-a');
      // sync_origin محفوظة بالشرطة السفلية (داخل _preserveSnakeCase)
      expect(payload['sync_origin'], 'local');
    });

    test('لا يُرسل المعرّف المحلي autoIncrement أبداً', () {
      final payload = mapper.roomToRemote(_room());

      expect(payload.containsKey('id'), isFalse);
    });

    test('putIfStringNotEmpty: الحقول الفارغة/النل تُحذف وليس تُرسل فارغة', () {
      final payload = mapper.roomToRemote(_room());

      expect(payload.containsKey('imageUrl'), isFalse);
      expect(payload.containsKey('lastCleanedHotelDay'), isFalse);
      expect(payload.containsKey('idempotencyKey'), isFalse);
      expect(payload.containsKey('serverId'), isFalse);
      expect(payload.containsKey('deletedAt'), isFalse);
    });

    test('الحقول الاختيارية المعبأة تُرسل بقيمها', () {
      final payload = mapper.roomToRemote(
        _room(
          imageUrl: 'https://cdn.example/101.jpg',
          lastCleanedHotelDay: '2026-09-23',
          idempotencyKey: 'idem-1',
          requiresMaintenance: true,
        ),
      );

      expect(payload['imageUrl'], 'https://cdn.example/101.jpg');
      expect(payload['lastCleanedHotelDay'], '2026-09-23');
      expect(payload['idempotencyKey'], 'idem-1');
      expect(payload['requiresMaintenance'], isTrue);
    });
  });

  group('bookingToRemote', () {
    test('amount الموحّد يُشتق من totalDueCached (عقد الحقل الموحد)', () {
      final payload = mapper.bookingToRemote(_booking());

      expect(payload['amount'], 75000);
      expect(payload['totalDueCached'], 75000);
      expect(payload['totalPaidCached'], 30000);
      expect(payload['remainingBalanceCached'], 45000);
    });

    test('syncTimestamp يُشتق من lastModified (حتمية LWW)', () {
      final payload = mapper.bookingToRemote(_booking());

      expect(payload['syncTimestamp'], _t0);
    });

    test('checkoutDate/actualCheckout يُرسلان حتى لو null (مفتاح موجود)', () {
      final payload = mapper.bookingToRemote(_booking());

      expect(payload.containsKey('checkoutDate'), isTrue);
      expect(payload['checkoutDate'], isNull);
      expect(payload.containsKey('actualCheckout'), isTrue);
    });

    test('حقول ISO النل تُحذف ولا تلوث الحمولة', () {
      final payload = mapper.bookingToRemote(_booking());

      expect(payload.containsKey('createdAtIso'), isFalse);
      expect(payload.containsKey('updatedAtIso'), isFalse);
      expect(payload.containsKey('deletedAtIso'), isFalse);
      expect(payload.containsKey('notes'), isFalse);
      expect(payload.containsKey('financialFrozenAt'), isFalse);
    });
  });

  group('expenseToRemote', () {
    test(
      'isAutoGenerated يُرسل دائماً كـ boolean — حتى false (إصلاح P1-5)',
      () {
        final payload = mapper.expenseToRemote(
          _expense(isAutoGenerated: false),
        );

        expect(payload.containsKey('isAutoGenerated'), isTrue);
        expect(payload['isAutoGenerated'], isFalse);
      },
    );

    test('employeeUuid الفارغ يُحذف والمعبأ يُرسل', () {
      final empty = mapper.expenseToRemote(_expense(employeeUuid: null));
      final filled = mapper.expenseToRemote(
        _expense(employeeUuid: 'employee-uuid-0001'),
      );

      expect(empty.containsKey('employeeUuid'), isFalse);
      expect(filled['employeeUuid'], 'employee-uuid-0001');
    });

    test('حقول الهوية والمزامنة موجودة', () {
      final payload = mapper.expenseToRemote(_expense());

      expect(payload['localUuid'], 'expense-uuid-0001');
      expect(payload['amount'], 5000);
      expect(payload['hotelDayKey'], '2026-09-23');
      expect(payload.containsKey('syncTimestamp'), isTrue);
      expect(payload['deviceId'], 'dev-a');
    });
  });

  group('employeeToRemote', () {
    test('salary مرآة إلزامية لـ basicSalary (مطلوب من Secondary)', () {
      final payload = mapper.employeeToRemote(_employee());

      expect(payload['basicSalary'], 120000);
      expect(payload['salary'], 120000);
    });

    test('EmployeeID يُرسل بالتسمية المعتمدة في مخطط Appwrite', () {
      final payload = mapper.employeeToRemote(_employee());

      expect(payload['EmployeeID'], 'EMP-77');
      expect(payload.containsKey('employeeID'), isFalse);
    });

    test('حقول الإنهاء النل تُحذف', () {
      final payload = mapper.employeeToRemote(_employee());

      expect(payload.containsKey('terminationDate'), isFalse);
      expect(payload.containsKey('terminationReason'), isFalse);
      expect(payload.containsKey('deletedAt'), isFalse);
    });

    test('sanitizePayload يمنع أي حقل خارج مخطط employees', () {
      final payload = mapper.employeeToRemote(_employee());
      const allowed = {
        'localUuid',
        'serverId',
        'createdAt',
        'updatedAt',
        'deletedAt',
        'lastModified',
        'createdAtIso',
        'updatedAtIso',
        'deletedAtIso',
        'createdAtEpoch',
        'lastModifiedEpoch',
        'version',
        'origin',
        'vectorClock',
        'deviceId',
        'idempotencyKey',
        'syncTimestamp',
        'sync_origin',
        'name',
        'basicSalary',
        'salary',
        'position',
        'phone',
        'hireDate',
        'status',
        'terminationDate',
        'terminationReason',
        'EmployeeID',
      };

      expect(payload.keys.every(allowed.contains), isTrue);
    });
  });

  group('guestInfoToRemote', () {
    test('بيانات الهوية الأساسية تُرسل كاملة', () {
      final payload = mapper.guestInfoToRemote(_guestInfo());

      expect(payload['localUuid'], 'guestinfo-uuid-0001');
      expect(payload['roomNumber'], '101');
      expect(payload['guestName'], 'أحمد صالح');
      expect(payload['nationality'], 'يمني');
      expect(payload['idNumber'], '12345');
      expect(payload['idType'], 'بطاقة شخصية');
      expect(payload['deviceId'], 'dev-a');
    });

    test('guestPhone محلي فقط ولا يخرج للسحابة من هذا المحوّل', () {
      final payload = mapper.guestInfoToRemote(_guestInfo());

      expect(payload.containsKey('guestPhone'), isFalse);
    });

    test('الحقول الاختيارية النل/الفارغة تُحذف', () {
      final payload = mapper.guestInfoToRemote(_guestInfo());

      expect(payload.containsKey('issueDate'), isFalse);
      expect(payload.containsKey('issuePlace'), isFalse);
      expect(payload.containsKey('governorate'), isFalse);
      expect(payload.containsKey('notes'), isFalse);
    });

    test('الحقول الاختيارية المعبأة تُرسل', () {
      final payload = mapper.guestInfoToRemote(
        _guestInfo(governorate: 'عدن', notes: 'نزيل متكرر'),
      );

      expect(payload['governorate'], 'عدن');
      expect(payload['notes'], 'نزيل متكرر');
    });
  });

  group('paymentVoidToRemote', () {
    test('حقول الإلغاء الأساسية تُرسل كاملة', () {
      final payload = mapper.paymentVoidToRemote(_paymentVoid());

      expect(payload['localUuid'], 'void-uuid-0001');
      expect(payload['originalPaymentUuid'], 'payment-uuid-0001');
      // originalPaymentId معرف محلي لكنه حقل عمل داخل جدول payment_voids
      // (مرجع تدقيقي فقط — الربط عبر originalPaymentUuid/bookingUuid)
      expect(payload['originalPaymentId'], 44);
      expect(payload['bookingUuid'], 'booking-uuid-0001');
      expect(payload['voidedAmount'], 15000);
      expect(payload['voidReason'], 'خطأ إدخال');
      expect(payload['voidedBy'], 'manager-1');
      expect(payload['voidedAt'], _t0);
      expect(payload['hotelDayKey'], '2026-09-24');
    });

    test('الحقول v2 الاختيارية النل تُحذف', () {
      final payload = mapper.paymentVoidToRemote(_paymentVoid());

      expect(payload.containsKey('reversalPaymentUuid'), isFalse);
      expect(payload.containsKey('approvedBy'), isFalse);
      expect(payload.containsKey('note'), isFalse);
      expect(payload.containsKey('originalAmount'), isFalse);
      expect(payload.containsKey('paymentUuid'), isFalse);
    });

    test('الحقول v2 المعبأة تُرسل بقيمها الصحيحة', () {
      final payload = mapper.paymentVoidToRemote(
        _paymentVoid(originalAmount: 20000, note: 'إلغاء جزئي معتمد'),
      );

      expect(payload['originalAmount'], 20000);
      expect(payload['note'], 'إلغاء جزئي معتمد');
    });
  });
}
