/// Closed wire contract for `expense_kind`, mirroring branch3 worker
/// `src/expense-kind.ts` and the Android `domain/model/ExpenseKind.kt`.
///
/// The discriminator replaces the legacy Arabic-string matching in
/// `PayloadMapper.isSalaryExpenseType` with a stable cross-platform
/// value. NULL is a pre-contract row; the next accepted edit
/// materialises the kind atomically with `updated_at`.
///
/// Once a kind is present on a row, free-text description edits never
/// re-classify it — the server preserves the existing kind when an
/// incoming push omits the field (see `worker/src/database.ts`
/// `updateRecord` `expense_kind` preservation).
///
/// The legacy classifier (`legacyExpenseKind`) is used only when an
/// incoming row lacks an explicit kind. It produces the same result
/// across Flutter (Dart), Android (Kotlin) and Worker (TypeScript) so
/// a legacy client on either platform produces the same kind on the
/// server.
library;

/// The closed set of accepted `expense_kind` values.
///
/// Mirrors `worker/src/expense-kind.ts EXPENSE_KINDS` and the Android
/// `domain/model/ExpenseKind.kt values` set. Adding a new value here
/// MUST be done simultaneously in all three locations or push
/// validation will reject the new value as `Invalid expense_kind`.
const Set<String> kExpenseKinds = {
  'normal',
  'salary_advance',
  'salary_installment',
  'salary_withdrawal',
  'salary_deduction',
  'unclassified',
};

/// Conservative legacy classifier — used when an incoming row lacks an
/// explicit `expense_kind`. Mirrors `legacyExpenseKind` in
/// `worker/src/expense-kind.ts` and the Android `ExpenseKind.fromLegacy`.
///
/// The Arabic `expense_type` strings here match the existing Flutter
/// payload mapper (`PayloadMapper.isSalaryExpenseType`) and the Android
/// `EmployeeExpenseTypes` set, so a legacy client on either platform
/// produces the same kind on the server.
String legacyExpenseKind({
  required String expenseType,
  required bool isAutoGenerated,
  required String description,
}) {
  final type = expenseType.trim();
  if (['رواتب', 'سحب راتب', 'سحب من الراتب'].contains(type)) {
    return 'salary_withdrawal';
  }
  if (type == 'سلفة') return 'salary_advance';
  if (type == 'خصم من الراتب') {
    if (!isAutoGenerated) return 'salary_deduction';
    return description.contains('قسط سلفة') ? 'salary_installment' : 'unclassified';
  }
  if (['خصم راتب', 'خصم', 'غياب'].contains(type)) return 'salary_deduction';
  return 'normal';
}

/// Resolve the canonical kind for an incoming row. If the client sent
/// an explicit kind we trust it (after validating against
/// [kExpenseKinds]); otherwise we derive one conservatively from the
/// legacy fields.
///
/// Throws an [ArgumentError] on an invalid explicit kind so the
/// outbox/sync layer can surface it as a validation error rather than
/// silently dropping the row.
String resolveExpenseKind({
  String? explicitKind,
  required String expenseType,
  required bool isAutoGenerated,
  required String description,
}) {
  if (explicitKind == null) {
    return legacyExpenseKind(
      expenseType: expenseType,
      isAutoGenerated: isAutoGenerated,
      description: description,
    );
  }
  if (!kExpenseKinds.contains(explicitKind)) {
    throw ArgumentError.value(explicitKind, 'expense_kind', 'Invalid expense_kind');
  }
  return explicitKind;
}
