class FieldMapper {
  FieldMapper._();

  static final Map<String, Map<String, String>> _flutterToPhp = {
    'rooms': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'roomNumber': 'room_number',
      'type': 'type',
      'price': 'price',
      'status': 'status',
      'imageUrl': 'image_url',
      'cleaningStatus': 'cleaning_status',
      'lastCleanedHotelDay': 'last_cleaned_hotel_day',
      'lastOccupiedHotelDay': 'last_occupied_hotel_day',
      'requiresMaintenance': 'requires_maintenance',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'deletedAt': 'deleted_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
    'bookings': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'serverBookingId': 'id',
      'roomNumber': 'room_number',
      'guestName': 'guest_name',
      'guestPhone': 'guest_phone',
      'guestIdType': 'guest_id_type',
      'guestIdNumber': 'guest_id_number',
      'guestIdIssueDate': 'guest_id_issue_date',
      'guestIdIssuePlace': 'guest_id_issue_place',
      'guestNationality': 'guest_nationality',
      'guestEmail': 'guest_email',
      'guestAddress': 'guest_address',
      'checkinDate': 'checkin_date',
      'checkoutDate': 'checkout_date',
      'actualCheckout': 'actual_checkout',
      'status': 'status',
      'notes': 'notes',
      'discount': 'discount',
      'discountType': 'discount_type',
      'discountStartDate': 'discount_start_date',
      'expectedNights': 'expected_nights',
      'calculatedNights': 'calculated_nights',
      'totalNightsCached': 'total_nights_cached',
      'stayDurationIso': 'stay_duration_iso',
      'lastNightEpoch': 'last_night_epoch',
      'isOverdue': 'is_overdue',
      'needsCheckoutReview': 'needs_checkout_review',
      'totalDueCached': 'total_due_cached',
      'totalPaidCached': 'total_paid_cached',
      'remainingBalanceCached': 'remaining_balance_cached',
      'isFullyPaid': 'is_fully_paid',
      'hotelDayCheckin': 'hotel_day_checkin',
      'hotelDayCheckout': 'hotel_day_checkout',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'deletedAt': 'deleted_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
    'booking_notes': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'bookingId': 'booking_id',
      'noteText': 'note_text',
      'alertType': 'alert_type',
      'alertUntil': 'alert_until',
      'isActive': 'is_active',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'deletedAt': 'deleted_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
    'employees': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'name': 'name',
      'basicSalary': 'basic_salary',
      'position': 'position',
      'phone': 'phone',
      'hireDate': 'hire_date',
      'status': 'status',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'deletedAt': 'deleted_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
    'expenses': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'expenseType': 'expense_type',
      'relatedId': 'related_id',
      'description': 'description',
      'amount': 'amount',
      'date': 'date',
      'cashTransactionId': 'cash_transaction_id',
      'hotelDayKey': 'hotel_day_key',
      'categoryUuid': 'category_uuid',
      'cashFlowUuid': 'cash_flow_uuid',
      'isAutoGenerated': 'is_auto_generated',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'deletedAt': 'deleted_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
    'cash_transactions': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'registerId': 'register_id',
      'transactionType': 'transaction_type',
      'amount': 'amount',
      'referenceType': 'reference_type',
      'referenceId': 'reference_id',
      'description': 'description',
      'transactionTime': 'transaction_time',
      'createdBy': 'created_by',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'deletedAt': 'deleted_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
    'payments': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'serverPaymentId': 'id',
      'bookingLocalId': 'booking_local_id',
      'serverBookingId': 'booking_id',
      'roomNumber': 'room_number',
      'amount': 'amount',
      'paymentDate': 'payment_date',
      'notes': 'notes',
      'paymentMethod': 'payment_method',
      'revenueType': 'revenue_type',
      'cashTransactionLocalId': 'cash_transaction_local_id',
      'cashTransactionServerId': 'cash_transaction_id',
      'referenceNumber': 'reference_number',
      'hotelDayKey': 'hotel_day_key',
      'isPendingBalance': 'is_pending_balance',
      'linkedDebtUuid': 'linked_debt_uuid',
      'bookingUuidCache': 'booking_uuid_cache',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'deletedAt': 'deleted_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
    'system_settings': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'settingKey': 'setting_key',
      'settingValue': 'setting_value',
      'settingType': 'setting_type',
      'description': 'description',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
    'users': {
      'localUuid': 'local_uuid',
      'serverId': 'id',
      'username': 'username',
      'passwordHash': 'password_hash',
      'fullName': 'full_name',
      'role': 'role',
      'isActive': 'is_active',
      'createdAt': 'created_at',
      'updatedAt': 'updated_at',
      'lastModified': 'last_modified',
      'version': 'version',
    },
  };

  static final Map<String, Map<String, String>> _phpToFlutter = {};

  static void _buildReverseMap() {
    if (_phpToFlutter.isNotEmpty) return;
    for (final entity in _flutterToPhp.keys) {
      _phpToFlutter[entity] = {};
      for (final entry in _flutterToPhp[entity]!.entries) {
        _phpToFlutter[entity]![entry.value] = entry.key;
      }
    }
  }

  static String toPhpField(String entity, String flutterField) {
    return _flutterToPhp[entity]?[flutterField] ?? _camelToSnake(flutterField);
  }

  static String toFlutterField(String entity, String phpField) {
    _buildReverseMap();
    return _phpToFlutter[entity]?[phpField] ?? _snakeToCamel(phpField);
  }

  static Map<String, dynamic> toPhpMap(
    String entity,
    Map<String, dynamic> flutterMap,
  ) {
    final result = <String, dynamic>{};
    for (final entry in flutterMap.entries) {
      final phpKey = toPhpField(entity, entry.key);
      result[phpKey] = _convertValueToPhp(entry.value);
    }
    return result;
  }

  static Map<String, dynamic> toFlutterMap(
    String entity,
    Map<String, dynamic> phpMap,
  ) {
    _buildReverseMap();
    final result = <String, dynamic>{};
    for (final entry in phpMap.entries) {
      final flutterKey = toFlutterField(entity, entry.key);
      result[flutterKey] = _convertValueToFlutter(entry.value);
    }
    return result;
  }

  static List<Map<String, dynamic>> toPhpList(
    String entity,
    List<Map<String, dynamic>> flutterList,
  ) {
    return flutterList.map((m) => toPhpMap(entity, m)).toList();
  }

  static List<Map<String, dynamic>> toFlutterList(
    String entity,
    List<dynamic> phpList,
  ) {
    return phpList
        .map((m) => toFlutterMap(entity, Map<String, dynamic>.from(m)))
        .toList();
  }

  static dynamic _convertValueToPhp(dynamic value) {
    if (value == null) return null;
    if (value is bool) return value ? 1 : 0;
    if (value is DateTime) return value.toIso8601String();
    if (value is List) return value.map(_convertValueToPhp).toList();
    if (value is Map) {
      return value.map((k, v) => MapEntry(k, _convertValueToPhp(v)));
    }
    return value;
  }

  static dynamic _convertValueToFlutter(dynamic value) {
    if (value == null) return null;
    if (value is int && (value == 0 || value == 1)) {
      return value;
    }
    if (value is String) {
      final dateRegex = RegExp(r'^\d{4}-\d{2}-\d{2}');
      if (dateRegex.hasMatch(value)) {
        try {
          return DateTime.parse(value);
        } catch (_) {
          return value;
        }
      }
    }
    if (value is List) return value.map(_convertValueToFlutter).toList();
    if (value is Map) {
      return value.map((k, v) => MapEntry(k, _convertValueToFlutter(v)));
    }
    return value;
  }

  static String _camelToSnake(String input) {
    return input.replaceAllMapped(
      RegExp(r'[A-Z]'),
      (match) => '_${match.group(0)!.toLowerCase()}',
    );
  }

  static String _snakeToCamel(String input) {
    return input.replaceAllMapped(
      RegExp(r'_([a-z])'),
      (match) => match.group(1)!.toUpperCase(),
    );
  }

  static List<String> getEntityFields(String entity) {
    return _flutterToPhp[entity]?.keys.toList() ?? [];
  }

  static List<String> getSupportedEntities() {
    return _flutterToPhp.keys.toList();
  }

  static bool isEntitySupported(String entity) {
    return _flutterToPhp.containsKey(entity);
  }

  static Map<String, dynamic> extractSyncFields(Map<String, dynamic> data) {
    const syncFields = [
      'localUuid',
      'serverId',
      'createdAt',
      'updatedAt',
      'deletedAt',
      'lastModified',
      'version',
      'origin',
      'vectorClock',
    ];
    return Map.fromEntries(
      data.entries.where((e) => syncFields.contains(e.key)),
    );
  }

  static Map<String, dynamic> excludeSyncFields(Map<String, dynamic> data) {
    const syncFields = [
      'localUuid',
      'serverId',
      'createdAt',
      'updatedAt',
      'deletedAt',
      'lastModified',
      'version',
      'origin',
      'vectorClock',
      'createdAtIso',
      'updatedAtIso',
      'deletedAtIso',
      'createdAtEpoch',
      'lastModifiedEpoch',
    ];
    return Map.fromEntries(
      data.entries.where((e) => !syncFields.contains(e.key)),
    );
  }

  static Map<String, dynamic> prepareForInsert(
    String entity,
    Map<String, dynamic> data, {
    bool includeId = false,
  }) {
    final phpData = toPhpMap(entity, data);
    if (!includeId) {
      phpData.remove('id');
    }
    phpData.remove('local_uuid');
    return phpData;
  }

  static Map<String, dynamic> prepareForUpdate(
    String entity,
    Map<String, dynamic> data,
  ) {
    final phpData = toPhpMap(entity, data);
    phpData.remove('id');
    phpData.remove('local_uuid');
    phpData.remove('created_at');
    phpData['updated_at'] = DateTime.now().toIso8601String();
    return phpData;
  }

  static final Map<String, List<String>> _requiredFields = {
    'rooms': ['room_number', 'type', 'price', 'status'],
    'bookings': [
      'room_number',
      'guest_name',
      'guest_phone',
      'guest_nationality',
      'checkin_date',
      'status',
    ],
    'employees': ['name', 'basic_salary', 'status'],
    'expenses': ['expense_type', 'description', 'amount', 'date'],
    'payments': ['amount', 'payment_date', 'payment_method', 'revenue_type'],
    'cash_transactions': ['transaction_type', 'amount', 'transaction_time'],
  };

  static List<String> validateRequiredFields(
    String entity,
    Map<String, dynamic> phpData,
  ) {
    final required = _requiredFields[entity] ?? [];
    final missing = <String>[];
    for (final field in required) {
      if (!phpData.containsKey(field) || phpData[field] == null) {
        missing.add(field);
      }
    }
    return missing;
  }

  static final Map<String, String> _entityEndpoints = {
    'rooms': 'rooms',
    'bookings': 'bookings',
    'booking_notes': 'booking_notes',
    'employees': 'employees',
    'expenses': 'expenses',
    'cash_transactions': 'cash_transactions',
    'payments': 'payments',
    'system_settings': 'settings',
    'users': 'users',
  };

  static String getEndpoint(String entity) {
    return _entityEndpoints[entity] ?? entity;
  }
}

class FieldMappingException implements Exception {
  final String message;
  final String? entity;
  final String? field;

  FieldMappingException(this.message, {this.entity, this.field});

  @override
  String toString() {
    var msg = 'FieldMappingException: $message';
    if (entity != null) msg += ' (entity: $entity)';
    if (field != null) msg += ' (field: $field)';
    return msg;
  }
}
