#!/usr/bin/env python3
import sqlite3
import json
import urllib.request
import urllib.error
import asyncio
import sys
from pathlib import Path

ENDPOINT = "https://fra.cloud.appwrite.io/v1"
PROJECT_ID = "6a2b01d0000752ce97e7"
API_KEY = "standard_721adc4e95401dab9274bc2a7596ce0a61bfcdf7bbe37e7c64d52fb2113414e27c8d3e8f1977ebaafcf8ae63e7f3c873aad38c2a07e3ab93229cd7cd745a3ad2f6b9ec3fc407e8abfae2be3e5be00315f4d4a74cc07bc5ba5b0eda13e4569c8ee8ce2532a7bd43d827c7b83a84495974b9995d12f031e2bead685cebbe31aa3d"
DATABASE_ID = "6a2b030d000445596163"
SQLITE_PATH = "/home/daytona/uploads/marina_hotel_backup_2026-06-29_1782697246985.sqlite"

UPLOAD_ORDER = [
    "rooms",
    "bookings",
    "payments",
    "expenses",
    "employees",
    "debts",
    "booking_notes",
    "booking_nights",
    "cash_transactions",
    "salary_cycles",
    "salary_payments",
    "salary_withdrawals",
    "salary_carry_over_logs",
    "shift_notes",
    "price_adjustments",
    "booking_price_adjustments",
    "audit_logs",
    "payment_voids",
    "devices",
    "sync_logs",
    "app_settings",
    "app_users",
    "guest_infos",
    "blacklist",
]

SNAKE_TO_CAMEL = {
    "local_uuid": "localUuid",
    "server_id": "serverId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "deleted_at": "deletedAt",
    "last_modified": "lastModified",
    "created_at_iso": "createdAtIso",
    "updated_at_iso": "updatedAtIso",
    "deleted_at_iso": "deletedAtIso",
    "created_at_epoch": "createdAtEpoch",
    "last_modified_epoch": "lastModifiedEpoch",
    "vector_clock": "vectorClock",
    "device_id": "deviceId",
    "room_number": "roomNumber",
    "guest_name": "guestName",
    "guest_phone": "guestPhone",
    "guest_id_type": "guestIdType",
    "guest_id_number": "guestIdNumber",
    "guest_id_issue_date": "guestIdIssueDate",
    "guest_id_issue_place": "guestIdIssuePlace",
    "guest_nationality": "guestNationality",
    "guest_email": "guestEmail",
    "guest_address": "guestAddress",
    "checkin_date": "checkinDate",
    "checkout_date": "checkoutDate",
    "actual_checkout": "actualCheckout",
    "discount_type": "discountType",
    "discount_start_date": "discountStartDate",
    "expected_nights": "expectedNights",
    "calculated_nights": "calculatedNights",
    "total_nights_cached": "totalNightsCached",
    "stay_duration_iso": "stayDurationIso",
    "last_night_epoch": "lastNightEpoch",
    "is_overdue": "isOverdue",
    "needs_checkout_review": "needsCheckoutReview",
    "total_due_cached": "totalDueCached",
    "total_paid_cached": "totalPaidCached",
    "remaining_balance_cached": "remainingBalanceCached",
    "is_fully_paid": "isFullyPaid",
    "hotel_day_checkin": "hotelDayCheckin",
    "hotel_day_checkout": "hotelDayCheckout",
    "server_booking_id": "serverBookingId",
    "server_payment_id": "serverPaymentId",
    "booking_local_id": "bookingLocalId",
    "payment_date": "paymentDate",
    "payment_method": "paymentMethod",
    "revenue_type": "revenueType",
    "cash_transaction_local_id": "cashTransactionLocalId",
    "cash_transaction_server_id": "cashTransactionServerId",
    "reference_number": "referenceNumber",
    "hotel_day_key": "hotelDayKey",
    "is_pending_balance": "isPendingBalance",
    "linked_debt_uuid": "linkedDebtUuid",
    "booking_uuid_cache": "bookingUuidCache",
    "discount_amount": "discountAmount",
    "is_voided": "isVoided",
    "voided_at": "voidedAt",
    "voided_by": "voidedBy",
    "expense_type": "expenseType",
    "related_id": "relatedId",
    "cash_transaction_id": "cashTransactionId",
    "category_uuid": "categoryUuid",
    "cash_flow_uuid": "cashFlowUuid",
    "is_auto_generated": "isAutoGenerated",
    "basic_salary": "basicSalary",
    "hire_date": "hireDate",
    "termination_date": "terminationDate",
    "termination_reason": "terminationReason",
    "date_recorded": "dateRecorded",
    "debt_reason": "debtReason",
    "paid_amount": "paidAmount",
    "is_settled": "isSettled",
    "pledge_type": "pledgeType",
    "debt_uuid": "debtUuid",
    "hotel_day_opened": "hotelDayOpened",
    "hotel_day_closed": "hotelDayClosed",
    "is_from_auto_fix": "isFromAutoFix",
    "settlement_confirmed": "settlementConfirmed",
    "booking_id": "bookingId",
    "note_text": "noteText",
    "alert_type": "alertType",
    "alert_until": "alertUntil",
    "is_active": "isActive",
    "night_start": "nightStart",
    "night_end": "nightEnd",
    "nightly_rate": "nightlyRate",
    "is_processed_by_auto_fix": "isProcessedByAutoFix",
    "base_rate": "baseRate",
    "applied_adjustment_uuid": "appliedAdjustmentUuid",
    "applied_adjustments_json": "appliedAdjustmentsJson",
    "register_id": "registerId",
    "transaction_type": "transactionType",
    "reference_type": "referenceType",
    "reference_id": "referenceId",
    "transaction_time": "transactionTime",
    "created_by": "createdBy",
    "cycle_key": "cycleKey",
    "hotel_day_start": "hotelDayStart",
    "hotel_day_end": "hotelDayEnd",
    "expected_amount": "expectedAmount",
    "actual_paid": "actualPaid",
    "employee_id": "employeeId",
    "payment_date_iso": "paymentDateIso",
    "withdraw_date": "withdrawDate",
    "withdrawal_type": "withdrawalType",
    "previous_cycle_start": "previousCycleStart",
    "previous_cycle_end": "previousCycleEnd",
    "new_cycle_start": "newCycleStart",
    "new_cycle_end": "newCycleEnd",
    "carried_at": "carriedAt",
    "title": "title",
    "content": "content",
    "priority": "priority",
    "shift_type": "shiftType",
    "is_read": "isRead",
    "expires_at": "expiresAt",
    "target_type": "targetType",
    "target_uuid": "targetUuid",
    "adjustment_type": "adjustmentType",
    "previous_value": "previousValue",
    "new_value": "newValue",
    "effective_date": "effectiveDate",
    "applied_by": "appliedBy",
    "is_reversed": "isReversed",
    "reversed_at": "reversedAt",
    "reversed_by": "reversedBy",
    "booking_local_uuid": "bookingLocalUuid",
    "adjustment_mode": "adjustmentMode",
    "end_hotel_day": "endHotelDay",
    "effective_hotel_day": "effectiveHotelDay",
    "cancelled_at": "cancelledAt",
    "cancelled_by": "cancelledBy",
    "operation_type": "operationType",
    "entity_type": "entityType",
    "entity_uuid": "entityUuid",
    "entity_id": "entityId",
    "performed_by": "performedBy",
    "ip_address": "ipAddress",
    "timestamp_iso": "timestampIso",
    "is_financial": "isFinancial",
    "amount_impact": "amountImpact",
    "original_payment_uuid": "originalPaymentUuid",
    "original_payment_id": "originalPaymentId",
    "booking_uuid": "bookingUuid",
    "voided_amount": "voidedAmount",
    "void_reason": "voidReason",
    "voided_at_iso": "voidedAtIso",
    "reversal_payment_uuid": "reversalPaymentUuid",
    "approved_by": "approvedBy",
}


def map_key(key):
    return SNAKE_TO_CAMEL.get(key, key)


def map_row(row, valid_fields):
    out = {}
    for sqlite_key, value in row.items():
        cloud_key = map_key(sqlite_key)
        if cloud_key in ("id", "$id"):
            continue
        if cloud_key in valid_fields:
            field_type = valid_fields.get(cloud_key, "string")
            if value is None:
                out[cloud_key] = None
            elif isinstance(value, bool):
                out[cloud_key] = value
            elif field_type == "boolean" and isinstance(value, int) and not isinstance(value, bool):
                out[cloud_key] = bool(value)
            elif isinstance(value, int) and not isinstance(value, bool):
                out[cloud_key] = value
            elif isinstance(value, float):
                out[cloud_key] = value
            elif isinstance(value, str):
                try:
                    if field_type == "integer":
                        out[cloud_key] = int(value)
                    elif field_type in ("float", "double"):
                        out[cloud_key] = float(value)
                    elif field_type == "boolean":
                        out[cloud_key] = value.lower() in ("1", "true", "yes", "on")
                    else:
                        out[cloud_key] = value
                except (ValueError, TypeError):
                    out[cloud_key] = value
            else:
                out[cloud_key] = value
    return out


def appwrite_request(method, path, data=None):
    url = f"{ENDPOINT}/databases/{DATABASE_ID}{path}"
    headers = {
        "X-Appwrite-Key": API_KEY,
        "X-Appwrite-Project": PROJECT_ID,
        "Content-Type": "application/json",
    }
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        err = e.read().decode()
        raise Exception(f"HTTP {e.code}: {err}")


def fetch_valid_fields(collection_id):
    # Prefer discovering fields from a real document (documents can contain
    # fields that the attributes listing omits on some Appwrite versions).
    try:
        data = appwrite_request("GET", f"/collections/{collection_id}/documents?limit=1")
        docs = data.get("documents", [])
        if docs:
            doc = docs[0]
            return {
                k: "boolean" if isinstance(v, bool) else
                   "integer" if isinstance(v, int) and not isinstance(v, bool) else
                   "float" if isinstance(v, float) else
                   "string"
                for k, v in doc.items()
                if not k.startswith("$")
            }
    except Exception as e:
        print(f"  warn: could not fetch sample doc for {collection_id}: {e}")

    fields = {}
    offset = 0
    while True:
        data = appwrite_request("GET", f"/collections/{collection_id}/attributes?limit=100&offset={offset}")
        for a in data.get("attributes", []):
            fields[a["key"]] = a.get("type", "string")
        if len(data.get("attributes", [])) < 100:
            break
        offset += len(data.get("attributes", []))
    return fields


def process_table(conn, table_name, valid_fields):
    cursor = conn.cursor()
    cursor.execute(f"SELECT * FROM {table_name}")
    rows = cursor.fetchall()
    cols = [desc[0] for desc in cursor.description]

    print(f"\n=== {table_name} ({len(rows)} records) ===")

    if not rows:
        print("  (empty, skipping)")
        return {"created": 0, "skipped": 0, "failed": 0}

    created = 0
    skipped = 0
    failed = 0

    for i, row in enumerate(rows):
        row_dict = dict(zip(cols, row))
        document_id = row_dict.get("local_uuid") or row_dict.get("localUuid")
        if not document_id:
            failed += 1
            continue

        payload = map_row(row_dict, valid_fields)
        try:
            appwrite_request("POST", f"/collections/{table_name}/documents", {
                "documentId": document_id,
                "data": payload,
            })
            created += 1
        except Exception as e:
            msg = str(e)
            if "already exists" in msg or "409" in msg:
                skipped += 1
            else:
                failed += 1
                if failed <= 5:
                    print(f"  ✖ {document_id}: {msg}")

        if (i + 1) % 100 == 0 or i + 1 == len(rows):
            print(f"\r  Progress: {i + 1}/{len(rows)} (created: {created}, skipped: {skipped}, failed: {failed})", end="", flush=True)

    print(f"\n  Done: created={created}, skipped={skipped}, failed={failed}")
    return {"created": created, "skipped": skipped, "failed": failed}


def main():
    if not Path(SQLITE_PATH).exists():
        print(f"SQLite backup not found: {SQLITE_PATH}")
        sys.exit(1)

    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row

    total_created = 0
    total_skipped = 0
    total_failed = 0

    for table_name in UPLOAD_ORDER:
        try:
            cursor = conn.cursor()
            cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
            count = cursor.fetchone()[0]
            if count == 0:
                print(f"\n--- {table_name} ({count} records) ---")
                print("  (empty, skipping)")
                continue

            print(f"Fetching Cloud schema for {table_name}...", end=" ", flush=True)
            valid_fields = fetch_valid_fields(table_name)
            print(f"{len(valid_fields)} fields")

            result = process_table(conn, table_name, valid_fields)
            total_created += result["created"]
            total_skipped += result["skipped"]
            total_failed += result["failed"]
        except Exception as e:
            print(f"\n✖ Failed to process {table_name}: {e}")
            total_failed += 1

    conn.close()

    print(f"\n=== SUMMARY ===")
    print(f"Created:  {total_created}")
    print(f"Skipped:  {total_skipped}")
    print(f"Failed:   {total_failed}")
    print(f"Total:    {total_created + total_skipped + total_failed}")


if __name__ == "__main__":
    main()
