const { Client, Databases, Query } = require("node-appwrite");
const sqlite3 = require("sqlite3").verbose();
const fs = require("fs");

const endpoint = "https://fra.cloud.appwrite.io/v1";
const projectId = "6a2b01d0000752ce97e7";
const apiKey = "standard_721adc4e95401dab9274bc2a7596ce0a61bfcdf7bbe37e7c64d52fb2113414e27c8d3e8f1977ebaafcf8ae63e7f3c873aad38c2a07e3ab93229cd7cd745a3ad2f6b9ec3fc407e8abfae2be3e5be00315f4d4a74cc07bc5ba5b0eda13e4569c8ee8ce2532a7bd43d827c7b83a84495974b9995d12f031e2bead685cebbe31aa3d";
const databaseId = "6a2b030d000445596163";
const sqlitePath = "/home/daytona/uploads/marina_hotel_backup_2026-06-29_1782697246985.sqlite";

const client = new Client().setEndpoint(endpoint).setProject(projectId).setKey(apiKey);
const databases = new Databases(client);

const UPLOAD_ORDER = [
  "rooms",
  "bookings",
  "payments",
  "expenses",
  "employees",
  "debts",
  "booking_notes",
  "booking_nights",
  "cash_transactions",
  "salary_cycles",
  "salary_payments",
  "salary_withdrawals",
  "salary_carry_over_logs",
  "shift_notes",
  "price_adjustments",
  "booking_price_adjustments",
  "audit_logs",
  "payment_voids",
  "devices",
  "sync_logs",
  "app_settings",
  "app_users",
  "guest_infos",
  "blacklist",
];

const SNAKE_TO_CAMEL = {
  local_uuid: "localUuid",
  server_id: "serverId",
  created_at: "createdAt",
  updated_at: "updatedAt",
  deleted_at: "deletedAt",
  last_modified: "lastModified",
  created_at_iso: "createdAtIso",
  updated_at_iso: "updatedAtIso",
  deleted_at_iso: "deletedAtIso",
  created_at_epoch: "createdAtEpoch",
  last_modified_epoch: "lastModifiedEpoch",
  vector_clock: "vectorClock",
  device_id: "deviceId",
  room_number: "roomNumber",
  guest_name: "guestName",
  guest_phone: "guestPhone",
  guest_id_type: "guestIdType",
  guest_id_number: "guestIdNumber",
  guest_id_issue_date: "guestIdIssueDate",
  guest_id_issue_place: "guestIdIssuePlace",
  guest_nationality: "guestNationality",
  guest_email: "guestEmail",
  guest_address: "guestAddress",
  checkin_date: "checkinDate",
  checkout_date: "checkoutDate",
  actual_checkout: "actualCheckout",
  discount_type: "discountType",
  discount_start_date: "discountStartDate",
  expected_nights: "expectedNights",
  calculated_nights: "calculatedNights",
  total_nights_cached: "totalNightsCached",
  stay_duration_iso: "stayDurationIso",
  last_night_epoch: "lastNightEpoch",
  is_overdue: "isOverdue",
  needs_checkout_review: "needsCheckoutReview",
  total_due_cached: "totalDueCached",
  total_paid_cached: "totalPaidCached",
  remaining_balance_cached: "remainingBalanceCached",
  is_fully_paid: "isFullyPaid",
  hotel_day_checkin: "hotelDayCheckin",
  hotel_day_checkout: "hotelDayCheckout",
  server_booking_id: "serverBookingId",
  server_payment_id: "serverPaymentId",
  booking_local_id: "bookingLocalId",
  server_booking_id: "serverBookingId",
  payment_date: "paymentDate",
  payment_method: "paymentMethod",
  revenue_type: "revenueType",
  cash_transaction_local_id: "cashTransactionLocalId",
  cash_transaction_server_id: "cashTransactionServerId",
  reference_number: "referenceNumber",
  hotel_day_key: "hotelDayKey",
  is_pending_balance: "isPendingBalance",
  linked_debt_uuid: "linkedDebtUuid",
  booking_uuid_cache: "bookingUuidCache",
  discount_amount: "discountAmount",
  is_voided: "isVoided",
  voided_at: "voidedAt",
  voided_by: "voidedBy",
  expense_type: "expenseType",
  related_id: "relatedId",
  cash_transaction_id: "cashTransactionId",
  category_uuid: "categoryUuid",
  cash_flow_uuid: "cashFlowUuid",
  is_auto_generated: "isAutoGenerated",
  basic_salary: "basicSalary",
  hire_date: "hireDate",
  termination_date: "terminationDate",
  termination_reason: "terminationReason",
  date_recorded: "dateRecorded",
  debt_reason: "debtReason",
  paid_amount: "paidAmount",
  is_settled: "isSettled",
  pledge_type: "pledgeType",
  debt_uuid: "debtUuid",
  hotel_day_opened: "hotelDayOpened",
  hotel_day_closed: "hotelDayClosed",
  is_from_auto_fix: "isFromAutoFix",
  settlement_confirmed: "settlementConfirmed",
  booking_id: "bookingId",
  note_text: "noteText",
  alert_type: "alertType",
  alert_until: "alertUntil",
  is_active: "isActive",
  night_start: "nightStart",
  night_end: "nightEnd",
  nightly_rate: "nightlyRate",
  is_processed_by_auto_fix: "isProcessedByAutoFix",
  base_rate: "baseRate",
  applied_adjustment_uuid: "appliedAdjustmentUuid",
  applied_adjustments_json: "appliedAdjustmentsJson",
  register_id: "registerId",
  transaction_type: "transactionType",
  reference_type: "referenceType",
  reference_id: "referenceId",
  transaction_time: "transactionTime",
  created_by: "createdBy",
  cycle_key: "cycleKey",
  hotel_day_start: "hotelDayStart",
  hotel_day_end: "hotelDayEnd",
  expected_amount: "expectedAmount",
  actual_paid: "actualPaid",
  employee_id: "employeeId",
  payment_date_iso: "paymentDateIso",
  withdraw_date: "withdrawDate",
  withdrawal_type: "withdrawalType",
  previous_cycle_start: "previousCycleStart",
  previous_cycle_end: "previousCycleEnd",
  new_cycle_start: "newCycleStart",
  new_cycle_end: "newCycleEnd",
  carried_at: "carriedAt",
  shift_type: "shiftType",
  is_read: "isRead",
  expires_at: "expiresAt",
  target_type: "targetType",
  target_uuid: "targetUuid",
  adjustment_type: "adjustmentType",
  previous_value: "previousValue",
  new_value: "newValue",
  effective_date: "effectiveDate",
  applied_by: "appliedBy",
  is_reversed: "isReversed",
  reversed_at: "reversedAt",
  reversed_by: "reversedBy",
  booking_local_uuid: "bookingLocalUuid",
  adjustment_mode: "adjustmentMode",
  end_hotel_day: "endHotelDay",
  effective_hotel_day: "effectiveHotelDay",
  cancelled_at: "cancelledAt",
  cancelled_by: "cancelledBy",
  operation_type: "operationType",
  entity_type: "entityType",
  entity_uuid: "entityUuid",
  entity_id: "entityId",
  performed_by: "performedBy",
  ip_address: "ipAddress",
  timestamp_iso: "timestampIso",
  is_financial: "isFinancial",
  amount_impact: "amountImpact",
  original_payment_uuid: "originalPaymentUuid",
  original_payment_id: "originalPaymentId",
  booking_uuid: "bookingUuid",
  voided_amount: "voidedAmount",
  void_reason: "voidReason",
  voided_at_iso: "voidedAtIso",
  reversal_payment_uuid: "reversalPaymentUuid",
  approved_by: "approvedBy",
};

function mapKey(key) {
  return SNAKE_TO_CAMEL[key] || key;
}

async function fetchValidFields(collectionId) {
  const fields = new Set();
  let offset = 0;
  while (true) {
    const res = await databases.listAttributes(databaseId, collectionId, [
      Query.limit(100),
      Query.offset(offset),
    ]);
    for (const attr of res.attributes) {
      fields.add(attr.key);
    }
    if (res.attributes.length < 100) break;
    offset += res.attributes.length;
  }
  return fields;
}

function mapRow(row, validFields) {
  const out = {};
  for (const [sqliteKey, value] of Object.entries(row)) {
    if (value === undefined || value === null) continue;
    const cloudKey = mapKey(sqliteKey);
    if (cloudKey === "$id" || cloudKey === "id") continue;
    if (validFields.has(cloudKey)) {
      out[cloudKey] = value;
    }
  }
  return out;
}

async function processTable(db, tableName, validFields) {
  const collectionId = tableName;
  const sql = `SELECT * FROM ${tableName}`;
  const rows = await new Promise((resolve, reject) => {
    db.all(sql, (err, rows) => {
      if (err) reject(err);
      else resolve(rows);
    });
  });

  console.log(`\n=== ${tableName} (${rows.length} records) ===`);

  if (rows.length === 0) {
    console.log("  (empty, skipping)");
    return { created: 0, skipped: 0, failed: 0 };
  }

  let created = 0;
  let skipped = 0;
  let failed = 0;

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const documentId = row.local_uuid || row.localUuid;
    if (!documentId) {
      failed++;
      continue;
    }
    const payload = mapRow(row, validFields);
    try {
      await databases.createDocument(databaseId, collectionId, documentId, payload);
      created++;
    } catch (e) {
      const msg = e.message || "";
      if (msg.includes("already exists") || msg.includes("409")) {
        skipped++;
      } else {
        failed++;
        if (failed <= 5) {
          console.error(`  ✖ ${documentId}: ${msg}`);
        }
      }
    }

    if ((i + 1) % 100 === 0 || i + 1 === rows.length) {
      process.stdout.write(`\r  Progress: ${i + 1}/${rows.length} (created: ${created}, skipped: ${skipped}, failed: ${failed})`);
    }
  }
  console.log(`\n  Done: created=${created}, skipped=${skipped}, failed=${failed}`);
  return { created, skipped, failed };
}

async function main() {
  if (!fs.existsSync(sqlitePath)) {
    console.error("SQLite backup not found:", sqlitePath);
    process.exit(1);
  }

  const db = new sqlite3.Database(sqlitePath, sqlite3.OPEN_READONLY);

  let totalCreated = 0;
  let totalSkipped = 0;
  let totalFailed = 0;

  for (const tableName of UPLOAD_ORDER) {
    try {
      const validFields = await fetchValidFields(tableName);
      console.log(`Table ${tableName}: ${validFields.size} Cloud fields`);
      const result = await processTable(db, tableName, validFields);
      totalCreated += result.created;
      totalSkipped += result.skipped;
      totalFailed += result.failed;
    } catch (e) {
      console.error(`\n✖ Failed to process ${tableName}: ${e.message}`);
      totalFailed++;
    }
  }

  await db.close();

  console.log(`\n=== SUMMARY ===`);
  console.log(`Created:  ${totalCreated}`);
  console.log(`Skipped:  ${totalSkipped}`);
  console.log(`Failed:   ${totalFailed}`);
  console.log(`Total:    ${totalCreated + totalSkipped + totalFailed}`);
}

main().catch((e) => {
  console.error("Fatal:", e);
  process.exit(1);
});
