const { Client, Databases } = require('node-appwrite');

const ENDPOINT = 'https://fra.cloud.appwrite.io/v1';
const PROJECT_ID = '690ff0da0025518570c1';
const API_KEY = 'standard_4158f40bb3d2e370befc7df85f6f66dfa06dcc068036f60085b155e88d46546f57ffec6c9a6d4ea3b7ba11bf0e5dce276122ecb5aa20cd96bb8d08aa33eddd0d7a531171bf7d763509215657a3d138d1a9393228550ff14102903127bfade5ef0b93f87baa39d2850e7f7d4cedca6190d9179d2e5239a2c53c4d941a89ef84da';
const DATABASE_ID = 'hotel_db';

const client = new Client()
    .setEndpoint(ENDPOINT)
    .setProject(PROJECT_ID)
    .setKey(API_KEY);

const databases = new Databases(client);

// Sync fields required for all synced tables
const syncFields = [
    'localUuid', 'serverId', 'createdAt', 'updatedAt', 'deletedAt',
    'lastModified', 'version', 'origin', 'vectorClock'
];

// Required fields per collection (from local_db.dart)
const collectionSchemas = {
    'rooms': {
        required: ['roomNumber', 'type', 'price', 'status', ...syncFields],
        optional: ['imageUrl', 'cleaningStatus', 'lastCleanedHotelDay', 'lastOccupiedHotelDay', 'requiresMaintenance', 
                   'createdAtIso', 'updatedAtIso', 'deletedAtIso', 'createdAtEpoch', 'lastModifiedEpoch']
    },
    'bookings': {
        required: ['roomNumber', 'guestName', 'guestPhone', 'guestNationality', 'checkinDate', 'status', ...syncFields],
        optional: ['serverBookingId', 'guestIdType', 'guestIdNumber', 'guestIdIssueDate', 'guestIdIssuePlace',
                   'guestEmail', 'guestAddress', 'checkoutDate', 'actualCheckout', 'notes', 'discount', 'discountType',
                   'discountStartDate', 'expectedNights', 'calculatedNights', 'totalNightsCached', 'stayDurationIso',
                   'financialHash', 'financialFrozenAt', 'lastNightEpoch', 'isOverdue', 'needsCheckoutReview',
                   'totalDueCached', 'totalPaidCached', 'remainingBalanceCached', 'isFullyPaid',
                   'hotelDayCheckin', 'hotelDayCheckout', 'createdAtIso', 'updatedAtIso', 'deletedAtIso',
                   'createdAtEpoch', 'lastModifiedEpoch']
    },
    'payments': {
        required: ['amount', 'paymentDate', 'paymentMethod', 'revenueType', ...syncFields],
        optional: ['serverPaymentId', 'bookingLocalId', 'serverBookingId', 'roomNumber', 'notes',
                   'cashTransactionLocalId', 'cashTransactionServerId', 'referenceNumber', 'hotelDayKey',
                   'isPendingBalance', 'linkedDebtUuid', 'bookingUuidCache', 'createdAtIso', 'updatedAtIso',
                   'deletedAtIso', 'createdAtEpoch', 'lastModifiedEpoch']
    },
    'expenses': {
        required: ['expenseType', 'description', 'amount', 'date', ...syncFields],
        optional: ['relatedId', 'cashTransactionId', 'hotelDayKey', 'categoryUuid', 'cashFlowUuid',
                   'isAutoGenerated', 'createdAtIso', 'updatedAtIso', 'deletedAtIso', 
                   'createdAtEpoch', 'lastModifiedEpoch']
    },
    'employees': {
        required: ['name', 'basicSalary', 'status', ...syncFields],
        optional: ['position', 'phone', 'hireDate', 'createdAtIso', 'updatedAtIso', 'deletedAtIso',
                   'createdAtEpoch', 'lastModifiedEpoch']
    },
    'debts': {
        required: ['guestName', 'checkinDate', 'checkoutDate', 'totalAmount', 'paidAmount', 
                   'remainingAmount', 'paymentDate', ...syncFields],
        optional: ['bookingLocalId', 'dateRecorded', 'debtReason', 'isSettled', 'pledge', 'pledgeType',
                   'note', 'debtUuid', 'hotelDayOpened', 'hotelDayClosed', 'isFromAutoFix',
                   'settlementConfirmed', 'createdAtIso', 'updatedAtIso', 'deletedAtIso',
                   'createdAtEpoch', 'lastModifiedEpoch']
    },
    'booking_notes': {
        required: ['bookingId', 'noteText', 'alertType', ...syncFields],
        optional: ['alertUntil', 'isActive', 'createdAtIso', 'updatedAtIso', 'deletedAtIso',
                   'createdAtEpoch', 'lastModifiedEpoch']
    },
    'booking_nights': {
        required: ['bookingLocalId', 'hotelDayKey', 'nightStart', 'nightEnd', ...syncFields],
        optional: ['nightlyRate', 'sequence', 'isProcessedByAutoFix', 'baseRate', 'adjustment',
                   'finalRate', 'appliedAdjustmentUuid', 'appliedAdjustmentsJson',
                   'createdAtIso', 'updatedAtIso', 'deletedAtIso', 'createdAtEpoch', 'lastModifiedEpoch']
    },
    'cash_transactions': {
        required: ['transactionType', 'amount', 'transactionTime', ...syncFields],
        optional: ['registerId', 'referenceType', 'referenceId', 'description', 'createdBy',
                   'createdAtIso', 'updatedAtIso', 'deletedAtIso', 'createdAtEpoch', 'lastModifiedEpoch']
    },
    'salary_cycles': {
        required: ['employeeId', 'cycleKey', ...syncFields],
        optional: ['hotelDayStart', 'hotelDayEnd', 'expectedAmount', 'actualPaid', 'remainingAmount', 'status',
                   'createdAtIso', 'updatedAtIso', 'deletedAtIso', 'createdAtEpoch', 'lastModifiedEpoch']
    },
    'salary_payments': {
        required: ['cycleId', 'paymentDateIso', ...syncFields],
        optional: ['amount', 'hotelDayKey', 'method', 'isAutoGenerated',
                   'createdAtIso', 'updatedAtIso', 'deletedAtIso', 'createdAtEpoch', 'lastModifiedEpoch']
    },
    'salary_withdrawals': {
        required: ['employeeId', 'action', 'amount', 'date', ...syncFields],
        optional: ['expenseId', 'note', 'createdAtIso', 'updatedAtIso', 'deletedAtIso',
                   'createdAtEpoch', 'lastModifiedEpoch']
    },
    'shift_notes': {
        required: ['title', 'content', ...syncFields],
        optional: ['priority', 'shiftType', 'isRead', 'expiresAt', 'createdBy',
                   'createdAtIso', 'updatedAtIso', 'deletedAtIso', 'createdAtEpoch', 'lastModifiedEpoch']
    },
    'hotel_day_ledger': {
        required: ['hotelDayKey', ...syncFields],
        optional: ['totalIncome', 'totalExpenses', 'pendingBalances', 'occupancyRate',
                   'bookingsProcessed', 'paymentsProcessed', 'debtsProcessed', 'expensesProcessed', 'status',
                   'createdAtIso', 'updatedAtIso', 'deletedAtIso', 'createdAtEpoch', 'lastModifiedEpoch']
    }
};

async function main() {
    console.log('🔍 Checking All Collections for Missing Attributes...\n');
    console.log('='.repeat(80));
    
    const allCollections = await databases.listCollections(DATABASE_ID);
    const results = [];
    
    for (const [collectionId, schema] of Object.entries(collectionSchemas)) {
        console.log(`\n📦 Checking: ${collectionId}`);
        
        try {
            const attrs = await databases.listAttributes(DATABASE_ID, collectionId);
            const existingKeys = attrs.attributes.map(a => a.key);
            const allRequired = [...schema.required, ...schema.optional];
            
            // Find missing attributes
            const missingRequired = schema.required.filter(k => !existingKeys.includes(k));
            const missingOptional = schema.optional.filter(k => !existingKeys.includes(k));
            const missingAll = [...missingRequired, ...missingOptional];
            
            // Find extra attributes (in Appwrite but not in schema)
            const extra = existingKeys.filter(k => !allRequired.includes(k) && !['syncTimestamp', 'deviceId'].includes(k));
            
            const status = missingRequired.length === 0 ? '✅ OK' : '❌ MISSING';
            console.log(`   ${status} - ${attrs.total} attributes`);
            
            results.push({
                id: collectionId,
                status: missingRequired.length === 0 ? 'ok' : 'missing',
                missingRequired,
                missingOptional,
                extra,
                total: attrs.total
            });
            
            if (missingRequired.length > 0) {
                console.log(`   ❌ Missing Required: ${missingRequired.join(', ')}`);
            }
            if (missingOptional.length > 0) {
                console.log(`   ⚠️  Missing Optional: ${missingOptional.slice(0, 5).join(', ')}${missingOptional.length > 5 ? '...' : ''}`);
            }
            
        } catch (error) {
            console.log(`   ❌ ERROR: ${error.message}`);
            results.push({ id: collectionId, status: 'error', error: error.message });
        }
    }
    
    console.log('\n\n' + '='.repeat(80));
    console.log('📊 SUMMARY\n');
    
    const okCount = results.filter(r => r.status === 'ok').length;
    const missingCount = results.filter(r => r.status === 'missing').length;
    const errorCount = results.filter(r => r.status === 'error').length;
    
    console.log(`✅ Complete: ${okCount}`);
    console.log(`❌ Missing Fields: ${missingCount}`);
    console.log(`⚠️  Errors: ${errorCount}`);
    
    if (missingCount > 0 || errorCount > 0) {
        console.log('\n📋 Collections needing attention:');
        results.filter(r => r.status !== 'ok').forEach(r => {
            if (r.status === 'missing') {
                console.log(`   - ${r.id}: Missing ${r.missingRequired.length} required fields`);
            } else {
                console.log(`   - ${r.id}: ${r.error}`);
            }
        });
    }
    
    // Return collections that need fixes
    return results.filter(r => r.status === 'missing');
}

main().catch(console.error);
