name: Dart CI

on:
  # Run on PRs and pushes to main and feature branches from main.
  push:
    branches:
      - main
      - 'capy/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: test-package-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - id: install
        name: Install dependencies
        run: flutter pub get
      - name: Generate code with build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
        if: always() && steps.install.outcome == 'success'
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'
        continue-on-error: true
      - name: Analyze code
        run: flutter analyze --no-pub --fatal-infos
        if: always() && steps.install.outcome == 'success'

  test:
    needs: analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - id: install
        name: Install dependencies
        run: flutter pub get
      - name: Run Flutter tests
        run: flutter test
        if: always() && steps.install.outcome == 'success'
